import { createAudioPlayer, setAudioModeAsync, type AudioPlayer } from 'expo-audio';

/**
 * UI sound cues, gated by the user's setting.
 *
 * Deliberately shaped like `feedback.ts`: the settings provider calls
 * `configureSound` on hydration and on change, so call sites stay synchronous
 * and need no context. That symmetry matters — haptics and sound are the same
 * decision made twice, and a learner who turns one off is usually reaching for
 * the other.
 *
 * **Policy is not here.** This file knows how to play a file and whether sound
 * is switched on; *which* moment earns which cue is a question about the
 * learning experience, and it lives at the call sites — the session player, the
 * results screen — where the moment is. That is the same split that moved the
 * snapshot rules out of `snapshots.ts`.
 *
 * The cues themselves are generated by `scripts/make-sounds.mjs`; see its header
 * for the family they belong to.
 */

export type SoundCue = 'correct' | 'incorrect' | 'complete' | 'levelUp' | 'unlock';

const SOURCES: Record<SoundCue, number> = {
  correct: require('@/assets/audio/correct.wav'),
  incorrect: require('@/assets/audio/incorrect.wav'),
  complete: require('@/assets/audio/complete.wav'),
  levelUp: require('@/assets/audio/levelUp.wav'),
  unlock: require('@/assets/audio/unlock.wav'),
};

/**
 * Per-cue trim. The generator normalises every file to the same peak, which is
 * what keeps them a family, but "the same peak" is not "the same loudness" —
 * the level-up is a chord held for a second and the correct chime is two notes
 * over in a fifth of that, so matching their peaks leaves the fanfare shouting.
 */
const VOLUME: Record<SoundCue, number> = {
  correct: 0.55,
  incorrect: 0.4,
  complete: 0.5,
  levelUp: 0.6,
  unlock: 0.5,
};

let enabled = true;
let modeSet = false;
const players = new Map<SoundCue, AudioPlayer>();

export function configureSound(options: { sounds: boolean }) {
  enabled = options.sounds;
}

/**
 * Both settings below are already Expo's defaults, and both are set anyway.
 *
 * `mixWithOthers` is the one that would actually be missed: without it the app
 * takes audio focus for a 300ms chime and stops whatever the learner had
 * playing, which is the single rudest thing a sound effect can do. Being
 * explicit also means a future change to Expo's defaults cannot quietly make
 * this app start interrupting music.
 */
function ensureMode() {
  if (modeSet) return;
  modeSet = true;
  setAudioModeAsync({
    playsInSilentMode: true,
    interruptionMode: 'mixWithOthers',
    shouldPlayInBackground: false,
    allowsRecording: false,
  }).catch(() => {
    /* An audio session we could not configure still plays; it just plays rudely. */
  });
}

function playerFor(cue: SoundCue): AudioPlayer | null {
  const existing = players.get(cue);
  if (existing) return existing;
  try {
    const player = createAudioPlayer(SOURCES[cue]);
    player.volume = VOLUME[cue];
    players.set(cue, player);
    return player;
  } catch {
    return null;
  }
}

/**
 * Decodes the cues ahead of the moment that needs them.
 *
 * Call it when a session opens, not at app start. Creating the player lazily
 * inside `play` costs a decode on the first correct answer of the run, which is
 * long enough to land after the haptic and read as two separate events rather
 * than one — and app start is the worst possible time to do five decodes,
 * because it is the one moment the learner is already waiting.
 */
export function primeSounds(): void {
  if (!enabled) return;
  ensureMode();
  (Object.keys(SOURCES) as SoundCue[]).forEach(playerFor);
}

export function playCue(cue: SoundCue): void {
  if (!enabled) return;
  ensureMode();
  const player = playerFor(cue);
  if (!player) return;
  try {
    // Rewind rather than overlap: a learner answering quickly should hear the
    // cue restart, not two of them beating against each other.
    player.seekTo(0);
    player.play();
  } catch {
    /* Best-effort, exactly like haptics: audio must never interrupt a lesson. */
  }
}

/** Mirrors `feedback`, so a call site reads `feedback.correct(); sound.correct();`. */
export const sound = {
  correct: () => playCue('correct'),
  incorrect: () => playCue('incorrect'),
  /** A lesson or session finished. */
  complete: () => playCue('complete'),
  /** A level was crossed — the loudest thing the app ever does. */
  levelUp: () => playCue('levelUp'),
  /** An achievement unlocked. */
  unlock: () => playCue('unlock'),
};
