import type { VocabConcept } from '@/content/types';

/**
 * The rest of A1: numbers, the calendar, colours, weather, nationalities,
 * describing people, possessives and demonstratives.
 *
 * These are the everyday building blocks the original Foundations stage
 * skipped — you cannot claim A1 without being able to say your age, arrange a
 * day, or describe someone. Peninsular throughout.
 */
export const a1CoreVocab: VocabConcept[] = [
  // --- Numbers -------------------------------------------------------------
  // 0–15 are each their own word and have to be retrievable individually;
  // 1–10 and 20 already live in `everyday.ts`. From 16 the pattern takes over,
  // which is what the grammar card teaches.
  { id: 'v.cero', kind: 'vocab', level: 'A0', topics: ['numbers'], es: 'cero', en: 'zero', pos: 'number' },
  { id: 'v.once', kind: 'vocab', level: 'A1', topics: ['numbers'], es: 'once', en: 'eleven', pos: 'number' },
  { id: 'v.doce', kind: 'vocab', level: 'A1', topics: ['numbers'], es: 'doce', en: 'twelve', pos: 'number' },
  { id: 'v.trece', kind: 'vocab', level: 'A1', topics: ['numbers'], es: 'trece', en: 'thirteen', pos: 'number' },
  { id: 'v.catorce', kind: 'vocab', level: 'A1', topics: ['numbers'], es: 'catorce', en: 'fourteen', pos: 'number' },
  { id: 'v.quince', kind: 'vocab', level: 'A1', topics: ['numbers'], es: 'quince', en: 'fifteen', pos: 'number' },
  {
    id: 'v.dieciseis',
    kind: 'vocab',
    level: 'A1',
    topics: ['numbers'],
    es: 'dieciséis',
    en: 'sixteen',
    pos: 'number',
    note: 'From here to 29 Spanish writes the number as one word: diez y seis became dieciséis.',
  },
  { id: 'v.diecisiete', kind: 'vocab', level: 'A1', topics: ['numbers'], es: 'diecisiete', en: 'seventeen', pos: 'number' },
  { id: 'v.dieciocho', kind: 'vocab', level: 'A1', topics: ['numbers'], es: 'dieciocho', en: 'eighteen', pos: 'number' },
  { id: 'v.diecinueve', kind: 'vocab', level: 'A1', topics: ['numbers'], es: 'diecinueve', en: 'nineteen', pos: 'number' },
  {
    id: 'v.veintiuno',
    kind: 'vocab',
    level: 'A1',
    topics: ['numbers'],
    es: 'veintiuno',
    en: 'twenty-one',
    pos: 'number',
    note: 'Drops to veintiún before a masculine noun: veintiún años.',
  },
  {
    id: 'v.cuarenta',
    kind: 'vocab',
    level: 'A1',
    topics: ['numbers'],
    es: 'cuarenta',
    en: 'forty',
    pos: 'number',
    note: 'From thirty upwards the tens are joined with y: cuarenta y dos.',
  },
  { id: 'v.cincuenta', kind: 'vocab', level: 'A1', topics: ['numbers'], es: 'cincuenta', en: 'fifty', pos: 'number' },
  { id: 'v.sesenta', kind: 'vocab', level: 'A1', topics: ['numbers'], es: 'sesenta', en: 'sixty', pos: 'number' },
  { id: 'v.setenta', kind: 'vocab', level: 'A1', topics: ['numbers'], es: 'setenta', en: 'seventy', pos: 'number' },
  { id: 'v.ochenta', kind: 'vocab', level: 'A1', topics: ['numbers'], es: 'ochenta', en: 'eighty', pos: 'number' },
  { id: 'v.noventa', kind: 'vocab', level: 'A1', topics: ['numbers'], es: 'noventa', en: 'ninety', pos: 'number' },
  {
    id: 'v.mil',
    kind: 'vocab',
    level: 'A1',
    topics: ['numbers'],
    es: 'mil',
    en: 'a thousand',
    pos: 'number',
    note: 'Never un mil — just mil. Years are read straight: mil novecientos noventa (1990).',
  },
  {
    id: 'v.numero',
    kind: 'vocab',
    level: 'A1',
    topics: ['numbers'],
    es: 'el número',
    en: 'the number',
    pos: 'noun',
    gender: 'm',
  },

  // --- Spelling ------------------------------------------------------------
  {
    id: 'p.como-se-escribe',
    kind: 'phrase',
    level: 'A1',
    topics: ['introductions'],
    es: '¿Cómo se escribe?',
    en: 'how do you spell it?',
    pos: 'expression',
    note: 'The question you will need every time you give your name in Spain.',
  },
  {
    id: 'p.se-escribe-con',
    kind: 'phrase',
    level: 'A1',
    topics: ['introductions'],
    es: 'se escribe con…',
    en: "it's spelled with…",
    pos: 'expression',
    note: 'Spaniards spell out loud constantly: se escribe con hache, con be…',
  },
  {
    id: 'v.letra',
    kind: 'vocab',
    level: 'A1',
    topics: ['introductions'],
    es: 'la letra',
    en: 'the letter',
    pos: 'noun',
    gender: 'f',
  },
  {
    id: 'p.puedes-repetir',
    kind: 'phrase',
    level: 'A1',
    topics: ['greetings'],
    es: '¿Puedes repetir, por favor?',
    en: 'can you say that again, please?',
    pos: 'expression',
    note: 'Learn this before anything else — it is what keeps a conversation alive.',
  },
  {
    id: 'p.mas-despacio',
    kind: 'phrase',
    level: 'A1',
    topics: ['greetings'],
    es: 'más despacio, por favor',
    en: 'slower, please',
    pos: 'expression',
  },
  {
    id: 'p.no-entiendo',
    kind: 'phrase',
    level: 'A0',
    topics: ['greetings'],
    es: 'no entiendo',
    en: "I don't understand",
    pos: 'expression',
  },

  // --- The calendar --------------------------------------------------------
  { id: 'v.martes', kind: 'vocab', level: 'A1', topics: ['time'], es: 'el martes', en: 'Tuesday', pos: 'noun', gender: 'm' },
  { id: 'v.miercoles', kind: 'vocab', level: 'A1', topics: ['time'], es: 'el miércoles', en: 'Wednesday', pos: 'noun', gender: 'm' },
  { id: 'v.jueves', kind: 'vocab', level: 'A1', topics: ['time'], es: 'el jueves', en: 'Thursday', pos: 'noun', gender: 'm' },
  { id: 'v.sabado', kind: 'vocab', level: 'A1', topics: ['time'], es: 'el sábado', en: 'Saturday', pos: 'noun', gender: 'm' },
  {
    id: 'v.domingo',
    kind: 'vocab',
    level: 'A1',
    topics: ['time'],
    es: 'el domingo',
    en: 'Sunday',
    pos: 'noun',
    gender: 'm',
    note: 'Days are lower-case in Spanish, and "on Monday" is just el lunes — no preposition.',
  },
  { id: 'v.dia', kind: 'vocab', level: 'A0', topics: ['time'], es: 'el día', en: 'the day', pos: 'noun', gender: 'm', note: 'Ends in -a but is masculine: el día, un buen día.' },
  { id: 'v.semana', kind: 'vocab', level: 'A1', topics: ['time'], es: 'la semana', en: 'the week', pos: 'noun', gender: 'f' },
  { id: 'v.mes', kind: 'vocab', level: 'A1', topics: ['time'], es: 'el mes', en: 'the month', pos: 'noun', gender: 'm' },
  { id: 'v.ano-time', kind: 'vocab', level: 'A1', topics: ['time'], es: 'el año', en: 'the year', pos: 'noun', gender: 'm' },
  { id: 'v.enero', kind: 'vocab', level: 'A1', topics: ['time'], es: 'enero', en: 'January', pos: 'noun', gender: 'm' },
  { id: 'v.febrero', kind: 'vocab', level: 'A1', topics: ['time'], es: 'febrero', en: 'February', pos: 'noun', gender: 'm' },
  { id: 'v.marzo', kind: 'vocab', level: 'A1', topics: ['time'], es: 'marzo', en: 'March', pos: 'noun', gender: 'm' },
  { id: 'v.abril', kind: 'vocab', level: 'A1', topics: ['time'], es: 'abril', en: 'April', pos: 'noun', gender: 'm' },
  { id: 'v.mayo', kind: 'vocab', level: 'A1', topics: ['time'], es: 'mayo', en: 'May', pos: 'noun', gender: 'm' },
  { id: 'v.junio', kind: 'vocab', level: 'A1', topics: ['time'], es: 'junio', en: 'June', pos: 'noun', gender: 'm' },
  { id: 'v.julio', kind: 'vocab', level: 'A1', topics: ['time'], es: 'julio', en: 'July', pos: 'noun', gender: 'm' },
  { id: 'v.agosto', kind: 'vocab', level: 'A1', topics: ['time'], es: 'agosto', en: 'August', pos: 'noun', gender: 'm', note: 'Half of Spain is on holiday in August — shops and offices close for weeks.' },
  { id: 'v.septiembre', kind: 'vocab', level: 'A1', topics: ['time'], es: 'septiembre', en: 'September', pos: 'noun', gender: 'm' },
  { id: 'v.octubre', kind: 'vocab', level: 'A1', topics: ['time'], es: 'octubre', en: 'October', pos: 'noun', gender: 'm' },
  { id: 'v.noviembre', kind: 'vocab', level: 'A1', topics: ['time'], es: 'noviembre', en: 'November', pos: 'noun', gender: 'm' },
  { id: 'v.diciembre', kind: 'vocab', level: 'A1', topics: ['time'], es: 'diciembre', en: 'December', pos: 'noun', gender: 'm' },
  {
    id: 'p.cuando-es-tu-cumple',
    kind: 'phrase',
    level: 'A1',
    topics: ['time', 'social'],
    es: '¿Cuándo es tu cumpleaños?',
    en: 'when is your birthday?',
    pos: 'expression',
    note: 'Answer with el + number + de + month: el doce de marzo.',
  },
  {
    id: 'v.cumpleanos',
    kind: 'vocab',
    level: 'A1',
    topics: ['time', 'social'],
    es: 'el cumpleaños',
    en: 'the birthday',
    pos: 'noun',
    gender: 'm',
    note: 'Already plural in form — el cumpleaños, los cumpleaños.',
  },

  // --- Countries and nationalities ----------------------------------------
  {
    id: 'v.pais',
    kind: 'vocab',
    level: 'A1',
    topics: ['introductions'],
    es: 'el país',
    en: 'the country',
    pos: 'noun',
    gender: 'm',
  },
  { id: 'v.espana', kind: 'vocab', level: 'A0', topics: ['introductions'], es: 'España', en: 'Spain', pos: 'noun', gender: 'f' },
  { id: 'v.inglaterra', kind: 'vocab', level: 'A1', topics: ['introductions'], es: 'Inglaterra', en: 'England', pos: 'noun', gender: 'f' },
  {
    id: 'v.ingles',
    kind: 'vocab',
    level: 'A1',
    topics: ['introductions'],
    es: 'inglés / inglesa',
    en: 'English',
    pos: 'adjective',
    note: 'Nationalities are lower-case. The masculine loses its accent in the feminine: inglés → inglesa.',
  },
  { id: 'v.francia', kind: 'vocab', level: 'A1', topics: ['introductions'], es: 'Francia', en: 'France', pos: 'noun', gender: 'f' },
  { id: 'v.frances', kind: 'vocab', level: 'A1', topics: ['introductions'], es: 'francés / francesa', en: 'French', pos: 'adjective' },
  { id: 'v.alemania', kind: 'vocab', level: 'A1', topics: ['introductions'], es: 'Alemania', en: 'Germany', pos: 'noun', gender: 'f' },
  { id: 'v.aleman', kind: 'vocab', level: 'A1', topics: ['introductions'], es: 'alemán / alemana', en: 'German', pos: 'adjective' },
  { id: 'v.italia', kind: 'vocab', level: 'A1', topics: ['introductions'], es: 'Italia', en: 'Italy', pos: 'noun', gender: 'f' },
  { id: 'v.italiano', kind: 'vocab', level: 'A1', topics: ['introductions'], es: 'italiano / italiana', en: 'Italian', pos: 'adjective' },
  { id: 'v.eslovenia', kind: 'vocab', level: 'A1', topics: ['introductions'], es: 'Eslovenia', en: 'Slovenia', pos: 'noun', gender: 'f' },
  {
    id: 'v.idioma',
    kind: 'vocab',
    level: 'A1',
    topics: ['introductions'],
    es: 'el idioma',
    en: 'the language',
    pos: 'noun',
    gender: 'm',
    note: 'Masculine despite the -a: el idioma, los idiomas.',
  },
  {
    id: 'p.hablo-un-poco',
    kind: 'phrase',
    level: 'A1',
    topics: ['introductions'],
    es: 'hablo un poco de español',
    en: 'I speak a bit of Spanish',
    pos: 'expression',
  },

  // --- Colours -------------------------------------------------------------
  { id: 'v.rojo', kind: 'vocab', level: 'A1', topics: ['describing'], es: 'rojo / roja', en: 'red', pos: 'adjective' },
  {
    id: 'v.azul',
    kind: 'vocab',
    level: 'A1',
    topics: ['describing'],
    es: 'azul',
    en: 'blue',
    pos: 'adjective',
    note: 'Ends in a consonant, so it has no separate feminine: un coche azul, una casa azul.',
  },
  { id: 'v.verde', kind: 'vocab', level: 'A1', topics: ['describing'], es: 'verde', en: 'green', pos: 'adjective' },
  { id: 'v.amarillo', kind: 'vocab', level: 'A1', topics: ['describing'], es: 'amarillo / amarilla', en: 'yellow', pos: 'adjective' },
  { id: 'v.negro', kind: 'vocab', level: 'A1', topics: ['describing'], es: 'negro / negra', en: 'black', pos: 'adjective' },
  { id: 'v.blanco', kind: 'vocab', level: 'A1', topics: ['describing'], es: 'blanco / blanca', en: 'white', pos: 'adjective' },
  { id: 'v.gris', kind: 'vocab', level: 'A1', topics: ['describing'], es: 'gris', en: 'grey', pos: 'adjective' },
  {
    id: 'v.color',
    kind: 'vocab',
    level: 'A1',
    topics: ['describing'],
    es: 'el color',
    en: 'the colour',
    pos: 'noun',
    gender: 'm',
  },

  // --- Weather -------------------------------------------------------------
  {
    id: 'p.que-tiempo-hace',
    kind: 'phrase',
    level: 'A1',
    topics: ['weather'],
    es: '¿Qué tiempo hace?',
    en: "what's the weather like?",
    pos: 'expression',
    note: 'Spanish uses hacer for weather, so literally "what weather does it make?".',
  },
  { id: 'p.hace-calor', kind: 'phrase', level: 'A1', topics: ['weather'], es: 'hace calor', en: "it's hot", pos: 'expression' },
  { id: 'p.hace-frio', kind: 'phrase', level: 'A1', topics: ['weather'], es: 'hace frío', en: "it's cold", pos: 'expression' },
  { id: 'p.hace-sol', kind: 'phrase', level: 'A1', topics: ['weather'], es: 'hace sol', en: "it's sunny", pos: 'expression' },
  {
    id: 'p.hace-viento',
    kind: 'phrase',
    level: 'A1',
    topics: ['weather'],
    es: 'hace viento',
    en: "it's windy",
    pos: 'expression',
  },
  {
    id: 'v.llover',
    kind: 'vocab',
    level: 'A1',
    topics: ['weather'],
    es: 'llueve',
    en: "it's raining / it rains",
    pos: 'verb',
    note: 'Only ever used in this one form — there is no "yo lluevo".',
  },
  {
    id: 'v.tiempo',
    kind: 'vocab',
    level: 'A1',
    topics: ['weather', 'time'],
    es: 'el tiempo',
    en: 'the weather / the time',
    pos: 'noun',
    gender: 'm',
    note: 'Both meanings share one word. Context decides: hace buen tiempo vs no tengo tiempo.',
  },

  // --- Describing people ---------------------------------------------------
  { id: 'v.alto', kind: 'vocab', level: 'A1', topics: ['describing'], es: 'alto / alta', en: 'tall', pos: 'adjective' },
  { id: 'v.bajo', kind: 'vocab', level: 'A1', topics: ['describing'], es: 'bajo / baja', en: 'short (in height)', pos: 'adjective' },
  { id: 'v.rubio', kind: 'vocab', level: 'A1', topics: ['describing'], es: 'rubio / rubia', en: 'blond / fair-haired', pos: 'adjective' },
  { id: 'v.moreno', kind: 'vocab', level: 'A1', topics: ['describing'], es: 'moreno / morena', en: 'dark-haired', pos: 'adjective' },
  {
    id: 'v.simpatico',
    kind: 'vocab',
    level: 'A1',
    topics: ['describing'],
    es: 'simpático / simpática',
    en: 'friendly / nice',
    pos: 'adjective',
    note: 'A false friend: it means warm and likeable, not "sympathetic".',
  },
  { id: 'v.guapo', kind: 'vocab', level: 'A1', topics: ['describing'], es: 'guapo / guapa', en: 'good-looking', pos: 'adjective' },
  { id: 'v.joven', kind: 'vocab', level: 'A1', topics: ['describing'], es: 'joven', en: 'young', pos: 'adjective' },
  {
    id: 'v.mayor',
    kind: 'vocab',
    level: 'A1',
    topics: ['describing', 'family'],
    es: 'mayor',
    en: 'older / elderly',
    pos: 'adjective',
    note: 'The polite word for an older person — viejo about people can sound blunt.',
  },
  { id: 'v.pelo', kind: 'vocab', level: 'A1', topics: ['describing'], es: 'el pelo', en: 'the hair', pos: 'noun', gender: 'm' },
  { id: 'v.ojos', kind: 'vocab', level: 'A1', topics: ['describing'], es: 'los ojos', en: 'the eyes', pos: 'noun', gender: 'm' },

  // --- Possessives ---------------------------------------------------------
  {
    id: 'v.mi',
    kind: 'vocab',
    level: 'A0',
    topics: ['family', 'people'],
    es: 'mi / mis',
    en: 'my',
    pos: 'determiner',
    note: 'Agrees with the thing owned, not the owner: mi hermano, mis hermanos.',
  },
  { id: 'v.tu-pos', kind: 'vocab', level: 'A1', topics: ['family', 'people'], es: 'tu / tus', en: 'your', pos: 'determiner', note: 'No accent — tu casa is "your house", tú is "you".' },
  {
    id: 'v.su',
    kind: 'vocab',
    level: 'A1',
    topics: ['family', 'people'],
    es: 'su / sus',
    en: 'his / her / their / your (formal)',
    pos: 'determiner',
    note: 'One word covering all of them. Spanish leaves the owner to context.',
  },
  { id: 'v.nuestro', kind: 'vocab', level: 'A1', topics: ['family', 'people'], es: 'nuestro / nuestra', en: 'our', pos: 'determiner' },
  {
    id: 'v.vuestro',
    kind: 'vocab',
    level: 'A1',
    topics: ['family', 'people'],
    es: 'vuestro / vuestra',
    en: 'your (plural)',
    pos: 'determiner',
    spainOnly: true,
    regional: { spain: 'vuestro coche', latam: 'su coche', note: 'The possessive that goes with vosotros — Spain only.' },
  },

  // --- Demonstratives ------------------------------------------------------
  {
    id: 'v.este',
    kind: 'vocab',
    level: 'A1',
    topics: ['describing', 'shopping'],
    es: 'este / esta',
    en: 'this',
    pos: 'determiner',
    note: 'For what is near you. Shop Spanish runs on it: quiero este.',
  },
  {
    id: 'v.ese',
    kind: 'vocab',
    level: 'A1',
    topics: ['describing', 'shopping'],
    es: 'ese / esa',
    en: 'that',
    pos: 'determiner',
    note: 'For what is near the other person — a distinction English does not make.',
  },
  {
    id: 'v.aquel',
    kind: 'vocab',
    level: 'A1',
    topics: ['describing'],
    es: 'aquel / aquella',
    en: 'that one over there',
    pos: 'determiner',
    note: 'Third level of distance: far from both of you.',
  },

  // --- Small words that hold sentences together ----------------------------
  { id: 'v.en', kind: 'vocab', level: 'A0', topics: ['city'], es: 'en', en: 'in / on / at', pos: 'preposition' },
  { id: 'v.de', kind: 'vocab', level: 'A0', topics: ['introductions'], es: 'de', en: 'of / from', pos: 'preposition' },
  { id: 'v.a-prep', kind: 'vocab', level: 'A0', topics: ['city'], es: 'a', en: 'to', pos: 'preposition' },
  { id: 'v.con', kind: 'vocab', level: 'A0', topics: ['social'], es: 'con', en: 'with', pos: 'preposition' },
  { id: 'v.sin', kind: 'vocab', level: 'A1', topics: ['cafe'], es: 'sin', en: 'without', pos: 'preposition' },
  { id: 'v.para-prep', kind: 'vocab', level: 'A1', topics: ['cafe'], es: 'para', en: 'for / in order to', pos: 'preposition' },
  { id: 'v.aqui', kind: 'vocab', level: 'A1', topics: ['city'], es: 'aquí', en: 'here', pos: 'adverb' },
  { id: 'v.alli', kind: 'vocab', level: 'A1', topics: ['city'], es: 'allí', en: 'there', pos: 'adverb' },
  { id: 'v.mas', kind: 'vocab', level: 'A1', topics: ['describing'], es: 'más', en: 'more', pos: 'adverb' },
  { id: 'v.menos', kind: 'vocab', level: 'A1', topics: ['describing'], es: 'menos', en: 'less / fewer', pos: 'adverb' },
  { id: 'v.otro', kind: 'vocab', level: 'A1', topics: ['shopping'], es: 'otro / otra', en: 'another / other', pos: 'determiner', note: 'Never un otro — just otro café.' },
  { id: 'v.todo', kind: 'vocab', level: 'A1', topics: ['describing'], es: 'todo / toda', en: 'all / everything', pos: 'determiner' },
  { id: 'v.bien', kind: 'vocab', level: 'A0', topics: ['feelings'], es: 'bien', en: 'well / fine', pos: 'adverb' },
  { id: 'v.mal', kind: 'vocab', level: 'A1', topics: ['feelings'], es: 'mal', en: 'badly / bad', pos: 'adverb' },

  // --- More food and drink -------------------------------------------------
  { id: 'v.leche', kind: 'vocab', level: 'A1', topics: ['food'], es: 'la leche', en: 'the milk', pos: 'noun', gender: 'f' },
  { id: 'v.cerveza', kind: 'vocab', level: 'A1', topics: ['food', 'cafe'], es: 'la cerveza', en: 'the beer', pos: 'noun', gender: 'f' },
  { id: 'v.vino', kind: 'vocab', level: 'A1', topics: ['food', 'restaurant'], es: 'el vino', en: 'the wine', pos: 'noun', gender: 'm' },
  { id: 'v.fruta', kind: 'vocab', level: 'A1', topics: ['food'], es: 'la fruta', en: 'the fruit', pos: 'noun', gender: 'f' },
  { id: 'v.verdura', kind: 'vocab', level: 'A1', topics: ['food'], es: 'la verdura', en: 'the vegetables', pos: 'noun', gender: 'f' },
  { id: 'v.carne', kind: 'vocab', level: 'A1', topics: ['food'], es: 'la carne', en: 'the meat', pos: 'noun', gender: 'f' },
  { id: 'v.pescado', kind: 'vocab', level: 'A1', topics: ['food'], es: 'el pescado', en: 'the fish (as food)', pos: 'noun', gender: 'm' },
  { id: 'v.queso', kind: 'vocab', level: 'A1', topics: ['food'], es: 'el queso', en: 'the cheese', pos: 'noun', gender: 'm' },
  {
    id: 'v.jamon',
    kind: 'vocab',
    level: 'A1',
    topics: ['food'],
    es: 'el jamón',
    en: 'the cured ham',
    pos: 'noun',
    gender: 'm',
    note: 'Jamón serrano is the everyday one; jamón ibérico is the expensive one worth the money.',
  },
  { id: 'v.huevo', kind: 'vocab', level: 'A1', topics: ['food'], es: 'el huevo', en: 'the egg', pos: 'noun', gender: 'm' },
  { id: 'v.pollo', kind: 'vocab', level: 'A1', topics: ['food'], es: 'el pollo', en: 'the chicken', pos: 'noun', gender: 'm' },
  { id: 'v.arroz', kind: 'vocab', level: 'A1', topics: ['food'], es: 'el arroz', en: 'the rice', pos: 'noun', gender: 'm' },

  // --- Asking for what you want -------------------------------------------
  {
    id: 'p.quiero',
    kind: 'phrase',
    level: 'A1',
    topics: ['cafe', 'shopping'],
    es: 'quiero…',
    en: 'I want…',
    pos: 'expression',
    note: 'Direct but normal in a bar. Softened to querría or me pones for anything more formal.',
  },
  {
    id: 'p.quisiera',
    kind: 'phrase',
    level: 'A1',
    topics: ['restaurant', 'shopping'],
    es: 'quisiera…',
    en: 'I would like…',
    pos: 'expression',
    register: 'formal',
  },
  {
    id: 'p.hay-que-comer',
    kind: 'phrase',
    level: 'A1',
    topics: ['food'],
    es: '¿Qué hay para comer?',
    en: "what is there to eat?",
    pos: 'expression',
  },
];
