import type { VocabConcept } from '@/content/types';

/**
 * A2 vocabulary the course was missing: health and the body, clothes, and the
 * language of comparing and preferring things.
 *
 * A2 is where a learner stops naming objects and starts handling situations —
 * a chemist, a changing room, an argument about which city is better — so the
 * chunks matter at least as much as the nouns.
 */
export const a2CoreVocab: VocabConcept[] = [
  // --- Health and the body -------------------------------------------------
  {
    id: 'p.que-te-pasa',
    kind: 'phrase',
    level: 'A2',
    topics: ['health'],
    es: '¿Qué te pasa?',
    en: "what's wrong?",
    pos: 'expression',
    note: 'The everyday way to ask. ¿Qué le pasa? if you are using usted.',
  },
  {
    id: 'p.me-duele',
    kind: 'phrase',
    level: 'A2',
    topics: ['health'],
    es: 'me duele…',
    en: '… hurts',
    pos: 'expression',
    note: 'Works like gustar: me duele la cabeza, me duelen los pies. The body part is the subject.',
  },
  {
    id: 'p.estoy-malo',
    kind: 'phrase',
    level: 'A2',
    topics: ['health'],
    es: 'estoy malo / mala',
    en: "I'm ill",
    pos: 'expression',
    spainOnly: true,
    note: 'Spain says estoy malo far more than estoy enfermo, which sounds serious.',
  },
  { id: 'v.cabeza', kind: 'vocab', level: 'A2', topics: ['health'], es: 'la cabeza', en: 'the head', pos: 'noun', gender: 'f' },
  { id: 'v.estomago', kind: 'vocab', level: 'A2', topics: ['health'], es: 'el estómago', en: 'the stomach', pos: 'noun', gender: 'm' },
  { id: 'v.garganta', kind: 'vocab', level: 'A2', topics: ['health'], es: 'la garganta', en: 'the throat', pos: 'noun', gender: 'f' },
  { id: 'v.espalda', kind: 'vocab', level: 'A2', topics: ['health'], es: 'la espalda', en: 'the back', pos: 'noun', gender: 'f' },
  { id: 'v.mano', kind: 'vocab', level: 'A2', topics: ['health'], es: 'la mano', en: 'the hand', pos: 'noun', gender: 'f', note: 'Ends in -o but is feminine: la mano, las manos.' },
  { id: 'v.pie', kind: 'vocab', level: 'A2', topics: ['health'], es: 'el pie', en: 'the foot', pos: 'noun', gender: 'm' },
  {
    id: 'v.medico',
    kind: 'vocab',
    level: 'A2',
    topics: ['health'],
    es: 'el médico / la médica',
    en: 'the doctor',
    pos: 'noun',
    gender: 'mf',
  },
  { id: 'v.farmacia', kind: 'vocab', level: 'A2', topics: ['health', 'city'], es: 'la farmacia', en: 'the pharmacy', pos: 'noun', gender: 'f' },
  {
    id: 'v.cita',
    kind: 'vocab',
    level: 'A2',
    topics: ['health'],
    es: 'la cita',
    en: 'the appointment',
    pos: 'noun',
    gender: 'f',
    note: 'pedir cita is what you do at the health centre — and what everyone complains about.',
  },
  { id: 'v.fiebre', kind: 'vocab', level: 'A2', topics: ['health'], es: 'la fiebre', en: 'the fever', pos: 'noun', gender: 'f' },
  { id: 'v.resfriado', kind: 'vocab', level: 'A2', topics: ['health'], es: 'el resfriado', en: 'the cold (illness)', pos: 'noun', gender: 'm' },
  {
    id: 'p.que-te-mejores',
    kind: 'phrase',
    level: 'A2',
    topics: ['health', 'social'],
    es: 'que te mejores',
    en: 'get well soon',
    pos: 'expression',
    note: 'A fixed phrase — you are meeting the subjunctive here long before you study it.',
  },

  // --- Clothes and the changing room ---------------------------------------
  { id: 'v.ropa', kind: 'vocab', level: 'A2', topics: ['shopping'], es: 'la ropa', en: 'the clothes', pos: 'noun', gender: 'f', note: 'Singular in Spanish: la ropa está sucia.' },
  { id: 'v.camiseta', kind: 'vocab', level: 'A2', topics: ['shopping'], es: 'la camiseta', en: 'the T-shirt', pos: 'noun', gender: 'f' },
  { id: 'v.camisa', kind: 'vocab', level: 'A2', topics: ['shopping'], es: 'la camisa', en: 'the shirt', pos: 'noun', gender: 'f' },
  { id: 'v.pantalones', kind: 'vocab', level: 'A2', topics: ['shopping'], es: 'los pantalones', en: 'the trousers', pos: 'noun', gender: 'm', note: 'Always plural, like in English.' },
  { id: 'v.zapatos', kind: 'vocab', level: 'A2', topics: ['shopping'], es: 'los zapatos', en: 'the shoes', pos: 'noun', gender: 'm' },
  { id: 'v.chaqueta', kind: 'vocab', level: 'A2', topics: ['shopping'], es: 'la chaqueta', en: 'the jacket', pos: 'noun', gender: 'f' },
  { id: 'v.vestido', kind: 'vocab', level: 'A2', topics: ['shopping'], es: 'el vestido', en: 'the dress', pos: 'noun', gender: 'm' },
  {
    id: 'p.puedo-probarme',
    kind: 'phrase',
    level: 'A2',
    topics: ['shopping'],
    es: '¿Puedo probármelo?',
    en: 'can I try it on?',
    pos: 'expression',
    note: 'Two pronouns stuck on the end — you will meet the rule properly at B1, but learn the phrase now.',
  },
  {
    id: 'p.me-queda-bien',
    kind: 'phrase',
    level: 'A2',
    topics: ['shopping'],
    es: 'me queda bien',
    en: 'it fits me / it suits me',
    pos: 'expression',
    note: 'quedar again, but a completely different sense from "to meet up".',
  },
  {
    id: 'p.solo-estoy-mirando',
    kind: 'phrase',
    level: 'A2',
    topics: ['shopping'],
    es: 'solo estoy mirando',
    en: "I'm just looking",
    pos: 'expression',
    note: 'The polite escape from a shop assistant.',
  },

  // --- Comparing and preferring --------------------------------------------
  {
    id: 'v.mejor',
    kind: 'vocab',
    level: 'A2',
    topics: ['describing', 'opinions'],
    es: 'mejor',
    en: 'better / best',
    pos: 'adjective',
    confusableWith: ['v.mayor'],
    note: 'Never "más bueno" — mejor already means "more good".',
  },
  { id: 'v.peor', kind: 'vocab', level: 'A2', topics: ['describing', 'opinions'], es: 'peor', en: 'worse / worst', pos: 'adjective' },
  { id: 'v.tan', kind: 'vocab', level: 'A2', topics: ['describing'], es: 'tan… como', en: 'as… as', pos: 'adverb' },
  {
    id: 'v.preferir',
    kind: 'vocab',
    level: 'A2',
    topics: ['opinions', 'shopping'],
    es: 'preferir',
    en: 'to prefer',
    pos: 'verb',
    note: 'Stem change e → ie: prefiero, prefieres, prefiere… but preferimos.',
  },
  {
    id: 'p.prefiero-porque',
    kind: 'phrase',
    level: 'A2',
    topics: ['opinions'],
    es: 'prefiero… porque…',
    en: 'I prefer… because…',
    pos: 'expression',
    note: 'The A2 jump: not just stating a preference, but giving the reason.',
  },
  {
    id: 'p.no-soporto',
    kind: 'phrase',
    level: 'A2',
    topics: ['opinions'],
    es: 'no soporto…',
    en: "I can't stand…",
    pos: 'expression',
    register: 'colloquial',
  },
  {
    id: 'v.demasiado',
    kind: 'vocab',
    level: 'A2',
    topics: ['describing', 'shopping'],
    es: 'demasiado / demasiada',
    en: 'too / too much',
    pos: 'adverb',
    note: 'demasiado caro = too expensive. Distinct from muy caro, which is only "very".',
  },
  {
    id: 'v.bastante',
    kind: 'vocab',
    level: 'A2',
    topics: ['describing'],
    es: 'bastante',
    en: 'quite / fairly / enough',
    pos: 'adverb',
    note: 'Usually positive in Spain: bastante bien means "pretty good", not "barely acceptable".',
  },
];
