import type { VocabConcept } from '@/content/types';

/** Getting around, ordering, paying — the language of actually being in Spain. */
export const aroundSpainVocab: VocabConcept[] = [
  // --- Directions ----------------------------------------------------------
  {
    id: 'p.donde-esta',
    kind: 'phrase',
    level: 'A1',
    topics: ['directions'],
    es: '¿Dónde está…?',
    en: 'where is…?',
    pos: 'expression',
    note: 'Estar, not ser — location always takes estar.',
  },
  {
    id: 'p.perdona-donde',
    kind: 'phrase',
    level: 'A2',
    topics: ['directions'],
    es: 'Perdona, ¿sabes dónde está…?',
    en: 'excuse me, do you know where … is?',
    pos: 'expression',
    note: 'Softer than a bare ¿dónde está…? and what people actually say in the street.',
  },
  {
    id: 'v.derecha',
    kind: 'vocab',
    level: 'A1',
    topics: ['directions'],
    es: 'la derecha',
    en: 'the right',
    pos: 'noun',
    gender: 'f',
    note: 'A la derecha = on/to the right.',
  },
  {
    id: 'v.izquierda',
    kind: 'vocab',
    level: 'A1',
    topics: ['directions'],
    es: 'la izquierda',
    en: 'the left',
    pos: 'noun',
    gender: 'f',
  },
  {
    id: 'v.recto',
    kind: 'vocab',
    level: 'A1',
    topics: ['directions'],
    es: 'todo recto',
    en: 'straight on',
    pos: 'expression',
    spainOnly: true,
    regional: { spain: 'todo recto', latam: 'derecho' },
  },
  {
    id: 'v.cerca',
    kind: 'vocab',
    level: 'A1',
    topics: ['directions'],
    es: 'cerca',
    en: 'near / close',
    pos: 'adverb',
    note: 'Cerca de la plaza = near the square.',
  },
  {
    id: 'v.lejos',
    kind: 'vocab',
    level: 'A1',
    topics: ['directions'],
    es: 'lejos',
    en: 'far',
    pos: 'adverb',
  },
  {
    id: 'v.al-lado',
    kind: 'phrase',
    level: 'A2',
    topics: ['directions'],
    es: 'al lado de',
    en: 'next to',
    pos: 'expression',
  },
  {
    id: 'v.enfrente',
    kind: 'vocab',
    level: 'A2',
    topics: ['directions'],
    es: 'enfrente de',
    en: 'opposite / across from',
    pos: 'expression',
  },
  {
    id: 'v.delante',
    kind: 'vocab',
    level: 'A2',
    topics: ['directions'],
    es: 'delante de',
    en: 'in front of',
    pos: 'expression',
  },
  {
    id: 'v.esquina',
    kind: 'vocab',
    level: 'A2',
    topics: ['directions', 'city'],
    es: 'la esquina',
    en: 'the corner',
    pos: 'noun',
    gender: 'f',
  },
  {
    id: 'v.girar',
    kind: 'vocab',
    level: 'A2',
    topics: ['directions'],
    es: 'girar',
    en: 'to turn',
    pos: 'verb',
    verbId: 'girar',
  },
  {
    id: 'v.seguir',
    kind: 'vocab',
    level: 'A2',
    topics: ['directions'],
    es: 'seguir',
    en: 'to continue / to carry on',
    pos: 'verb',
    verbId: 'seguir',
    note: 'Sigue todo recto = carry straight on.',
  },

  // --- Transport ------------------------------------------------------------
  {
    id: 'v.metro',
    kind: 'vocab',
    level: 'A1',
    topics: ['transport'],
    es: 'el metro',
    en: 'the metro / underground',
    pos: 'noun',
    gender: 'm',
  },
  {
    id: 'v.autobus',
    kind: 'vocab',
    level: 'A1',
    topics: ['transport'],
    es: 'el autobús',
    en: 'the bus',
    pos: 'noun',
    gender: 'm',
    note: 'Shortened to el bus in speech.',
  },
  {
    id: 'v.tren',
    kind: 'vocab',
    level: 'A1',
    topics: ['transport', 'travel'],
    es: 'el tren',
    en: 'the train',
    pos: 'noun',
    gender: 'm',
  },
  {
    id: 'v.billete',
    kind: 'vocab',
    level: 'A2',
    topics: ['transport', 'travel'],
    es: 'el billete',
    en: 'the ticket (travel)',
    pos: 'noun',
    gender: 'm',
    spainOnly: true,
    regional: { spain: 'el billete', latam: 'el boleto / pasaje' },
    note: 'Travel ticket. For a concert or museum you want una entrada instead.',
    confusableWith: ['v.entrada'],
  },
  {
    id: 'v.entrada',
    kind: 'vocab',
    level: 'A2',
    topics: ['transport', 'hobbies'],
    es: 'la entrada',
    en: 'the ticket (event) / the entrance',
    pos: 'noun',
    gender: 'f',
    confusableWith: ['v.billete'],
    note: 'Cinema, concert, museum. Also the way in.',
  },
  {
    id: 'v.parada',
    kind: 'vocab',
    level: 'A2',
    topics: ['transport'],
    es: 'la parada',
    en: 'the stop',
    pos: 'noun',
    gender: 'f',
  },
  {
    id: 'v.estacion',
    kind: 'vocab',
    level: 'A2',
    topics: ['transport', 'travel'],
    es: 'la estación',
    en: 'the station',
    pos: 'noun',
    gender: 'f',
  },
  {
    id: 'v.andar',
    kind: 'vocab',
    level: 'A2',
    topics: ['transport'],
    es: 'andar / ir andando',
    en: 'to walk / to go on foot',
    pos: 'verb',
    spainOnly: true,
    note: 'Voy andando is the normal way to say "I’ll walk" in Spain.',
  },

  // --- Café and restaurant --------------------------------------------------
  {
    id: 'p.me-pones',
    kind: 'phrase',
    level: 'A2',
    topics: ['cafe', 'restaurant'],
    es: '¿Me pones…?',
    en: 'can I get…? (in a bar)',
    pos: 'expression',
    register: 'colloquial',
    spainOnly: true,
    note: 'The natural bar order in Spain: "¿Me pones una caña?" Sounds friendlier than quiero.',
  },
  {
    id: 'p.me-puede-poner',
    kind: 'phrase',
    level: 'A2',
    topics: ['cafe', 'restaurant'],
    es: '¿Me puede poner…?',
    en: 'could you get me…?',
    pos: 'expression',
    register: 'formal',
  },
  {
    id: 'p.para-tomar-aqui',
    kind: 'phrase',
    level: 'A2',
    topics: ['cafe'],
    es: '¿Para tomar aquí o para llevar?',
    en: 'to have here or takeaway?',
    pos: 'expression',
  },
  {
    id: 'p.la-cuenta-porfa',
    kind: 'phrase',
    level: 'A2',
    topics: ['restaurant'],
    es: 'La cuenta, por favor.',
    en: 'the bill, please',
    pos: 'expression',
  },
  {
    id: 'v.camarero',
    kind: 'vocab',
    level: 'A2',
    topics: ['restaurant', 'work'],
    es: 'el camarero / la camarera',
    en: 'the waiter / waitress',
    pos: 'noun',
    gender: 'mf',
  },
  {
    id: 'v.mesa',
    kind: 'vocab',
    level: 'A1',
    topics: ['restaurant', 'home'],
    es: 'la mesa',
    en: 'the table',
    pos: 'noun',
    gender: 'f',
  },
  {
    id: 'v.reservar',
    kind: 'vocab',
    level: 'A2',
    topics: ['restaurant', 'travel'],
    es: 'reservar',
    en: 'to book / to reserve',
    pos: 'verb',
    verbId: 'reservar',
  },
  {
    id: 'p.menu-del-dia',
    kind: 'phrase',
    level: 'A2',
    topics: ['restaurant', 'food'],
    es: 'el menú del día',
    en: 'the set lunch menu',
    pos: 'expression',
    spainOnly: true,
    note: 'Weekday lunch institution: starter, main, bread, drink and dessert for one price.',
  },
  {
    id: 'v.primero',
    kind: 'vocab',
    level: 'A2',
    topics: ['restaurant'],
    es: 'el primero / el segundo',
    en: 'the starter / the main course',
    pos: 'noun',
    gender: 'm',
    spainOnly: true,
  },

  // --- Shopping and paying --------------------------------------------------
  {
    id: 'p.cuanto-cuesta',
    kind: 'phrase',
    level: 'A1',
    topics: ['shopping'],
    es: '¿Cuánto cuesta?',
    en: 'how much does it cost?',
    pos: 'expression',
  },
  {
    id: 'p.cuanto-es',
    kind: 'phrase',
    level: 'A1',
    topics: ['shopping', 'cafe'],
    es: '¿Cuánto es?',
    en: 'how much is it?',
    pos: 'expression',
    note: 'What you say at the till when you are paying for what you just had.',
  },
  {
    id: 'v.pagar',
    kind: 'vocab',
    level: 'A1',
    topics: ['shopping'],
    es: 'pagar',
    en: 'to pay',
    pos: 'verb',
    verbId: 'pagar',
  },
  {
    id: 'p.con-tarjeta',
    kind: 'phrase',
    level: 'A2',
    topics: ['shopping'],
    es: '¿Con tarjeta o en efectivo?',
    en: 'by card or in cash?',
    pos: 'expression',
  },
  {
    id: 'v.comprar',
    kind: 'vocab',
    level: 'A1',
    topics: ['shopping'],
    es: 'comprar',
    en: 'to buy',
    pos: 'verb',
    verbId: 'comprar',
  },
  {
    id: 'v.talla',
    kind: 'vocab',
    level: 'A2',
    topics: ['shopping'],
    es: 'la talla',
    en: 'the size (clothes)',
    pos: 'noun',
    gender: 'f',
    note: 'Talla for clothes, número for shoes.',
  },
  {
    id: 'v.probar',
    kind: 'vocab',
    level: 'A2',
    topics: ['shopping', 'food'],
    es: 'probar / probarse',
    en: 'to try / to try on',
    pos: 'verb',
    verbId: 'probar',
    note: '¿Me lo puedo probar? = can I try it on?',
  },

  // --- Travel ---------------------------------------------------------------
  {
    id: 'v.viaje',
    kind: 'vocab',
    level: 'A2',
    topics: ['travel'],
    es: 'el viaje',
    en: 'the trip / journey',
    pos: 'noun',
    gender: 'm',
  },
  {
    id: 'v.playa',
    kind: 'vocab',
    level: 'A1',
    topics: ['travel'],
    es: 'la playa',
    en: 'the beach',
    pos: 'noun',
    gender: 'f',
  },
  {
    id: 'v.hotel',
    kind: 'vocab',
    level: 'A1',
    topics: ['travel'],
    es: 'el hotel',
    en: 'the hotel',
    pos: 'noun',
    gender: 'm',
  },
  {
    id: 'v.llave',
    kind: 'vocab',
    level: 'A2',
    topics: ['travel', 'home'],
    es: 'la llave',
    en: 'the key',
    pos: 'noun',
    gender: 'f',
  },
  {
    id: 'v.maleta',
    kind: 'vocab',
    level: 'A2',
    topics: ['travel'],
    es: 'la maleta',
    en: 'the suitcase',
    pos: 'noun',
    gender: 'f',
  },
  {
    id: 'p.se-me-ha-olvidado',
    kind: 'phrase',
    level: 'B1',
    topics: ['travel', 'feelings'],
    es: 'se me ha olvidado',
    en: 'I forgot / it slipped my mind',
    pos: 'expression',
    note: 'Spanish loves this construction — the thing forgets itself on you rather than you forgetting it.',
  },
];
