import type { VocabConcept } from '@/content/types';

/** Numbers, time, family, food and the café — the fabric of an ordinary day. */
export const everydayVocab: VocabConcept[] = [
  // --- Numbers -------------------------------------------------------------
  {
    id: 'v.uno',
    kind: 'vocab',
    level: 'A0',
    topics: ['numbers'],
    es: 'uno / una',
    en: 'one',
    pos: 'number',
    note: 'Before a noun it shortens: un café, una caña.',
  },
  { id: 'v.dos', kind: 'vocab', level: 'A0', topics: ['numbers'], es: 'dos', en: 'two', pos: 'number' },
  { id: 'v.tres', kind: 'vocab', level: 'A0', topics: ['numbers'], es: 'tres', en: 'three', pos: 'number' },
  { id: 'v.cuatro', kind: 'vocab', level: 'A0', topics: ['numbers'], es: 'cuatro', en: 'four', pos: 'number' },
  { id: 'v.cinco', kind: 'vocab', level: 'A0', topics: ['numbers'], es: 'cinco', en: 'five', pos: 'number' },
  { id: 'v.seis', kind: 'vocab', level: 'A0', topics: ['numbers'], es: 'seis', en: 'six', pos: 'number' },
  { id: 'v.siete', kind: 'vocab', level: 'A0', topics: ['numbers'], es: 'siete', en: 'seven', pos: 'number' },
  { id: 'v.ocho', kind: 'vocab', level: 'A0', topics: ['numbers'], es: 'ocho', en: 'eight', pos: 'number' },
  { id: 'v.nueve', kind: 'vocab', level: 'A0', topics: ['numbers'], es: 'nueve', en: 'nine', pos: 'number' },
  { id: 'v.diez', kind: 'vocab', level: 'A0', topics: ['numbers'], es: 'diez', en: 'ten', pos: 'number' },
  {
    id: 'v.veinte',
    kind: 'vocab',
    level: 'A1',
    topics: ['numbers'],
    es: 'veinte',
    en: 'twenty',
    pos: 'number',
    note: '21–29 are written as one word: veintiuno, veintidós, veintitrés…',
  },
  {
    id: 'v.treinta',
    kind: 'vocab',
    level: 'A1',
    topics: ['numbers'],
    es: 'treinta',
    en: 'thirty',
    pos: 'number',
    note: 'From 31 upwards you need y: treinta y uno, cuarenta y dos.',
  },
  { id: 'v.cien', kind: 'vocab', level: 'A1', topics: ['numbers'], es: 'cien', en: 'a hundred', pos: 'number' },

  // --- Time ----------------------------------------------------------------
  {
    id: 'p.que-hora-es',
    kind: 'phrase',
    level: 'A1',
    topics: ['time'],
    es: '¿Qué hora es?',
    en: 'what time is it?',
    pos: 'expression',
  },
  {
    id: 'v.hora',
    kind: 'vocab',
    level: 'A1',
    topics: ['time'],
    es: 'la hora',
    en: 'the hour / the time',
    pos: 'noun',
    gender: 'f',
  },
  {
    id: 'p.son-las',
    kind: 'phrase',
    level: 'A1',
    topics: ['time'],
    es: 'son las',
    en: 'it’s … o’clock',
    pos: 'expression',
    note: 'Plural because you are counting hours: son las tres. Only one o’clock takes the singular — es la una.',
  },
  {
    id: 'v.media',
    kind: 'vocab',
    level: 'A1',
    topics: ['time'],
    es: 'y media',
    en: 'half past',
    pos: 'expression',
  },
  {
    id: 'v.cuarto',
    kind: 'vocab',
    level: 'A1',
    topics: ['time'],
    es: 'y cuarto / menos cuarto',
    en: 'quarter past / quarter to',
    pos: 'expression',
  },
  {
    id: 'p.sobre-las',
    kind: 'phrase',
    level: 'A2',
    topics: ['time', 'plans'],
    es: 'sobre las ocho',
    en: 'around eight',
    pos: 'expression',
    spainOnly: true,
    note: 'The everyday way to be vague about time in Spain. A las ocho is exact; sobre las ocho is realistic.',
  },
  {
    id: 'v.manana',
    kind: 'vocab',
    level: 'A1',
    topics: ['time'],
    es: 'mañana',
    en: 'tomorrow / morning',
    pos: 'adverb',
    note: 'Two meanings: mañana on its own is "tomorrow"; por la mañana is "in the morning".',
  },
  {
    id: 'v.hoy',
    kind: 'vocab',
    level: 'A1',
    topics: ['time'],
    es: 'hoy',
    en: 'today',
    pos: 'adverb',
  },
  {
    id: 'v.ayer',
    kind: 'vocab',
    level: 'A2',
    topics: ['time', 'past'],
    es: 'ayer',
    en: 'yesterday',
    pos: 'adverb',
  },
  {
    id: 'v.ahora',
    kind: 'vocab',
    level: 'A1',
    topics: ['time'],
    es: 'ahora',
    en: 'now',
    pos: 'adverb',
  },
  {
    id: 'v.siempre',
    kind: 'vocab',
    level: 'A1',
    topics: ['time', 'daily-routine'],
    es: 'siempre',
    en: 'always',
    pos: 'adverb',
  },
  {
    id: 'v.nunca',
    kind: 'vocab',
    level: 'A1',
    topics: ['time', 'daily-routine'],
    es: 'nunca',
    en: 'never',
    pos: 'adverb',
  },
  {
    id: 'v.a-veces',
    kind: 'phrase',
    level: 'A1',
    topics: ['time', 'daily-routine'],
    es: 'a veces',
    en: 'sometimes',
    pos: 'expression',
  },
  {
    id: 'v.tarde',
    kind: 'vocab',
    level: 'A1',
    topics: ['time'],
    es: 'la tarde',
    en: 'the afternoon / evening',
    pos: 'noun',
    gender: 'f',
    note: 'Stretches from lunch until dark — much longer than an English "afternoon".',
  },
  {
    id: 'v.noche',
    kind: 'vocab',
    level: 'A1',
    topics: ['time'],
    es: 'la noche',
    en: 'the night',
    pos: 'noun',
    gender: 'f',
  },
  {
    id: 'v.fin-de-semana',
    kind: 'vocab',
    level: 'A1',
    topics: ['time', 'plans'],
    es: 'el fin de semana',
    en: 'the weekend',
    pos: 'noun',
    gender: 'm',
  },
  {
    id: 'v.lunes',
    kind: 'vocab',
    level: 'A1',
    topics: ['time'],
    es: 'el lunes',
    en: 'Monday',
    pos: 'noun',
    gender: 'm',
    note: 'Days are lower-case, and "on Monday" is just el lunes — no preposition.',
  },
  {
    id: 'v.viernes',
    kind: 'vocab',
    level: 'A1',
    topics: ['time'],
    es: 'el viernes',
    en: 'Friday',
    pos: 'noun',
    gender: 'm',
  },

  // --- Family and people ---------------------------------------------------
  {
    id: 'v.familia',
    kind: 'vocab',
    level: 'A1',
    topics: ['family'],
    es: 'la familia',
    en: 'the family',
    pos: 'noun',
    gender: 'f',
  },
  {
    id: 'v.madre',
    kind: 'vocab',
    level: 'A1',
    topics: ['family'],
    es: 'la madre',
    en: 'the mother',
    pos: 'noun',
    gender: 'f',
    note: 'Day to day people say mi madre; mamá is what you call her directly.',
  },
  {
    id: 'v.padre',
    kind: 'vocab',
    level: 'A1',
    topics: ['family'],
    es: 'el padre',
    en: 'the father',
    pos: 'noun',
    gender: 'm',
    plural: 'los padres',
    note: 'Los padres means "the parents", not "the fathers".',
  },
  {
    id: 'v.hermano',
    kind: 'vocab',
    level: 'A1',
    topics: ['family'],
    es: 'el hermano / la hermana',
    en: 'the brother / the sister',
    pos: 'noun',
    gender: 'mf',
  },
  {
    id: 'v.hijo',
    kind: 'vocab',
    level: 'A1',
    topics: ['family'],
    es: 'el hijo / la hija',
    en: 'the son / the daughter',
    pos: 'noun',
    gender: 'mf',
  },
  {
    id: 'v.abuelo',
    kind: 'vocab',
    level: 'A2',
    topics: ['family'],
    es: 'el abuelo / la abuela',
    en: 'the grandfather / grandmother',
    pos: 'noun',
    gender: 'mf',
  },
  {
    id: 'v.amigo',
    kind: 'vocab',
    level: 'A0',
    topics: ['family', 'social'],
    es: 'el amigo / la amiga',
    en: 'the friend',
    pos: 'noun',
    gender: 'mf',
  },
  {
    id: 'v.novio',
    kind: 'vocab',
    level: 'A2',
    topics: ['family', 'social'],
    es: 'el novio / la novia',
    en: 'the boyfriend / girlfriend',
    pos: 'noun',
    gender: 'mf',
  },
  {
    id: 'v.companero',
    kind: 'vocab',
    level: 'A2',
    topics: ['university', 'work'],
    es: 'el compañero / la compañera',
    en: 'the classmate / colleague / flatmate',
    pos: 'noun',
    gender: 'mf',
    note: 'Hugely useful and hard to translate: compañero de piso, de clase, de trabajo.',
  },
  {
    id: 'v.gente',
    kind: 'vocab',
    level: 'A2',
    topics: ['people', 'social'],
    es: 'la gente',
    en: 'people',
    pos: 'noun',
    gender: 'f',
    note: 'Singular in Spanish: la gente es maja, not son majos.',
  },

  // --- Café and food -------------------------------------------------------
  {
    id: 'v.cafe',
    kind: 'vocab',
    level: 'A0',
    topics: ['cafe', 'food'],
    es: 'el café',
    en: 'the coffee / the café',
    pos: 'noun',
    gender: 'm',
  },
  {
    id: 'p.cafe-con-leche',
    kind: 'phrase',
    level: 'A1',
    topics: ['cafe'],
    es: 'un café con leche',
    en: 'a coffee with milk',
    pos: 'expression',
    note: 'The default Spanish coffee order. A cortado is an espresso with a splash of milk; a café solo is a straight espresso.',
  },
  {
    id: 'v.cana',
    kind: 'vocab',
    level: 'A2',
    topics: ['cafe', 'social'],
    es: 'la caña',
    en: 'a small draught beer',
    pos: 'noun',
    gender: 'f',
    spainOnly: true,
    note: 'About 200ml. Ordering "una caña" is the single most Spanish thing you can do in a bar.',
  },
  {
    id: 'v.tapa',
    kind: 'vocab',
    level: 'A2',
    topics: ['food', 'cafe'],
    es: 'la tapa',
    en: 'the tapa (small dish)',
    pos: 'noun',
    gender: 'f',
    spainOnly: true,
  },
  {
    id: 'v.agua',
    kind: 'vocab',
    level: 'A1',
    topics: ['food', 'cafe'],
    es: 'el agua',
    en: 'the water',
    pos: 'noun',
    gender: 'f',
    note: 'Feminine, but takes el to avoid two a-sounds colliding: el agua fría.',
  },
  {
    id: 'v.zumo',
    kind: 'vocab',
    level: 'A1',
    topics: ['food', 'cafe'],
    es: 'el zumo',
    en: 'the juice',
    pos: 'noun',
    gender: 'm',
    spainOnly: true,
    regional: { spain: 'el zumo', latam: 'el jugo' },
  },
  {
    id: 'v.pan',
    kind: 'vocab',
    level: 'A1',
    topics: ['food'],
    es: 'el pan',
    en: 'the bread',
    pos: 'noun',
    gender: 'm',
  },
  {
    id: 'v.tortilla',
    kind: 'vocab',
    level: 'A1',
    topics: ['food'],
    es: 'la tortilla',
    en: 'the Spanish omelette',
    pos: 'noun',
    gender: 'f',
    spainOnly: true,
    regional: {
      spain: 'tortilla = potato omelette',
      latam: 'tortilla = flatbread',
      note: 'Same word, completely different food. In Spain, ask for tortilla de patatas.',
    },
  },
  {
    id: 'v.desayuno',
    kind: 'vocab',
    level: 'A1',
    topics: ['food', 'daily-routine'],
    es: 'el desayuno',
    en: 'the breakfast',
    pos: 'noun',
    gender: 'm',
  },
  {
    id: 'v.comida',
    kind: 'vocab',
    level: 'A1',
    topics: ['food', 'daily-routine'],
    es: 'la comida',
    en: 'the food / the lunch',
    pos: 'noun',
    gender: 'f',
    note: 'In Spain la comida is usually the midday meal — the big one, around 2–3pm.',
  },
  {
    id: 'v.cena',
    kind: 'vocab',
    level: 'A1',
    topics: ['food', 'daily-routine'],
    es: 'la cena',
    en: 'the dinner',
    pos: 'noun',
    gender: 'f',
    note: 'Typically 9–10pm in Spain, and lighter than lunch.',
  },
  {
    id: 'v.cuenta',
    kind: 'vocab',
    level: 'A2',
    topics: ['restaurant', 'cafe'],
    es: 'la cuenta',
    en: 'the bill / the check',
    pos: 'noun',
    gender: 'f',
    note: 'La cuenta, por favor. Waiters never bring it unasked in Spain.',
  },
  {
    id: 'v.carta',
    kind: 'vocab',
    level: 'A2',
    topics: ['restaurant'],
    es: 'la carta',
    en: 'the menu',
    pos: 'noun',
    gender: 'f',
    note: 'La carta is the menu you choose from; el menú usually means the fixed-price menu del día.',
  },

  // --- Places --------------------------------------------------------------
  {
    id: 'v.casa',
    kind: 'vocab',
    level: 'A0',
    topics: ['home'],
    es: 'la casa',
    en: 'the house / home',
    pos: 'noun',
    gender: 'f',
    note: 'En casa means "at home" — no article.',
  },
  {
    id: 'v.piso',
    kind: 'vocab',
    level: 'A1',
    topics: ['home', 'city'],
    es: 'el piso',
    en: 'the flat / apartment',
    pos: 'noun',
    gender: 'm',
    spainOnly: true,
    regional: { spain: 'el piso', latam: 'el departamento / apartamento' },
  },
  {
    id: 'v.calle',
    kind: 'vocab',
    level: 'A1',
    topics: ['city', 'directions'],
    es: 'la calle',
    en: 'the street',
    pos: 'noun',
    gender: 'f',
  },
  {
    id: 'v.plaza',
    kind: 'vocab',
    level: 'A1',
    topics: ['city', 'directions'],
    es: 'la plaza',
    en: 'the square',
    pos: 'noun',
    gender: 'f',
  },
  {
    id: 'v.ciudad',
    kind: 'vocab',
    level: 'A1',
    topics: ['city'],
    es: 'la ciudad',
    en: 'the city',
    pos: 'noun',
    gender: 'f',
  },
  {
    id: 'v.trabajo',
    kind: 'vocab',
    level: 'A1',
    topics: ['work'],
    es: 'el trabajo',
    en: 'the work / the job',
    pos: 'noun',
    gender: 'm',
  },
  {
    id: 'v.universidad',
    kind: 'vocab',
    level: 'A1',
    topics: ['university'],
    es: 'la universidad',
    en: 'the university',
    pos: 'noun',
    gender: 'f',
    note: 'Shortened to la uni constantly in speech.',
  },
  {
    id: 'v.clase',
    kind: 'vocab',
    level: 'A1',
    topics: ['university'],
    es: 'la clase',
    en: 'the class',
    pos: 'noun',
    gender: 'f',
  },
  {
    id: 'v.tienda',
    kind: 'vocab',
    level: 'A1',
    topics: ['shopping'],
    es: 'la tienda',
    en: 'the shop',
    pos: 'noun',
    gender: 'f',
  },
  {
    id: 'v.supermercado',
    kind: 'vocab',
    level: 'A1',
    topics: ['shopping'],
    es: 'el supermercado',
    en: 'the supermarket',
    pos: 'noun',
    gender: 'm',
  },

  // --- Objects you actually own --------------------------------------------
  {
    id: 'v.movil',
    kind: 'vocab',
    level: 'A1',
    topics: ['home', 'city'],
    es: 'el móvil',
    en: 'the mobile phone',
    pos: 'noun',
    gender: 'm',
    spainOnly: true,
    regional: { spain: 'el móvil', latam: 'el celular' },
  },
  {
    id: 'v.ordenador',
    kind: 'vocab',
    level: 'A1',
    topics: ['home', 'work', 'university'],
    es: 'el ordenador',
    en: 'the computer',
    pos: 'noun',
    gender: 'm',
    spainOnly: true,
    regional: { spain: 'el ordenador', latam: 'la computadora' },
  },
  {
    id: 'v.coche',
    kind: 'vocab',
    level: 'A1',
    topics: ['transport'],
    es: 'el coche',
    en: 'the car',
    pos: 'noun',
    gender: 'm',
    spainOnly: true,
    regional: { spain: 'el coche', latam: 'el carro / el auto' },
  },
  {
    id: 'v.perro',
    kind: 'vocab',
    level: 'A0',
    topics: ['home', 'family'],
    es: 'el perro',
    en: 'the dog',
    pos: 'noun',
    gender: 'm',
  },
  {
    id: 'v.libro',
    kind: 'vocab',
    level: 'A0',
    topics: ['university', 'hobbies'],
    es: 'el libro',
    en: 'the book',
    pos: 'noun',
    gender: 'm',
  },
  {
    id: 'v.dinero',
    kind: 'vocab',
    level: 'A1',
    topics: ['shopping'],
    es: 'el dinero',
    en: 'the money',
    pos: 'noun',
    gender: 'm',
  },
];
