import type { VocabConcept } from '@/content/types';

/**
 * Greetings, introductions, pronouns and the connective tissue of basic
 * sentences. Peninsular throughout: vosotros is taught from the start, not
 * bolted on later.
 */
export const foundationsVocab: VocabConcept[] = [
  // --- Greetings -----------------------------------------------------------
  {
    id: 'v.hola',
    kind: 'vocab',
    level: 'A0',
    topics: ['greetings'],
    es: 'hola',
    en: 'hi / hello',
    pos: 'interjection',
    note: 'Works at any hour and with anyone — in Spain it is not considered too informal for shops or offices.',
  },
  {
    id: 'p.buenos-dias',
    kind: 'phrase',
    level: 'A0',
    topics: ['greetings'],
    es: 'buenos días',
    en: 'good morning',
    pos: 'expression',
    note: 'Used until roughly 2pm, when lunch happens in Spain — then it becomes buenas tardes.',
  },
  {
    id: 'p.buenas-tardes',
    kind: 'phrase',
    level: 'A0',
    topics: ['greetings'],
    es: 'buenas tardes',
    en: 'good afternoon / good evening',
    pos: 'expression',
    note: 'Covers the long Spanish afternoon — roughly 2pm until sunset.',
  },
  {
    id: 'p.buenas-noches',
    kind: 'phrase',
    level: 'A0',
    topics: ['greetings'],
    es: 'buenas noches',
    en: 'good night / good evening',
    pos: 'expression',
    note: 'Both a greeting after dark and a goodbye when leaving.',
  },
  {
    id: 'p.buenas',
    kind: 'phrase',
    level: 'A2',
    topics: ['greetings', 'slang'],
    es: '¡Buenas!',
    en: 'hey there!',
    pos: 'expression',
    register: 'colloquial',
    spainOnly: true,
    note: 'Very common shortcut in Spain for any of the buenos días / tardes / noches greetings.',
  },
  {
    id: 'v.adios',
    kind: 'vocab',
    level: 'A0',
    topics: ['greetings'],
    es: 'adiós',
    en: 'goodbye',
    pos: 'interjection',
  },
  {
    id: 'p.hasta-luego',
    kind: 'phrase',
    level: 'A0',
    topics: ['greetings'],
    es: 'hasta luego',
    en: 'see you later',
    pos: 'expression',
    note: 'The default goodbye in Spain — far more frequent than adiós, even to strangers in a shop.',
  },
  {
    id: 'p.hasta-manana',
    kind: 'phrase',
    level: 'A1',
    topics: ['greetings'],
    es: 'hasta mañana',
    en: 'see you tomorrow',
    pos: 'expression',
  },
  {
    id: 'p.que-tal',
    kind: 'phrase',
    level: 'A0',
    topics: ['greetings'],
    es: '¿Qué tal?',
    en: 'how are you? / how’s it going?',
    pos: 'expression',
    note: 'The everyday "how are you" in Spain. ¿Cómo estás? is fine but sounds slightly more careful.',
  },
  {
    id: 'p.como-estas',
    kind: 'phrase',
    level: 'A0',
    topics: ['greetings'],
    es: '¿Cómo estás?',
    en: 'how are you?',
    pos: 'expression',
    confusableWith: ['p.como-eres'],
  },
  {
    id: 'p.como-eres',
    kind: 'phrase',
    level: 'A2',
    topics: ['describing', 'people'],
    es: '¿Cómo eres?',
    en: 'what are you like?',
    pos: 'expression',
    confusableWith: ['p.como-estas'],
    note: 'Ser, so it asks about personality — not how you are feeling. That is ¿cómo estás?',
  },
  {
    id: 'p.muy-bien',
    kind: 'phrase',
    level: 'A0',
    topics: ['greetings'],
    es: 'muy bien',
    en: 'very well / really good',
    pos: 'expression',
  },
  {
    id: 'p.y-tu',
    kind: 'phrase',
    level: 'A0',
    topics: ['greetings'],
    es: '¿Y tú?',
    en: 'and you?',
    pos: 'expression',
  },
  {
    id: 'v.gracias',
    kind: 'vocab',
    level: 'A0',
    topics: ['greetings'],
    es: 'gracias',
    en: 'thank you',
    pos: 'interjection',
  },
  {
    id: 'p.de-nada',
    kind: 'phrase',
    level: 'A0',
    topics: ['greetings'],
    es: 'de nada',
    en: 'you’re welcome',
    pos: 'expression',
  },
  {
    id: 'v.perdona',
    kind: 'vocab',
    level: 'A1',
    topics: ['greetings', 'city'],
    es: 'perdona',
    en: 'excuse me / sorry',
    pos: 'expression',
    note: 'Use perdona with someone you address as tú, perdone with usted. Great for stopping someone in the street.',
  },
  {
    id: 'p.por-favor',
    kind: 'phrase',
    level: 'A0',
    topics: ['greetings', 'cafe'],
    es: 'por favor',
    en: 'please',
    pos: 'expression',
  },
  {
    id: 'v.vale',
    kind: 'vocab',
    level: 'A1',
    topics: ['social', 'slang'],
    es: 'vale',
    en: 'okay / alright',
    pos: 'interjection',
    spainOnly: true,
    regional: {
      spain: 'vale',
      latam: 'okay / bueno / dale',
      note: 'You will hear vale constantly in Spain — it is probably the single most Spanish word on this list.',
    },
    note: 'Agreement, acknowledgement, "got it". ¿Vale? at the end of a sentence means "okay?".',
  },

  // --- Introductions -------------------------------------------------------
  {
    id: 'p.me-llamo',
    kind: 'phrase',
    level: 'A0',
    topics: ['introductions'],
    es: 'me llamo',
    en: 'my name is',
    pos: 'expression',
    note: 'Literally "I call myself" — llamarse is reflexive, which is why me comes first.',
  },
  {
    id: 'p.como-te-llamas',
    kind: 'phrase',
    level: 'A0',
    topics: ['introductions'],
    es: '¿Cómo te llamas?',
    en: 'what’s your name?',
    pos: 'expression',
  },
  {
    id: 'p.encantado',
    kind: 'phrase',
    level: 'A1',
    topics: ['introductions'],
    es: 'encantado / encantada',
    en: 'nice to meet you',
    altEn: ['pleased to meet you', 'delighted to meet you', 'a pleasure to meet you'],
    pos: 'expression',
    note: 'Agrees with you, the speaker: a man says encantado, a woman encantada.',
  },
  {
    id: 'p.de-donde-eres',
    kind: 'phrase',
    level: 'A0',
    topics: ['introductions'],
    es: '¿De dónde eres?',
    en: 'where are you from?',
    pos: 'expression',
  },
  {
    id: 'p.soy-de',
    kind: 'phrase',
    level: 'A0',
    topics: ['introductions'],
    es: 'soy de',
    en: 'I’m from',
    pos: 'expression',
  },
  {
    id: 'v.esloveno',
    kind: 'vocab',
    level: 'A1',
    topics: ['introductions', 'people'],
    es: 'esloveno / eslovena',
    en: 'Slovenian',
    pos: 'adjective',
    gender: 'mf',
    note: 'Nationalities are lower-case in Spanish: soy esloveno, not soy Esloveno.',
  },
  {
    id: 'v.espanol',
    kind: 'vocab',
    level: 'A0',
    topics: ['introductions', 'people'],
    es: 'español / española',
    en: 'Spanish',
    pos: 'adjective',
    gender: 'mf',
  },
  {
    id: 'p.cuantos-anos-tienes',
    kind: 'phrase',
    level: 'A1',
    topics: ['introductions', 'numbers'],
    es: '¿Cuántos años tienes?',
    en: 'how old are you?',
    pos: 'expression',
    note: 'Spanish uses tener for age — literally "how many years do you have?". Never use ser here.',
  },
  {
    id: 'v.anos',
    kind: 'vocab',
    level: 'A1',
    topics: ['introductions', 'numbers'],
    es: 'los años',
    en: 'years',
    pos: 'noun',
    gender: 'm',
    note: 'Mind the ñ: año is "year", ano is something else entirely.',
  },
  {
    id: 'p.vivo-en',
    kind: 'phrase',
    level: 'A1',
    topics: ['introductions', 'city'],
    es: 'vivo en',
    en: 'I live in',
    pos: 'expression',
  },
  {
    id: 'p.mucho-gusto',
    kind: 'phrase',
    level: 'A1',
    topics: ['introductions'],
    es: 'mucho gusto',
    en: 'pleased to meet you',
    pos: 'expression',
    register: 'formal',
  },

  // --- Pronouns ------------------------------------------------------------
  {
    id: 'v.yo',
    kind: 'vocab',
    level: 'A0',
    topics: ['people'],
    es: 'yo',
    en: 'I',
    pos: 'pronoun',
    note: 'Usually dropped — the verb ending already says who. Use it for emphasis or contrast.',
  },
  {
    id: 'v.tu',
    kind: 'vocab',
    level: 'A0',
    topics: ['people'],
    es: 'tú',
    en: 'you (informal)',
    pos: 'pronoun',
    note: 'The default in Spain with anyone roughly your age, in shops, and at university.',
  },
  {
    id: 'v.el-pron',
    kind: 'vocab',
    level: 'A0',
    topics: ['people'],
    es: 'él / ella',
    en: 'he / she',
    pos: 'pronoun',
  },
  {
    id: 'v.nosotros',
    kind: 'vocab',
    level: 'A0',
    topics: ['people'],
    es: 'nosotros / nosotras',
    en: 'we',
    pos: 'pronoun',
  },
  {
    id: 'v.vosotros',
    kind: 'vocab',
    level: 'A0',
    topics: ['people'],
    es: 'vosotros / vosotras',
    en: 'you (plural, informal)',
    pos: 'pronoun',
    spainOnly: true,
    regional: {
      spain: 'vosotros habláis',
      latam: 'ustedes hablan',
      note: 'Vosotros is used constantly in Spain and not at all in Latin America. Learning it is non-negotiable for es-ES.',
    },
    note: 'Talking to two or more friends? Vosotros. Its verb endings are the ones textbooks love to skip.',
  },
  {
    id: 'v.ellos',
    kind: 'vocab',
    level: 'A0',
    topics: ['people'],
    es: 'ellos / ellas',
    en: 'they',
    pos: 'pronoun',
  },
  {
    id: 'v.usted',
    kind: 'vocab',
    level: 'A2',
    topics: ['people'],
    es: 'usted',
    en: 'you (formal)',
    pos: 'pronoun',
    register: 'formal',
    note: 'In Spain reserved for much older people, officials and formal writing. Over-using it can sound distant.',
  },

  // --- Question words ------------------------------------------------------
  {
    id: 'v.que',
    kind: 'vocab',
    level: 'A0',
    topics: ['greetings'],
    es: 'qué',
    en: 'what',
    pos: 'pronoun',
  },
  {
    id: 'v.donde',
    kind: 'vocab',
    level: 'A0',
    topics: ['directions'],
    es: 'dónde',
    en: 'where',
    pos: 'adverb',
  },
  {
    id: 'v.cuando',
    kind: 'vocab',
    level: 'A1',
    topics: ['time'],
    es: 'cuándo',
    en: 'when',
    pos: 'adverb',
  },
  {
    id: 'v.como-q',
    kind: 'vocab',
    level: 'A0',
    topics: ['greetings'],
    es: 'cómo',
    en: 'how',
    pos: 'adverb',
  },
  {
    id: 'v.por-que',
    kind: 'vocab',
    level: 'A1',
    topics: ['opinions'],
    es: 'por qué',
    en: 'why',
    pos: 'adverb',
    note: 'Two words with an accent for the question; porque (one word, no accent) means "because".',
    confusableWith: ['v.porque'],
  },
  {
    id: 'v.porque',
    kind: 'vocab',
    level: 'A1',
    topics: ['opinions'],
    es: 'porque',
    en: 'because',
    pos: 'conjunction',
    confusableWith: ['v.por-que'],
  },
  {
    id: 'v.quien',
    kind: 'vocab',
    level: 'A1',
    topics: ['people'],
    es: 'quién',
    en: 'who',
    pos: 'pronoun',
  },
  {
    id: 'v.cuanto',
    kind: 'vocab',
    level: 'A1',
    topics: ['shopping', 'numbers'],
    es: 'cuánto / cuánta',
    en: 'how much',
    pos: 'determiner',
  },

  // --- Basic connectives and fillers ---------------------------------------
  {
    id: 'v.y',
    kind: 'vocab',
    level: 'A0',
    topics: ['greetings'],
    es: 'y',
    en: 'and',
    pos: 'conjunction',
  },
  {
    id: 'v.pero',
    kind: 'vocab',
    level: 'A0',
    topics: ['opinions'],
    es: 'pero',
    en: 'but',
    pos: 'conjunction',
  },
  {
    id: 'v.tambien',
    kind: 'vocab',
    level: 'A1',
    topics: ['opinions'],
    es: 'también',
    en: 'also / too',
    pos: 'adverb',
  },
  {
    id: 'v.muy',
    kind: 'vocab',
    level: 'A0',
    topics: ['describing'],
    es: 'muy',
    en: 'very',
    pos: 'adverb',
    note: 'Goes before adjectives: muy cansado. For "a lot" with verbs you need mucho.',
    confusableWith: ['v.mucho'],
  },
  {
    id: 'v.mucho',
    kind: 'vocab',
    level: 'A1',
    topics: ['describing'],
    es: 'mucho',
    en: 'a lot / much',
    pos: 'adverb',
    confusableWith: ['v.muy'],
  },
  {
    id: 'v.un-poco',
    kind: 'phrase',
    level: 'A1',
    topics: ['describing'],
    es: 'un poco',
    en: 'a bit / a little',
    pos: 'expression',
  },
  {
    id: 'v.si',
    kind: 'vocab',
    level: 'A0',
    topics: ['greetings'],
    es: 'sí',
    en: 'yes',
    pos: 'adverb',
    note: 'With the accent it means "yes"; si without it means "if".',
  },
  {
    id: 'v.no',
    kind: 'vocab',
    level: 'A0',
    topics: ['greetings'],
    es: 'no',
    en: 'no / not',
    pos: 'adverb',
    note: 'Also the way to make any verb negative — it goes straight before it: no hablo francés.',
  },
];
