import type { VocabConcept } from '@/content/types';

/**
 * The verbs a daily routine is built from, plus the adjectives you need to say
 * how you are. Verbs carry a `verbId` so tapping one opens its conjugation.
 */
export const routineVocab: VocabConcept[] = [
  // --- The essential irregulars -------------------------------------------
  {
    id: 'v.ser',
    kind: 'vocab',
    level: 'A0',
    topics: ['introductions', 'describing'],
    es: 'ser',
    en: 'to be (permanent)',
    pos: 'verb',
    verbId: 'ser',
    confusableWith: ['v.estar'],
    note: 'Identity, origin, profession, what something fundamentally is.',
  },
  {
    id: 'v.estar',
    kind: 'vocab',
    level: 'A0',
    topics: ['feelings', 'directions'],
    es: 'estar',
    en: 'to be (state, location)',
    pos: 'verb',
    verbId: 'estar',
    confusableWith: ['v.ser'],
    note: 'How something is right now, and where it is.',
  },
  {
    id: 'v.tener',
    kind: 'vocab',
    level: 'A0',
    topics: ['home', 'family'],
    es: 'tener',
    en: 'to have',
    pos: 'verb',
    verbId: 'tener',
    note: 'Also does the work of English "to be" in tengo hambre, tengo 21 años, tengo frío.',
  },
  {
    id: 'v.ir',
    kind: 'vocab',
    level: 'A1',
    topics: ['transport', 'plans'],
    es: 'ir',
    en: 'to go',
    pos: 'verb',
    verbId: 'ir',
    note: 'ir a + infinitive is how Spaniards talk about the future far more often than the future tense.',
  },
  {
    id: 'v.hacer',
    kind: 'vocab',
    level: 'A1',
    topics: ['daily-routine', 'plans'],
    es: 'hacer',
    en: 'to do / to make',
    pos: 'verb',
    verbId: 'hacer',
  },
  {
    id: 'v.querer',
    kind: 'vocab',
    level: 'A1',
    topics: ['plans', 'cafe'],
    es: 'querer',
    en: 'to want',
    pos: 'verb',
    verbId: 'querer',
    note: 'Quiero un café is direct but normal. Querría or quería softens it in a shop.',
  },
  {
    id: 'v.poder',
    kind: 'vocab',
    level: 'A1',
    topics: ['plans'],
    es: 'poder',
    en: 'can / to be able to',
    pos: 'verb',
    verbId: 'poder',
  },
  {
    id: 'v.saber',
    kind: 'vocab',
    level: 'A2',
    topics: ['opinions'],
    es: 'saber',
    en: 'to know (facts, how to)',
    pos: 'verb',
    verbId: 'saber',
    confusableWith: ['v.conocer'],
    note: 'Facts and skills: sé nadar, no sé dónde está.',
  },
  {
    id: 'v.conocer',
    kind: 'vocab',
    level: 'A2',
    topics: ['social', 'travel'],
    es: 'conocer',
    en: 'to know (people, places)',
    pos: 'verb',
    verbId: 'conocer',
    confusableWith: ['v.saber'],
    note: 'Being familiar with someone or somewhere: conozco Madrid, conozco a tu hermana.',
  },

  // --- Regular workhorses ---------------------------------------------------
  {
    id: 'v.hablar',
    kind: 'vocab',
    level: 'A0',
    topics: ['introductions', 'social'],
    es: 'hablar',
    en: 'to speak / to talk',
    pos: 'verb',
    verbId: 'hablar',
  },
  {
    id: 'v.comer',
    kind: 'vocab',
    level: 'A0',
    topics: ['food', 'daily-routine'],
    es: 'comer',
    en: 'to eat / to have lunch',
    pos: 'verb',
    verbId: 'comer',
    note: 'On its own, comer often means specifically "to have lunch" in Spain.',
  },
  {
    id: 'v.vivir',
    kind: 'vocab',
    level: 'A0',
    topics: ['home', 'introductions'],
    es: 'vivir',
    en: 'to live',
    pos: 'verb',
    verbId: 'vivir',
  },
  {
    id: 'v.trabajar',
    kind: 'vocab',
    level: 'A1',
    topics: ['work'],
    es: 'trabajar',
    en: 'to work',
    pos: 'verb',
    verbId: 'trabajar',
  },
  {
    id: 'v.estudiar',
    kind: 'vocab',
    level: 'A1',
    topics: ['university'],
    es: 'estudiar',
    en: 'to study',
    pos: 'verb',
    verbId: 'estudiar',
  },
  {
    id: 'v.beber',
    kind: 'vocab',
    level: 'A1',
    topics: ['food', 'cafe'],
    es: 'beber',
    en: 'to drink',
    pos: 'verb',
    verbId: 'beber',
    note: 'In a bar, tomar is far more common than beber: ¿tomamos algo?',
  },
  {
    id: 'v.tomar',
    kind: 'vocab',
    level: 'A1',
    topics: ['cafe', 'social'],
    es: 'tomar',
    en: 'to take / to have (a drink, food)',
    pos: 'verb',
    verbId: 'tomar',
    note: 'Tomar algo = to have a drink. Also "to take" a bus or a decision.',
  },
  {
    id: 'v.escuchar',
    kind: 'vocab',
    level: 'A1',
    topics: ['hobbies'],
    es: 'escuchar',
    en: 'to listen to',
    pos: 'verb',
    verbId: 'escuchar',
    note: 'No preposition needed: escucho música, not escucho a música.',
  },
  {
    id: 'v.leer',
    kind: 'vocab',
    level: 'A1',
    topics: ['hobbies'],
    es: 'leer',
    en: 'to read',
    pos: 'verb',
    verbId: 'leer',
  },
  {
    id: 'v.escribir',
    kind: 'vocab',
    level: 'A1',
    topics: ['university', 'work'],
    es: 'escribir',
    en: 'to write',
    pos: 'verb',
    verbId: 'escribir',
  },
  {
    id: 'v.ver',
    kind: 'vocab',
    level: 'A1',
    topics: ['hobbies', 'social'],
    es: 'ver',
    en: 'to see / to watch',
    pos: 'verb',
    verbId: 'ver',
    note: 'Also "to meet up with": nos vemos mañana.',
  },
  {
    id: 'v.salir',
    kind: 'vocab',
    level: 'A2',
    topics: ['social', 'plans'],
    es: 'salir',
    en: 'to go out / to leave',
    pos: 'verb',
    verbId: 'salir',
  },
  {
    id: 'v.venir',
    kind: 'vocab',
    level: 'A2',
    topics: ['social', 'plans'],
    es: 'venir',
    en: 'to come',
    pos: 'verb',
    verbId: 'venir',
  },
  {
    id: 'v.decir',
    kind: 'vocab',
    level: 'A2',
    topics: ['social'],
    es: 'decir',
    en: 'to say / to tell',
    pos: 'verb',
    verbId: 'decir',
  },
  {
    id: 'v.coger',
    kind: 'vocab',
    level: 'A2',
    topics: ['transport'],
    es: 'coger',
    en: 'to take / to catch (a bus, a taxi)',
    pos: 'verb',
    verbId: 'coger',
    spainOnly: true,
    regional: {
      spain: 'coger el metro',
      latam: 'tomar el metro',
      note: 'In much of Latin America coger is crude slang. In Spain it is completely ordinary — you cogeas buses, keys and colds.',
    },
  },
  {
    id: 'v.conducir',
    kind: 'vocab',
    level: 'A2',
    topics: ['transport'],
    es: 'conducir',
    en: 'to drive',
    pos: 'verb',
    verbId: 'conducir',
    spainOnly: true,
    regional: { spain: 'conducir', latam: 'manejar' },
  },

  // --- Reflexives / the shape of a day -------------------------------------
  {
    id: 'v.levantarse',
    kind: 'vocab',
    level: 'A2',
    topics: ['daily-routine'],
    es: 'levantarse',
    en: 'to get up',
    pos: 'verb',
    verbId: 'levantarse',
    note: 'Reflexive: me levanto, te levantas, se levanta…',
  },
  {
    id: 'v.despertarse',
    kind: 'vocab',
    level: 'A2',
    topics: ['daily-routine'],
    es: 'despertarse',
    en: 'to wake up',
    pos: 'verb',
    verbId: 'despertarse',
  },
  {
    id: 'v.ducharse',
    kind: 'vocab',
    level: 'A2',
    topics: ['daily-routine'],
    es: 'ducharse',
    en: 'to have a shower',
    pos: 'verb',
    verbId: 'ducharse',
  },
  {
    id: 'v.acostarse',
    kind: 'vocab',
    level: 'A2',
    topics: ['daily-routine'],
    es: 'acostarse',
    en: 'to go to bed',
    pos: 'verb',
    verbId: 'acostarse',
  },
  {
    id: 'v.llamarse',
    kind: 'vocab',
    level: 'A0',
    topics: ['introductions'],
    es: 'llamarse',
    en: 'to be called',
    pos: 'verb',
    verbId: 'llamarse',
  },

  // --- Feelings and states --------------------------------------------------
  {
    id: 'v.cansado',
    kind: 'vocab',
    level: 'A1',
    topics: ['feelings'],
    es: 'cansado / cansada',
    en: 'tired',
    pos: 'adjective',
    gender: 'mf',
    note: 'A state, so it takes estar: estoy cansado. Ser cansado would mean you are a tiring person.',
  },
  {
    id: 'v.contento',
    kind: 'vocab',
    level: 'A1',
    topics: ['feelings'],
    es: 'contento / contenta',
    en: 'happy / pleased',
    pos: 'adjective',
    gender: 'mf',
  },
  {
    id: 'v.triste',
    kind: 'vocab',
    level: 'A1',
    topics: ['feelings'],
    es: 'triste',
    en: 'sad',
    pos: 'adjective',
    note: 'Same form for both genders — adjectives ending in -e do not change.',
  },
  {
    id: 'v.nervioso',
    kind: 'vocab',
    level: 'A2',
    topics: ['feelings'],
    es: 'nervioso / nerviosa',
    en: 'nervous',
    pos: 'adjective',
    gender: 'mf',
  },
  {
    id: 'v.enfadado',
    kind: 'vocab',
    level: 'A2',
    topics: ['feelings'],
    es: 'enfadado / enfadada',
    en: 'angry',
    pos: 'adjective',
    gender: 'mf',
    spainOnly: true,
    regional: { spain: 'enfadado', latam: 'enojado' },
  },
  {
    id: 'p.tengo-hambre',
    kind: 'phrase',
    level: 'A1',
    topics: ['food', 'feelings'],
    es: 'tengo hambre',
    en: 'I’m hungry',
    pos: 'expression',
    note: 'Literally "I have hunger". Estoy hambriento exists but nobody says it.',
  },
  {
    id: 'p.tengo-sueno',
    kind: 'phrase',
    level: 'A1',
    topics: ['feelings', 'daily-routine'],
    es: 'tengo sueño',
    en: 'I’m sleepy',
    pos: 'expression',
  },
  {
    id: 'p.tengo-prisa',
    kind: 'phrase',
    level: 'A2',
    topics: ['feelings', 'time'],
    es: 'tengo prisa',
    en: 'I’m in a hurry',
    pos: 'expression',
  },
  {
    id: 'p.tener-que',
    kind: 'phrase',
    level: 'A2',
    topics: ['daily-routine', 'work'],
    es: 'tener que + infinitivo',
    en: 'to have to (do something)',
    pos: 'expression',
    note: 'Tengo que estudiar. The que is not optional.',
  },

  // --- Describing -----------------------------------------------------------
  {
    id: 'v.grande',
    kind: 'vocab',
    level: 'A1',
    topics: ['describing'],
    es: 'grande',
    en: 'big',
    pos: 'adjective',
    note: 'Before a singular noun it shortens to gran, and the meaning shifts: una gran ciudad = a great city.',
  },
  {
    id: 'v.pequeno',
    kind: 'vocab',
    level: 'A1',
    topics: ['describing'],
    es: 'pequeño / pequeña',
    en: 'small',
    pos: 'adjective',
    gender: 'mf',
  },
  {
    id: 'v.bonito',
    kind: 'vocab',
    level: 'A1',
    topics: ['describing'],
    es: 'bonito / bonita',
    en: 'pretty / nice',
    pos: 'adjective',
    gender: 'mf',
  },
  {
    id: 'v.majo',
    kind: 'vocab',
    level: 'A2',
    topics: ['describing', 'social'],
    es: 'majo / maja',
    en: 'nice / lovely (of a person)',
    pos: 'adjective',
    gender: 'mf',
    spainOnly: true,
    register: 'colloquial',
    note: 'Very Spanish. Es muy maja is the warm, everyday way to say someone is lovely.',
  },
  {
    id: 'v.dificil',
    kind: 'vocab',
    level: 'A1',
    topics: ['university', 'describing'],
    es: 'difícil',
    en: 'difficult',
    pos: 'adjective',
  },
  {
    id: 'v.facil',
    kind: 'vocab',
    level: 'A1',
    topics: ['university', 'describing'],
    es: 'fácil',
    en: 'easy',
    pos: 'adjective',
  },
  {
    id: 'v.caro',
    kind: 'vocab',
    level: 'A1',
    topics: ['shopping', 'describing'],
    es: 'caro / cara',
    en: 'expensive',
    pos: 'adjective',
    gender: 'mf',
  },
  {
    id: 'v.barato',
    kind: 'vocab',
    level: 'A1',
    topics: ['shopping', 'describing'],
    es: 'barato / barata',
    en: 'cheap',
    pos: 'adjective',
    gender: 'mf',
  },
  {
    id: 'v.dar',
    kind: 'vocab',
    level: 'A2',
    topics: ['social', 'feelings'],
    es: 'dar',
    en: 'to give',
    pos: 'verb',
    verbId: 'dar',
    note: 'Also the engine of a whole family of feelings: me da pena, me da miedo, me da igual.',
  },
  {
    id: 'v.poner',
    kind: 'vocab',
    level: 'A2',
    topics: ['cafe', 'home'],
    es: 'poner',
    en: 'to put',
    pos: 'verb',
    verbId: 'poner',
    spainOnly: true,
    regional: {
      spain: '¿me pones un café?',
      latam: '¿me da un café?',
      note: 'Ordering with poner is very Spain; much of Latin America uses dar instead.',
    },
  },
  {
    id: 'v.llevar',
    kind: 'vocab',
    level: 'A2',
    topics: ['daily-routine', 'time'],
    es: 'llevar',
    en: 'to carry / to wear / to have been',
    pos: 'verb',
    verbId: 'llevar',
    note: 'llevar + time + gerundio is how Spanish says "have been doing": llevo dos años aquí.',
  },
  {
    id: 'v.traer',
    kind: 'vocab',
    level: 'A2',
    topics: ['restaurant', 'social'],
    es: 'traer',
    en: 'to bring',
    pos: 'verb',
    verbId: 'traer',
    confusableWith: ['v.llevar'],
    note: 'traer is towards the speaker, llevar away from them — the opposite of English "bring/take".',
  },
];
