import type { VocabConcept } from '@/content/types';

/**
 * Making plans, saying what you like, and the filler words that make Spanish
 * sound like Spanish. The colloquial entries are levelled so they arrive once
 * the learner can actually place them, not on day one.
 */
export const socialVocab: VocabConcept[] = [
  // --- Making plans --------------------------------------------------------
  {
    id: 'v.quedar',
    kind: 'vocab',
    level: 'A2',
    topics: ['plans', 'social'],
    es: 'quedar',
    en: 'to meet up / to arrange to meet',
    pos: 'verb',
    verbId: 'quedar',
    spainOnly: true,
    note: 'The core social verb in Spain. ¿Quedamos mañana? = shall we meet tomorrow? It means arranging the plan, not just meeting by chance.',
  },
  {
    id: 'p.quieres-quedar',
    kind: 'phrase',
    level: 'A2',
    topics: ['plans', 'social'],
    es: '¿Quieres quedar mañana?',
    en: 'do you want to meet up tomorrow?',
    pos: 'expression',
  },
  {
    id: 'p.hemos-quedado',
    kind: 'phrase',
    level: 'B1',
    topics: ['plans', 'social'],
    es: 'hemos quedado a las ocho',
    en: 'we’re meeting at eight',
    pos: 'expression',
    note: 'Present perfect, but describing a plan already made. Extremely common in Spain.',
  },
  {
    id: 'p.tomar-algo',
    kind: 'phrase',
    level: 'A2',
    topics: ['plans', 'social', 'cafe'],
    es: 'tomar algo',
    en: 'to grab a drink',
    pos: 'expression',
    spainOnly: true,
    note: '¿Tomamos algo? is the standard invitation. Deliberately vague about whether it is coffee or beer.',
  },
  {
    id: 'p.me-apetece',
    kind: 'phrase',
    level: 'A2',
    topics: ['plans', 'feelings'],
    es: 'me apetece',
    en: 'I fancy / I feel like',
    pos: 'expression',
    spainOnly: true,
    regional: { spain: 'me apetece', latam: 'tengo ganas de / se me antoja' },
    note: 'Works like gustar: me apetece un café, me apetecen unas tapas.',
  },
  {
    id: 'p.qué-haces',
    kind: 'phrase',
    level: 'A1',
    topics: ['plans'],
    es: '¿Qué haces mañana?',
    en: 'what are you doing tomorrow?',
    pos: 'expression',
    note: 'Present tense for a future plan — completely normal in Spanish.',
  },
  {
    id: 'p.quedamos-en',
    kind: 'phrase',
    level: 'B1',
    topics: ['plans', 'directions'],
    es: 'quedamos delante del metro',
    en: 'let’s meet in front of the metro',
    pos: 'expression',
  },
  {
    id: 'v.fiesta',
    kind: 'vocab',
    level: 'A1',
    topics: ['social', 'plans'],
    es: 'la fiesta',
    en: 'the party',
    pos: 'noun',
    gender: 'f',
  },
  {
    id: 'p.salir-de-fiesta',
    kind: 'phrase',
    level: 'A2',
    topics: ['social'],
    es: 'salir de fiesta',
    en: 'to go out (partying)',
    pos: 'expression',
    spainOnly: true,
  },

  // --- Likes and opinions ---------------------------------------------------
  {
    id: 'v.gustar',
    kind: 'vocab',
    level: 'A1',
    topics: ['hobbies', 'opinions'],
    es: 'gustar',
    en: 'to be pleasing (to like)',
    pos: 'verb',
    note: 'Backwards from English: me gusta el café literally means "coffee is pleasing to me". Because it is almost only ever used in the third person, it has no full conjugation sheet — see the grammar card instead.',
  },
  {
    id: 'p.me-gusta',
    kind: 'phrase',
    level: 'A1',
    topics: ['hobbies', 'opinions'],
    es: 'me gusta',
    en: 'I like (it)',
    pos: 'expression',
  },
  {
    id: 'p.me-gustan',
    kind: 'phrase',
    level: 'A1',
    topics: ['hobbies', 'opinions'],
    es: 'me gustan',
    en: 'I like (them)',
    pos: 'expression',
    note: 'Plural thing, plural verb: me gustan los perros.',
  },
  {
    id: 'p.me-encanta',
    kind: 'phrase',
    level: 'A2',
    topics: ['opinions'],
    es: 'me encanta',
    en: 'I love it',
    pos: 'expression',
    note: 'Already means "a lot", so me encanta mucho is wrong.',
  },
  {
    id: 'p.no-me-gusta-nada',
    kind: 'phrase',
    level: 'A2',
    topics: ['opinions'],
    es: 'no me gusta nada',
    en: 'I don’t like it at all',
    pos: 'expression',
    note: 'Spanish happily uses double negatives: no … nada.',
  },
  {
    id: 'v.creo-que',
    kind: 'phrase',
    level: 'A2',
    topics: ['opinions'],
    es: 'creo que',
    en: 'I think that',
    pos: 'expression',
  },
  {
    id: 'p.me-parece',
    kind: 'phrase',
    level: 'B1',
    topics: ['opinions'],
    es: 'me parece que',
    en: 'it seems to me that',
    pos: 'expression',
  },
  {
    id: 'p.estoy-de-acuerdo',
    kind: 'phrase',
    level: 'B1',
    topics: ['opinions'],
    es: 'estoy de acuerdo',
    en: 'I agree',
    pos: 'expression',
  },

  // --- Hobbies --------------------------------------------------------------
  {
    id: 'v.musica',
    kind: 'vocab',
    level: 'A1',
    topics: ['hobbies'],
    es: 'la música',
    en: 'the music',
    pos: 'noun',
    gender: 'f',
  },
  {
    id: 'v.pelicula',
    kind: 'vocab',
    level: 'A1',
    topics: ['hobbies'],
    es: 'la película',
    en: 'the film / movie',
    pos: 'noun',
    gender: 'f',
  },
  {
    id: 'v.futbol',
    kind: 'vocab',
    level: 'A1',
    topics: ['hobbies'],
    es: 'el fútbol',
    en: 'football',
    pos: 'noun',
    gender: 'm',
  },
  {
    id: 'v.deporte',
    kind: 'vocab',
    level: 'A1',
    topics: ['hobbies'],
    es: 'el deporte',
    en: 'sport',
    pos: 'noun',
    gender: 'm',
    note: 'Hacer deporte = to do sport / exercise.',
  },
  {
    id: 'v.viajar',
    kind: 'vocab',
    level: 'A1',
    topics: ['travel', 'hobbies'],
    es: 'viajar',
    en: 'to travel',
    pos: 'verb',
    verbId: 'viajar',
  },
  {
    id: 'v.cocinar',
    kind: 'vocab',
    level: 'A1',
    topics: ['hobbies', 'food'],
    es: 'cocinar',
    en: 'to cook',
    pos: 'verb',
    verbId: 'cocinar',
  },

  // --- The words that make you sound Spanish -------------------------------
  {
    id: 'v.venga',
    kind: 'vocab',
    level: 'A2',
    topics: ['slang', 'social'],
    es: 'venga',
    en: 'come on / alright then',
    pos: 'interjection',
    register: 'colloquial',
    spainOnly: true,
    note: 'Encouragement, agreement, or winding up a phone call: "venga, hasta luego".',
  },
  {
    id: 'v.pues',
    kind: 'vocab',
    level: 'A2',
    topics: ['slang', 'social'],
    es: 'pues',
    en: 'well… / so…',
    pos: 'interjection',
    register: 'colloquial',
    note: 'Buys you a moment at the start of an answer, exactly like English "well…".',
  },
  {
    id: 'v.claro',
    kind: 'vocab',
    level: 'A2',
    topics: ['slang', 'social'],
    es: 'claro',
    en: 'of course / sure',
    pos: 'interjection',
    register: 'colloquial',
  },
  {
    id: 'v.bueno',
    kind: 'vocab',
    level: 'A2',
    topics: ['slang', 'social'],
    es: 'bueno',
    en: 'well / okay',
    pos: 'interjection',
    register: 'colloquial',
    note: 'As a filler it softens or changes direction — not the adjective "good".',
  },
  {
    id: 'p.a-ver',
    kind: 'phrase',
    level: 'B1',
    topics: ['slang', 'social'],
    es: 'a ver',
    en: 'let’s see',
    pos: 'expression',
    register: 'colloquial',
  },
  {
    id: 'v.ya',
    kind: 'vocab',
    level: 'A2',
    topics: ['slang', 'time'],
    es: 'ya',
    en: 'already / now / right',
    pos: 'adverb',
    register: 'colloquial',
    note: 'Slippery but everywhere. Ya está = that’s it, done. ¿Ya? = already?',
  },
  {
    id: 'v.tio',
    kind: 'vocab',
    level: 'B1',
    topics: ['slang', 'social'],
    es: 'tío / tía',
    en: 'mate / dude',
    pos: 'noun',
    gender: 'mf',
    register: 'colloquial',
    spainOnly: true,
    note: 'Literally uncle/aunt. Between friends in Spain it is punctuation: "qué fuerte, tío".',
  },
  {
    id: 'p.que-guay',
    kind: 'phrase',
    level: 'B1',
    topics: ['slang', 'opinions'],
    es: 'qué guay',
    en: 'how cool',
    pos: 'expression',
    register: 'colloquial',
    spainOnly: true,
  },
  {
    id: 'v.molar',
    kind: 'vocab',
    level: 'B1',
    topics: ['slang', 'opinions'],
    es: 'molar',
    en: 'to be cool / to rock',
    pos: 'verb',
    register: 'colloquial',
    spainOnly: true,
    note: 'Works like gustar: me mola esa canción.',
  },
  {
    id: 'p.da-igual',
    kind: 'phrase',
    level: 'B1',
    topics: ['slang', 'opinions'],
    es: 'da igual',
    en: 'it doesn’t matter / whatever',
    pos: 'expression',
    register: 'colloquial',
  },
  {
    id: 'p.ni-idea',
    kind: 'phrase',
    level: 'B1',
    topics: ['slang', 'opinions'],
    es: 'ni idea',
    en: 'no idea',
    pos: 'expression',
    register: 'colloquial',
  },
  {
    id: 'p.que-rollo',
    kind: 'phrase',
    level: 'B1',
    topics: ['slang', 'opinions'],
    es: 'qué rollo',
    en: 'what a drag',
    pos: 'expression',
    register: 'colloquial',
    spainOnly: true,
  },
  {
    id: 'p.en-plan',
    kind: 'phrase',
    level: 'B1',
    topics: ['slang', 'social'],
    es: 'en plan',
    en: 'like… / sort of',
    pos: 'expression',
    register: 'colloquial',
    spainOnly: true,
    note: 'The Spanish equivalent of conversational "like". Extremely common under 35.',
  },
  {
    id: 'p.que-fuerte',
    kind: 'phrase',
    level: 'B1',
    topics: ['slang', 'opinions'],
    es: 'qué fuerte',
    en: 'that’s intense / no way',
    pos: 'expression',
    register: 'colloquial',
    spainOnly: true,
  },

  // --- Connectors for longer sentences --------------------------------------
  {
    id: 'v.aunque',
    kind: 'vocab',
    level: 'B1',
    topics: ['opinions', 'storytelling'],
    es: 'aunque',
    en: 'although / even though',
    pos: 'conjunction',
  },
  {
    id: 'v.entonces',
    kind: 'vocab',
    level: 'A2',
    topics: ['storytelling'],
    es: 'entonces',
    en: 'so / then',
    pos: 'adverb',
  },
  {
    id: 'v.luego',
    kind: 'vocab',
    level: 'A2',
    topics: ['storytelling', 'time'],
    es: 'luego',
    en: 'later / then',
    pos: 'adverb',
  },
  {
    id: 'v.despues',
    kind: 'vocab',
    level: 'A1',
    topics: ['storytelling', 'time'],
    es: 'después',
    en: 'after / afterwards',
    pos: 'adverb',
  },
  {
    id: 'v.antes',
    kind: 'vocab',
    level: 'A2',
    topics: ['storytelling', 'time'],
    es: 'antes',
    en: 'before',
    pos: 'adverb',
  },
  {
    id: 'v.sobre-todo',
    kind: 'phrase',
    level: 'B1',
    topics: ['opinions'],
    es: 'sobre todo',
    en: 'above all / especially',
    pos: 'expression',
  },
];
