import type { Sentence } from '@/content/types';

/**
 * Sentences for the rest of A1: numbers and prices, the calendar, where you are
 * from, describing people and things, weather, and the small grammar that holds
 * them together.
 *
 * Written as things a person would actually say in Spain, not as slots for a
 * paradigm. Where a line exists to drill a form, it still has to be a line
 * somebody would use.
 */
export const a1CoreSentences: Sentence[] = [
  // --- Numbers, age, prices ------------------------------------------------
  {
    id: 's.k1',
    es: 'Tengo veintiséis años.',
    en: "I'm twenty-six.",
    altEn: ['I am twenty-six years old.'],
    concepts: ['v.anos', 'g.numbers-system', 'g.tener-expressions'],
    level: 'A1',
    topics: ['numbers', 'introductions'],
    blanks: ['veintiséis'],
    note: 'Age is something you have in Spanish, never something you are.',
  },
  {
    id: 's.k2',
    es: '¿Cuántos años tiene tu hermana?',
    en: 'How old is your sister?',
    concepts: ['p.cuantos-anos-tienes', 'v.tu-pos', 'v.hermano', 'g.possessives'],
    level: 'A1',
    topics: ['numbers', 'family'],
  },
  {
    id: 's.k3',
    es: 'Son cuarenta y cinco euros.',
    en: "That's forty-five euros.",
    concepts: ['g.numbers-system', 'v.cuarenta', 'v.cinco'],
    level: 'A1',
    topics: ['numbers', 'shopping'],
    blanks: ['cuarenta'],
  },
  {
    id: 's.k4',
    es: '¿Cuánto cuesta el billete?',
    en: 'How much does the ticket cost?',
    concepts: ['p.cuanto-cuesta', 'v.billete', 'g.articles'],
    level: 'A1',
    topics: ['numbers', 'transport'],
  },
  {
    id: 's.k5',
    es: 'Mi número es seis, uno, cuatro, dos, ocho.',
    en: 'My number is six, one, four, two, eight.',
    concepts: ['v.numero', 'v.mi', 'g.possessives'],
    level: 'A1',
    topics: ['numbers'],
    note: 'Spaniards usually give phone numbers in pairs: seis, catorce, veintiocho.',
  },
  {
    id: 's.k6',
    es: 'Hay treinta y dos personas en la clase.',
    en: 'There are thirty-two people in the class.',
    concepts: ['g.hay-estar', 'g.numbers-system', 'v.clase'],
    level: 'A1',
    topics: ['numbers', 'university'],
    blanks: ['treinta y dos'],
  },
  {
    id: 's.k7',
    es: 'Quiero dos cafés y una tortilla.',
    en: 'I want two coffees and a tortilla.',
    concepts: ['p.quiero', 'v.dos', 'v.cafe', 'v.tortilla', 'g.plurals'],
    level: 'A1',
    topics: ['cafe', 'numbers'],
  },
  {
    id: 's.k8',
    es: 'El piso cuesta mil euros al mes.',
    en: 'The flat costs a thousand euros a month.',
    concepts: ['v.mil', 'v.piso', 'v.mes'],
    level: 'A1',
    topics: ['numbers', 'home'],
  },

  // --- The calendar --------------------------------------------------------
  {
    id: 's.k9',
    es: 'Mi cumpleaños es el doce de marzo.',
    en: 'My birthday is the twelfth of March.',
    concepts: ['v.cumpleanos', 'v.marzo', 'g.dates', 'v.mi'],
    level: 'A1',
    topics: ['time'],
    blanks: ['doce', 'marzo'],
  },
  {
    id: 's.k10',
    es: 'Los lunes voy al gimnasio.',
    en: 'On Mondays I go to the gym.',
    concepts: ['v.lunes', 'g.dates', 'v.ir'],
    level: 'A1',
    topics: ['time', 'daily-routine'],
    note: 'Plural article = every Monday. El lunes would be this coming Monday.',
  },
  {
    id: 's.k11',
    es: 'El sábado voy a la playa con mis amigos.',
    en: "On Saturday I'm going to the beach with my friends.",
    concepts: ['v.sabado', 'g.dates', 'v.playa', 'v.con', 'v.mi', 'g.ir-a-infinitive'],
    level: 'A1',
    topics: ['time', 'social'],
  },
  {
    id: 's.k12',
    es: 'En agosto no trabaja nadie.',
    en: 'Nobody works in August.',
    concepts: ['v.agosto', 'v.trabajar', 'g.negation'],
    level: 'A1',
    topics: ['time', 'work'],
    note: 'Only half a joke — much of Spain shuts down for August.',
  },
  {
    id: 's.k13',
    es: '¿Qué día es hoy?',
    en: 'What day is it today?',
    concepts: ['v.dia', 'v.hoy', 'g.questions'],
    level: 'A1',
    topics: ['time'],
  },
  {
    id: 's.k14',
    es: 'La semana que viene tengo tres exámenes.',
    en: 'Next week I have three exams.',
    concepts: ['v.semana', 'v.tres', 'v.tener'],
    level: 'A1',
    topics: ['time', 'university'],
    note: 'que viene is how Spain says "next" for time: el mes que viene, el año que viene.',
  },
  {
    id: 's.k15',
    es: 'Nos vemos el jueves por la tarde.',
    en: "See you on Thursday afternoon.",
    concepts: ['v.jueves', 'v.tarde', 'g.dates'],
    level: 'A1',
    topics: ['time', 'social'],
    note: 'por la mañana / por la tarde / por la noche — the part of the day takes por.',
  },

  // --- Where you are from --------------------------------------------------
  {
    id: 's.k16',
    es: 'Soy esloveno, pero soy de un pueblo, no de la capital.',
    en: "I'm Slovenian, but I'm from a village, not the capital.",
    concepts: ['v.esloveno', 'p.soy-de', 'v.ser'],
    level: 'A1',
    topics: ['introductions'],
  },
  {
    id: 's.k17',
    es: 'Mi madre es italiana y mi padre es alemán.',
    en: 'My mother is Italian and my father is German.',
    concepts: ['v.italiano', 'v.aleman', 'v.madre', 'v.padre', 'g.adjective-agreement'],
    level: 'A1',
    topics: ['introductions', 'family'],
    blanks: ['italiana', 'alemán'],
  },
  {
    id: 's.k18',
    es: '¿Cómo se escribe tu apellido?',
    en: 'How do you spell your surname?',
    concepts: ['p.como-se-escribe', 'v.tu-pos'],
    level: 'A1',
    topics: ['introductions'],
  },
  {
    id: 's.k19',
    es: 'Se escribe con hache al principio.',
    en: "It's spelled with an H at the start.",
    concepts: ['p.se-escribe-con', 'v.letra'],
    level: 'A1',
    topics: ['introductions'],
  },
  {
    id: 's.k20',
    es: 'Hablo un poco de español, pero no mucho.',
    en: "I speak a bit of Spanish, but not much.",
    concepts: ['p.hablo-un-poco', 'v.pero', 'v.mucho', 'v.hablar'],
    level: 'A1',
    topics: ['introductions'],
  },
  {
    id: 's.k21',
    es: '¿Puedes repetir, por favor? No entiendo.',
    en: "Can you say that again, please? I don't understand.",
    concepts: ['p.puedes-repetir', 'p.no-entiendo', 'p.por-favor'],
    level: 'A1',
    topics: ['greetings'],
  },
  {
    id: 's.k22',
    es: 'Más despacio, por favor.',
    en: 'Slower, please.',
    concepts: ['p.mas-despacio'],
    level: 'A0',
    topics: ['greetings'],
  },
  {
    id: 's.k23',
    es: 'En España se hablan cuatro idiomas.',
    en: 'Four languages are spoken in Spain.',
    concepts: ['v.espana', 'v.idioma', 'v.cuatro', 'g.plurals'],
    level: 'A1',
    topics: ['introductions'],
    note: 'Castilian, Catalan, Galician and Basque are all official somewhere in Spain.',
  },

  // --- Describing people and things ---------------------------------------
  {
    id: 's.k24',
    es: 'Mi hermana es alta y morena.',
    en: 'My sister is tall and dark-haired.',
    concepts: ['v.alto', 'v.moreno', 'v.hermano', 'g.adjective-agreement', 'v.mi'],
    level: 'A1',
    topics: ['describing', 'family'],
    blanks: ['alta', 'morena'],
  },
  {
    id: 's.k25',
    es: 'Es un chico muy simpático.',
    en: "He's a really friendly guy.",
    concepts: ['v.simpatico', 'v.muy', 'g.articles'],
    level: 'A1',
    topics: ['describing'],
  },
  {
    id: 's.k26',
    es: 'Tiene los ojos verdes y el pelo rubio.',
    en: 'She has green eyes and blond hair.',
    concepts: ['v.ojos', 'v.pelo', 'v.verde', 'v.rubio', 'g.articles'],
    level: 'A1',
    topics: ['describing'],
    note: 'Spanish uses the article here where English uses a possessive.',
  },
  {
    id: 's.k27',
    es: 'Quiero el coche rojo, no el azul.',
    en: 'I want the red car, not the blue one.',
    concepts: ['v.rojo', 'v.azul', 'v.coche', 'g.articles', 'g.negation'],
    level: 'A1',
    topics: ['describing', 'shopping'],
  },
  {
    id: 's.k28',
    es: 'Las casas blancas son muy bonitas.',
    en: 'The white houses are very pretty.',
    concepts: ['v.blanco', 'v.bonito', 'g.plurals', 'g.adjective-agreement'],
    level: 'A1',
    topics: ['describing'],
    blanks: ['blancas', 'bonitas'],
  },
  {
    id: 's.k29',
    es: 'Mis abuelos son mayores pero están muy bien.',
    en: 'My grandparents are elderly but they are doing very well.',
    concepts: ['v.mayor', 'v.abuelo', 'g.ser-estar', 'g.possessives'],
    level: 'A1',
    topics: ['describing', 'family'],
    note: 'ser mayor is what they are; estar bien is how they are today.',
  },

  // --- Possessives and family ---------------------------------------------
  {
    id: 's.k30',
    es: 'Mi hermana vive en un piso pequeño en el centro.',
    en: 'My sister lives in a small flat in the centre.',
    concepts: ['v.mi', 'g.possessives', 'v.vivir', 'v.pequeno'],
    level: 'A1',
    topics: ['family', 'home'],
    blanks: ['Mi'],
  },
  {
    id: 's.k31',
    es: 'Su hermano trabaja en Madrid.',
    en: 'His brother works in Madrid.',
    altEn: ['Her brother works in Madrid.'],
    concepts: ['v.su', 'g.possessives', 'v.trabajar'],
    level: 'A1',
    topics: ['family', 'work'],
    note: 'su is his, her, their or your — only context tells you which.',
  },
  {
    id: 's.k32',
    es: '¿Es vuestra casa?',
    en: 'Is it your house?',
    concepts: ['v.vuestro', 'g.possessives', 'v.casa'],
    level: 'A1',
    topics: ['family', 'home'],
    note: 'Addressed to more than one person — Spain uses vuestro where Latin America says su.',
  },
  {
    id: 's.k33',
    es: 'Nuestro piso está cerca de la plaza.',
    en: 'Our flat is near the square.',
    concepts: ['v.nuestro', 'g.possessives', 'v.piso', 'v.cerca', 'g.hay-estar'],
    level: 'A1',
    topics: ['home', 'city'],
  },

  // --- Demonstratives ------------------------------------------------------
  {
    id: 's.k34',
    es: 'Quiero este, por favor.',
    en: 'I want this one, please.',
    concepts: ['v.este', 'g.demonstratives', 'p.quiero'],
    level: 'A1',
    topics: ['shopping', 'cafe'],
  },
  {
    id: 's.k35',
    es: 'Esa chaqueta es muy cara.',
    en: 'That jacket is very expensive.',
    concepts: ['v.ese', 'g.demonstratives', 'v.caro'],
    level: 'A1',
    topics: ['shopping'],
    blanks: ['Esa'],
  },
  {
    id: 's.k36',
    es: '¿Qué es esto?',
    en: 'What is this?',
    concepts: ['v.este', 'g.demonstratives', 'v.que'],
    level: 'A1',
    topics: ['shopping'],
    note: 'esto is the neuter form — for something you cannot name yet.',
  },
  {
    id: 's.k37',
    es: 'Este café está muy bueno.',
    en: 'This coffee is really good.',
    concepts: ['v.este', 'v.cafe', 'g.ser-estar'],
    level: 'A1',
    topics: ['cafe'],
    note: 'estar bueno for how it tastes today; ser bueno would be a judgement about coffee in general.',
  },

  // --- Weather -------------------------------------------------------------
  {
    id: 's.k38',
    es: '¿Qué tiempo hace en Madrid?',
    en: "What's the weather like in Madrid?",
    concepts: ['p.que-tiempo-hace', 'v.en'],
    level: 'A1',
    topics: ['weather'],
  },
  {
    id: 's.k39',
    es: 'En verano hace mucho calor aquí.',
    en: "In summer it's very hot here.",
    concepts: ['p.hace-calor', 'v.mucho', 'v.aqui'],
    level: 'A1',
    topics: ['weather'],
    blanks: ['calor'],
  },
  {
    id: 's.k40',
    es: 'Hoy hace frío y llueve.',
    en: "Today it's cold and raining.",
    concepts: ['p.hace-frio', 'v.llover', 'v.hoy'],
    level: 'A1',
    topics: ['weather'],
  },
  {
    id: 's.k41',
    es: 'Hace sol, vamos a la playa.',
    en: "It's sunny, let's go to the beach.",
    concepts: ['p.hace-sol', 'v.playa', 'v.ir'],
    level: 'A1',
    topics: ['weather', 'plans'],
  },

  // --- Food, ordering, articles -------------------------------------------
  {
    id: 's.k42',
    es: 'Un café con leche y un zumo de naranja, por favor.',
    en: 'A coffee with milk and an orange juice, please.',
    concepts: ['p.cafe-con-leche', 'v.zumo', 'v.leche', 'g.articles'],
    level: 'A1',
    topics: ['cafe'],
  },
  {
    id: 's.k43',
    es: 'No me gusta el pescado, pero me encanta el jamón.',
    en: "I don't like fish, but I love ham.",
    concepts: ['v.pescado', 'v.jamon', 'g.gustar', 'g.negation'],
    level: 'A1',
    topics: ['food'],
    note: 'Talking about food in general takes the article: el pescado, el jamón.',
  },
  {
    id: 's.k44',
    es: 'Quiero un bocadillo de queso, sin tomate.',
    en: 'I want a cheese sandwich, without tomato.',
    concepts: ['p.quiero', 'v.queso', 'v.sin', 'v.de'],
    level: 'A1',
    topics: ['cafe', 'food'],
  },
  {
    id: 's.k45',
    es: 'Para mí, el pollo con arroz.',
    en: "For me, the chicken with rice.",
    concepts: ['v.para-prep', 'v.pollo', 'v.arroz', 'v.con'],
    level: 'A1',
    topics: ['restaurant'],
    note: 'Para mí… is how you order at a table without repeating quiero every time.',
  },
  {
    id: 's.k46',
    es: 'Quisiera una mesa para dos, por favor.',
    en: "I'd like a table for two, please.",
    concepts: ['p.quisiera', 'v.mesa', 'v.para-prep', 'v.dos'],
    level: 'A1',
    topics: ['restaurant'],
    register: 'formal',
  },
  {
    id: 's.k47',
    es: 'Vamos al bar de la esquina.',
    en: "Let's go to the bar on the corner.",
    concepts: ['g.articles', 'v.ir', 'v.esquina'],
    level: 'A1',
    topics: ['city', 'cafe'],
    blanks: ['al'],
    note: 'a + el contracts to al. Never "a el".',
  },
  {
    id: 's.k48',
    es: 'La puerta del piso está abierta.',
    en: 'The door of the flat is open.',
    concepts: ['g.articles', 'v.piso', 'g.hay-estar'],
    level: 'A1',
    topics: ['home'],
    blanks: ['del'],
  },

  // --- Plurals and quantity ------------------------------------------------
  {
    id: 's.k49',
    es: 'Tengo dos hermanos y una hermana.',
    en: 'I have two brothers and one sister.',
    concepts: ['g.plurals', 'v.hermano', 'v.tener', 'g.numbers-system'],
    level: 'A1',
    topics: ['family', 'numbers'],
  },
  {
    id: 's.k50',
    es: 'Los coches son más caros aquí.',
    en: 'Cars are more expensive here.',
    concepts: ['g.plurals', 'v.coche', 'v.mas', 'v.caro'],
    level: 'A1',
    topics: ['shopping'],
  },
  {
    id: 's.k51',
    es: 'Hay muchos bares en esta calle.',
    en: 'There are lots of bars on this street.',
    concepts: ['g.hay-estar', 'g.plurals', 'v.este', 'v.calle'],
    level: 'A1',
    topics: ['city'],
  },
  {
    id: 's.k52',
    es: 'Quiero otro café, por favor.',
    en: 'I want another coffee, please.',
    concepts: ['v.otro', 'v.cafe', 'p.quiero'],
    level: 'A1',
    topics: ['cafe'],
    note: 'Never un otro — otro already means "another".',
  },
  {
    id: 's.k53',
    es: 'No tengo mucho dinero este mes.',
    en: "I don't have much money this month.",
    concepts: ['v.mucho', 'v.dinero', 'v.este', 'g.negation'],
    level: 'A1',
    topics: ['shopping', 'time'],
  },
  {
    id: 's.k54',
    es: 'Todos mis amigos viven en Barcelona.',
    en: 'All my friends live in Barcelona.',
    concepts: ['v.todo', 'v.mi', 'v.amigo', 'v.vivir', 'g.plurals'],
    level: 'A1',
    topics: ['family', 'city'],
  },

  // --- Courtesy and the rest of the greeting kit ---------------------------
  {
    id: 's.k55',
    es: 'Buenas noches, hasta mañana.',
    en: 'Good night, see you tomorrow.',
    concepts: ['p.buenas-noches', 'p.hasta-manana'],
    level: 'A0',
    topics: ['greetings'],
  },
  {
    id: 's.k56',
    es: '¿Cómo estás? — Muy bien, gracias.',
    en: 'How are you? — Very well, thanks.',
    concepts: ['p.como-estas', 'p.muy-bien', 'v.gracias', 'v.bien'],
    level: 'A0',
    topics: ['greetings'],
  },
  {
    id: 's.k57',
    es: 'Muchas gracias. — De nada.',
    en: 'Thank you very much. — You’re welcome.',
    concepts: ['v.gracias', 'p.de-nada'],
    level: 'A0',
    topics: ['greetings'],
  },
  {
    id: 's.k58',
    es: 'Un café, por favor. — Adiós, hasta luego.',
    en: 'A coffee, please. — Bye, see you later.',
    concepts: ['p.por-favor', 'v.adios', 'p.hasta-luego', 'v.cafe'],
    level: 'A0',
    topics: ['greetings', 'cafe'],
  },
  {
    id: 's.k59',
    es: 'Mucho gusto. Vivo en Madrid desde enero.',
    en: 'Pleased to meet you. I’ve lived in Madrid since January.',
    concepts: ['p.mucho-gusto', 'p.vivo-en', 'v.enero'],
    level: 'A1',
    topics: ['introductions'],
  },

  // --- Question words and connectors --------------------------------------
  {
    id: 's.k60',
    es: '¿Cuándo llegas? — El viernes por la noche.',
    en: 'When do you arrive? — Friday night.',
    concepts: ['v.cuando', 'v.viernes', 'v.noche', 'g.questions'],
    level: 'A1',
    topics: ['time'],
  },
  {
    id: 's.k61',
    es: '¿Por qué estudias español? — Porque vivo en España.',
    en: 'Why do you study Spanish? — Because I live in Spain.',
    concepts: ['v.por-que', 'v.porque', 'v.estudiar', 'v.espana'],
    level: 'A1',
    topics: ['introductions', 'university'],
    note: 'Two words with an accent for the question, one word without for the answer.',
  },
  {
    id: 's.k62',
    es: '¿Cuánto cuesta? Es muy caro.',
    en: 'How much does it cost? It’s very expensive.',
    concepts: ['v.cuanto', 'v.muy', 'v.caro', 'p.cuanto-cuesta'],
    level: 'A1',
    topics: ['shopping'],
  },
  {
    id: 's.k63',
    es: 'Hablo inglés y un poco de español, pero no francés.',
    en: 'I speak English and a bit of Spanish, but not French.',
    concepts: ['v.y', 'v.pero', 'v.un-poco', 'v.ingles', 'v.frances', 'g.negation'],
    level: 'A1',
    topics: ['introductions'],
  },
  {
    id: 's.k64',
    es: 'Mi hermano también trabaja aquí.',
    en: 'My brother works here too.',
    concepts: ['v.tambien', 'v.hermano', 'v.trabajar', 'v.aqui'],
    level: 'A1',
    topics: ['family', 'work'],
  },
  {
    id: 's.k65',
    es: 'Hoy estoy mal, pero mañana voy a estar bien.',
    en: 'Today I feel bad, but tomorrow I’ll be fine.',
    concepts: ['v.mal', 'v.bien', 'g.ir-a-infinitive', 'g.ser-estar'],
    level: 'A1',
    topics: ['feelings'],
  },
  {
    id: 's.k66',
    es: 'El español no es difícil, es fácil.',
    en: 'Spanish isn’t difficult, it’s easy.',
    concepts: ['v.dificil', 'v.facil', 'v.espanol', 'g.negation'],
    level: 'A1',
    topics: ['university'],
  },
  {
    id: 's.k67',
    es: 'Quiero más pan y menos arroz.',
    en: 'I want more bread and less rice.',
    concepts: ['v.mas', 'v.menos', 'v.pan', 'v.arroz'],
    level: 'A1',
    topics: ['food'],
  },
  {
    id: 's.k68',
    es: 'Voy con mi hermana, no con mis padres.',
    en: 'I’m going with my sister, not with my parents.',
    concepts: ['v.con', 'v.mi', 'g.negation', 'v.ir'],
    level: 'A1',
    topics: ['family'],
  },
  {
    id: 's.k69',
    es: 'Es la casa de mi abuela.',
    en: 'It’s my grandmother’s house.',
    concepts: ['v.de', 'v.casa', 'v.abuelo', 'g.possessives'],
    level: 'A1',
    topics: ['family', 'home'],
    note: 'Spanish has no apostrophe-s: possession is built with de.',
  },

  // --- Food on the table ---------------------------------------------------
  {
    id: 's.k70',
    es: '¿Qué hay para comer?',
    en: 'What is there to eat?',
    concepts: ['p.hay-que-comer', 'g.hay-estar', 'v.comer'],
    level: 'A1',
    topics: ['food'],
  },
  {
    id: 's.k71',
    es: 'Como carne, pescado y mucha verdura.',
    en: 'I eat meat, fish and lots of vegetables.',
    concepts: ['v.carne', 'v.pescado', 'v.verdura', 'v.mucho', 'v.comer'],
    level: 'A1',
    topics: ['food'],
  },
  {
    id: 's.k72',
    es: 'Para desayunar tomo fruta y un huevo.',
    en: 'For breakfast I have fruit and an egg.',
    concepts: ['v.fruta', 'v.huevo', 'v.tomar', 'v.desayuno'],
    level: 'A1',
    topics: ['food'],
  },
  {
    id: 's.k73',
    es: 'Una copa de vino tinto, por favor.',
    en: 'A glass of red wine, please.',
    concepts: ['v.vino', 'p.por-favor', 'v.de'],
    level: 'A1',
    topics: ['restaurant'],
  },
  {
    id: 's.k74',
    es: '¿Se puede pagar con tarjeta o solo en efectivo?',
    en: 'Can you pay by card or only in cash?',
    concepts: ['v.pagar', 'v.con', 'v.poder'],
    level: 'A1',
    topics: ['shopping', 'cafe'],
  },

  // --- Work, study, travel -------------------------------------------------
  {
    id: 's.k75',
    es: 'Trabajo en una tienda y estudio en la universidad.',
    en: 'I work in a shop and study at university.',
    concepts: ['v.trabajo', 'v.universidad', 'v.trabajar', 'v.estudiar', 'v.tienda'],
    level: 'A1',
    topics: ['work', 'university'],
  },
  {
    id: 's.k76',
    es: 'La clase es a las nueve de la mañana.',
    en: 'The class is at nine in the morning.',
    concepts: ['v.clase', 'v.nueve', 'v.manana', 'p.son-las'],
    level: 'A1',
    topics: ['university', 'time'],
  },
  {
    id: 's.k77',
    es: 'Me gusta viajar, sobre todo en verano.',
    en: 'I like travelling, especially in summer.',
    concepts: ['v.viajar', 'p.me-gusta', 'g.gustar'],
    level: 'A1',
    topics: ['hobbies', 'travel'],
  },
  {
    id: 's.k78',
    es: 'Después de la playa vamos al hotel.',
    en: 'After the beach we go to the hotel.',
    concepts: ['v.despues', 'v.playa', 'v.hotel', 'g.articles'],
    level: 'A1',
    topics: ['travel'],
  },
  {
    id: 's.k79',
    es: '¿Qué hacéis mañana por la tarde?',
    en: 'What are you (all) doing tomorrow afternoon?',
    concepts: ['v.manana', 'v.tarde', 'v.hacer', 'v.vosotros'],
    level: 'A1',
    topics: ['plans'],
  },
  {
    id: 's.k80',
    es: 'No me gusta el fútbol, pero me gustan las películas.',
    en: 'I don’t like football, but I like films.',
    concepts: ['p.me-gusta', 'p.me-gustan', 'v.futbol', 'v.pelicula', 'g.gustar', 'g.negation'],
    level: 'A1',
    topics: ['hobbies'],
    note: 'gusta for one thing, gustan for several — the verb agrees with what is liked.',
  },
// --- Numbers you actually hear said aloud --------------------------------
  {
    id: 's.k81',
    es: 'Mi número es seis, cero, once, veinte, trece.',
    en: 'My number is six, zero, eleven, twenty, thirteen.',
    concepts: ['v.seis', 'v.cero', 'v.once', 'v.veinte', 'v.trece'],
    level: 'A1',
    topics: ['numbers'],
    note: 'Spanish phone numbers are read in pairs or singly — never as one long figure.',
  },
  {
    id: 's.k82',
    es: 'El autobús catorce pasa cada quince minutos.',
    en: 'The number fourteen bus comes every fifteen minutes.',
    concepts: ['v.catorce', 'v.quince', 'v.autobus'],
    level: 'A1',
    topics: ['numbers', 'transport'],
  },
  {
    id: 's.k83',
    es: 'Somos dieciséis en clase, diecisiete con el profesor.',
    en: 'There are sixteen of us in the class, seventeen with the teacher.',
    concepts: ['v.dieciseis', 'v.diecisiete', 'v.clase'],
    level: 'A1',
    topics: ['numbers', 'university'],
  },
  {
    id: 's.k84',
    es: 'Cumplo dieciocho el jueves y mi hermano diecinueve en mayo.',
    en: 'I turn eighteen on Thursday and my brother nineteen in May.',
    concepts: ['v.dieciocho', 'v.diecinueve', 'v.mayo', 'v.hermano'],
    level: 'A1',
    topics: ['numbers', 'family', 'time'],
  },
  {
    id: 's.k85',
    es: 'El billete cuesta veintiuno con cincuenta.',
    en: 'The ticket costs twenty-one fifty.',
    concepts: ['v.veintiuno', 'v.cincuenta', 'v.billete'],
    level: 'A1',
    topics: ['numbers', 'transport'],
    note: 'Prices join euros and cents with con: veintiuno con cincuenta.',
  },
  {
    id: 's.k86',
    es: 'Mi abuela tiene sesenta y siete años y mi abuelo setenta.',
    en: 'My grandmother is sixty-seven and my grandfather seventy.',
    concepts: ['v.sesenta', 'v.setenta', 'v.anos'],
    level: 'A1',
    topics: ['numbers', 'family'],
  },
  {
    id: 's.k87',
    es: 'De Madrid a Toledo hay ochenta kilómetros; a Segovia, noventa.',
    en: 'From Madrid to Toledo it’s eighty kilometres; to Segovia, ninety.',
    concepts: ['v.ochenta', 'v.noventa'],
    level: 'A1',
    topics: ['numbers', 'travel'],
  },
  {
    id: 's.k88',
    es: 'Póngame cien gramos de jamón, por favor.',
    en: 'Give me a hundred grams of ham, please.',
    concepts: ['v.cien', 'p.por-favor'],
    level: 'A1',
    topics: ['numbers', 'shopping', 'food'],
  },
  {
    id: 's.k89',
    es: 'Doce menos uno son once, y once menos dos son nueve.',
    en: 'Twelve minus one is eleven, and eleven minus two is nine.',
    concepts: ['v.doce', 'v.once', 'v.menos'],
    level: 'A1',
    topics: ['numbers'],
  },

  // --- The calendar in use -------------------------------------------------
  {
    id: 's.k90',
    es: 'En febrero hace frío, pero en abril ya se está bien.',
    en: 'In February it’s cold, but by April it’s already pleasant.',
    concepts: ['v.febrero', 'v.abril', 'p.hace-frio'],
    level: 'A1',
    topics: ['time', 'weather'],
  },
  {
    id: 's.k91',
    es: 'Las vacaciones son en julio o en agosto, nunca en junio.',
    en: 'The holidays are in July or August, never in June.',
    concepts: ['v.julio', 'v.junio', 'v.nunca'],
    level: 'A1',
    topics: ['time'],
  },
  {
    id: 's.k92',
    es: 'El curso empieza en septiembre y termina en diciembre.',
    en: 'The course starts in September and finishes in December.',
    concepts: ['v.septiembre', 'v.diciembre', 'v.clase'],
    level: 'A1',
    topics: ['time', 'university'],
  },
  {
    id: 's.k93',
    es: 'En octubre llueve mucho; en noviembre, más.',
    en: 'In October it rains a lot; in November, more.',
    concepts: ['v.octubre', 'v.noviembre', 'v.llover'],
    level: 'A1',
    topics: ['time', 'weather'],
  },
  {
    id: 's.k94',
    es: 'Los miércoles voy al gimnasio y los domingos no hago nada.',
    en: 'On Wednesdays I go to the gym and on Sundays I do nothing.',
    concepts: ['v.miercoles', 'v.domingo', 'v.hacer'],
    level: 'A1',
    topics: ['time', 'daily-routine'],
    note: 'los miércoles — with the plural article — means "every Wednesday".',
  },
  {
    id: 's.k95',
    es: '¿Cuándo es tu cumpleaños? — El dos de mayo.',
    en: 'When is your birthday? — The second of May.',
    concepts: ['p.cuando-es-tu-cumple', 'v.mayo', 'v.dos'],
    level: 'A1',
    topics: ['time', 'social'],
  },

  // --- Where people are from -----------------------------------------------
  {
    id: 's.k96',
    es: 'Mi madre es de Francia y mi padre de Italia.',
    en: 'My mother is from France and my father from Italy.',
    concepts: ['v.francia', 'v.italia', 'p.soy-de'],
    level: 'A1',
    topics: ['introductions', 'family'],
  },
  {
    id: 's.k97',
    es: 'He estado en Inglaterra y en Alemania, pero nunca en Eslovenia.',
    en: 'I’ve been to England and Germany, but never to Slovenia.',
    concepts: ['v.inglaterra', 'v.alemania', 'v.eslovenia'],
    level: 'A1',
    topics: ['travel', 'introductions'],
  },

  // --- Pronouns doing real work -------------------------------------------
  {
    id: 's.k98',
    es: 'Yo soy Mate. ¿Y tú cómo te llamas?',
    en: 'I’m Mate. And what’s your name?',
    concepts: ['v.yo', 'v.tu', 'v.como-q'],
    level: 'A1',
    topics: ['introductions', 'greetings'],
    note: 'Spanish drops subject pronouns by default — yo and tú appear here precisely to contrast the two people.',
  },
  {
    id: 's.k99',
    es: 'Él es mi hermano y ellos son mis primos.',
    en: 'He is my brother and they are my cousins.',
    concepts: ['v.el-pron', 'v.ellos', 'v.hermano'],
    level: 'A1',
    topics: ['family', 'people'],
  },
  {
    id: 's.k100',
    es: '¿Quién es esa chica? — No sé quién es.',
    en: 'Who is that girl? — I don’t know who she is.',
    concepts: ['v.quien', 'v.saber'],
    level: 'A1',
    topics: ['people', 'introductions'],
  },

  // --- Colour, appearance and mood ----------------------------------------
  {
    id: 's.k101',
    es: 'Mi color favorito es el amarillo; el gris no me gusta nada.',
    en: 'My favourite colour is yellow; I don’t like grey at all.',
    concepts: ['v.color', 'v.amarillo', 'v.gris'],
    level: 'A1',
    topics: ['describing'],
  },
  {
    id: 's.k102',
    es: 'Es bajo, joven y bastante guapo.',
    en: 'He’s short, young and quite good-looking.',
    concepts: ['v.bajo', 'v.joven', 'v.guapo'],
    level: 'A1',
    topics: ['describing', 'people'],
  },
  {
    id: 's.k103',
    es: 'Hoy estoy triste, pero mañana estaré mejor.',
    en: 'Today I’m sad, but tomorrow I’ll be better.',
    concepts: ['v.triste', 'v.estar', 'v.manana'],
    level: 'A1',
    topics: ['feelings'],
  },
  {
    id: 's.k104',
    es: 'Aquel edificio de allí es el más antiguo del barrio.',
    en: 'That building over there is the oldest in the neighbourhood.',
    concepts: ['v.aquel', 'g.demonstratives'],
    level: 'A1',
    topics: ['city', 'describing'],
    note: 'aquel is for things far from both speakers — Spanish has three distances, not two.',
  },

  // --- The rest of everyday A1 --------------------------------------------
  {
    id: 's.k105',
    es: 'Hace viento y hace frío, pero no llueve.',
    en: 'It’s windy and cold, but it isn’t raining.',
    concepts: ['p.hace-viento', 'p.hace-frio', 'v.llover'],
    level: 'A1',
    topics: ['weather'],
  },
  {
    id: 's.k106',
    es: 'Dos cervezas y algo de comida, por favor.',
    en: 'Two beers and something to eat, please.',
    concepts: ['v.cerveza', 'v.comida', 'v.dos'],
    level: 'A1',
    topics: ['cafe', 'food'],
  },
  {
    id: 's.k107',
    es: 'Voy a la playa a las cinco con mis amigos.',
    en: 'I’m going to the beach at five with my friends.',
    concepts: ['v.a-prep', 'v.ir', 'v.amigo'],
    level: 'A1',
    topics: ['plans', 'social'],
    note: 'The same a marks both destination (a la playa) and time (a las cinco).',
  },
  {
    id: 's.k108',
    es: 'Perdona, ¿dónde está el baño?',
    en: 'Excuse me, where’s the toilet?',
    concepts: ['p.donde-esta', 'v.perdona'],
    level: 'A1',
    topics: ['cafe', 'directions'],
  },
  {
    id: 's.k109',
    es: 'A mí me gusta el cine, pero a él le gusta más el teatro.',
    en: 'I like the cinema, but he prefers the theatre.',
    concepts: ['v.gustar', 'g.gustar', 'v.el-pron'],
    level: 'A1',
    topics: ['hobbies', 'opinions'],
    note: 'a mí / a él are added only to contrast people — the me and le are the obligatory part.',
  },
  {
    id: 's.k110',
    es: '¿Qué haces mañana? — Nada especial, ¿por qué?',
    en: 'What are you doing tomorrow? — Nothing special, why?',
    concepts: ['p.qué-haces', 'v.manana', 'v.hacer'],
    level: 'A1',
    topics: ['plans', 'social'],
  },
  {
    id: 's.k111',
    es: 'El problema es que la mano derecha me duele mucho.',
    en: 'The problem is that my right hand hurts a lot.',
    concepts: ['g.gender', 'v.mano', 'p.me-duele'],
    level: 'A1',
    topics: ['health'],
    note: 'Two traps at once: el problema is masculine despite the -a, la mano feminine despite the -o.',
  },
  {
    id: 's.k112',
    es: 'Buenas tardes, ¿está libre esta mesa?',
    en: 'Good afternoon, is this table free?',
    concepts: ['p.buenas-tardes', 'v.mesa', 'v.estar'],
    level: 'A1',
    topics: ['cafe', 'greetings'],
    note: 'buenas tardes runs from after lunch — around three — until it gets dark, not from noon.',
  },
];
