import type { Sentence } from '@/content/types';

/**
 * A2 sentences: health, clothes, comparing things and saying why you prefer
 * one over another.
 *
 * A2 is where sentences stop being single clauses. Many of these carry a
 * reason, a contrast or a comparison, because that is the actual jump from A1 —
 * not longer vocabulary but connected thought.
 */
export const a2CoreSentences: Sentence[] = [
  // --- Health --------------------------------------------------------------
  {
    id: 's.m1',
    es: '¿Qué te pasa? — Me duele la cabeza.',
    en: "What's wrong? — My head hurts.",
    concepts: ['p.que-te-pasa', 'p.me-duele', 'v.cabeza'],
    level: 'A2',
    topics: ['health'],
    blanks: ['duele'],
  },
  {
    id: 's.m2',
    es: 'Me duelen los pies porque he andado mucho.',
    en: "My feet hurt because I've walked a lot.",
    concepts: ['p.me-duele', 'v.pie', 'v.porque', 'g.present-perfect'],
    level: 'A2',
    topics: ['health'],
    note: 'duelen, plural, because los pies is the subject — the same backwards logic as gustar.',
  },
  {
    id: 's.m3',
    es: 'Estoy malo. Creo que tengo fiebre.',
    en: "I'm ill. I think I have a fever.",
    concepts: ['p.estoy-malo', 'v.fiebre', 'v.creo-que', 'g.ser-estar'],
    level: 'A2',
    topics: ['health'],
  },
  {
    id: 's.m4',
    es: 'Tengo que pedir cita con el médico.',
    en: 'I have to make an appointment with the doctor.',
    concepts: ['v.cita', 'v.medico', 'p.tener-que'],
    level: 'A2',
    topics: ['health'],
  },
  {
    id: 's.m5',
    es: 'La farmacia está enfrente del supermercado.',
    en: 'The pharmacy is opposite the supermarket.',
    concepts: ['v.farmacia', 'v.enfrente', 'v.supermercado', 'g.hay-estar'],
    level: 'A2',
    topics: ['health', 'city'],
  },
  {
    id: 's.m6',
    es: 'Me duele la garganta y tengo un resfriado.',
    en: 'My throat hurts and I have a cold.',
    concepts: ['v.garganta', 'v.resfriado', 'p.me-duele'],
    level: 'A2',
    topics: ['health'],
  },
  {
    id: 's.m7',
    es: 'No he dormido bien, me duele la espalda.',
    en: "I haven't slept well, my back hurts.",
    concepts: ['v.espalda', 'p.me-duele', 'g.present-perfect', 'g.negation'],
    level: 'A2',
    topics: ['health'],
  },
  {
    id: 's.m8',
    es: 'Que te mejores pronto.',
    en: 'Get well soon.',
    concepts: ['p.que-te-mejores'],
    level: 'A2',
    topics: ['health', 'social'],
  },

  // --- Clothes and shopping ------------------------------------------------
  {
    id: 's.m9',
    es: '¿Puedo probármelo? — Sí, claro, el probador está allí.',
    en: 'Can I try it on? — Yes, of course, the changing room is over there.',
    concepts: ['p.puedo-probarme', 'v.claro', 'v.alli'],
    level: 'A2',
    topics: ['shopping'],
  },
  {
    id: 's.m10',
    es: 'Esta camiseta me queda bien, pero es demasiado cara.',
    en: 'This T-shirt fits me, but it’s too expensive.',
    concepts: ['v.camiseta', 'p.me-queda-bien', 'v.demasiado', 'v.caro', 'v.este'],
    level: 'A2',
    topics: ['shopping'],
    blanks: ['demasiado'],
  },
  {
    id: 's.m11',
    es: 'Busco unos pantalones negros de la talla cuarenta.',
    en: "I'm looking for black trousers in size forty.",
    concepts: ['v.pantalones', 'v.negro', 'v.talla', 'v.cuarenta'],
    level: 'A2',
    topics: ['shopping'],
  },
  {
    id: 's.m12',
    es: 'No, gracias, solo estoy mirando.',
    en: "No thanks, I'm just looking.",
    concepts: ['p.solo-estoy-mirando', 'v.gracias'],
    level: 'A2',
    topics: ['shopping'],
  },
  {
    id: 's.m13',
    es: 'Prefiero la chaqueta azul porque es más barata.',
    en: 'I prefer the blue jacket because it’s cheaper.',
    concepts: ['v.preferir', 'v.chaqueta', 'v.azul', 'v.porque', 'g.comparisons', 'v.barato'],
    level: 'A2',
    topics: ['shopping', 'opinions'],
    blanks: ['Prefiero', 'más'],
  },
  {
    id: 's.m14',
    es: 'Estos zapatos son más cómodos que los otros.',
    en: 'These shoes are more comfortable than the others.',
    concepts: ['v.zapatos', 'g.comparisons', 'v.este', 'v.otro'],
    level: 'A2',
    topics: ['shopping'],
  },

  // --- Comparing -----------------------------------------------------------
  {
    id: 's.m15',
    es: 'Madrid es más grande que Sevilla, pero Sevilla es más bonita.',
    en: 'Madrid is bigger than Seville, but Seville is prettier.',
    concepts: ['g.comparisons', 'v.grande', 'v.bonito', 'v.pero'],
    level: 'A2',
    topics: ['city', 'opinions'],
    blanks: ['más grande que'],
  },
  {
    id: 's.m16',
    es: 'El metro es más rápido que el autobús y más barato que el taxi.',
    en: 'The metro is faster than the bus and cheaper than a taxi.',
    concepts: ['g.comparisons', 'v.metro', 'v.autobus', 'v.barato'],
    level: 'A2',
    topics: ['transport'],
  },
  {
    id: 's.m17',
    es: 'Esta es la mejor tortilla del barrio.',
    en: 'This is the best tortilla in the neighbourhood.',
    concepts: ['v.mejor', 'g.comparisons', 'v.tortilla'],
    level: 'A2',
    topics: ['food', 'opinions'],
    note: 'Superlative takes de, never en: la mejor de Madrid.',
  },
  {
    id: 's.m18',
    es: 'Hoy hace peor tiempo que ayer.',
    en: 'The weather is worse today than yesterday.',
    concepts: ['v.peor', 'g.comparisons', 'v.tiempo', 'v.ayer'],
    level: 'A2',
    topics: ['weather'],
  },
  {
    id: 's.m19',
    es: 'Mi piso no es tan grande como el tuyo.',
    en: "My flat isn't as big as yours.",
    concepts: ['v.tan', 'g.comparisons', 'v.piso', 'g.negation'],
    level: 'A2',
    topics: ['home'],
    blanks: ['tan', 'como'],
  },
  {
    id: 's.m20',
    es: 'El billete cuesta más de treinta euros.',
    en: 'The ticket costs more than thirty euros.',
    concepts: ['g.comparisons', 'v.billete', 'v.treinta'],
    level: 'A2',
    topics: ['transport', 'numbers'],
    note: 'Before a number it is más de, not más que.',
  },
  {
    id: 's.m21',
    es: 'Mi hermano mayor vive en Valencia.',
    en: 'My older brother lives in Valencia.',
    concepts: ['v.mayor', 'v.hermano', 'g.comparisons'],
    level: 'A2',
    topics: ['family'],
    note: 'mayor and menor are the normal words for older and younger siblings.',
  },

  // --- muy vs mucho, and giving reasons ------------------------------------
  {
    id: 's.m22',
    es: 'Hace mucho calor y estoy muy cansado.',
    en: "It's very hot and I'm very tired.",
    concepts: ['g.muy-mucho', 'p.hace-calor', 'v.cansado'],
    level: 'A2',
    topics: ['weather', 'feelings'],
    blanks: ['mucho', 'muy'],
    note: 'mucho with the noun calor, muy with the adjective cansado.',
  },
  {
    id: 's.m23',
    es: 'Hay muchos turistas en agosto, demasiados.',
    en: 'There are a lot of tourists in August, too many.',
    concepts: ['g.muy-mucho', 'v.demasiado', 'v.agosto', 'g.hay-estar'],
    level: 'A2',
    topics: ['travel'],
  },
  {
    id: 's.m24',
    es: 'El curso es bastante difícil, pero me gusta mucho.',
    en: "The course is fairly hard, but I like it a lot.",
    concepts: ['v.bastante', 'v.dificil', 'g.muy-mucho', 'p.me-gusta'],
    level: 'A2',
    topics: ['university', 'opinions'],
  },
  {
    id: 's.m25',
    es: 'Me encanta cocinar, pero no soporto fregar.',
    en: "I love cooking, but I can't stand washing up.",
    concepts: ['p.me-encanta', 'p.no-soporto', 'v.cocinar'],
    level: 'A2',
    topics: ['hobbies', 'opinions'],
  },
  {
    id: 's.m26',
    es: 'Prefiero el tren porque puedo leer durante el viaje.',
    en: 'I prefer the train because I can read during the journey.',
    concepts: ['p.prefiero-porque', 'v.preferir', 'v.tren', 'v.leer', 'v.viaje'],
    level: 'A2',
    topics: ['transport', 'opinions'],
    note: 'Preference plus reason — the sentence shape A2 is really about.',
  },
  {
    id: 's.m27',
    es: 'No me gusta nada este barrio, es demasiado ruidoso.',
    en: "I don't like this neighbourhood at all, it's too noisy.",
    concepts: ['p.no-me-gusta-nada', 'v.demasiado', 'v.este'],
    level: 'A2',
    topics: ['city', 'opinions'],
  },
  {
    id: 's.m28',
    es: 'Me encantan las ciudades pequeñas, son más tranquilas.',
    en: 'I love small cities, they’re calmer.',
    concepts: ['p.me-encanta', 'v.ciudad', 'v.pequeno', 'g.comparisons', 'g.plurals'],
    level: 'A2',
    topics: ['city', 'opinions'],
  },

  // --- The body and being unwell -------------------------------------------
  {
    id: 's.m29',
    es: '—¿Qué te pasa? —Nada, que me duele un poco la cabeza.',
    en: '“What’s wrong?” “Nothing, my head just hurts a bit.”',
    concepts: ['p.que-te-pasa', 'v.cabeza', 'p.me-duele'],
    level: 'A2',
    topics: ['health'],
    note: 'That opening Nada, que… softens the complaint before making it — very Spanish.',
  },
  {
    id: 's.m30',
    es: 'Estoy malo desde el lunes, creo que tengo fiebre.',
    en: 'I’ve been ill since Monday, I think I have a temperature.',
    concepts: ['p.estoy-malo', 'v.fiebre', 'v.lunes'],
    level: 'A2',
    topics: ['health'],
    note: 'estar malo is ill; ser malo would mean a bad person.',
  },
  {
    id: 's.m31',
    es: 'Con este resfriado me duele la garganta al hablar.',
    en: 'With this cold my throat hurts when I speak.',
    concepts: ['v.resfriado', 'v.garganta', 'v.hablar'],
    level: 'A2',
    topics: ['health'],
    note: 'al + infinitivo = "when/on doing" — al hablar, al salir, al llegar.',
  },
  {
    id: 's.m32',
    es: 'Después de correr me duelen las piernas y la espalda.',
    en: 'After running my legs and back hurt.',
    concepts: ['v.espalda', 'p.me-duele', 'v.despues'],
    level: 'A2',
    topics: ['health', 'daily-routine'],
  },
  {
    id: 's.m33',
    es: 'Llevo todo el día de pie y ya no puedo más.',
    en: 'I’ve been on my feet all day and I can’t take any more.',
    concepts: ['v.pie', 'v.poder', 'v.dia'],
    level: 'A2',
    topics: ['health', 'work'],
    register: 'colloquial',
  },
  {
    id: 's.m34',
    es: 'Si sigues así, tienes que ir al médico, no a la farmacia.',
    en: 'If you carry on like this, you have to see a doctor, not go to the chemist.',
    concepts: ['v.medico', 'v.farmacia', 'p.tener-que'],
    level: 'A2',
    topics: ['health'],
  },
  {
    id: 's.m35',
    es: 'Me duele el estómago, creo que ha sido la cena.',
    en: 'My stomach hurts, I think it was dinner.',
    concepts: ['v.estomago', 'g.present-perfect', 'v.cena'],
    level: 'A2',
    topics: ['health', 'food'],
  },
  {
    id: 's.m36',
    es: '—Me voy a la cama. —Vale, que te mejores.',
    en: '“I’m off to bed.” “Okay, get well soon.”',
    concepts: ['p.que-te-mejores', 'v.vale'],
    level: 'A2',
    topics: ['health', 'social'],
    note: 'que + subjunctive as a wish: que te mejores, que descanses, que aproveche.',
  },

  // --- Clothes and trying things on ----------------------------------------
  {
    id: 's.m37',
    es: 'Necesito ropa de invierno: una chaqueta y unos zapatos buenos.',
    en: 'I need winter clothes: a jacket and some decent shoes.',
    concepts: ['v.ropa', 'v.chaqueta', 'v.zapatos'],
    level: 'A2',
    topics: ['shopping'],
  },
  {
    id: 's.m38',
    es: 'Estos pantalones me quedan largos, ¿hay una talla menos?',
    en: 'These trousers are too long on me, is there a size smaller?',
    concepts: ['v.pantalones', 'p.me-queda-bien', 'v.talla'],
    level: 'A2',
    topics: ['shopping'],
  },
  {
    id: 's.m39',
    es: 'La camisa blanca con el vestido negro queda muy bien.',
    en: 'The white shirt goes really well with the black dress.',
    concepts: ['v.camisa', 'v.vestido', 'v.blanco'],
    level: 'A2',
    topics: ['shopping', 'describing'],
  },
  {
    id: 's.m40',
    es: '¿Puedo probarme estos dos y luego decido?',
    en: 'Can I try these two on and decide afterwards?',
    concepts: ['p.puedo-probarme', 'v.probar', 'v.luego'],
    level: 'A2',
    topics: ['shopping'],
  },
  {
    id: 's.m41',
    es: '—¿Te ayudo? —No, gracias, solo estoy mirando.',
    en: '“Can I help?” “No thanks, I’m just looking.”',
    concepts: ['p.solo-estoy-mirando', 'v.gracias'],
    level: 'A2',
    topics: ['shopping'],
  },

  // --- Comparing, which is where A2 opinions start -------------------------
  {
    id: 's.m42',
    es: 'Este bar es mejor que el otro y encima más barato.',
    en: 'This bar is better than the other one and cheaper on top of that.',
    concepts: ['v.mejor', 'g.comparisons', 'v.barato'],
    level: 'A2',
    topics: ['opinions', 'cafe'],
  },
  {
    id: 's.m43',
    es: 'El tiempo hoy está peor que ayer, y ayer ya era malo.',
    en: 'The weather today is worse than yesterday, and yesterday was already bad.',
    concepts: ['v.peor', 'g.comparisons', 'v.tiempo'],
    level: 'A2',
    topics: ['weather', 'opinions'],
  },
  {
    id: 's.m44',
    es: 'Mi piso no es tan grande como el tuyo, pero está más céntrico.',
    en: 'My flat isn’t as big as yours, but it’s more central.',
    concepts: ['v.tan', 'g.comparisons', 'v.piso'],
    level: 'A2',
    topics: ['home', 'opinions'],
    blanks: ['tan'],
    note: 'tan… como for equality; más… que for difference. Mixing them is the usual slip.',
  },
  {
    id: 's.m45',
    es: 'Prefiero quedar por la tarde porque por la mañana trabajo.',
    en: 'I prefer meeting in the afternoon because I work in the morning.',
    concepts: ['p.prefiero-porque', 'v.quedar', 'v.tarde'],
    level: 'A2',
    topics: ['plans', 'opinions'],
  },

  // --- Present perfect across the persons, including vosotros --------------
  {
    id: 's.m46',
    es: '¿Habéis visto lo que ha pasado en la plaza?',
    en: 'Have you seen what’s happened in the square?',
    concepts: ['g.present-perfect', 'v.vosotros', 'v.ver'],
    level: 'A2',
    topics: ['city', 'past'],
  },
  {
    id: 's.m47',
    es: 'Hemos tenido mucha suerte con el tiempo esta semana.',
    en: 'We’ve been very lucky with the weather this week.',
    concepts: ['g.present-perfect', 'v.tener', 'v.tiempo'],
    level: 'A2',
    topics: ['weather', 'past'],
  },
  {
    id: 's.m48',
    es: 'Todavía no ha venido nadie, es muy temprano.',
    en: 'Nobody has come yet, it’s very early.',
    concepts: ['g.present-perfect', 'v.venir', 'g.negation'],
    level: 'A2',
    topics: ['social'],
  },
  {
    id: 's.m49',
    es: '¿Has salido ya del trabajo o sigues allí?',
    en: 'Have you left work yet or are you still there?',
    concepts: ['g.present-perfect', 'v.salir', 'v.trabajo'],
    level: 'A2',
    topics: ['work'],
  },
  {
    id: 's.m50',
    es: 'Han dicho en la radio que va a llover.',
    en: 'They said on the radio that it’s going to rain.',
    concepts: ['g.present-perfect', 'v.decir', 'v.llover'],
    level: 'A2',
    topics: ['weather'],
  },
  {
    id: 's.m51',
    es: 'He puesto la mesa y he hecho la cena, te toca fregar.',
    en: 'I’ve laid the table and made dinner — you’re washing up.',
    concepts: ['g.present-perfect', 'v.poner', 'v.hacer'],
    level: 'A2',
    topics: ['home', 'food'],
    note: 'puesto and hecho are irregular participles — never ponido or hacido.',
  },
  {
    id: 's.m52',
    es: 'Hemos ido dos veces y las dos estaba cerrado.',
    en: 'We’ve been twice and both times it was closed.',
    concepts: ['g.present-perfect', 'v.ir', 'v.dos'],
    level: 'A2',
    topics: ['past', 'city'],
  },
  {
    id: 's.m53',
    es: 'Nunca hemos estado en Galicia, pero nos apetece mucho.',
    en: 'We’ve never been to Galicia, but we’d really like to.',
    concepts: ['g.present-perfect', 'v.estar', 'p.me-apetece'],
    level: 'A2',
    topics: ['travel'],
  },
  {
    id: 's.m54',
    es: '¿Le habéis dado ya el regalo?',
    en: 'Have you given him the present yet?',
    concepts: ['g.present-perfect', 'v.dar', 'v.vosotros'],
    level: 'A2',
    topics: ['social'],
  },

  // --- muy or mucho, the distinction that never stops mattering ------------
  {
    id: 's.m55',
    es: 'Trabaja mucho y está muy cansado.',
    en: 'He works a lot and he’s very tired.',
    concepts: ['g.muy-mucho', 'v.trabajar', 'v.cansado'],
    level: 'A2',
    topics: ['work', 'feelings'],
    blanks: ['mucho', 'muy'],
    note: 'mucho modifies the verb, muy the adjective. One sentence, both jobs.',
  },
  {
    id: 's.m56',
    es: 'Hay mucha gente y hace muy buen tiempo.',
    en: 'There are a lot of people and the weather is very good.',
    concepts: ['g.muy-mucho', 'v.gente', 'p.que-tiempo-hace'],
    level: 'A2',
    topics: ['weather', 'city'],
  },
  {
    id: 's.m57',
    es: 'Me gusta mucho, pero es muy caro para mí.',
    en: 'I like it a lot, but it’s too expensive for me.',
    concepts: ['g.muy-mucho', 'g.gustar', 'v.caro'],
    level: 'A2',
    topics: ['shopping', 'opinions'],
  },
  {
    id: 's.m58',
    es: 'Tengo muchos amigos aquí, pero muy poco tiempo libre.',
    en: 'I have a lot of friends here, but very little free time.',
    concepts: ['g.muy-mucho', 'v.amigo', 'v.tiempo'],
    level: 'A2',
    topics: ['social'],
    note: 'muchos agrees with amigos; muy never changes.',
  },

  // --- Addressing a group: the register a Spain course cannot skip ---------
  //
  // The corpus skewed hard to él and yo, which left `vosotros` — the form that
  // most distinguishes Peninsular Spanish — with almost no presence. These are
  // ordinary things you say to two or more friends, which is the natural home
  // of the form rather than a conjugation drill dressed up as a sentence.
  {
    id: 's.m59',
    es: '¿Viajáis mucho por trabajo o solo en vacaciones?',
    en: 'Do you travel a lot for work or only on holiday?',
    concepts: ['v.viajar', 'v.vosotros', 'v.trabajo'],
    level: 'A2',
    topics: ['travel', 'work'],
  },
  {
    id: 's.m60',
    es: 'Ellos viajan siempre en tren, dicen que es más cómodo.',
    en: 'They always travel by train, they say it’s more comfortable.',
    concepts: ['v.viajar', 'v.decir', 'v.tren'],
    level: 'A2',
    topics: ['travel', 'transport'],
  },
  {
    id: 's.m61',
    es: '¿Dónde compráis el pescado? El del mercado está mejor.',
    en: 'Where do you buy fish? The market one is better.',
    concepts: ['v.comprar', 'v.vosotros', 'v.mejor'],
    level: 'A2',
    topics: ['shopping', 'food'],
  },
  {
    id: 's.m62',
    es: 'Nosotros reservamos siempre por internet, sale más barato.',
    en: 'We always book online, it works out cheaper.',
    concepts: ['v.reservar', 'v.barato', 'v.nosotros'],
    level: 'A2',
    topics: ['travel', 'restaurant'],
  },
  {
    id: 's.m63',
    es: '¿Conducís vosotros o vamos todos en tren?',
    en: 'Are you two driving or shall we all go by train?',
    concepts: ['v.conducir', 'v.vosotros', 'v.tren'],
    level: 'A2',
    topics: ['transport', 'plans'],
  },
  {
    id: 's.m64',
    es: '¿Probáis el postre? Lo ha hecho mi madre.',
    en: 'Will you try the dessert? My mother made it.',
    concepts: ['v.probar', 'v.vosotros', 'g.present-perfect'],
    level: 'A2',
    topics: ['food', 'family'],
  },
  {
    id: 's.m65',
    es: '¿Pagáis a medias o cada uno lo suyo?',
    en: 'Are you splitting it or is everyone paying their own?',
    concepts: ['v.pagar', 'v.vosotros'],
    level: 'A2',
    topics: ['restaurant', 'shopping'],
    note: 'a medias — to go halves. Asked in every Spanish restaurant, constantly.',
  },
  {
    id: 's.m66',
    es: 'Ellos pagan con tarjeta y nosotros en efectivo.',
    en: 'They pay by card and we pay cash.',
    concepts: ['v.pagar', 'p.con-tarjeta', 'v.nosotros'],
    level: 'A2',
    topics: ['shopping'],
  },
  {
    id: 's.m67',
    es: 'Tú conduces mejor que yo, coge tú el coche.',
    en: 'You drive better than me, you take the car.',
    concepts: ['v.conducir', 'v.tu', 'g.comparisons'],
    level: 'A2',
    topics: ['transport'],
  },
  {
    id: 's.m68',
    es: '¿Tú compras el pan por la mañana o por la tarde?',
    en: 'Do you buy the bread in the morning or the afternoon?',
    concepts: ['v.comprar', 'v.tu', 'v.pan'],
    level: 'A2',
    topics: ['shopping', 'daily-routine'],
  },

  // --- What the group has done today: the present perfect, all persons ----
  {
    id: 's.m69',
    es: '¿Ya habéis comido o os espero?',
    en: 'Have you eaten already or shall I wait for you?',
    concepts: ['v.comer', 'g.present-perfect', 'v.vosotros'],
    level: 'A2',
    topics: ['food', 'social'],
  },
  {
    id: 's.m70',
    es: 'Oye, ¿habéis hablado ya con el casero?',
    en: 'Listen, have you spoken to the landlord yet?',
    concepts: ['v.hablar', 'g.present-perfect', 'v.vosotros'],
    level: 'A2',
    topics: ['home'],
  },
  {
    id: 's.m71',
    es: 'Nos hemos conocido en el curso de italiano.',
    en: 'We met on the Italian course.',
    concepts: ['v.conocer', 'g.present-perfect', 'v.italiano'],
    level: 'A2',
    topics: ['social', 'university'],
  },
  {
    id: 's.m72',
    es: 'Han salido a cenar y han vuelto tardísimo.',
    en: 'They went out for dinner and got back really late.',
    concepts: ['v.salir', 'g.present-perfect', 'v.cena'],
    level: 'A2',
    topics: ['social'],
  },
  {
    id: 's.m73',
    es: '¿Habéis vivido siempre en este barrio?',
    en: 'Have you always lived in this neighbourhood?',
    concepts: ['v.vivir', 'g.present-perfect', 'v.vosotros'],
    level: 'A2',
    topics: ['home'],
  },
  {
    id: 's.m74',
    es: 'Ha tenido que quedarse en casa con los niños.',
    en: 'She’s had to stay at home with the children.',
    concepts: ['v.tener', 'g.present-perfect', 'p.tener-que'],
    level: 'A2',
    topics: ['family'],
  },
  {
    id: 's.m75',
    es: 'He sido yo, lo siento, se me olvidó avisar.',
    en: 'It was me, sorry, I forgot to say.',
    concepts: ['v.ser', 'g.present-perfect', 'p.lo-siento-mucho'],
    level: 'A2',
    topics: ['social'],
  },
  {
    id: 's.m76',
    es: '¿Has escrito tú el mensaje del grupo?',
    en: 'Did you write the group message?',
    concepts: ['v.escribir', 'g.present-perfect', 'v.tu'],
    level: 'A2',
    topics: ['social'],
  },
  {
    id: 's.m77',
    es: 'Le hemos dado tu número, espero que no te importe.',
    en: 'We’ve given him your number, I hope you don’t mind.',
    concepts: ['v.dar', 'g.present-perfect', 'g.subjunctive-intro'],
    level: 'A2',
    topics: ['social'],
  },
  {
    id: 's.m78',
    es: 'Habéis venido muy pronto, todavía no está nada listo.',
    en: 'You’ve arrived very early, nothing’s ready yet.',
    concepts: ['v.venir', 'g.present-perfect', 'v.vosotros'],
    level: 'A2',
    topics: ['social'],
  },
  {
    id: 's.m79',
    es: 'Has llevado tú la comida las tres últimas veces.',
    en: 'You’ve brought the food the last three times.',
    concepts: ['v.llevar', 'g.present-perfect', 'v.tu'],
    level: 'A2',
    topics: ['social', 'food'],
  },

  // --- Health, second pass -------------------------------------------------
  // The body vocabulary was introduced once each and then never met again. These
  // put the same words in genuinely different situations — at work, at the
  // chemist, texting a friend, playing down a symptom — rather than restating
  // "me duele X" six times.
  {
    id: 's.m80',
    es: 'Llevo toda la semana con dolor de cabeza y no se me pasa.',
    en: "I've had a headache all week and it won't go away.",
    concepts: ['v.cabeza', 'v.llevar', 'v.semana'],
    level: 'A2',
    topics: ['health'],
    note: 'llevo + time + con = how long you have been putting up with something.',
  },
  {
    id: 's.m81',
    es: '¿Te duele mucho el estómago o solo un poco?',
    en: 'Does your stomach hurt a lot or only a bit?',
    concepts: ['p.me-duele', 'v.estomago', 'v.mucho'],
    level: 'A2',
    topics: ['health'],
    blanks: ['duele'],
  },
  {
    id: 's.m82',
    es: 'Me duele la garganta desde el lunes y ya casi no puedo hablar.',
    en: "My throat has hurt since Monday and I can barely talk now.",
    concepts: ['v.garganta', 'p.me-duele', 'v.ya', 'v.lunes'],
    level: 'A2',
    topics: ['health'],
  },
  {
    id: 's.m83',
    es: 'Me duele la espalda de estar todo el día sentado delante del ordenador.',
    en: 'My back hurts from sitting in front of the computer all day.',
    concepts: ['v.espalda', 'p.me-duele', 'v.ordenador', 'v.dia'],
    level: 'A2',
    topics: ['health', 'work'],
  },
  {
    id: 's.m84',
    es: 'Me he hecho daño en la mano jugando al pádel.',
    en: 'I hurt my hand playing padel.',
    concepts: ['v.mano', 'g.present-perfect', 'v.deporte'],
    level: 'A2',
    topics: ['health', 'hobbies'],
    note: 'In Spain a recent injury is present perfect, not preterite: me he hecho daño.',
  },
  {
    id: 's.m85',
    es: 'Tengo los pies destrozados, hemos andado como diez kilómetros.',
    en: "My feet are wrecked, we've walked about ten kilometres.",
    concepts: ['v.pie', 'v.andar', 'g.present-perfect'],
    level: 'A2',
    topics: ['health', 'travel'],
  },
  {
    id: 's.m86',
    es: '¿Vas al médico o esperas a ver si se te pasa solo?',
    en: "Are you going to the doctor or waiting to see if it clears up on its own?",
    concepts: ['v.medico', 'v.ir', 'v.ver'],
    level: 'A2',
    topics: ['health'],
  },
  {
    id: 's.m87',
    es: 'He ido a la farmacia a por algo para la fiebre.',
    en: "I've been to the chemist for something for the fever.",
    concepts: ['v.farmacia', 'v.fiebre', 'g.present-perfect', 'v.ir'],
    level: 'A2',
    topics: ['health'],
    note: 'ir a por algo — going to fetch something. Standard in Spain, unusual elsewhere.',
  },
  {
    id: 's.m88',
    es: 'He pedido cita para el jueves por la tarde.',
    en: "I've made an appointment for Thursday afternoon.",
    concepts: ['v.cita', 'v.jueves', 'v.tarde', 'g.present-perfect'],
    level: 'A2',
    topics: ['health'],
  },
  {
    id: 's.m89',
    es: 'Tengo un resfriado de esos que no se van en dos semanas.',
    en: "I've got one of those colds that doesn't shift for a fortnight.",
    concepts: ['v.resfriado', 'v.semana', 'v.dos'],
    level: 'A2',
    topics: ['health'],
  },
  {
    id: 's.m90',
    es: '¡Que te mejores! Tómate el día libre y descansa.',
    en: 'Get well soon! Take the day off and rest.',
    concepts: ['p.que-te-mejores', 'v.dia', 'v.tomar'],
    level: 'A2',
    topics: ['health', 'social'],
  },
  {
    id: 's.m91',
    es: 'No estoy malo, solo estoy cansado y necesito dormir.',
    en: "I'm not ill, I'm just tired and I need to sleep.",
    concepts: ['p.estoy-malo', 'v.cansado', 'g.ser-estar', 'g.negation'],
    level: 'A2',
    topics: ['health', 'feelings'],
    note: 'estar malo = ill. ser malo = a bad person. The verb carries the whole difference.',
  },
  {
    id: 's.m92',
    es: '¿Qué te pasa? Tienes muy mala cara.',
    en: "What's wrong? You look terrible.",
    concepts: ['p.que-te-pasa', 'v.muy'],
    level: 'A2',
    topics: ['health', 'social'],
  },
  {
    id: 's.m93',
    es: 'No sé qué le pasa al pequeño, no ha comido nada en todo el día.',
    en: "I don't know what's wrong with the little one, he hasn't eaten a thing all day.",
    concepts: ['p.que-te-pasa', 'g.present-perfect', 'v.comer', 'v.dia'],
    level: 'A2',
    topics: ['health', 'family'],
  },

  // --- ser in the preterite ------------------------------------------------
  // ser and ir share their entire preterite, so a learner meeting "fui" has no
  // way to tell which verb it is except from what the sentence is doing. These
  // are all unmistakably ser: identity, evaluation, where an event took place,
  // and the cleft "fui yo quien…".
  {
    id: 's.m94',
    es: 'La boda fue en un pueblo pequeño cerca de Toledo.',
    en: 'The wedding was in a small village near Toledo.',
    concepts: ['v.ser', 'g.preterite', 'v.pequeno', 'v.cerca'],
    level: 'A2',
    topics: ['past', 'social'],
    blanks: ['fue'],
    note: 'Where an *event* happens is ser, not estar: la boda fue en Toledo, but Toledo está en Castilla.',
  },
  {
    id: 's.m95',
    es: 'Fue un año muy duro, pero aprendimos mucho.',
    en: 'It was a very hard year, but we learned a lot.',
    concepts: ['v.ser', 'g.preterite', 'v.ano-time', 'v.mucho'],
    level: 'A2',
    topics: ['past'],
    blanks: ['Fue'],
  },
  {
    id: 's.m96',
    es: 'Fui yo quien lo propuso, no ella.',
    en: 'It was me who suggested it, not her.',
    concepts: ['v.ser', 'g.preterite', 'v.yo', 'g.negation'],
    level: 'A2',
    topics: ['past', 'social'],
    blanks: ['Fui'],
    note: 'fui here is ser, not ir. "Fui yo quien…" is how Spanish says "it was me who…".',
  },
  {
    id: 's.m97',
    es: '¿Fuiste tú el que cerró la puerta con llave?',
    en: 'Was it you who locked the door?',
    concepts: ['v.ser', 'g.preterite', 'v.tu', 'g.questions'],
    level: 'A2',
    topics: ['past', 'home'],
    blanks: ['Fuiste'],
  },
  {
    id: 's.m98',
    es: 'Fuimos los primeros en llegar y no había nadie.',
    en: 'We were the first to arrive and there was nobody there.',
    concepts: ['v.ser', 'g.preterite', 'v.primero', 'g.negation'],
    level: 'A2',
    topics: ['past', 'social'],
    blanks: ['Fuimos'],
  },
  {
    id: 's.m99',
    es: '¿Fuisteis vosotros los que organizasteis la fiesta del año pasado?',
    en: "Was it you lot who organised last year's party?",
    concepts: ['v.ser', 'g.preterite', 'v.vosotros', 'v.fiesta'],
    level: 'A2',
    topics: ['past', 'social'],
    blanks: ['Fuisteis'],
  },
  {
    id: 's.m100',
    es: 'Mis abuelos fueron profesores toda su vida y nunca cambiaron de trabajo.',
    en: 'My grandparents were teachers all their lives and never changed jobs.',
    concepts: ['v.ser', 'g.preterite', 'v.abuelo', 'v.trabajo'],
    level: 'A2',
    topics: ['past', 'family'],
    blanks: ['fueron'],
    note: 'A finished stretch of life takes the preterite even for something as permanent as a profession.',
  },

  // --- ver in the present perfect ------------------------------------------
  {
    id: 's.m101',
    es: '¿Has visto mi móvil? No lo encuentro por ningún lado.',
    en: "Have you seen my phone? I can't find it anywhere.",
    concepts: ['v.ver', 'g.present-perfect', 'v.movil', 'v.tu'],
    level: 'A2',
    topics: ['home', 'social'],
    blanks: ['visto'],
  },
  {
    id: 's.m102',
    es: 'Nunca he visto una cola tan larga en el aeropuerto.',
    en: "I've never seen such a long queue at the airport.",
    concepts: ['v.ver', 'g.present-perfect', 'v.nunca', 'v.tan'],
    level: 'A2',
    topics: ['travel'],
  },
  {
    id: 's.m103',
    es: 'Mi madre ha visto la serie entera en un fin de semana.',
    en: 'My mother watched the whole series in one weekend.',
    concepts: ['v.ver', 'g.present-perfect', 'v.madre', 'v.fin-de-semana'],
    level: 'A2',
    topics: ['hobbies', 'family'],
  },
  {
    id: 's.m104',
    es: 'Hemos visto tres pisos esta mañana y ninguno nos convence.',
    en: "We've seen three flats this morning and none of them convinces us.",
    concepts: ['v.ver', 'g.present-perfect', 'v.piso', 'v.manana'],
    level: 'A2',
    topics: ['home'],
  },
  {
    id: 's.m105',
    es: 'Mis vecinos han visto el partido en el bar de abajo.',
    en: 'My neighbours watched the match at the bar downstairs.',
    // Not `v.amigo`: there is no "amigo" in this sentence, and the mis-tag put
    // an A2 present-perfect line into the practice pool of a word taught in the
    // first Family unit. `audit:content` now reports tags a sentence does not
    // carry, and `learning/eligibility.ts` refuses to build production from a
    // line like this whatever it is tagged with.
    concepts: ['v.ver', 'g.present-perfect'],
    level: 'A2',
    topics: ['social', 'hobbies'],
  },

  // --- reservar in the present ---------------------------------------------
  {
    id: 's.m106',
    es: '¿Reservo yo la mesa o lo haces tú?',
    en: 'Shall I book the table or will you?',
    concepts: ['v.reservar', 'v.mesa', 'v.hacer', 'g.questions'],
    level: 'A2',
    topics: ['restaurant', 'plans'],
    blanks: ['Reservo'],
  },
  {
    id: 's.m107',
    es: 'Si reservas con dos semanas de antelación, sale mucho más barato.',
    en: 'If you book two weeks in advance, it works out much cheaper.',
    concepts: ['v.reservar', 'v.semana', 'v.barato', 'v.si'],
    level: 'A2',
    topics: ['travel', 'plans'],
  },
  {
    id: 's.m108',
    es: 'Mi hermano siempre reserva en el mismo hotel de la costa.',
    en: 'My brother always books the same hotel on the coast.',
    concepts: ['v.reservar', 'v.hermano', 'v.siempre', 'v.hotel'],
    level: 'A2',
    topics: ['travel', 'family'],
  },
  {
    id: 's.m109',
    es: '¿Reserváis vosotros para el sábado o lo dejamos para otro día?',
    en: 'Are you lot booking for Saturday or shall we leave it for another day?',
    concepts: ['v.reservar', 'v.vosotros', 'v.sabado', 'v.dia'],
    level: 'A2',
    topics: ['restaurant', 'plans'],
    blanks: ['Reserváis'],
  },
  {
    id: 's.m110',
    es: 'Muchos restaurantes ya no reservan por teléfono, solo por internet.',
    en: "A lot of restaurants don't take phone bookings any more, only online.",
    concepts: ['v.reservar', 'v.ya', 'g.negation'],
    level: 'A2',
    topics: ['restaurant'],
  },

  // --- probar in the present -----------------------------------------------
  {
    id: 's.m111',
    es: 'Nunca pruebo nada antes de comprarlo y luego me arrepiento.',
    en: 'I never try anything on before buying it and then I regret it.',
    concepts: ['v.probar', 'v.nunca', 'v.luego'],
    level: 'A2',
    topics: ['shopping'],
    blanks: ['pruebo'],
  },
  {
    id: 's.m112',
    es: '¿Pruebas el jamón? Está buenísimo, en serio.',
    en: 'Do you want to try the ham? It’s amazing, honestly.',
    concepts: ['v.probar', 'v.jamon', 'g.ser-estar'],
    level: 'A2',
    topics: ['food', 'social'],
    blanks: ['Pruebas'],
  },
  {
    id: 's.m113',
    es: 'Mi padre prueba el vino antes de pedir la botella entera.',
    en: 'My father tastes the wine before ordering the whole bottle.',
    concepts: ['v.probar', 'v.vino', 'v.padre'],
    level: 'A2',
    topics: ['restaurant', 'family'],
  },
  {
    id: 's.m114',
    es: 'Probamos las dos tallas y nos quedamos con la grande.',
    en: "We'll try both sizes and go with the big one.",
    concepts: ['v.probar', 'v.talla', 'v.quedar', 'v.grande'],
    level: 'A2',
    topics: ['shopping'],
  },
  {
    id: 's.m115',
    es: 'Los pequeños no prueban la verdura ni de broma.',
    en: 'The little ones will not touch a vegetable, not a chance.',
    concepts: ['v.probar', 'v.verdura', 'g.negation'],
    level: 'A2',
    topics: ['food', 'family'],
  },

  // --- quedar, llevar, hacer: three verbs doing a dozen jobs ------------------
  // These are the verbs a learner keeps meeting and never finishes learning,
  // because each one covers a fan of unrelated meanings. Density here is worth
  // far more than another noun: quedar alone is arranging to meet, having some
  // left, something suiting you, and staying put.
  {
    id: 's.m116',
    es: '¿Quedamos el viernes a las ocho en la plaza?',
    en: 'Shall we meet on Friday at eight in the square?',
    concepts: ['v.quedar', 'v.viernes', 'v.ocho'],
    level: 'A2',
    topics: ['plans', 'social'],
    blanks: ['Quedamos'],
    note: 'quedar on its own = to arrange to meet. It is the single commonest way to make a plan in Spain.',
  },
  {
    id: 's.m117',
    es: 'Solo quedan dos entradas, date prisa.',
    en: 'There are only two tickets left, hurry up.',
    concepts: ['v.quedar', 'v.dos'],
    level: 'A2',
    topics: ['plans', 'shopping'],
    note: 'quedar as "to be left over". The thing remaining is the subject, so it can be plural.',
  },
  {
    id: 's.m118',
    es: 'Esa chaqueta te queda muy bien, llévatela.',
    en: 'That jacket suits you, take it.',
    concepts: ['v.quedar', 'p.me-queda-bien', 'v.chaqueta'],
    level: 'A2',
    topics: ['shopping'],
  },
  {
    id: 's.m119',
    es: 'Me quedo en casa, que mañana madrugo.',
    en: 'I’m staying in, I’m up early tomorrow.',
    concepts: ['v.quedar', 'v.casa', 'g.reflexive'],
    level: 'A2',
    topics: ['plans', 'home'],
    note: 'quedarse, with the pronoun, is to stay. Without it, quedar is to meet. One letter, opposite plans.',
  },
  {
    id: 's.m120',
    es: 'Quedamos en que traías tú el postre, ¿no?',
    en: 'We agreed you were bringing dessert, weren’t we?',
    concepts: ['v.quedar', 'g.imperfect', 'v.traer'],
    level: 'A2',
    topics: ['food', 'social'],
    note: 'quedar en que… = to agree that…. A third meaning again.',
  },
  {
    id: 's.m121',
    es: '¿Queda café o lo hago nuevo?',
    en: 'Is there coffee left or shall I make fresh?',
    concepts: ['v.quedar', 'v.cafe', 'v.hacer'],
    level: 'A2',
    topics: ['cafe', 'home'],
  },
  {
    id: 's.m122',
    es: 'Nos quedan tres días de vacaciones y no hemos hecho nada.',
    en: 'We’ve got three days of holiday left and we haven’t done a thing.',
    concepts: ['v.quedar', 'g.present-perfect', 'v.dia'],
    level: 'A2',
    topics: ['travel', 'time'],
  },
  {
    id: 's.m123',
    es: 'Llevo dos años viviendo aquí y todavía me pierdo.',
    en: 'I’ve been living here for two years and I still get lost.',
    concepts: ['v.llevar', 'v.todavia', 'v.ano-time'],
    level: 'A2',
    topics: ['home', 'time'],
    blanks: ['Llevo'],
    note: 'llevo + time + gerund is how Spanish says "I have been doing X for". No perfect tense involved.',
  },
  {
    id: 's.m124',
    es: 'Lleva una camisa azul y unos vaqueros.',
    en: 'He’s wearing a blue shirt and jeans.',
    concepts: ['v.llevar', 'v.camisa', 'v.azul'],
    level: 'A2',
    topics: ['describing', 'shopping'],
    note: 'llevar is the everyday verb for wearing. vestir is for shop windows and novels.',
  },
  {
    id: 's.m125',
    es: '¿Te llevo al aeropuerto o coges un taxi?',
    en: 'Shall I give you a lift to the airport or are you getting a taxi?',
    concepts: ['v.llevar', 'v.coger', 'v.viaje'],
    level: 'A2',
    topics: ['transport', 'travel'],
  },
  {
    id: 's.m126',
    es: 'Me llevo bien con mis compañeros, la verdad.',
    en: 'I get on well with my colleagues, honestly.',
    concepts: ['v.llevar', 'g.reflexive', 'v.trabajo'],
    level: 'A2',
    topics: ['work', 'social'],
    note: 'llevarse bien con alguien = to get on with someone. Another verb that changes job with a pronoun.',
  },
  {
    id: 's.m127',
    es: 'Llévate el paraguas, que va a llover.',
    en: 'Take the umbrella, it’s going to rain.',
    concepts: ['v.llevar', 'g.ir-a-infinitive', 'g.reflexive'],
    level: 'A2',
    topics: ['weather', 'daily-routine'],
  },
  {
    id: 's.m128',
    es: 'Hace falta más gente para montar esto.',
    en: 'We need more people to set this up.',
    concepts: ['v.hacer', 'v.gente', 'v.mas'],
    level: 'A2',
    topics: ['work', 'social'],
    note: 'hacer falta = to be needed. Impersonal: it is the thing needed that is the subject.',
  },
  {
    id: 's.m129',
    es: 'Hace tres semanas que no voy al gimnasio.',
    en: 'I haven’t been to the gym for three weeks.',
    concepts: ['v.hacer', 'v.semana', 'g.negation'],
    level: 'A2',
    topics: ['hobbies', 'time'],
    note: 'hace + time + que = "for" or "ago". The verb stays in the present.',
  },
  {
    id: 's.m130',
    es: 'No le hagas caso, siempre está de broma.',
    en: 'Don’t take any notice of him, he’s always joking.',
    concepts: ['v.hacer', 'g.negation', 'g.ser-estar'],
    level: 'A2',
    topics: ['social', 'people'],
  },
  {
    id: 's.m131',
    es: '¿Qué haces este finde? — Nada, hacer el vago.',
    en: 'What are you up to this weekend? — Nothing, being lazy.',
    concepts: ['v.hacer', 'v.fin-de-semana', 'p.qué-haces'],
    level: 'A2',
    topics: ['plans', 'social'],
    register: 'colloquial',
  },
  {
    id: 's.m132',
    es: 'Se ha hecho muy tarde, deberíamos irnos.',
    en: 'It’s got very late, we ought to go.',
    concepts: ['v.hacer', 'g.present-perfect', 'v.tarde'],
    level: 'A2',
    topics: ['time', 'social'],
    note: 'hacerse = to become, gradually. Se ha hecho tarde is what you say to end an evening.',
  },

  // --- Clothes, in shops that answer back ------------------------------------
  {
    id: 's.m133',
    es: 'Los pantalones me quedan largos, ¿los tienes en otra talla?',
    en: 'The trousers are too long on me, do you have them in another size?',
    concepts: ['v.pantalones', 'v.talla', 'p.me-queda-bien', 'v.quedar'],
    level: 'A2',
    topics: ['shopping'],
  },
  {
    id: 's.m134',
    es: 'Necesito zapatos cómodos, voy a estar todo el día de pie.',
    en: 'I need comfortable shoes, I’m going to be on my feet all day.',
    concepts: ['v.zapatos', 'g.ir-a-infinitive', 'v.pie'],
    level: 'A2',
    topics: ['shopping', 'work'],
  },
  {
    id: 's.m135',
    es: 'Ese vestido es precioso, pero para el invierno no.',
    en: 'That dress is lovely, but not for winter.',
    concepts: ['v.vestido', 'g.ser-estar', 'v.tiempo'],
    level: 'A2',
    topics: ['shopping', 'describing'],
  },
  {
    id: 's.m136',
    es: 'Me he comprado dos camisetas porque estaban de oferta.',
    en: 'I bought two T-shirts because they were on offer.',
    concepts: ['v.camiseta', 'g.present-perfect', 'g.imperfect'],
    level: 'A2',
    topics: ['shopping'],
  },
  {
    id: 's.m137',
    es: 'Con esta ropa vas a pasar frío, coge una chaqueta.',
    en: 'You’ll be cold in those clothes, take a jacket.',
    concepts: ['v.ropa', 'v.chaqueta', 'v.coger'],
    level: 'A2',
    topics: ['shopping', 'weather'],
  },
];
