import type { Sentence } from '@/content/types';

/**
 * A2 sentences: health, clothes, comparing things and saying why you prefer
 * one over another.
 *
 * A2 is where sentences stop being single clauses. Many of these carry a
 * reason, a contrast or a comparison, because that is the actual jump from A1 —
 * not longer vocabulary but connected thought.
 */
export const a2CoreSentences: Sentence[] = [
  // --- Health --------------------------------------------------------------
  {
    id: 's.m1',
    es: '¿Qué te pasa? — Me duele la cabeza.',
    en: "What's wrong? — My head hurts.",
    concepts: ['p.que-te-pasa', 'p.me-duele', 'v.cabeza'],
    level: 'A2',
    topics: ['health'],
    blanks: ['duele'],
  },
  {
    id: 's.m2',
    es: 'Me duelen los pies porque he andado mucho.',
    en: "My feet hurt because I've walked a lot.",
    concepts: ['p.me-duele', 'v.pie', 'v.porque', 'g.present-perfect'],
    level: 'A2',
    topics: ['health'],
    note: 'duelen, plural, because los pies is the subject — the same backwards logic as gustar.',
  },
  {
    id: 's.m3',
    es: 'Estoy malo. Creo que tengo fiebre.',
    en: "I'm ill. I think I have a fever.",
    concepts: ['p.estoy-malo', 'v.fiebre', 'v.creo-que', 'g.ser-estar'],
    level: 'A2',
    topics: ['health'],
  },
  {
    id: 's.m4',
    es: 'Tengo que pedir cita con el médico.',
    en: 'I have to make an appointment with the doctor.',
    concepts: ['v.cita', 'v.medico', 'p.tener-que'],
    level: 'A2',
    topics: ['health'],
  },
  {
    id: 's.m5',
    es: 'La farmacia está enfrente del supermercado.',
    en: 'The pharmacy is opposite the supermarket.',
    concepts: ['v.farmacia', 'v.enfrente', 'v.supermercado', 'g.hay-estar'],
    level: 'A2',
    topics: ['health', 'city'],
  },
  {
    id: 's.m6',
    es: 'Me duele la garganta y tengo un resfriado.',
    en: 'My throat hurts and I have a cold.',
    concepts: ['v.garganta', 'v.resfriado', 'p.me-duele'],
    level: 'A2',
    topics: ['health'],
  },
  {
    id: 's.m7',
    es: 'No he dormido bien, me duele la espalda.',
    en: "I haven't slept well, my back hurts.",
    concepts: ['v.espalda', 'p.me-duele', 'g.present-perfect', 'g.negation'],
    level: 'A2',
    topics: ['health'],
  },
  {
    id: 's.m8',
    es: 'Que te mejores pronto.',
    en: 'Get well soon.',
    concepts: ['p.que-te-mejores'],
    level: 'A2',
    topics: ['health', 'social'],
  },

  // --- Clothes and shopping ------------------------------------------------
  {
    id: 's.m9',
    es: '¿Puedo probármelo? — Sí, claro, el probador está allí.',
    en: 'Can I try it on? — Yes, of course, the changing room is over there.',
    concepts: ['p.puedo-probarme', 'v.claro', 'v.alli'],
    level: 'A2',
    topics: ['shopping'],
  },
  {
    id: 's.m10',
    es: 'Esta camiseta me queda bien, pero es demasiado cara.',
    en: 'This T-shirt fits me, but it’s too expensive.',
    concepts: ['v.camiseta', 'p.me-queda-bien', 'v.demasiado', 'v.caro', 'v.este'],
    level: 'A2',
    topics: ['shopping'],
    blanks: ['demasiado'],
  },
  {
    id: 's.m11',
    es: 'Busco unos pantalones negros de la talla cuarenta.',
    en: "I'm looking for black trousers in size forty.",
    concepts: ['v.pantalones', 'v.negro', 'v.talla', 'v.cuarenta'],
    level: 'A2',
    topics: ['shopping'],
  },
  {
    id: 's.m12',
    es: 'No, gracias, solo estoy mirando.',
    en: "No thanks, I'm just looking.",
    concepts: ['p.solo-estoy-mirando', 'v.gracias'],
    level: 'A2',
    topics: ['shopping'],
  },
  {
    id: 's.m13',
    es: 'Prefiero la chaqueta azul porque es más barata.',
    en: 'I prefer the blue jacket because it’s cheaper.',
    concepts: ['v.preferir', 'v.chaqueta', 'v.azul', 'v.porque', 'g.comparisons', 'v.barato'],
    level: 'A2',
    topics: ['shopping', 'opinions'],
    blanks: ['Prefiero', 'más'],
  },
  {
    id: 's.m14',
    es: 'Estos zapatos son más cómodos que los otros.',
    en: 'These shoes are more comfortable than the others.',
    concepts: ['v.zapatos', 'g.comparisons', 'v.este', 'v.otro'],
    level: 'A2',
    topics: ['shopping'],
  },

  // --- Comparing -----------------------------------------------------------
  {
    id: 's.m15',
    es: 'Madrid es más grande que Sevilla, pero Sevilla es más bonita.',
    en: 'Madrid is bigger than Seville, but Seville is prettier.',
    concepts: ['g.comparisons', 'v.grande', 'v.bonito', 'v.pero'],
    level: 'A2',
    topics: ['city', 'opinions'],
    blanks: ['más grande que'],
  },
  {
    id: 's.m16',
    es: 'El metro es más rápido que el autobús y más barato que el taxi.',
    en: 'The metro is faster than the bus and cheaper than a taxi.',
    concepts: ['g.comparisons', 'v.metro', 'v.autobus', 'v.barato'],
    level: 'A2',
    topics: ['transport'],
  },
  {
    id: 's.m17',
    es: 'Esta es la mejor tortilla del barrio.',
    en: 'This is the best tortilla in the neighbourhood.',
    concepts: ['v.mejor', 'g.comparisons', 'v.tortilla'],
    level: 'A2',
    topics: ['food', 'opinions'],
    note: 'Superlative takes de, never en: la mejor de Madrid.',
  },
  {
    id: 's.m18',
    es: 'Hoy hace peor tiempo que ayer.',
    en: 'The weather is worse today than yesterday.',
    concepts: ['v.peor', 'g.comparisons', 'v.tiempo', 'v.ayer'],
    level: 'A2',
    topics: ['weather'],
  },
  {
    id: 's.m19',
    es: 'Mi piso no es tan grande como el tuyo.',
    en: "My flat isn't as big as yours.",
    concepts: ['v.tan', 'g.comparisons', 'v.piso', 'g.negation'],
    level: 'A2',
    topics: ['home'],
    blanks: ['tan', 'como'],
  },
  {
    id: 's.m20',
    es: 'El billete cuesta más de treinta euros.',
    en: 'The ticket costs more than thirty euros.',
    concepts: ['g.comparisons', 'v.billete', 'v.treinta'],
    level: 'A2',
    topics: ['transport', 'numbers'],
    note: 'Before a number it is más de, not más que.',
  },
  {
    id: 's.m21',
    es: 'Mi hermano mayor vive en Valencia.',
    en: 'My older brother lives in Valencia.',
    concepts: ['v.mayor', 'v.hermano', 'g.comparisons'],
    level: 'A2',
    topics: ['family'],
    note: 'mayor and menor are the normal words for older and younger siblings.',
  },

  // --- muy vs mucho, and giving reasons ------------------------------------
  {
    id: 's.m22',
    es: 'Hace mucho calor y estoy muy cansado.',
    en: "It's very hot and I'm very tired.",
    concepts: ['g.muy-mucho', 'p.hace-calor', 'v.cansado'],
    level: 'A2',
    topics: ['weather', 'feelings'],
    blanks: ['mucho', 'muy'],
    note: 'mucho with the noun calor, muy with the adjective cansado.',
  },
  {
    id: 's.m23',
    es: 'Hay muchos turistas en agosto, demasiados.',
    en: 'There are a lot of tourists in August, too many.',
    concepts: ['g.muy-mucho', 'v.demasiado', 'v.agosto', 'g.hay-estar'],
    level: 'A2',
    topics: ['travel'],
  },
  {
    id: 's.m24',
    es: 'El curso es bastante difícil, pero me gusta mucho.',
    en: "The course is fairly hard, but I like it a lot.",
    concepts: ['v.bastante', 'v.dificil', 'g.muy-mucho', 'p.me-gusta'],
    level: 'A2',
    topics: ['university', 'opinions'],
  },
  {
    id: 's.m25',
    es: 'Me encanta cocinar, pero no soporto fregar.',
    en: "I love cooking, but I can't stand washing up.",
    concepts: ['p.me-encanta', 'p.no-soporto', 'v.cocinar'],
    level: 'A2',
    topics: ['hobbies', 'opinions'],
  },
  {
    id: 's.m26',
    es: 'Prefiero el tren porque puedo leer durante el viaje.',
    en: 'I prefer the train because I can read during the journey.',
    concepts: ['p.prefiero-porque', 'v.preferir', 'v.tren', 'v.leer', 'v.viaje'],
    level: 'A2',
    topics: ['transport', 'opinions'],
    note: 'Preference plus reason — the sentence shape A2 is really about.',
  },
  {
    id: 's.m27',
    es: 'No me gusta nada este barrio, es demasiado ruidoso.',
    en: "I don't like this neighbourhood at all, it's too noisy.",
    concepts: ['p.no-me-gusta-nada', 'v.demasiado', 'v.este'],
    level: 'A2',
    topics: ['city', 'opinions'],
  },
  {
    id: 's.m28',
    es: 'Me encantan las ciudades pequeñas, son más tranquilas.',
    en: 'I love small cities, they’re calmer.',
    concepts: ['p.me-encanta', 'v.ciudad', 'v.pequeno', 'g.comparisons', 'g.plurals'],
    level: 'A2',
    topics: ['city', 'opinions'],
  },
];
