import type { Sentence } from '@/content/types';

/**
 * A2 sentences: health, clothes, comparing things and saying why you prefer
 * one over another.
 *
 * A2 is where sentences stop being single clauses. Many of these carry a
 * reason, a contrast or a comparison, because that is the actual jump from A1 —
 * not longer vocabulary but connected thought.
 */
export const a2CoreSentences: Sentence[] = [
  // --- Health --------------------------------------------------------------
  {
    id: 's.m1',
    es: '¿Qué te pasa? — Me duele la cabeza.',
    en: "What's wrong? — My head hurts.",
    concepts: ['p.que-te-pasa', 'p.me-duele', 'v.cabeza'],
    level: 'A2',
    topics: ['health'],
    blanks: ['duele'],
  },
  {
    id: 's.m2',
    es: 'Me duelen los pies porque he andado mucho.',
    en: "My feet hurt because I've walked a lot.",
    concepts: ['p.me-duele', 'v.pie', 'v.porque', 'g.present-perfect'],
    level: 'A2',
    topics: ['health'],
    note: 'duelen, plural, because los pies is the subject — the same backwards logic as gustar.',
  },
  {
    id: 's.m3',
    es: 'Estoy malo. Creo que tengo fiebre.',
    en: "I'm ill. I think I have a fever.",
    concepts: ['p.estoy-malo', 'v.fiebre', 'v.creo-que', 'g.ser-estar'],
    level: 'A2',
    topics: ['health'],
  },
  {
    id: 's.m4',
    es: 'Tengo que pedir cita con el médico.',
    en: 'I have to make an appointment with the doctor.',
    concepts: ['v.cita', 'v.medico', 'p.tener-que'],
    level: 'A2',
    topics: ['health'],
  },
  {
    id: 's.m5',
    es: 'La farmacia está enfrente del supermercado.',
    en: 'The pharmacy is opposite the supermarket.',
    concepts: ['v.farmacia', 'v.enfrente', 'v.supermercado', 'g.hay-estar'],
    level: 'A2',
    topics: ['health', 'city'],
  },
  {
    id: 's.m6',
    es: 'Me duele la garganta y tengo un resfriado.',
    en: 'My throat hurts and I have a cold.',
    concepts: ['v.garganta', 'v.resfriado', 'p.me-duele'],
    level: 'A2',
    topics: ['health'],
  },
  {
    id: 's.m7',
    es: 'No he dormido bien, me duele la espalda.',
    en: "I haven't slept well, my back hurts.",
    concepts: ['v.espalda', 'p.me-duele', 'g.present-perfect', 'g.negation'],
    level: 'A2',
    topics: ['health'],
  },
  {
    id: 's.m8',
    es: 'Que te mejores pronto.',
    en: 'Get well soon.',
    concepts: ['p.que-te-mejores'],
    level: 'A2',
    topics: ['health', 'social'],
  },

  // --- Clothes and shopping ------------------------------------------------
  {
    id: 's.m9',
    es: '¿Puedo probármelo? — Sí, claro, el probador está allí.',
    en: 'Can I try it on? — Yes, of course, the changing room is over there.',
    concepts: ['p.puedo-probarme', 'v.claro', 'v.alli'],
    level: 'A2',
    topics: ['shopping'],
  },
  {
    id: 's.m10',
    es: 'Esta camiseta me queda bien, pero es demasiado cara.',
    en: 'This T-shirt fits me, but it’s too expensive.',
    concepts: ['v.camiseta', 'p.me-queda-bien', 'v.demasiado', 'v.caro', 'v.este'],
    level: 'A2',
    topics: ['shopping'],
    blanks: ['demasiado'],
  },
  {
    id: 's.m11',
    es: 'Busco unos pantalones negros de la talla cuarenta.',
    en: "I'm looking for black trousers in size forty.",
    concepts: ['v.pantalones', 'v.negro', 'v.talla', 'v.cuarenta'],
    level: 'A2',
    topics: ['shopping'],
  },
  {
    id: 's.m12',
    es: 'No, gracias, solo estoy mirando.',
    en: "No thanks, I'm just looking.",
    concepts: ['p.solo-estoy-mirando', 'v.gracias'],
    level: 'A2',
    topics: ['shopping'],
  },
  {
    id: 's.m13',
    es: 'Prefiero la chaqueta azul porque es más barata.',
    en: 'I prefer the blue jacket because it’s cheaper.',
    concepts: ['v.preferir', 'v.chaqueta', 'v.azul', 'v.porque', 'g.comparisons', 'v.barato'],
    level: 'A2',
    topics: ['shopping', 'opinions'],
    blanks: ['Prefiero', 'más'],
  },
  {
    id: 's.m14',
    es: 'Estos zapatos son más cómodos que los otros.',
    en: 'These shoes are more comfortable than the others.',
    concepts: ['v.zapatos', 'g.comparisons', 'v.este', 'v.otro'],
    level: 'A2',
    topics: ['shopping'],
  },

  // --- Comparing -----------------------------------------------------------
  {
    id: 's.m15',
    es: 'Madrid es más grande que Sevilla, pero Sevilla es más bonita.',
    en: 'Madrid is bigger than Seville, but Seville is prettier.',
    concepts: ['g.comparisons', 'v.grande', 'v.bonito', 'v.pero'],
    level: 'A2',
    topics: ['city', 'opinions'],
    blanks: ['más grande que'],
  },
  {
    id: 's.m16',
    es: 'El metro es más rápido que el autobús y más barato que el taxi.',
    en: 'The metro is faster than the bus and cheaper than a taxi.',
    concepts: ['g.comparisons', 'v.metro', 'v.autobus', 'v.barato'],
    level: 'A2',
    topics: ['transport'],
  },
  {
    id: 's.m17',
    es: 'Esta es la mejor tortilla del barrio.',
    en: 'This is the best tortilla in the neighbourhood.',
    concepts: ['v.mejor', 'g.comparisons', 'v.tortilla'],
    level: 'A2',
    topics: ['food', 'opinions'],
    note: 'Superlative takes de, never en: la mejor de Madrid.',
  },
  {
    id: 's.m18',
    es: 'Hoy hace peor tiempo que ayer.',
    en: 'The weather is worse today than yesterday.',
    concepts: ['v.peor', 'g.comparisons', 'v.tiempo', 'v.ayer'],
    level: 'A2',
    topics: ['weather'],
  },
  {
    id: 's.m19',
    es: 'Mi piso no es tan grande como el tuyo.',
    en: "My flat isn't as big as yours.",
    concepts: ['v.tan', 'g.comparisons', 'v.piso', 'g.negation'],
    level: 'A2',
    topics: ['home'],
    blanks: ['tan', 'como'],
  },
  {
    id: 's.m20',
    es: 'El billete cuesta más de treinta euros.',
    en: 'The ticket costs more than thirty euros.',
    concepts: ['g.comparisons', 'v.billete', 'v.treinta'],
    level: 'A2',
    topics: ['transport', 'numbers'],
    note: 'Before a number it is más de, not más que.',
  },
  {
    id: 's.m21',
    es: 'Mi hermano mayor vive en Valencia.',
    en: 'My older brother lives in Valencia.',
    concepts: ['v.mayor', 'v.hermano', 'g.comparisons'],
    level: 'A2',
    topics: ['family'],
    note: 'mayor and menor are the normal words for older and younger siblings.',
  },

  // --- muy vs mucho, and giving reasons ------------------------------------
  {
    id: 's.m22',
    es: 'Hace mucho calor y estoy muy cansado.',
    en: "It's very hot and I'm very tired.",
    concepts: ['g.muy-mucho', 'p.hace-calor', 'v.cansado'],
    level: 'A2',
    topics: ['weather', 'feelings'],
    blanks: ['mucho', 'muy'],
    note: 'mucho with the noun calor, muy with the adjective cansado.',
  },
  {
    id: 's.m23',
    es: 'Hay muchos turistas en agosto, demasiados.',
    en: 'There are a lot of tourists in August, too many.',
    concepts: ['g.muy-mucho', 'v.demasiado', 'v.agosto', 'g.hay-estar'],
    level: 'A2',
    topics: ['travel'],
  },
  {
    id: 's.m24',
    es: 'El curso es bastante difícil, pero me gusta mucho.',
    en: "The course is fairly hard, but I like it a lot.",
    concepts: ['v.bastante', 'v.dificil', 'g.muy-mucho', 'p.me-gusta'],
    level: 'A2',
    topics: ['university', 'opinions'],
  },
  {
    id: 's.m25',
    es: 'Me encanta cocinar, pero no soporto fregar.',
    en: "I love cooking, but I can't stand washing up.",
    concepts: ['p.me-encanta', 'p.no-soporto', 'v.cocinar'],
    level: 'A2',
    topics: ['hobbies', 'opinions'],
  },
  {
    id: 's.m26',
    es: 'Prefiero el tren porque puedo leer durante el viaje.',
    en: 'I prefer the train because I can read during the journey.',
    concepts: ['p.prefiero-porque', 'v.preferir', 'v.tren', 'v.leer', 'v.viaje'],
    level: 'A2',
    topics: ['transport', 'opinions'],
    note: 'Preference plus reason — the sentence shape A2 is really about.',
  },
  {
    id: 's.m27',
    es: 'No me gusta nada este barrio, es demasiado ruidoso.',
    en: "I don't like this neighbourhood at all, it's too noisy.",
    concepts: ['p.no-me-gusta-nada', 'v.demasiado', 'v.este'],
    level: 'A2',
    topics: ['city', 'opinions'],
  },
  {
    id: 's.m28',
    es: 'Me encantan las ciudades pequeñas, son más tranquilas.',
    en: 'I love small cities, they’re calmer.',
    concepts: ['p.me-encanta', 'v.ciudad', 'v.pequeno', 'g.comparisons', 'g.plurals'],
    level: 'A2',
    topics: ['city', 'opinions'],
  },

  // --- The body and being unwell -------------------------------------------
  {
    id: 's.m29',
    es: '—¿Qué te pasa? —Nada, que me duele un poco la cabeza.',
    en: '“What’s wrong?” “Nothing, my head just hurts a bit.”',
    concepts: ['p.que-te-pasa', 'v.cabeza', 'p.me-duele'],
    level: 'A2',
    topics: ['health'],
    note: 'That opening Nada, que… softens the complaint before making it — very Spanish.',
  },
  {
    id: 's.m30',
    es: 'Estoy malo desde el lunes, creo que tengo fiebre.',
    en: 'I’ve been ill since Monday, I think I have a temperature.',
    concepts: ['p.estoy-malo', 'v.fiebre', 'v.lunes'],
    level: 'A2',
    topics: ['health'],
    note: 'estar malo is ill; ser malo would mean a bad person.',
  },
  {
    id: 's.m31',
    es: 'Con este resfriado me duele la garganta al hablar.',
    en: 'With this cold my throat hurts when I speak.',
    concepts: ['v.resfriado', 'v.garganta', 'v.hablar'],
    level: 'A2',
    topics: ['health'],
    note: 'al + infinitivo = "when/on doing" — al hablar, al salir, al llegar.',
  },
  {
    id: 's.m32',
    es: 'Después de correr me duelen las piernas y la espalda.',
    en: 'After running my legs and back hurt.',
    concepts: ['v.espalda', 'p.me-duele', 'v.despues'],
    level: 'A2',
    topics: ['health', 'daily-routine'],
  },
  {
    id: 's.m33',
    es: 'Llevo todo el día de pie y ya no puedo más.',
    en: 'I’ve been on my feet all day and I can’t take any more.',
    concepts: ['v.pie', 'v.poder', 'v.dia'],
    level: 'A2',
    topics: ['health', 'work'],
    register: 'colloquial',
  },
  {
    id: 's.m34',
    es: 'Si sigues así, tienes que ir al médico, no a la farmacia.',
    en: 'If you carry on like this, you have to see a doctor, not go to the chemist.',
    concepts: ['v.medico', 'v.farmacia', 'p.tener-que'],
    level: 'A2',
    topics: ['health'],
  },
  {
    id: 's.m35',
    es: 'Me duele el estómago, creo que ha sido la cena.',
    en: 'My stomach hurts, I think it was dinner.',
    concepts: ['v.estomago', 'g.present-perfect', 'v.cena'],
    level: 'A2',
    topics: ['health', 'food'],
  },
  {
    id: 's.m36',
    es: '—Me voy a la cama. —Vale, que te mejores.',
    en: '“I’m off to bed.” “Okay, get well soon.”',
    concepts: ['p.que-te-mejores', 'v.vale'],
    level: 'A2',
    topics: ['health', 'social'],
    note: 'que + subjunctive as a wish: que te mejores, que descanses, que aproveche.',
  },

  // --- Clothes and trying things on ----------------------------------------
  {
    id: 's.m37',
    es: 'Necesito ropa de invierno: una chaqueta y unos zapatos buenos.',
    en: 'I need winter clothes: a jacket and some decent shoes.',
    concepts: ['v.ropa', 'v.chaqueta', 'v.zapatos'],
    level: 'A2',
    topics: ['shopping'],
  },
  {
    id: 's.m38',
    es: 'Estos pantalones me quedan largos, ¿hay una talla menos?',
    en: 'These trousers are too long on me, is there a size smaller?',
    concepts: ['v.pantalones', 'p.me-queda-bien', 'v.talla'],
    level: 'A2',
    topics: ['shopping'],
  },
  {
    id: 's.m39',
    es: 'La camisa blanca con el vestido negro queda muy bien.',
    en: 'The white shirt goes really well with the black dress.',
    concepts: ['v.camisa', 'v.vestido', 'v.blanco'],
    level: 'A2',
    topics: ['shopping', 'describing'],
  },
  {
    id: 's.m40',
    es: '¿Puedo probarme estos dos y luego decido?',
    en: 'Can I try these two on and decide afterwards?',
    concepts: ['p.puedo-probarme', 'v.probar', 'v.luego'],
    level: 'A2',
    topics: ['shopping'],
  },
  {
    id: 's.m41',
    es: '—¿Te ayudo? —No, gracias, solo estoy mirando.',
    en: '“Can I help?” “No thanks, I’m just looking.”',
    concepts: ['p.solo-estoy-mirando', 'v.gracias'],
    level: 'A2',
    topics: ['shopping'],
  },

  // --- Comparing, which is where A2 opinions start -------------------------
  {
    id: 's.m42',
    es: 'Este bar es mejor que el otro y encima más barato.',
    en: 'This bar is better than the other one and cheaper on top of that.',
    concepts: ['v.mejor', 'g.comparisons', 'v.barato'],
    level: 'A2',
    topics: ['opinions', 'cafe'],
  },
  {
    id: 's.m43',
    es: 'El tiempo hoy está peor que ayer, y ayer ya era malo.',
    en: 'The weather today is worse than yesterday, and yesterday was already bad.',
    concepts: ['v.peor', 'g.comparisons', 'v.tiempo'],
    level: 'A2',
    topics: ['weather', 'opinions'],
  },
  {
    id: 's.m44',
    es: 'Mi piso no es tan grande como el tuyo, pero está más céntrico.',
    en: 'My flat isn’t as big as yours, but it’s more central.',
    concepts: ['v.tan', 'g.comparisons', 'v.piso'],
    level: 'A2',
    topics: ['home', 'opinions'],
    blanks: ['tan'],
    note: 'tan… como for equality; más… que for difference. Mixing them is the usual slip.',
  },
  {
    id: 's.m45',
    es: 'Prefiero quedar por la tarde porque por la mañana trabajo.',
    en: 'I prefer meeting in the afternoon because I work in the morning.',
    concepts: ['p.prefiero-porque', 'v.quedar', 'v.tarde'],
    level: 'A2',
    topics: ['plans', 'opinions'],
  },

  // --- Present perfect across the persons, including vosotros --------------
  {
    id: 's.m46',
    es: '¿Habéis visto lo que ha pasado en la plaza?',
    en: 'Have you seen what’s happened in the square?',
    concepts: ['g.present-perfect', 'v.vosotros', 'v.ver'],
    level: 'A2',
    topics: ['city', 'past'],
  },
  {
    id: 's.m47',
    es: 'Hemos tenido mucha suerte con el tiempo esta semana.',
    en: 'We’ve been very lucky with the weather this week.',
    concepts: ['g.present-perfect', 'v.tener', 'v.tiempo'],
    level: 'A2',
    topics: ['weather', 'past'],
  },
  {
    id: 's.m48',
    es: 'Todavía no ha venido nadie, es muy temprano.',
    en: 'Nobody has come yet, it’s very early.',
    concepts: ['g.present-perfect', 'v.venir', 'g.negation'],
    level: 'A2',
    topics: ['social'],
  },
  {
    id: 's.m49',
    es: '¿Has salido ya del trabajo o sigues allí?',
    en: 'Have you left work yet or are you still there?',
    concepts: ['g.present-perfect', 'v.salir', 'v.trabajo'],
    level: 'A2',
    topics: ['work'],
  },
  {
    id: 's.m50',
    es: 'Han dicho en la radio que va a llover.',
    en: 'They said on the radio that it’s going to rain.',
    concepts: ['g.present-perfect', 'v.decir', 'v.llover'],
    level: 'A2',
    topics: ['weather'],
  },
  {
    id: 's.m51',
    es: 'He puesto la mesa y he hecho la cena, te toca fregar.',
    en: 'I’ve laid the table and made dinner — you’re washing up.',
    concepts: ['g.present-perfect', 'v.poner', 'v.hacer'],
    level: 'A2',
    topics: ['home', 'food'],
    note: 'puesto and hecho are irregular participles — never ponido or hacido.',
  },
  {
    id: 's.m52',
    es: 'Hemos ido dos veces y las dos estaba cerrado.',
    en: 'We’ve been twice and both times it was closed.',
    concepts: ['g.present-perfect', 'v.ir', 'v.dos'],
    level: 'A2',
    topics: ['past', 'city'],
  },
  {
    id: 's.m53',
    es: 'Nunca hemos estado en Galicia, pero nos apetece mucho.',
    en: 'We’ve never been to Galicia, but we’d really like to.',
    concepts: ['g.present-perfect', 'v.estar', 'p.me-apetece'],
    level: 'A2',
    topics: ['travel'],
  },
  {
    id: 's.m54',
    es: '¿Le habéis dado ya el regalo?',
    en: 'Have you given him the present yet?',
    concepts: ['g.present-perfect', 'v.dar', 'v.vosotros'],
    level: 'A2',
    topics: ['social'],
  },

  // --- muy or mucho, the distinction that never stops mattering ------------
  {
    id: 's.m55',
    es: 'Trabaja mucho y está muy cansado.',
    en: 'He works a lot and he’s very tired.',
    concepts: ['g.muy-mucho', 'v.trabajar', 'v.cansado'],
    level: 'A2',
    topics: ['work', 'feelings'],
    blanks: ['mucho', 'muy'],
    note: 'mucho modifies the verb, muy the adjective. One sentence, both jobs.',
  },
  {
    id: 's.m56',
    es: 'Hay mucha gente y hace muy buen tiempo.',
    en: 'There are a lot of people and the weather is very good.',
    concepts: ['g.muy-mucho', 'v.gente', 'p.que-tiempo-hace'],
    level: 'A2',
    topics: ['weather', 'city'],
  },
  {
    id: 's.m57',
    es: 'Me gusta mucho, pero es muy caro para mí.',
    en: 'I like it a lot, but it’s too expensive for me.',
    concepts: ['g.muy-mucho', 'g.gustar', 'v.caro'],
    level: 'A2',
    topics: ['shopping', 'opinions'],
  },
  {
    id: 's.m58',
    es: 'Tengo muchos amigos aquí, pero muy poco tiempo libre.',
    en: 'I have a lot of friends here, but very little free time.',
    concepts: ['g.muy-mucho', 'v.amigo', 'v.tiempo'],
    level: 'A2',
    topics: ['social'],
    note: 'muchos agrees with amigos; muy never changes.',
  },
];
