import type { Sentence } from '@/content/types';

/**
 * The corpus behind the B2–C2 expansion.
 *
 * At these levels a sentence is not an illustration of a word — it *is* the
 * word, because what the learner is acquiring is a move in a conversation
 * rather than a label for a thing. `ahora bien` cannot be shown in isolation;
 * it only means anything after a concession. So most of these lines carry the
 * turn they belong to, and several are written as two halves of one thought.
 *
 * Two sentences minimum per concept, in different frames, because
 * `getSentencesForConcept` draws from this pool and a chunk with one line comes
 * back as the same line under every exercise kind — which at C1 is the
 * difference between learning a phrase and memorising a sentence.
 */
export const advancedExpansionSentences: Sentence[] = [
  // --- B2: conceding and qualifying ---------------------------------------
  { id: 's.u1', es: 'Tienes razón en lo del precio. Ahora bien, el plazo sigue sin cuadrarme.', en: "You're right about the price. That said, the deadline still doesn't work for me.", concepts: ['p.ahora-bien', 'v.el-plazo'], level: 'B2', topics: ['work', 'opinions'] },
  { id: 's.u2', es: 'Ahora bien, eso no significa que estemos de acuerdo en todo.', en: 'That said, it does not mean we agree on everything.', concepts: ['p.ahora-bien'], level: 'B2', topics: ['opinions'] },
  { id: 's.u3', es: 'Me gustó la película. Eso sí, es demasiado larga.', en: 'I liked the film. Mind you, it is far too long.', concepts: ['p.eso-si'], level: 'B2', topics: ['hobbies', 'opinions'] },
  { id: 's.u4', es: 'Te ayudo, eso sí, hasta las seis nada más.', en: "I'll help you — only until six, mind.", concepts: ['p.eso-si'], level: 'B2', topics: ['social'] },
  { id: 's.u5', es: 'De todas formas, ya está decidido.', en: 'In any case, it is already decided.', concepts: ['p.de-todas-formas'], level: 'B2', topics: ['work'] },
  { id: 's.u6', es: 'No me convence, pero de todas formas lo intentaremos.', en: 'It does not convince me, but we will try anyway.', concepts: ['p.de-todas-formas', 'v.intentar'], level: 'B2', topics: ['work', 'opinions'] },
  { id: 's.u7', es: 'Al fin y al cabo, nadie sabía lo que iba a pasar.', en: 'At the end of the day, nobody knew what was going to happen.', concepts: ['p.al-fin-y-al-cabo'], level: 'B2', topics: ['opinions'] },
  { id: 's.u8', es: 'Al fin y al cabo es su decisión, no la nuestra.', en: 'At the end of the day it is their decision, not ours.', concepts: ['p.al-fin-y-al-cabo'], level: 'B2', topics: ['opinions'] },
  { id: 's.u9', es: 'Por lo general no suelo quejarme.', en: 'Generally speaking I do not tend to complain.', concepts: ['p.por-lo-general'], level: 'B2', topics: ['opinions'] },
  { id: 's.u10', es: 'Por lo general la gente responde bien al cambio.', en: 'Generally speaking people respond well to change.', concepts: ['p.por-lo-general', 'v.cambiar'], level: 'B2', topics: ['work'] },
  { id: 's.u11', es: 'Estoy de acuerdo en la medida en que se respeten los plazos.', en: 'I agree insofar as the deadlines are respected.', concepts: ['p.en-la-medida-en-que', 'v.el-plazo'], level: 'B2', topics: ['work'] },
  { id: 's.u12', es: 'Colaboraremos en la medida en que podamos.', en: 'We will collaborate insofar as we can.', concepts: ['p.en-la-medida-en-que'], level: 'B2', topics: ['work'] },
  { id: 's.u13', es: 'Saldremos a las ocho, a no ser que llueva.', en: 'We will leave at eight, unless it rains.', concepts: ['p.a-no-ser-que'], level: 'B2', topics: ['plans', 'weather'] },
  { id: 's.u14', es: 'A no ser que me digas lo contrario, sigo adelante.', en: 'Unless you tell me otherwise, I am carrying on.', concepts: ['p.a-no-ser-que'], level: 'B2', topics: ['work'] },
  { id: 's.u15', es: 'Te lo presto siempre y cuando me lo devuelvas el lunes.', en: 'I will lend it to you provided you give it back on Monday.', concepts: ['p.siempre-y-cuando'], level: 'B2', topics: ['social'] },
  { id: 's.u16', es: 'Aceptamos, siempre y cuando se establezca un plazo claro.', en: 'We accept, provided a clear deadline is set.', concepts: ['p.siempre-y-cuando', 'v.establecer', 'v.el-plazo'], level: 'B2', topics: ['work'] },
  { id: 's.u17', es: 'Dicho esto, creo que merece la pena intentarlo.', en: 'Having said that, I think it is worth trying.', concepts: ['p.dicho-esto', 'v.intentar'], level: 'B2', topics: ['opinions'] },
  { id: 's.u18', es: 'Dicho esto, no voy a insistir más.', en: 'Having said that, I am not going to push it further.', concepts: ['p.dicho-esto'], level: 'B2', topics: ['opinions'] },
  { id: 's.u19', es: 'En cualquier caso, hay que avisar con antelación.', en: 'In any event, notice has to be given in advance.', concepts: ['p.en-cualquier-caso', 'g.obligation'], level: 'B2', topics: ['work'] },
  { id: 's.u20', es: 'En cualquier caso, yo te aviso en cuanto sepa algo.', en: 'In any event, I will let you know as soon as I hear anything.', concepts: ['p.en-cualquier-caso', 'p.en-cuanto'], level: 'B2', topics: ['social'] },

  { id: 's.u21', es: 'El motivo del retraso fue una huelga.', en: 'The reason for the delay was a strike.', concepts: ['v.el-motivo'], level: 'B2', topics: ['transport'] },
  { id: 's.u22', es: 'No entiendo el motivo de tanto secreto.', en: 'I do not understand the reason for so much secrecy.', concepts: ['v.el-motivo', 'v.entender'], level: 'B2', topics: ['opinions'] },
  { id: 's.u23', es: 'La causa del problema era mucho más simple.', en: 'The cause of the problem was far simpler.', concepts: ['v.la-causa'], level: 'B2', topics: ['work'] },
  { id: 's.u24', es: 'Confundimos la causa con la consecuencia.', en: 'We confused the cause with the consequence.', concepts: ['v.la-causa', 'v.la-consecuencia'], level: 'B2', topics: ['opinions'] },
  { id: 's.u25', es: 'Las consecuencias se notaron meses después.', en: 'The consequences were felt months later.', concepts: ['v.la-consecuencia'], level: 'B2', topics: ['opinions'] },
  { id: 's.u26', es: 'El riesgo es que nadie asuma la responsabilidad.', en: 'The risk is that nobody takes responsibility.', concepts: ['v.el-riesgo'], level: 'B2', topics: ['work'] },
  { id: 's.u27', es: 'Merece la pena correr ese riesgo.', en: 'That risk is worth taking.', concepts: ['v.el-riesgo'], level: 'B2', topics: ['opinions'] },
  { id: 's.u28', es: 'Han tomado medidas para reducir el ruido.', en: 'They have taken measures to reduce the noise.', concepts: ['v.la-medida'], level: 'B2', topics: ['city'] },
  { id: 's.u29', es: 'La medida entró en vigor en enero.', en: 'The measure came into force in January.', concepts: ['v.la-medida'], level: 'B2', topics: ['work'] },
  { id: 's.u30', es: 'El plazo termina el viernes a mediodía.', en: 'The deadline ends on Friday at midday.', concepts: ['v.el-plazo', 'v.terminar'], level: 'B2', topics: ['work'] },
  { id: 's.u31', es: 'Reconozco que me equivoqué.', en: 'I admit I was wrong.', concepts: ['v.reconocer'], level: 'B2', topics: ['opinions'] },
  { id: 's.u32', es: 'Reconoció el error sin que nadie se lo pidiera.', en: 'He admitted the mistake without anyone asking him to.', concepts: ['v.reconocer'], level: 'B2', topics: ['work'] },
  { id: 's.u33', es: 'No niego que sea complicado.', en: 'I do not deny that it is complicated.', concepts: ['v.negar'], level: 'B2', topics: ['opinions'], note: 'Negar que takes the subjunctive: sea, not es.' },
  { id: 's.u34', es: 'Negó haber estado allí.', en: 'He denied having been there.', concepts: ['v.negar'], level: 'B2', topics: ['storytelling'] },
  { id: 's.u35', es: 'Quiero matizar una cosa de lo que he dicho.', en: 'I want to qualify something I said.', concepts: ['v.matizar'], level: 'B2', topics: ['opinions'] },
  { id: 's.u36', es: 'Matizó su respuesta sin cambiarla del todo.', en: 'She qualified her answer without changing it entirely.', concepts: ['v.matizar'], level: 'B2', topics: ['opinions'] },
  { id: 's.u37', es: 'Rechazaron la propuesta por unanimidad.', en: 'They rejected the proposal unanimously.', concepts: ['v.rechazar'], level: 'B2', topics: ['work'] },
  { id: 's.u38', es: 'Rechazó el puesto por motivos personales.', en: 'She turned down the job for personal reasons.', concepts: ['v.rechazar', 'v.el-motivo'], level: 'B2', topics: ['work'] },

  // --- C1: register and implication ---------------------------------------
  { id: 's.u39', es: 'No es para tanto, de verdad.', en: "It's really not that big a deal.", concepts: ['p.no-es-para-tanto'], level: 'C1', topics: ['social'] },
  { id: 's.u40', es: 'Se enfadó muchísimo y no era para tanto.', en: 'He got furious and it really was not that big a deal.', concepts: ['p.no-es-para-tanto'], level: 'C1', topics: ['feelings'] },
  { id: 's.u41', es: 'Ni que decir tiene que contamos contigo.', en: 'It goes without saying that we are counting on you.', concepts: ['p.ni-que-decir-tiene', 'v.contar'], level: 'C1', topics: ['work', 'social'] },
  { id: 's.u42', es: 'Ni que decir tiene que todo esto es confidencial.', en: 'It goes without saying that all of this is confidential.', concepts: ['p.ni-que-decir-tiene'], level: 'C1', topics: ['work'] },
  { id: 's.u43', es: 'A decir verdad, no me lo esperaba.', en: 'To tell the truth, I was not expecting it.', concepts: ['p.a-decir-verdad', 'v.esperar'], level: 'C1', topics: ['feelings'] },
  { id: 's.u44', es: 'A decir verdad, nunca me convenció del todo.', en: 'To tell the truth, it never entirely convinced me.', concepts: ['p.a-decir-verdad'], level: 'C1', topics: ['opinions'] },
  { id: 's.u45', es: 'Llegamos tarde y, por si fuera poco, sin las entradas.', en: 'We arrived late and, as if that were not enough, without the tickets.', concepts: ['p.por-si-fuera-poco', 'v.llegar'], level: 'C1', topics: ['storytelling'] },
  { id: 's.u46', es: 'Perdió el vuelo y, por si fuera poco, el equipaje.', en: 'He missed the flight and, as if that were not enough, his luggage.', concepts: ['p.por-si-fuera-poco', 'v.perder', 'v.equipaje'], level: 'C1', topics: ['travel'] },
  { id: 's.u47', es: 'Se convocó la reunión a fin de aclarar las dudas.', en: 'The meeting was called in order to clear up the doubts.', concepts: ['p.a-fin-de'], level: 'C1', topics: ['work'] },
  { id: 's.u48', es: 'A fin de evitar malentendidos, lo pondremos por escrito.', en: 'In order to avoid misunderstandings, we will put it in writing.', concepts: ['p.a-fin-de'], level: 'C1', topics: ['work'] },
  { id: 's.u49', es: 'Cedieron en aras de un acuerdo rápido.', en: 'They gave ground for the sake of a quick agreement.', concepts: ['p.en-aras-de'], level: 'C1', topics: ['work'] },
  { id: 's.u50', es: 'En aras de la claridad, lo resumo en tres puntos.', en: 'For the sake of clarity, I will summarise it in three points.', concepts: ['p.en-aras-de'], level: 'C1', topics: ['work'] },
  { id: 's.u51', es: 'Es una zona protegida, de ahí que no se pueda construir.', en: 'It is a protected area, hence you cannot build there.', concepts: ['p.de-ahi-que'], level: 'C1', topics: ['city'] },
  { id: 's.u52', es: 'Llegó tardísimo, de ahí que nadie le esperara.', en: 'He arrived terribly late, which is why nobody waited for him.', concepts: ['p.de-ahi-que', 'v.esperar'], level: 'C1', topics: ['storytelling'] },
  { id: 's.u53', es: 'Estoy de acuerdo hasta cierto punto.', en: 'I agree up to a point.', concepts: ['p.hasta-cierto-punto'], level: 'C1', topics: ['opinions'] },
  { id: 's.u54', es: 'Hasta cierto punto es comprensible.', en: 'Up to a point it is understandable.', concepts: ['p.hasta-cierto-punto'], level: 'C1', topics: ['opinions'] },
  { id: 's.u55', es: 'Dejó caer que se iba de la empresa.', en: 'She dropped a hint that she was leaving the company.', concepts: ['p.dejar-caer'], level: 'C1', topics: ['work', 'social'] },
  { id: 's.u56', es: 'No lo dijo abiertamente, sólo lo dejó caer.', en: 'He did not say it openly, he just let it drop.', concepts: ['p.dejar-caer'], level: 'C1', topics: ['social'] },
  { id: 's.u57', es: 'No hace falta tirarle de la lengua, lo cuenta todo solo.', en: 'You do not need to draw him out, he tells you everything anyway.', concepts: ['p.tirar-de-la-lengua', 'v.contar'], level: 'C1', topics: ['social'] },
  { id: 's.u58', es: 'Le tiré de la lengua y acabó reconociéndolo.', en: 'I drew him out and he ended up admitting it.', concepts: ['p.tirar-de-la-lengua', 'v.reconocer'], level: 'C1', topics: ['social'] },
  { id: 's.u59', es: 'Nadie pone en tela de juicio su honestidad.', en: 'Nobody calls his honesty into question.', concepts: ['p.poner-en-tela-de-juicio'], level: 'C1', topics: ['opinions'] },
  { id: 's.u60', es: 'El informe pone en tela de juicio esa conclusión.', en: 'The report calls that conclusion into question.', concepts: ['p.poner-en-tela-de-juicio'], level: 'C1', topics: ['work'] },
  { id: 's.u61', es: 'Le encanta llevar la contraria.', en: 'He loves contradicting people for the sake of it.', concepts: ['p.llevar-la-contraria'], level: 'C1', topics: ['social'] },
  { id: 's.u62', es: 'No me lleves la contraria sólo por costumbre.', en: 'Do not disagree with me just out of habit.', concepts: ['p.llevar-la-contraria'], level: 'C1', topics: ['social'] },
  { id: 's.u63', es: 'La entrevista no tiene desperdicio.', en: 'The interview is worth every word.', concepts: ['p.no-tener-desperdicio'], level: 'C1', topics: ['opinions'] },
  { id: 's.u64', es: 'Su respuesta no tuvo desperdicio.', en: 'His answer was priceless.', concepts: ['p.no-tener-desperdicio'], level: 'C1', topics: ['opinions'] },

  { id: 's.u65', es: 'Hay un matiz importante que se nos escapa.', en: 'There is an important nuance we are missing.', concepts: ['v.el-matiz'], level: 'C1', topics: ['opinions'] },
  { id: 's.u66', es: 'Los dos verbos significan lo mismo, con un matiz.', en: 'The two verbs mean the same thing, with one shade of difference.', concepts: ['v.el-matiz'], level: 'C1', topics: ['opinions'] },
  { id: 's.u67', es: 'No sabíamos el alcance real del problema.', en: 'We did not know the real scope of the problem.', concepts: ['v.el-alcance'], level: 'C1', topics: ['work'] },
  { id: 's.u68', es: 'Conviene acotar el alcance antes de empezar.', en: 'It is worth narrowing the scope before starting.', concepts: ['v.el-alcance', 'v.acotar', 'v.empezar'], level: 'C1', topics: ['work'] },
  { id: 's.u69', es: 'El estudio tiene un sesgo evidente.', en: 'The study has an obvious bias.', concepts: ['v.el-sesgo'], level: 'C1', topics: ['opinions'] },
  { id: 's.u70', es: 'Todos tenemos algún sesgo, lo importante es reconocerlo.', en: 'We all have some bias; the point is admitting it.', concepts: ['v.el-sesgo', 'v.reconocer'], level: 'C1', topics: ['opinions'] },
  { id: 's.u71', es: 'Siguieron la pauta que marcó el equipo anterior.', en: 'They followed the pattern set by the previous team.', concepts: ['v.la-pauta'], level: 'C1', topics: ['work'] },
  { id: 's.u72', es: 'Hace falta una pauta clara para todos.', en: 'A clear guideline is needed for everybody.', concepts: ['v.la-pauta'], level: 'C1', topics: ['work'] },
  { id: 's.u73', es: 'Hay un vínculo directo entre las dos cosas.', en: 'There is a direct link between the two things.', concepts: ['v.el-vinculo', 'v.entre'], level: 'C1', topics: ['opinions'] },
  { id: 's.u74', es: 'Mantienen un vínculo muy fuerte con el pueblo.', en: 'They keep a very strong bond with the village.', concepts: ['v.el-vinculo', 'v.mantener', 'v.pueblo'], level: 'C1', topics: ['people'] },
  { id: 's.u75', es: 'Vamos a acotar el tema, que se nos va.', en: 'Let us narrow the topic down, it is getting away from us.', concepts: ['v.acotar'], level: 'C1', topics: ['work'] },
  { id: 's.u76', es: 'Esbozó un plan en cinco minutos.', en: 'He sketched out a plan in five minutes.', concepts: ['v.esbozar'], level: 'C1', topics: ['work'] },
  { id: 's.u77', es: 'Me limité a esbozar la idea general.', en: 'I confined myself to outlining the general idea.', concepts: ['v.esbozar'], level: 'C1', topics: ['work'] },
  { id: 's.u78', es: 'Quiero recalcar que esto no es definitivo.', en: 'I want to stress that this is not final.', concepts: ['v.recalcar'], level: 'C1', topics: ['work'] },
  { id: 's.u79', es: 'Recalcó dos veces la misma idea.', en: 'She stressed the same idea twice.', concepts: ['v.recalcar'], level: 'C1', topics: ['opinions'] },
  { id: 's.u80', es: 'Soslayó la pregunta con una broma.', en: 'He sidestepped the question with a joke.', concepts: ['v.soslayar'], level: 'C1', topics: ['social'] },
  { id: 's.u81', es: 'No podemos soslayar ese punto.', en: 'We cannot skirt around that point.', concepts: ['v.soslayar'], level: 'C1', topics: ['work'] },
  { id: 's.u82', es: 'Hay que subsanar el error antes del viernes.', en: 'The mistake has to be put right before Friday.', concepts: ['v.subsanar', 'g.obligation'], level: 'C1', topics: ['work'] },
  { id: 's.u83', es: 'Subsanaron el fallo sin decir nada a nadie.', en: 'They rectified the fault without telling anyone.', concepts: ['v.subsanar'], level: 'C1', topics: ['work'] },
  { id: 's.u84', es: 'Es muy escurridizo cuando le preguntas directamente.', en: 'He is very evasive when you ask him directly.', concepts: ['v.escurridizo'], level: 'C1', topics: ['describing'] },
  { id: 's.u85', es: 'Dio una respuesta escurridiza, como siempre.', en: 'She gave a slippery answer, as always.', concepts: ['v.escurridizo'], level: 'C1', topics: ['social'] },
  { id: 's.u86', es: 'Fue un no rotundo.', en: 'It was a flat no.', concepts: ['v.rotundo'], level: 'C1', topics: ['opinions'] },
  { id: 's.u87', es: 'El éxito fue rotundo.', en: 'The success was resounding.', concepts: ['v.rotundo'], level: 'C1', topics: ['work'] },
  { id: 's.u88', es: 'Su respuesta fue tajante.', en: 'Her answer was blunt.', concepts: ['v.tajante'], level: 'C1', topics: ['opinions'] },
  { id: 's.u89', es: 'Se mostró tajante: o eso, o nada.', en: 'He was categorical: that, or nothing.', concepts: ['v.tajante'], level: 'C1', topics: ['opinions'] },
  { id: 's.u90', es: 'Prefiero un resumen sucinto.', en: 'I would rather have a succinct summary.', concepts: ['v.escueto-adj'], level: 'C1', topics: ['work'] },
  { id: 's.u91', es: 'Escribió una nota sucinta y clarísima.', en: 'She wrote a succinct and perfectly clear note.', concepts: ['v.escueto-adj'], level: 'C1', topics: ['work'] },

  // --- C2: idiom and the last mile ----------------------------------------
  { id: 's.u92', es: 'No da el brazo a torcer ni cuando sabe que se equivoca.', en: 'He will not back down even when he knows he is wrong.', concepts: ['p.no-dar-el-brazo-a-torcer'], level: 'C2', topics: ['social'] },
  { id: 's.u93', es: 'Al final tuvo que dar el brazo a torcer.', en: 'In the end he had to back down.', concepts: ['p.no-dar-el-brazo-a-torcer'], level: 'C2', topics: ['storytelling'] },
  { id: 's.u94', es: 'Deja de buscarle tres pies al gato.', en: 'Stop overcomplicating things.', concepts: ['p.buscarle-tres-pies', 'v.dejar'], level: 'C2', topics: ['slang'] },
  { id: 's.u95', es: 'No le busques tres pies al gato: dijo que sí y ya está.', en: 'Do not overthink it: he said yes and that is that.', concepts: ['p.buscarle-tres-pies'], level: 'C2', topics: ['slang'] },
  { id: 's.u96', es: 'A toro pasado todos sabemos lo que había que hacer.', en: 'With hindsight we all know what should have been done.', concepts: ['p.a-toro-pasado'], level: 'C2', topics: ['opinions'] },
  { id: 's.u97', es: 'Es fácil opinar a toro pasado.', en: 'It is easy to have an opinion with hindsight.', concepts: ['p.a-toro-pasado'], level: 'C2', topics: ['opinions'] },
  { id: 's.u98', es: 'El dato no tiene vuelta de hoja.', en: 'The figure admits of no argument.', concepts: ['p.no-tener-vuelta-de-hoja'], level: 'C2', topics: ['opinions'] },
  { id: 's.u99', es: 'Eso no tiene vuelta de hoja, guste o no.', en: 'There are no two ways about it, like it or not.', concepts: ['p.no-tener-vuelta-de-hoja'], level: 'C2', topics: ['opinions'] },
  { id: 's.u100', es: 'Vamos al grano, que tenemos veinte minutos.', en: 'Let us get to the point, we have twenty minutes.', concepts: ['p.ir-al-grano', 'v.minuto'], level: 'C2', topics: ['work'] },
  { id: 's.u101', es: 'Fue al grano desde la primera frase.', en: 'She got to the point from the first sentence.', concepts: ['p.ir-al-grano'], level: 'C2', topics: ['work'] },
  { id: 's.u102', es: 'Intentó quitar hierro al asunto.', en: 'He tried to play the matter down.', concepts: ['p.quitar-hierro', 'v.intentar'], level: 'C2', topics: ['social'] },
  { id: 's.u103', es: 'No le quites hierro, fue grave.', en: 'Do not play it down, it was serious.', concepts: ['p.quitar-hierro'], level: 'C2', topics: ['opinions'] },
  { id: 's.u104', es: 'Me pilló el toro con el informe.', en: 'The deadline caught up with me on the report.', concepts: ['p.pillar-el-toro'], level: 'C2', topics: ['work'] },
  { id: 's.u105', es: 'Si lo dejas para el jueves, te pilla el toro.', en: 'If you leave it until Thursday, you will run out of time.', concepts: ['p.pillar-el-toro', 'v.dejar'], level: 'C2', topics: ['work'] },
  { id: 's.u106', es: 'Lo anunciaron a bombo y platillo y luego no pasó nada.', en: 'They announced it with great fanfare and then nothing happened.', concepts: ['p.a-bombo-y-platillo', 'v.pasar'], level: 'C2', topics: ['opinions'] },
  { id: 's.u107', es: 'Prefiero hacerlo sin bombo y platillo.', en: 'I would rather do it without any fanfare.', concepts: ['p.a-bombo-y-platillo'], level: 'C2', topics: ['social'] },
  { id: 's.u108', es: 'Ya que hemos llegado hasta aquí, de perdidos al río.', en: 'Since we have come this far, in for a penny, in for a pound.', concepts: ['p.de-perdidos-al-rio', 'v.llegar'], level: 'C2', topics: ['slang'] },
  { id: 's.u109', es: 'De perdidos al río: se lo digo todo hoy.', en: 'In for a penny: I am telling him everything today.', concepts: ['p.de-perdidos-al-rio'], level: 'C2', topics: ['slang'] },
  { id: 's.u110', es: 'Sin ir más lejos, ayer pasó lo mismo.', en: 'To take just one example, the same thing happened yesterday.', concepts: ['p.sin-ir-mas-lejos', 'v.pasar'], level: 'C2', topics: ['opinions'] },
  { id: 's.u111', es: 'Sin ir más lejos, mira lo que ocurrió en marzo.', en: 'To take just one example, look at what happened in March.', concepts: ['p.sin-ir-mas-lejos', 'v.ocurrir'], level: 'C2', topics: ['opinions'] },

  { id: 's.u112', es: 'Lo consiguió a base de empeño.', en: 'She managed it through sheer determination.', concepts: ['v.el-empeno', 'v.conseguir'], level: 'C2', topics: ['work'] },
  { id: 's.u113', es: 'Su empeño en negarlo lo empeoró todo.', en: 'His insistence on denying it made everything worse.', concepts: ['v.el-empeno', 'v.negar'], level: 'C2', topics: ['storytelling'] },
  { id: 's.u114', es: 'El desenlace fue mejor de lo que esperábamos.', en: 'The outcome was better than we expected.', concepts: ['v.el-desenlace', 'v.esperar'], level: 'C2', topics: ['storytelling'] },
  { id: 's.u115', es: 'Nadie se imaginaba ese desenlace.', en: 'Nobody imagined that ending.', concepts: ['v.el-desenlace'], level: 'C2', topics: ['storytelling'] },
  { id: 's.u116', es: 'Aceptó sin reparos.', en: 'She accepted without reservation.', concepts: ['v.el-reparo'], level: 'C2', topics: ['work'] },
  { id: 's.u117', es: 'Tengo algún reparo, pero adelante.', en: 'I have some misgivings, but go ahead.', concepts: ['v.el-reparo'], level: 'C2', topics: ['opinions'] },
  { id: 's.u118', es: 'Hay que canalizarlo por el cauce adecuado.', en: 'It has to go through the proper channel.', concepts: ['v.el-cauce', 'g.obligation'], level: 'C2', topics: ['work'] },
  { id: 's.u119', es: 'Volvió al cauce habitual en dos semanas.', en: 'It went back to its usual course in two weeks.', concepts: ['v.el-cauce', 'v.volver'], level: 'C2', topics: ['work'] },
  { id: 's.u120', es: 'Zanjó la discusión con una sola frase.', en: 'He settled the argument with a single sentence.', concepts: ['v.zanjar'], level: 'C2', topics: ['social'] },
  { id: 's.u121', es: 'Vamos a zanjar el tema aquí.', en: 'Let us close the subject here.', concepts: ['v.zanjar'], level: 'C2', topics: ['work'] },
  { id: 's.u122', es: 'Enmendaron el texto en el último momento.', en: 'They amended the text at the last moment.', concepts: ['v.enmendar'], level: 'C2', topics: ['work'] },
  { id: 's.u123', es: 'Nunca es tarde para enmendar un error.', en: 'It is never too late to make good a mistake.', concepts: ['v.enmendar'], level: 'C2', topics: ['opinions'] },
  { id: 's.u124', es: 'Sopesé las dos opciones durante días.', en: 'I weighed up the two options for days.', concepts: ['v.sopesar'], level: 'C2', topics: ['opinions'] },
  { id: 's.u125', es: 'Conviene sopesar el riesgo antes de decidir.', en: 'It is worth weighing up the risk before deciding.', concepts: ['v.sopesar', 'v.el-riesgo'], level: 'C2', topics: ['work'] },
  { id: 's.u126', es: 'Ese titular desvirtúa lo que dijo realmente.', en: 'That headline distorts what he actually said.', concepts: ['v.desvirtuar'], level: 'C2', topics: ['opinions'] },
  { id: 's.u127', es: 'No quiero desvirtuar el debate.', en: 'I do not want to derail the debate.', concepts: ['v.desvirtuar'], level: 'C2', topics: ['opinions'] },
  { id: 's.u128', es: 'Cíñete al guion, por favor.', en: 'Stick to the script, please.', concepts: ['v.ceñirse'], level: 'C2', topics: ['work'] },
  { id: 's.u129', es: 'Se ciñó a los hechos y no añadió nada.', en: 'She stuck to the facts and added nothing.', concepts: ['v.ceñirse'], level: 'C2', topics: ['work'] },
  { id: 's.u130', es: 'El argumento es contundente.', en: 'The argument is compelling.', concepts: ['v.contundente'], level: 'C2', topics: ['opinions'] },
  { id: 's.u131', es: 'Dio una respuesta contundente y se acabó la discusión.', en: 'He gave a forceful answer and the argument was over.', concepts: ['v.contundente'], level: 'C2', topics: ['opinions'] },
  { id: 's.u132', es: 'La prueba es bastante endeble.', en: 'The evidence is fairly flimsy.', concepts: ['v.endeble'], level: 'C2', topics: ['opinions'] },
  { id: 's.u133', es: 'Se apoya en un argumento endeble.', en: 'It rests on a weak argument.', concepts: ['v.endeble'], level: 'C2', topics: ['opinions'] },
  { id: 's.u134', es: 'Volvimos al consabido debate de siempre.', en: 'We went back to the same old debate.', concepts: ['v.consabido', 'v.volver'], level: 'C2', topics: ['opinions'] },
  { id: 's.u135', es: 'Llegó con la consabida excusa.', en: 'He turned up with the usual excuse.', concepts: ['v.consabido', 'v.llegar'], level: 'C2', topics: ['social'] },
  { id: 's.u136', es: 'La mejora es sólo aparente.', en: 'The improvement is only apparent.', concepts: ['v.aparente'], level: 'C2', topics: ['opinions'] },
  { id: 's.u137', es: 'Tras una calma aparente, todo estalló.', en: 'After an apparent calm, everything blew up.', concepts: ['v.aparente'], level: 'C2', topics: ['storytelling'] },
  { id: 's.u138', es: 'El cambio ha sido paulatino.', en: 'The change has been gradual.', concepts: ['v.paulatino', 'v.cambiar'], level: 'C2', topics: ['opinions'] },
  { id: 's.u139', es: 'Se produjo un descenso paulatino de la demanda.', en: 'There was a gradual fall in demand.', concepts: ['v.paulatino'], level: 'C2', topics: ['work'] },

  // --- Top-up: the B2/C1 concepts added to close the shallowness gap -------
  { id: 's.u140', es: 'Es un problema de otra índole.', en: 'It is a problem of a different kind.', concepts: ['v.la-indole'], level: 'C1', topics: ['opinions'] },
  { id: 's.u141', es: 'Recibimos quejas de toda índole.', en: 'We received complaints of every kind.', concepts: ['v.la-indole'], level: 'C1', topics: ['work'] },
  { id: 's.u142', es: 'Tanto más cuanto que nadie lo había avisado.', en: 'All the more so because nobody had given any warning.', concepts: ['p.tanto-mas-cuanto'], level: 'C1', topics: ['opinions'] },
  { id: 's.u143', es: 'Es grave, tanto más cuanto que era evitable.', en: 'It is serious, all the more so because it was avoidable.', concepts: ['p.tanto-mas-cuanto'], level: 'C1', topics: ['opinions'] },
  { id: 's.u144', es: 'En el ámbito laboral eso no se hace.', en: 'In a work context that is not done.', concepts: ['v.el-ambito'], level: 'B2', topics: ['work'] },
  { id: 's.u145', es: 'Es una figura conocida en su ámbito.', en: 'She is a well-known figure in her field.', concepts: ['v.el-ambito'], level: 'B2', topics: ['work'] },
  { id: 's.u146', es: 'No comparto ese criterio.', en: 'I do not share that view.', concepts: ['v.el-criterio'], level: 'B2', topics: ['opinions'] },
  { id: 's.u147', es: 'Aplicaron un criterio distinto en cada caso.', en: 'They applied a different criterion in each case.', concepts: ['v.el-criterio'], level: 'B2', topics: ['work'] },
  { id: 's.u148', es: 'Mantuvo su postura hasta el final.', en: 'He held his position to the end.', concepts: ['v.la-postura', 'v.mantener'], level: 'B2', topics: ['opinions'] },
  { id: 's.u149', es: 'Han cambiado de postura en dos semanas.', en: 'They have changed their stance in two weeks.', concepts: ['v.la-postura', 'v.cambiar'], level: 'B2', topics: ['opinions'] },
  { id: 's.u150', es: 'El hecho de que no llamara ya dice mucho.', en: 'The fact that he did not call says a lot in itself.', concepts: ['v.el-hecho'], level: 'B2', topics: ['opinions'] },
  { id: 's.u151', es: 'Los hechos son los que son.', en: 'The facts are what they are.', concepts: ['v.el-hecho'], level: 'B2', topics: ['opinions'] },
  { id: 's.u152', es: 'No hay pruebas de eso.', en: 'There is no evidence of that.', concepts: ['v.la-prueba'], level: 'B2', topics: ['opinions'] },
  { id: 's.u153', es: 'La prueba más clara es el propio informe.', en: 'The clearest evidence is the report itself.', concepts: ['v.la-prueba'], level: 'B2', topics: ['work'] },
  { id: 's.u154', es: '¿Qué aporta esto al debate?', en: 'What does this add to the debate?', concepts: ['v.aportar'], level: 'B2', topics: ['opinions'] },
  { id: 's.u155', es: 'Aportaron datos que nadie esperaba.', en: 'They provided figures nobody was expecting.', concepts: ['v.aportar', 'v.esperar'], level: 'B2', topics: ['work'] },
  { id: 's.u156', es: 'No descarto volver algún día.', en: 'I am not ruling out going back one day.', concepts: ['v.descartar', 'v.volver'], level: 'B2', topics: ['plans'] },
  { id: 's.u157', es: 'Descartaron esa opción enseguida.', en: 'They ruled that option out straight away.', concepts: ['v.descartar'], level: 'B2', topics: ['work'] },
  { id: 's.u158', es: 'Me planteo cambiar de trabajo.', en: 'I am considering changing jobs.', concepts: ['v.plantearse', 'v.cambiar'], level: 'B2', topics: ['work'] },
  { id: 's.u159', es: 'Nunca se planteó que pudiera salir mal.', en: 'It never occurred to him that it might go wrong.', concepts: ['v.plantearse'], level: 'B2', topics: ['storytelling'] },
  { id: 's.u160', es: 'A mi juicio, no es la mejor solución.', en: 'In my judgement, it is not the best solution.', concepts: ['p.a-mi-juicio'], level: 'B2', topics: ['opinions'] },
  { id: 's.u161', es: 'A mi juicio faltan datos.', en: 'In my judgement there is not enough data.', concepts: ['p.a-mi-juicio'], level: 'B2', topics: ['work'] },
  { id: 's.u162', es: 'No obstante, conviene revisarlo.', en: 'Nevertheless, it is worth reviewing.', concepts: ['p.no-obstante'], level: 'B2', topics: ['work'] },
  { id: 's.u163', es: 'Es caro; no obstante, dura años.', en: 'It is expensive; nevertheless, it lasts for years.', concepts: ['p.no-obstante'], level: 'B2', topics: ['shopping'] },
  { id: 's.u164', es: 'La premisa de la que partes es falsa.', en: 'The premise you are starting from is false.', concepts: ['v.el-planteamiento-c1'], level: 'C1', topics: ['opinions'] },
  { id: 's.u165', es: 'Aceptemos la premisa y sigamos.', en: 'Let us accept the premise and move on.', concepts: ['v.el-planteamiento-c1'], level: 'C1', topics: ['opinions'] },
  { id: 's.u166', es: 'Estoy de acuerdo, con una salvedad.', en: 'I agree, with one caveat.', concepts: ['v.la-salvedad'], level: 'C1', topics: ['opinions'] },
  { id: 's.u167', es: 'Firmaron con una salvedad importante.', en: 'They signed with one important proviso.', concepts: ['v.la-salvedad'], level: 'C1', topics: ['work'] },
  { id: 's.u168', es: 'Hay un desfase entre lo previsto y lo real.', en: 'There is a gap between what was forecast and what is real.', concepts: ['v.el-desfase', 'v.entre'], level: 'C1', topics: ['work'] },
  { id: 's.u169', es: 'El desfase horario me dejó hecho polvo.', en: 'The jet lag left me shattered.', concepts: ['v.el-desfase'], level: 'C1', topics: ['travel'] },
  { id: 's.u170', es: 'Hay que ponderar las dos posturas.', en: 'Both positions have to be weighed.', concepts: ['v.ponderar', 'v.la-postura'], level: 'C1', topics: ['opinions'] },
  { id: 's.u171', es: 'Ponderó mucho tu trabajo en la reunión.', en: 'He spoke very highly of your work in the meeting.', concepts: ['v.ponderar'], level: 'C1', topics: ['work'] },
  { id: 's.u172', es: 'Eso entraña un riesgo considerable.', en: 'That entails a considerable risk.', concepts: ['v.entrañar', 'v.el-riesgo'], level: 'C1', topics: ['work'] },
  { id: 's.u173', es: 'El cargo entraña mucha responsabilidad.', en: 'The post entails a great deal of responsibility.', concepts: ['v.entrañar'], level: 'C1', topics: ['work'] },
  { id: 's.u174', es: 'Eludió la pregunta con elegancia.', en: 'She evaded the question elegantly.', concepts: ['v.eludir'], level: 'C1', topics: ['social'] },
  { id: 's.u175', es: 'No se puede eludir esa responsabilidad.', en: 'That responsibility cannot be avoided.', concepts: ['v.eludir'], level: 'C1', topics: ['work'] },
  { id: 's.u176', es: 'Su ayuda fue imprescindible.', en: 'Her help was essential.', concepts: ['v.imprescindible'], level: 'C1', topics: ['work'] },
  { id: 's.u177', es: 'Es un libro imprescindible.', en: 'It is an essential book.', concepts: ['v.imprescindible'], level: 'C1', topics: ['hobbies'] },
  { id: 's.u178', es: 'Esa conclusión es muy discutible.', en: 'That conclusion is highly debatable.', concepts: ['v.discutible'], level: 'C1', topics: ['opinions'] },
  { id: 's.u179', es: 'Es discutible, pero no absurdo.', en: 'It is debatable, but not absurd.', concepts: ['v.discutible'], level: 'C1', topics: ['opinions'] },
  { id: 's.u180', es: 'A grandes rasgos, estamos de acuerdo.', en: 'Broadly speaking, we agree.', concepts: ['p.a-grandes-rasgos'], level: 'C1', topics: ['opinions'] },
  { id: 's.u181', es: 'Te lo cuento a grandes rasgos.', en: 'I will give you the broad outline.', concepts: ['p.a-grandes-rasgos', 'v.contar'], level: 'C1', topics: ['work'] },
];
