import type { Sentence } from '@/content/types';

/** Directions, transport, ordering and paying — language for being there. */
export const aroundSpainSentences: Sentence[] = [
  {
    id: 's.a1',
    es: 'Perdona, ¿sabes dónde está la estación?',
    en: 'Excuse me, do you know where the station is?',
    concepts: ['p.perdona-donde', 'v.saber', 'v.estar', 'v.estacion'],
    level: 'A2',
    topics: ['directions'],
  },
  {
    id: 's.a2',
    es: 'Sigue todo recto y gira a la derecha.',
    en: 'Carry straight on and turn right.',
    concepts: ['v.seguir', 'v.recto', 'v.girar', 'v.derecha', 'g.commands'],
    level: 'A2',
    topics: ['directions'],
    blanks: ['recto'],
  },
  {
    id: 's.a3',
    es: 'Está a la izquierda, después de la plaza.',
    en: 'It’s on the left, after the square.',
    concepts: ['v.estar', 'v.izquierda', 'v.despues', 'v.plaza'],
    level: 'A2',
    topics: ['directions'],
  },
  {
    id: 's.a4',
    es: '¿Está lejos de aquí?',
    en: 'Is it far from here?',
    concepts: ['v.estar', 'v.lejos'],
    level: 'A1',
    topics: ['directions'],
  },
  {
    id: 's.a5',
    es: 'No, está muy cerca, cinco minutos andando.',
    en: 'No, it’s very close, five minutes on foot.',
    concepts: ['v.cerca', 'v.andar', 'v.cinco', 'v.estar'],
    level: 'A2',
    topics: ['directions', 'transport'],
    note: 'Andando is how Spaniards say "on foot" — not a pie.',
  },
  {
    id: 's.a6',
    es: 'La farmacia está enfrente del banco.',
    en: 'The pharmacy is opposite the bank.',
    concepts: ['v.enfrente', 'v.estar'],
    level: 'A2',
    topics: ['directions', 'city'],
  },
  {
    id: 's.a7',
    es: 'Hay un supermercado en la esquina.',
    en: 'There’s a supermarket on the corner.',
    concepts: ['g.hay-estar', 'v.supermercado', 'v.esquina'],
    level: 'A2',
    topics: ['directions', 'shopping'],
    blanks: ['Hay'],
  },
  {
    id: 's.a8',
    es: '¿Qué línea de metro cojo para ir al centro?',
    en: 'Which metro line do I take to get to the centre?',
    concepts: ['v.coger', 'v.metro', 'g.por-para', 'v.ir'],
    level: 'B1',
    topics: ['transport', 'directions'],
  },
  {
    id: 's.a9',
    es: 'Un billete de ida y vuelta a Toledo, por favor.',
    en: 'A return ticket to Toledo, please.',
    concepts: ['v.billete', 'p.por-favor'],
    level: 'A2',
    topics: ['transport', 'travel'],
    note: 'Ida y vuelta = return. Just ida is one-way.',
  },
  {
    id: 's.a10',
    es: 'Compré dos entradas para el concierto.',
    en: 'I bought two tickets for the concert.',
    concepts: ['v.comprar', 'g.preterite', 'v.entrada', 'v.dos', 'g.por-para'],
    level: 'A2',
    topics: ['hobbies', 'past'],
    note: 'Entradas for events, billetes for travel.',
  },
  {
    id: 's.a11',
    es: 'El tren sale de la estación de Atocha.',
    en: 'The train leaves from Atocha station.',
    concepts: ['v.tren', 'v.salir', 'v.estacion'],
    level: 'A2',
    topics: ['transport', 'travel'],
  },
  {
    id: 's.a12',
    es: 'Me bajo en la próxima parada.',
    en: 'I’m getting off at the next stop.',
    concepts: ['g.reflexive', 'v.parada'],
    level: 'A2',
    topics: ['transport'],
  },
  {
    id: 's.a13',
    es: 'Buenas, ¿me pones una caña?',
    en: 'Hey, can I get a small beer?',
    concepts: ['p.buenas', 'p.me-pones', 'v.cana'],
    level: 'A2',
    topics: ['cafe'],
    note: 'The complete Spanish bar transaction, in five words.',
  },
  {
    id: 's.a14',
    es: 'Quería reservar una mesa para dos.',
    en: 'I’d like to book a table for two.',
    concepts: ['v.querer', 'v.reservar', 'v.mesa', 'v.dos', 'g.por-para'],
    level: 'A2',
    topics: ['restaurant'],
    note: 'Quería (imperfect) is the polite way to ask — quiero sounds blunt here.',
  },
  {
    id: 's.a15',
    es: '¿Tienen mesa para esta noche?',
    en: 'Do you have a table for tonight?',
    concepts: ['v.tener', 'v.mesa', 'v.noche'],
    level: 'A2',
    topics: ['restaurant'],
  },
  {
    id: 's.a16',
    es: 'El camarero nos trajo la carta enseguida.',
    en: 'The waiter brought us the menu straight away.',
    concepts: ['v.camarero', 'v.carta', 'g.preterite'],
    level: 'B1',
    topics: ['restaurant', 'past'],
  },
  {
    id: 's.a17',
    es: 'Todo estaba buenísimo, gracias.',
    en: 'Everything was delicious, thank you.',
    concepts: ['v.estar', 'g.imperfect', 'v.gracias'],
    level: 'B1',
    topics: ['restaurant'],
    note: 'Estar bueno = tasty. Ser bueno would be about quality or morality.',
  },
  {
    id: 's.a18',
    es: '¿Puedo pagar con tarjeta?',
    en: 'Can I pay by card?',
    concepts: ['v.poder', 'v.pagar', 'p.con-tarjeta'],
    level: 'A2',
    topics: ['shopping'],
  },
  {
    id: 's.a19',
    es: '¿Tienen esta camiseta en otra talla?',
    en: 'Do you have this t-shirt in another size?',
    concepts: ['v.tener', 'v.talla'],
    level: 'A2',
    topics: ['shopping'],
  },
  {
    id: 's.a20',
    es: '¿Me lo puedo probar?',
    en: 'Can I try it on?',
    concepts: ['v.probar', 'g.object-pronouns', 'v.poder'],
    level: 'B1',
    topics: ['shopping'],
  },
  {
    id: 's.a21',
    es: 'Es muy caro, ¿hay algo más barato?',
    en: 'It’s very expensive, is there anything cheaper?',
    concepts: ['v.caro', 'g.hay-estar', 'v.barato'],
    level: 'A2',
    topics: ['shopping'],
  },
  {
    id: 's.a22',
    es: 'He perdido las llaves del piso.',
    en: 'I’ve lost the keys to the flat.',
    concepts: ['g.present-perfect', 'v.llave', 'v.piso'],
    level: 'A2',
    topics: ['home', 'travel'],
  },
  {
    id: 's.a23',
    es: 'Se me ha olvidado la maleta en el tren.',
    en: 'I left my suitcase on the train.',
    concepts: ['p.se-me-ha-olvidado', 'v.maleta', 'v.tren'],
    level: 'B1',
    topics: ['travel'],
    note: 'Literally "the suitcase has forgotten itself on me" — Spanish shifts the blame off you.',
  },
  {
    id: 's.a24',
    es: 'El hotel está cerca de la playa.',
    en: 'The hotel is near the beach.',
    concepts: ['v.hotel', 'v.estar', 'v.cerca', 'v.playa'],
    level: 'A1',
    topics: ['travel'],
  },
  {
    id: 's.a25',
    es: 'Fuimos a Granada en tren y volvimos en autobús.',
    en: 'We went to Granada by train and came back by bus.',
    concepts: ['g.preterite', 'v.ir', 'v.tren', 'v.autobus'],
    level: 'B1',
    topics: ['travel', 'past'],
  },
  {
    id: 's.a26',
    es: 'El viaje fue largo pero mereció la pena.',
    en: 'The journey was long but it was worth it.',
    concepts: ['v.viaje', 'g.preterite', 'v.pero'],
    level: 'B1',
    topics: ['travel', 'past'],
    note: 'Merecer la pena = to be worth it. Very common.',
  },
  {
    id: 's.a27',
    es: 'No conozco Bilbao, pero me gustaría ir.',
    en: 'I don’t know Bilbao, but I’d like to go.',
    concepts: ['v.conocer', 'g.gustar', 'v.ir'],
    level: 'B1',
    topics: ['travel', 'opinions'],
    note: 'Me gustaría — the conditional is the polite, hypothetical "would like".',
  },
  {
    id: 's.a28',
    es: 'Dime, ¿qué te pongo?',
    en: 'Go on, what can I get you?',
    concepts: ['g.commands', 'v.decir'],
    level: 'B1',
    topics: ['cafe'],
    note: 'What the person behind the bar will actually say to you.',
  },
  {
    id: 's.a29',
    es: 'Ponme otra, por favor.',
    en: 'Get me another one, please.',
    concepts: ['g.commands', 'p.por-favor'],
    level: 'B1',
    topics: ['cafe'],
  },
  {
    id: 's.a30',
    es: 'Está al lado de la parada del autobús.',
    en: 'It’s next to the bus stop.',
    concepts: ['v.al-lado', 'v.parada', 'v.autobus', 'v.estar'],
    level: 'A2',
    topics: ['directions', 'transport'],
  },

  // --- Following a route on foot -------------------------------------------
  {
    id: 's.a31',
    es: 'Sigue por esta calle y gira en el segundo semáforo.',
    en: 'Carry on down this street and turn at the second set of lights.',
    concepts: ['v.seguir', 'v.girar', 'v.calle'],
    level: 'A2',
    topics: ['directions'],
  },
  {
    id: 's.a32',
    es: 'Está justo delante de la estación, no tiene pérdida.',
    en: 'It’s right in front of the station, you can’t miss it.',
    concepts: ['v.delante', 'v.estacion'],
    level: 'A2',
    topics: ['directions'],
    note: 'no tiene pérdida — "you can’t miss it" — the fixed reassurance at the end of directions.',
  },
  {
    id: 's.a33',
    es: 'Se va andando en diez minutos, no cojas el metro.',
    en: 'It’s a ten-minute walk, don’t take the metro.',
    concepts: ['v.andar', 'v.coger', 'v.metro'],
    level: 'A2',
    topics: ['directions', 'transport'],
  },
  {
    id: 's.a34',
    es: 'La entrada del museo cuesta doce euros, pero el domingo es gratis.',
    en: 'Museum admission is twelve euros, but on Sunday it’s free.',
    concepts: ['v.entrada', 'v.domingo', 'v.doce'],
    level: 'A2',
    topics: ['city', 'shopping'],
    note: 'entrada is admission to a place or event; a travel ticket is a billete.',
  },

  // --- Eating out ------------------------------------------------------------
  {
    id: 's.a35',
    es: 'El camarero nos ha traído una tapa con la caña.',
    en: 'The waiter brought us a tapa with the beer.',
    concepts: ['v.camarero', 'v.tapa', 'v.cana'],
    level: 'A2',
    topics: ['cafe', 'food'],
    note: 'In much of Spain the tapa comes free with the drink — you do not order it.',
  },
  {
    id: 's.a36',
    es: '¿Qué hay hoy en el menú del día? —Lentejas o ensalada de primero.',
    en: '“What’s on the set menu today?” “Lentils or salad to start.”',
    concepts: ['p.menu-del-dia', 'v.primero'],
    level: 'A2',
    topics: ['restaurant', 'food'],
  },
  {
    id: 's.a37',
    es: 'De primero una sopa y de segundo lo que sea, me da igual.',
    en: 'Soup to start and whatever for the main, I don’t mind.',
    concepts: ['v.primero', 'p.da-igual'],
    level: 'A2',
    topics: ['restaurant'],
    register: 'colloquial',
  },
  {
    id: 's.a38',
    es: 'Cuando puedas, la cuenta, por favor.',
    en: 'Whenever you can, the bill, please.',
    concepts: ['p.la-cuenta-porfa', 'v.camarero'],
    level: 'A2',
    topics: ['restaurant'],
    note: 'You almost always have to ask — a Spanish waiter will not bring the bill unprompted.',
  },
  {
    id: 's.a39',
    es: '¿Cómo está usted, don Alfonso? ¿Le traigo lo de siempre?',
    en: 'How are you, Don Alfonso? Shall I bring you the usual?',
    concepts: ['v.usted', 'v.camarero'],
    level: 'A2',
    topics: ['cafe', 'greetings'],
    register: 'formal',
    note: 'usted plus the first name is the warm-but-respectful register of a regular bar.',
  },
  {
    id: 's.a40',
    es: 'Perdone, ¿me puede decir usted a qué hora abren?',
    en: 'Excuse me, could you tell me what time they open?',
    concepts: ['v.usted', 'v.hora', 'v.decir'],
    level: 'A2',
    topics: ['directions', 'city'],
    register: 'formal',
  },
];
