import type { Sentence } from '@/content/types';

/**
 * B1 sentences: speculation, hypotheticals, advice, complaints and the
 * connectors that hold a paragraph together.
 *
 * The shape is the point. A2 sentences carry a reason; B1 sentences carry a
 * relationship between two ideas — contrast, consequence, condition — which is
 * what the connectors and the new tenses exist to express.
 */
export const b1CoreSentences: Sentence[] = [
  // --- Future and speculation ----------------------------------------------
  {
    id: 's.b1',
    es: 'El año que viene viviré en Madrid.',
    en: "Next year I'll live in Madrid.",
    concepts: ['g.future', 'v.ano-time'],
    level: 'B1',
    topics: ['plans'],
    blanks: ['viviré'],
  },
  {
    id: 's.b2',
    es: '¿Dónde está Ana? — No sé, estará en el metro.',
    en: "Where's Ana? — I don't know, she's probably on the metro.",
    concepts: ['g.future', 'v.metro'],
    level: 'B1',
    topics: ['plans'],
    note: 'The future used as a guess about the present — extremely common in speech.',
  },
  {
    id: 's.b3',
    es: 'Mañana te lo diré, ahora no tengo tiempo.',
    en: "I'll tell you tomorrow, I haven't got time now.",
    concepts: ['g.future', 'v.tiempo', 'v.ahora'],
    level: 'B1',
    topics: ['plans'],
  },
  {
    id: 's.b4',
    es: 'Tendremos que salir antes si hay retraso.',
    en: "We'll have to leave earlier if there's a delay.",
    concepts: ['g.future', 'v.retraso', 'p.tener-que'],
    level: 'B1',
    topics: ['transport', 'plans'],
  },

  // --- Conditional: politeness, advice, hypotheticals ----------------------
  {
    id: 's.b5',
    es: '¿Podrías echarme una mano con esto?',
    en: 'Could you give me a hand with this?',
    concepts: ['g.conditional', 'v.poder'],
    level: 'B1',
    topics: ['social', 'work'],
    blanks: ['Podrías'],
  },
  {
    id: 's.b6',
    es: 'Yo que tú, hablaría con tu jefe.',
    en: "If I were you, I'd talk to your boss.",
    concepts: ['p.yo-que-tu', 'g.conditional', 'v.jefe'],
    level: 'B1',
    topics: ['work', 'opinions'],
  },
  {
    id: 's.b7',
    es: 'Deberías descansar más, estás agobiado.',
    en: 'You should rest more, you’re stressed out.',
    concepts: ['p.deberias', 'v.agobiado'],
    level: 'B1',
    topics: ['opinions', 'feelings'],
  },
  {
    id: 's.b8',
    es: 'Me gustaría cambiar de trabajo, pero no es fácil.',
    en: "I'd like to change jobs, but it isn't easy.",
    concepts: ['g.conditional', 'v.trabajo', 'v.facil'],
    level: 'B1',
    topics: ['work'],
  },
  {
    id: 's.b9',
    es: 'Te recomiendo que vayas en tren, merece la pena.',
    en: 'I recommend you go by train, it’s worth it.',
    concepts: ['p.te-recomiendo', 'p.merece-la-pena', 'v.tren'],
    level: 'B1',
    topics: ['travel', 'opinions'],
  },

  // --- Pluperfect and storytelling -----------------------------------------
  {
    id: 's.b10',
    es: 'Cuando llegué a la estación, el tren ya se había ido.',
    en: "When I got to the station, the train had already left.",
    concepts: ['g.pluperfect', 'v.estacion', 'v.tren'],
    level: 'B1',
    topics: ['past', 'transport'],
    blanks: ['se había ido'],
  },
  {
    id: 's.b11',
    es: 'No sabía que habías estudiado en Salamanca.',
    en: "I didn't know you'd studied in Salamanca.",
    concepts: ['g.pluperfect', 'v.estudiar'],
    level: 'B1',
    topics: ['past', 'university'],
  },
  {
    id: 's.b12',
    es: 'Estaba leyendo tranquilamente cuando de repente sonó el móvil.',
    en: 'I was reading quietly when suddenly the phone rang.',
    concepts: ['v.de-repente', 'g.preterite-imperfect', 'v.movil'],
    level: 'B1',
    topics: ['storytelling'],
    note: 'Imperfect for the background, preterite for the interruption — de repente marks the switch.',
  },
  {
    id: 's.b13',
    es: 'Al final no fuimos, porque había empezado a llover.',
    en: "In the end we didn't go, because it had started raining.",
    concepts: ['v.al-final', 'g.pluperfect', 'v.llover'],
    level: 'B1',
    topics: ['storytelling'],
  },
  {
    id: 's.b14',
    es: 'Mientras cenábamos, nos dimos cuenta de que faltaba alguien.',
    en: 'While we were having dinner, we realised someone was missing.',
    concepts: ['v.mientras', 'p.darse-cuenta', 'g.preterite-imperfect'],
    level: 'B1',
    topics: ['storytelling'],
  },

  // --- se and impersonal ---------------------------------------------------
  {
    id: 's.b15',
    es: 'En España se cena muy tarde.',
    en: 'In Spain people have dinner very late.',
    concepts: ['g.se-impersonal', 'v.cena', 'v.espana'],
    level: 'B1',
    topics: ['city'],
    blanks: ['se cena'],
  },
  {
    id: 's.b16',
    es: '¿Cómo se dice esto en español?',
    en: 'How do you say this in Spanish?',
    concepts: ['g.se-impersonal', 'v.espanol'],
    level: 'B1',
    topics: ['introductions'],
  },
  {
    id: 's.b17',
    es: 'Se me ha olvidado el móvil en casa.',
    en: "I've left my phone at home.",
    concepts: ['g.se-impersonal', 'p.se-me-ha-olvidado', 'v.movil'],
    level: 'B1',
    topics: ['daily-routine'],
    note: 'The accidental se — the thing forgot itself on you. Standard, not an excuse.',
  },
  {
    id: 's.b18',
    es: 'Aquí se come muy bien y no es caro.',
    en: 'The food here is great and it isn’t expensive.',
    concepts: ['g.se-impersonal', 'v.comer', 'v.caro'],
    level: 'B1',
    topics: ['restaurant', 'opinions'],
  },

  // --- Relative clauses ----------------------------------------------------
  {
    id: 's.b19',
    es: 'El piso que alquilamos está en Lavapiés.',
    en: 'The flat we rented is in Lavapiés.',
    concepts: ['g.relatives', 'v.piso'],
    level: 'B1',
    topics: ['home'],
    note: 'English can drop "that"; Spanish never drops que.',
  },
  {
    id: 's.b20',
    es: 'No entiendo lo que quieres decir.',
    en: "I don't understand what you mean.",
    concepts: ['g.relatives'],
    level: 'B1',
    topics: ['opinions'],
    blanks: ['lo que'],
  },
  {
    id: 's.b21',
    es: 'La chica con quien hablé trabaja en la misma empresa.',
    en: 'The girl I spoke to works at the same company.',
    concepts: ['g.relatives', 'v.empresa'],
    level: 'B1',
    topics: ['work'],
  },
  {
    id: 's.b22',
    es: 'Eso es lo que me da rabia.',
    en: "That's what makes me angry.",
    concepts: ['g.relatives', 'p.me-da-rabia'],
    level: 'B1',
    topics: ['feelings'],
  },

  // --- Feelings with range -------------------------------------------------
  {
    id: 's.b23',
    es: 'Estoy harto de las reuniones que no sirven para nada.',
    en: "I'm fed up with meetings that are pointless.",
    concepts: ['v.harto', 'v.reunion', 'g.relatives'],
    level: 'B1',
    topics: ['work', 'feelings'],
  },
  {
    id: 's.b24',
    es: 'Me preocupa que no haya contestado todavía.',
    en: "It worries me that he hasn't replied yet.",
    concepts: ['p.me-preocupa', 'g.subjunctive-intro'],
    level: 'B1',
    topics: ['feelings'],
    note: 'Emotion + que sends the next verb into the subjunctive.',
  },
  {
    id: 's.b25',
    es: 'Echo mucho de menos a mi familia.',
    en: 'I really miss my family.',
    concepts: ['p.echar-de-menos', 'v.familia'],
    level: 'B1',
    topics: ['feelings', 'family'],
  },
  {
    id: 's.b26',
    es: 'Tengo muchas ganas de que llegue el verano.',
    en: "I'm really looking forward to summer.",
    concepts: ['p.tener-ganas', 'g.subjunctive-intro'],
    level: 'B1',
    topics: ['feelings', 'plans'],
  },
  {
    id: 's.b27',
    es: 'Me llevo muy bien con mis compañeros de piso.',
    en: 'I get on really well with my flatmates.',
    concepts: ['p.llevarse-bien', 'v.companero'],
    level: 'B1',
    topics: ['social', 'home'],
  },

  // --- Complaining and sorting problems out --------------------------------
  {
    id: 's.b28',
    es: 'Perdone, hay un problema con la reserva.',
    en: "Excuse me, there's a problem with the booking.",
    concepts: ['p.hay-un-problema', 'v.reservar'],
    level: 'B1',
    topics: ['travel'],
    register: 'formal',
  },
  {
    id: 's.b29',
    es: 'El ascensor no funciona, está averiado desde el martes.',
    en: "The lift doesn't work, it's been out of order since Tuesday.",
    concepts: ['p.no-funciona', 'v.averiado', 'v.martes'],
    level: 'B1',
    topics: ['home'],
  },
  {
    id: 's.b30',
    es: 'Creo que me han cobrado de más.',
    en: 'I think I’ve been overcharged.',
    concepts: ['p.me-han-cobrado', 'v.creo-que', 'g.present-perfect'],
    level: 'B1',
    topics: ['shopping'],
  },
  {
    id: 's.b31',
    es: 'Querría devolver esto, no me queda bien.',
    en: "I'd like to return this, it doesn't fit me.",
    concepts: ['p.querria-devolver', 'p.me-queda-bien', 'g.conditional'],
    level: 'B1',
    topics: ['shopping'],
    register: 'formal',
  },
  {
    id: 's.b32',
    es: 'Lo siento mucho, no volverá a pasar.',
    en: "I'm really sorry, it won't happen again.",
    concepts: ['p.lo-siento-mucho', 'g.future'],
    level: 'B1',
    topics: ['social'],
  },
  {
    id: 's.b33',
    es: 'No pasa nada, de verdad.',
    en: "It's fine, honestly.",
    concepts: ['p.no-pasa-nada'],
    level: 'B1',
    topics: ['social'],
  },

  // --- Connectors doing real work ------------------------------------------
  {
    id: 's.b34',
    es: 'El sueldo no está mal; sin embargo, el horario es horrible.',
    en: "The salary isn't bad; however, the hours are terrible.",
    concepts: ['v.sin-embargo', 'v.sueldo', 'v.horario'],
    level: 'B1',
    topics: ['work', 'opinions'],
    blanks: ['sin embargo'],
  },
  {
    id: 's.b35',
    es: 'Es caro y además está lejos, por eso no voy nunca.',
    en: "It's expensive and it's far as well, that's why I never go.",
    concepts: ['v.ademas', 'v.por-eso', 'v.lejos', 'v.nunca'],
    level: 'B1',
    topics: ['opinions'],
  },
  {
    id: 's.b36',
    es: 'A mí me gusta el norte; en cambio, mi hermano prefiere la costa.',
    en: 'I like the north; my brother, on the other hand, prefers the coast.',
    concepts: ['v.en-cambio', 'v.preferir', 'p.me-gusta'],
    level: 'B1',
    topics: ['opinions', 'travel'],
  },
  {
    id: 's.b37',
    es: 'Por lo visto han cambiado el horario otra vez.',
    en: 'Apparently they’ve changed the timetable again.',
    concepts: ['p.valer-la-pena', 'v.horario', 'g.present-perfect'],
    level: 'B1',
    topics: ['transport'],
  },
  {
    id: 's.b38',
    es: 'Tienes razón, o sea, que al final no merece la pena.',
    en: "You're right, I mean, in the end it isn't worth it.",
    concepts: ['p.tener-razon', 'v.o-sea', 'p.merece-la-pena', 'v.al-final'],
    level: 'B1',
    topics: ['opinions', 'slang'],
  },
  {
    id: 's.b39',
    es: 'Tengo que darme prisa, la reunión empieza en diez minutos.',
    en: "I have to hurry, the meeting starts in ten minutes.",
    concepts: ['p.darse-prisa', 'v.reunion', 'v.diez'],
    level: 'B1',
    topics: ['work'],
  },
  {
    id: 's.b40',
    es: 'Aprobé todas las asignaturas menos una.',
    en: 'I passed every subject except one.',
    concepts: ['v.aprobar', 'v.asignatura', 'v.menos'],
    level: 'B1',
    topics: ['university', 'past'],
  },

  // --- Imperfect: the background of a story -------------------------------
  {
    id: 's.b41',
    es: 'Cuando era pequeña, pasábamos todos los veranos en el pueblo.',
    en: 'When I was little, we spent every summer in the village.',
    concepts: ['g.imperfect', 'v.familia'],
    level: 'B1',
    topics: ['past', 'family'],
    blanks: ['era', 'pasábamos'],
    note: 'Repeated past habit → imperfect. Todos los veranos is the giveaway.',
  },
  {
    id: 's.b42',
    es: 'Antes fumaba mucho, pero lo dejé hace tres años.',
    en: 'I used to smoke a lot, but I gave up three years ago.',
    concepts: ['g.preterite-imperfect', 'v.antes'],
    level: 'B1',
    topics: ['past', 'health'],
    note: 'The habit is imperfect; the single event that ended it is preterite.',
  },
  {
    id: 's.b43',
    es: 'Estaba a punto de salir cuando me llamó mi hermano.',
    en: 'I was about to leave when my brother called me.',
    concepts: ['g.preterite-imperfect', 'v.hermano'],
    level: 'B1',
    topics: ['storytelling'],
    note: 'estar a punto de + infinitivo sets the scene the interruption cuts into.',
  },
  {
    id: 's.b44',
    es: 'Mientras esperaba el autobús, empezó a llover a mares.',
    en: 'While I was waiting for the bus, it started pouring down.',
    concepts: ['g.preterite-imperfect', 'v.mientras', 'v.llover'],
    level: 'B1',
    topics: ['storytelling', 'weather'],
    blanks: ['esperaba', 'empezó'],
  },
  {
    id: 's.b45',
    es: 'De pequeño no me gustaba nada el pescado; ahora me encanta.',
    en: "As a child I hated fish; now I love it.",
    concepts: ['g.imperfect', 'v.pescado'],
    level: 'B1',
    topics: ['food', 'past'],
  },
  {
    id: 's.b46',
    es: 'Éramos cuatro en clase y nos conocíamos desde siempre.',
    en: 'There were four of us in the class and we’d known each other forever.',
    concepts: ['g.imperfect', 'v.conocer'],
    level: 'B1',
    topics: ['past', 'university'],
  },
  {
    id: 's.b47',
    es: 'De repente se apagó la luz y nos quedamos a oscuras.',
    en: 'Suddenly the light went out and we were left in the dark.',
    concepts: ['v.de-repente', 'g.preterite'],
    level: 'B1',
    topics: ['storytelling'],
  },

  // --- Object pronouns: the level where they stop being optional ----------
  {
    id: 's.b48',
    es: 'El libro se lo presté a Marta la semana pasada.',
    en: 'I lent the book to Marta last week.',
    concepts: ['g.object-pronouns', 'g.preterite'],
    level: 'B1',
    topics: ['past'],
    blanks: ['se'],
    note: 'le + lo becomes se lo — Spanish never allows two l-pronouns in a row.',
  },
  {
    id: 's.b49',
    es: '¿Las llaves? Las dejé encima de la mesa.',
    en: 'The keys? I left them on the table.',
    concepts: ['g.object-pronouns', 'v.llave', 'v.mesa'],
    level: 'B1',
    topics: ['home'],
  },
  {
    id: 's.b50',
    es: 'Te lo explico otra vez, que veo que no ha quedado claro.',
    en: "I'll explain it to you again, I can see it wasn't clear.",
    concepts: ['g.object-pronouns'],
    level: 'B1',
    topics: ['university', 'social'],
  },
  {
    id: 's.b51',
    es: 'No me lo dijo nadie, me enteré por casualidad.',
    en: 'Nobody told me, I found out by chance.',
    concepts: ['g.object-pronouns', 'g.negation'],
    level: 'B1',
    topics: ['social', 'storytelling'],
  },
  {
    id: 's.b52',
    es: 'Voy a devolvérselo mañana sin falta.',
    en: "I'm going to give it back to him tomorrow without fail.",
    concepts: ['g.object-pronouns', 'g.ir-a-infinitive'],
    level: 'B1',
    topics: ['social'],
    note: 'Pronouns attach to the infinitive and pull the accent with them: devolvérselo.',
  },

  // --- First subjunctive: wanting, advising, doubting ---------------------
  {
    id: 's.b53',
    es: 'Quiero que me digas la verdad, aunque no me guste.',
    en: "I want you to tell me the truth, even if I don't like it.",
    concepts: ['g.subjunctive-intro'],
    level: 'B1',
    topics: ['social', 'feelings'],
    blanks: ['digas'],
  },
  {
    id: 's.b54',
    es: 'Te recomiendo que reserves con antelación, se llena mucho.',
    en: 'I recommend booking in advance, it gets very full.',
    concepts: ['p.te-recomiendo', 'v.reservar', 'g.subjunctive-intro'],
    level: 'B1',
    topics: ['restaurant', 'travel'],
    blanks: ['reserves'],
  },
  {
    id: 's.b55',
    es: 'Me preocupa que se lo tome a mal.',
    en: "I'm worried he'll take it badly.",
    concepts: ['p.me-preocupa', 'g.subjunctive-intro'],
    level: 'B1',
    topics: ['feelings', 'social'],
    blanks: ['tome'],
    note: 'tomarse algo a mal / a bien — how a message lands, not how it was meant.',
  },
  {
    id: 's.b56',
    es: 'Espero que te mejores pronto.',
    en: 'I hope you get better soon.',
    concepts: ['g.subjunctive-intro', 'p.lo-siento-mucho'],
    level: 'B1',
    topics: ['health', 'social'],
    note: 'The standard get-well message in Spain, and pure subjunctive.',
  },
  {
    id: 's.b57',
    es: 'Es mejor que lo hablemos en persona.',
    en: "It's better if we talk about it in person.",
    concepts: ['g.subjunctive-intro'],
    level: 'B1',
    topics: ['work', 'social'],
  },
  {
    id: 's.b58',
    es: 'No creo que llegue a tiempo con este tráfico.',
    en: "I don't think he'll get there in time in this traffic.",
    concepts: ['g.subjunctive-intro', 'v.tarde'],
    level: 'B1',
    topics: ['transport'],
  },

  // --- Future and conditional ---------------------------------------------
  {
    id: 's.b59',
    es: 'Estará en el metro, por eso no coge el móvil.',
    en: "He must be on the metro, that's why he isn't picking up.",
    concepts: ['g.future', 'v.metro', 'v.movil', 'v.por-eso'],
    level: 'B1',
    topics: ['transport'],
    note: 'The future used for a present guess — one of the most Spanish things in the language.',
  },
  {
    id: 's.b60',
    es: 'El año que viene me mudaré a Valencia, si todo sale bien.',
    en: "Next year I'll move to Valencia, if all goes well.",
    concepts: ['g.future', 'v.ano-time'],
    level: 'B1',
    topics: ['plans', 'home'],
  },
  {
    id: 's.b61',
    es: '¿Podrías echarme una mano con esto un momento?',
    en: 'Could you give me a hand with this for a moment?',
    concepts: ['g.conditional', 'v.poder'],
    level: 'B1',
    topics: ['social', 'work'],
    note: 'The conditional is the politeness gear: podrías, not puedes.',
  },
  {
    id: 's.b62',
    es: 'Yo en tu lugar no diría nada todavía.',
    en: "In your place I wouldn't say anything yet.",
    concepts: ['g.conditional', 'p.yo-que-tu'],
    level: 'B1',
    topics: ['opinions', 'social'],
  },
  {
    id: 's.b63',
    es: 'Me dijeron que la reunión sería el jueves.',
    en: 'They told me the meeting would be on Thursday.',
    concepts: ['g.conditional', 'v.reunion'],
    level: 'B1',
    topics: ['work'],
  },

  // --- Pluperfect and se ---------------------------------------------------
  {
    id: 's.b64',
    es: 'Cuando llegué, ya se habían ido todos.',
    en: 'When I arrived, everyone had already left.',
    concepts: ['g.pluperfect'],
    level: 'B1',
    topics: ['storytelling'],
    blanks: ['habían'],
  },
  {
    id: 's.b65',
    es: 'No sabía que habías estado en Galicia.',
    en: "I didn't know you'd been to Galicia.",
    concepts: ['g.pluperfect', 'g.imperfect'],
    level: 'B1',
    topics: ['travel', 'past'],
  },
  {
    id: 's.b66',
    es: 'Aquí se cena tardísimo, sobre las diez.',
    en: 'People eat dinner really late here, around ten.',
    concepts: ['g.se-impersonal', 'v.cena', 'v.diez'],
    level: 'B1',
    topics: ['food', 'social'],
  },
  {
    id: 's.b67',
    es: 'Se me ha roto el móvil justo antes del examen.',
    en: 'My phone broke right before the exam.',
    concepts: ['g.se-impersonal', 'v.movil'],
    level: 'B1',
    topics: ['university'],
    note: 'The accidental se: nobody broke it, it broke on me. Spanish avoids blaming the speaker.',
  },
  {
    id: 's.b68',
    es: 'En esa oficina se trabaja mucho y se cobra poco.',
    en: 'In that office people work a lot and get paid little.',
    concepts: ['g.se-impersonal', 'v.trabajo'],
    level: 'B1',
    topics: ['work'],
  },
  {
    id: 's.b69',
    es: 'Ese es el compañero del que te hablé.',
    en: "That's the colleague I told you about.",
    concepts: ['g.relatives', 'v.companero'],
    level: 'B1',
    topics: ['work', 'social'],
    note: 'Spanish keeps the preposition attached to the relative: del que, con el que, en el que.',
  },

  // --- Feelings, work and complaints with real texture --------------------
  {
    id: 's.b70',
    es: 'Estoy agobiada con el trabajo, no doy abasto.',
    en: "I'm overwhelmed with work, I can't keep up.",
    concepts: ['v.agobiado', 'v.trabajo'],
    level: 'B1',
    topics: ['work', 'feelings'],
    register: 'colloquial',
    note: 'no dar abasto — to be unable to cope with the volume. Heard constantly in Spain.',
  },
  {
    id: 's.b71',
    es: 'Estoy harto de que cambien el horario cada semana.',
    en: "I'm fed up with them changing the schedule every week.",
    concepts: ['v.harto', 'v.horario', 'g.subjunctive-intro'],
    level: 'B1',
    topics: ['work', 'feelings'],
    blanks: ['cambien'],
  },
  {
    id: 's.b72',
    es: 'Me da rabia haber perdido tanto tiempo con eso.',
    en: 'It makes me angry to have wasted so much time on that.',
    concepts: ['p.me-da-rabia', 'v.tiempo'],
    level: 'B1',
    topics: ['feelings'],
    register: 'colloquial',
  },
  {
    id: 's.b73',
    es: 'Con mi jefe me llevo bien; con el resto del equipo, menos.',
    en: 'I get on well with my boss; with the rest of the team, less so.',
    concepts: ['p.llevarse-bien', 'v.jefe', 'v.menos'],
    level: 'B1',
    topics: ['work', 'social'],
  },
  {
    id: 's.b74',
    es: 'Al final me di cuenta de que no merecía la pena discutir.',
    en: 'In the end I realised it wasn’t worth arguing.',
    concepts: ['p.darse-cuenta', 'p.merece-la-pena', 'v.al-final'],
    level: 'B1',
    topics: ['opinions', 'storytelling'],
  },
  {
    id: 's.b75',
    es: 'Tengo muchas ganas de que lleguen las vacaciones.',
    en: "I'm really looking forward to the holidays.",
    concepts: ['p.tener-ganas', 'g.subjunctive-intro'],
    level: 'B1',
    topics: ['plans', 'feelings'],
    blanks: ['lleguen'],
  },
  {
    id: 's.b76',
    es: 'Echo mucho de menos la comida de mi madre.',
    en: "I really miss my mother's cooking.",
    concepts: ['p.echar-de-menos', 'v.comer'],
    level: 'B1',
    topics: ['food', 'feelings'],
  },
  {
    id: 's.b77',
    es: 'Hay un problema con la calefacción, lleva dos días sin funcionar.',
    en: "There's a problem with the heating, it hasn't worked for two days.",
    concepts: ['p.hay-un-problema', 'p.no-funciona'],
    level: 'B1',
    topics: ['home'],
  },
  {
    id: 's.b78',
    es: 'El ascensor está averiado otra vez, sin embargo nadie lo arregla.',
    en: 'The lift is out of order again; however, nobody fixes it.',
    concepts: ['v.averiado', 'v.sin-embargo'],
    level: 'B1',
    topics: ['home'],
  },
  {
    id: 's.b79',
    es: 'Querría devolver esto, además tengo el tique aquí.',
    en: "I'd like to return this, and I've got the receipt here.",
    concepts: ['p.querria-devolver', 'v.ademas'],
    level: 'B1',
    topics: ['shopping'],
    register: 'formal',
  },
  {
    id: 's.b80',
    es: 'Estoy buscando trabajo, he echado el currículum en varios sitios.',
    en: "I'm looking for work, I've put my CV in at several places.",
    concepts: ['p.buscar-trabajo', 'p.echar-un-curriculum', 'g.present-perfect'],
    level: 'B1',
    topics: ['work'],
  },
  {
    id: 's.b81',
    es: 'Suspendí el primer examen, pero aprobé en septiembre.',
    en: 'I failed the first exam, but I passed in September.',
    concepts: ['v.suspender', 'v.aprobar', 'g.preterite'],
    level: 'B1',
    topics: ['university', 'past'],
  },
  {
    id: 's.b82',
    es: 'Lo mejor es que se lo digas tú directamente.',
    en: "The best thing is for you to tell him yourself.",
    concepts: ['p.lo-mejor-es', 'g.object-pronouns', 'g.subjunctive-intro'],
    level: 'B1',
    topics: ['social', 'opinions'],
  },
  {
    id: 's.b83',
    es: 'Date prisa, que el tren sale en diez minutos.',
    en: "Hurry up, the train leaves in ten minutes.",
    concepts: ['p.darse-prisa', 'v.tren', 'g.commands'],
    level: 'B1',
    topics: ['transport'],
    register: 'colloquial',
  },
  {
    id: 's.b84',
    es: 'Lo pasamos genial en Granada, en cambio en Sevilla llovió todo el finde.',
    en: 'We had a great time in Granada; in Seville, on the other hand, it rained all weekend.',
    concepts: ['p.pasarlo-bien', 'v.en-cambio', 'v.llover'],
    level: 'B1',
    topics: ['travel', 'past'],
    register: 'colloquial',
  },
  {
    id: 's.b85',
    es: 'Por lo visto han cambiado de opinión otra vez.',
    en: 'Apparently they’ve changed their minds again.',
    concepts: ['p.valer-la-pena', 'g.present-perfect'],
    level: 'B1',
    topics: ['work', 'opinions'],
  },
// --- Filling the gaps the audit found at B1 ------------------------------
  {
    id: 's.b86',
    es: 'Estoy muy orgulloso de ti, de verdad.',
    en: 'I’m really proud of you, honestly.',
    concepts: ['v.orgulloso'],
    level: 'B1',
    topics: ['feelings', 'social'],
  },
  {
    id: 's.b87',
    es: 'Me quedé bastante decepcionado con el final de la serie.',
    en: 'I was pretty disappointed with the end of the series.',
    concepts: ['v.decepcionado', 'g.preterite'],
    level: 'B1',
    topics: ['feelings', 'hobbies'],
  },
  {
    id: 's.b88',
    es: 'Me da pena que se vaya, nos llevábamos muy bien.',
    en: 'It makes me sad that he’s leaving, we got on really well.',
    concepts: ['p.me-da-pena', 'p.llevarse-bien', 'g.subjunctive-intro'],
    level: 'B1',
    topics: ['feelings', 'social'],
    blanks: ['vaya'],
  },
  {
    id: 's.b89',
    es: 'Me da miedo conducir de noche con esta lluvia.',
    en: 'I’m scared of driving at night in this rain.',
    concepts: ['p.me-da-miedo', 'v.conducir'],
    level: 'B1',
    topics: ['feelings', 'transport'],
  },
  {
    id: 's.b90',
    es: 'Estoy hasta las narices de las obras del edificio.',
    en: "I've had it up to here with the building works.",
    concepts: ['p.estoy-hasta'],
    level: 'B1',
    topics: ['feelings', 'home'],
    register: 'colloquial',
  },
  {
    id: 's.b91',
    es: 'Terminé la carrera en junio, sobre todo gracias a mi familia.',
    en: 'I finished my degree in June, above all thanks to my family.',
    concepts: ['v.carrera', 'v.sobre-todo', 'g.preterite'],
    level: 'B1',
    topics: ['university', 'family'],
  },
  {
    id: 's.b92',
    es: '¿Por qué no le echas un vistazo antes de enviarlo?',
    en: 'Why don’t you have a quick look at it before sending it?',
    concepts: ['p.por-que-no', 'p.echar-un-vistazo'],
    level: 'B1',
    topics: ['work', 'social'],
  },
  {
    id: 's.b93',
    es: 'Me parece que no prestaste atención a lo que dije.',
    en: 'I get the feeling you weren’t paying attention to what I said.',
    concepts: ['p.me-parece', 'p.prestar-atencion', 'g.relatives'],
    level: 'B1',
    topics: ['social', 'opinions'],
  },

  // --- Spiral: earlier vocabulary re-met inside B1 grammar -----------------
  {
    id: 's.b94',
    es: 'Cuando era pequeño mi abuela hacía una comida increíble los domingos.',
    en: 'When I was small my grandmother made incredible food on Sundays.',
    concepts: ['g.imperfect', 'v.comida', 'v.domingo', 'v.abuelo'],
    level: 'B1',
    topics: ['past', 'family', 'food'],
  },
  {
    id: 's.b95',
    es: 'Me di cuenta de que no entendía nada y pedí que hablaran más despacio.',
    en: 'I realised I understood nothing and asked them to speak more slowly.',
    concepts: ['p.darse-cuenta', 'p.mas-despacio', 'g.subjunctive-intro'],
    level: 'B1',
    topics: ['storytelling', 'social'],
    note: 'A repair phrase learned at A1 comes back inside a reported request at B1.',
  },
  {
    id: 's.b96',
    es: 'Espero que haga sol el domingo, tengo muchas ganas de ir a la playa.',
    en: 'I hope it’s sunny on Sunday, I’m really looking forward to going to the beach.',
    concepts: ['g.subjunctive-intro', 'p.hace-sol', 'p.tener-ganas', 'v.domingo'],
    level: 'B1',
    topics: ['weather', 'plans'],
    blanks: ['haga'],
  },
  {
    id: 's.b97',
    es: 'Yo que tú compraría el verde, el rojo se ve en todas partes.',
    en: 'If I were you I’d buy the green one, you see the red one everywhere.',
    concepts: ['p.yo-que-tu', 'v.verde', 'v.rojo', 'g.conditional'],
    level: 'B1',
    topics: ['shopping', 'opinions'],
  },
  {
    id: 's.b98',
    es: 'Nos conocimos en una fiesta y desde entonces nos llevamos muy bien.',
    en: 'We met at a party and we’ve got on well ever since.',
    concepts: ['v.fiesta', 'p.llevarse-bien', 'g.preterite'],
    level: 'B1',
    topics: ['social', 'past'],
  },
  {
    id: 's.b99',
    es: 'Antes no me gustaba nada el pescado; ahora lo como casi todas las semanas.',
    en: 'I used to hate fish; now I eat it almost every week.',
    concepts: ['g.preterite-imperfect', 'v.gustar', 'v.semana', 'v.antes'],
    level: 'B1',
    topics: ['food', 'past'],
  },
  {
    id: 's.b100',
    es: 'Le dije que era simpático, pero no me hizo ni caso.',
    en: 'I told him he was nice, but he paid me no attention at all.',
    concepts: ['v.simpatico', 'g.reported-speech', 'g.object-pronouns'],
    level: 'B1',
    topics: ['social', 'storytelling'],
    note: 'no hacer ni caso — to ignore completely. The ni is what makes it emphatic.',
  },
  {
    id: 's.b101',
    es: 'Te recomiendo que vayas en septiembre: hace buen tiempo y hay menos gente.',
    en: 'I recommend going in September: the weather is good and there are fewer people.',
    concepts: ['p.te-recomiendo', 'v.septiembre', 'p.que-tiempo-hace', 'v.gente'],
    level: 'B1',
    topics: ['travel', 'opinions'],
  },

  // --- Feelings with a cause attached --------------------------------------
  {
    id: 's.b102',
    es: 'Están preocupados porque su hijo lleva dos meses sin encontrar nada.',
    en: 'They’re worried because their son has spent two months finding nothing.',
    concepts: ['v.preocupado', 'v.hijo', 'p.buscar-trabajo'],
    level: 'B1',
    topics: ['feelings', 'work'],
  },
  {
    id: 's.b103',
    es: 'Mis padres están muy orgullosos de que haya terminado la carrera.',
    en: 'My parents are very proud that I’ve finished my degree.',
    concepts: ['v.orgulloso', 'v.carrera', 'g.subjunctive-intro'],
    level: 'B1',
    topics: ['feelings', 'university'],
    blanks: ['haya'],
    note: 'Emotion + que sends the next verb into the subjunctive, even when the fact is certain.',
  },
  {
    id: 's.b104',
    es: 'Me quedé decepcionada, esperaba bastante más de ese curso.',
    en: 'I was left disappointed, I expected quite a bit more from that course.',
    concepts: ['v.decepcionado', 'g.preterite-imperfect', 'v.clase'],
    level: 'B1',
    topics: ['feelings', 'university'],
  },
  {
    id: 's.b105',
    es: 'Me da pena dejar el piso, he vivido cuatro años aquí.',
    en: 'It makes me sad to leave the flat, I’ve lived here four years.',
    concepts: ['p.me-da-pena', 'v.piso', 'g.present-perfect'],
    level: 'B1',
    topics: ['feelings', 'home'],
  },
  {
    id: 's.b106',
    es: 'Me da miedo que se entere antes de que se lo cuente yo.',
    en: 'I’m scared he’ll find out before I tell him myself.',
    concepts: ['p.me-da-miedo', 'g.subjunctive-intro'],
    level: 'B1',
    topics: ['feelings', 'social'],
    blanks: ['entere'],
    note: 'antes de que always takes the subjunctive — no exceptions.',
  },
  {
    id: 's.b107',
    es: 'Estoy hasta las narices de que cambien el horario cada dos por tres.',
    en: 'I’ve had it up to here with them changing the schedule constantly.',
    concepts: ['p.estoy-hasta', 'v.horario', 'g.subjunctive-intro'],
    level: 'B1',
    topics: ['feelings', 'work'],
    register: 'colloquial',
    note: 'cada dos por tres — "all the time". One of those fixed phrases with no logic to parse.',
  },

  // --- Studying and looking for work ---------------------------------------
  {
    id: 's.b108',
    es: 'Suspendí una asignatura en febrero y la aprobé en junio.',
    en: 'I failed one subject in February and passed it in June.',
    concepts: ['v.suspender', 'v.asignatura', 'v.aprobar'],
    level: 'B1',
    topics: ['university', 'past'],
  },
  {
    id: 's.b109',
    es: 'La carrera está bien, pero hay asignaturas que no sirven para nada.',
    en: 'The degree is fine, but there are subjects that are completely useless.',
    concepts: ['v.carrera', 'v.asignatura', 'g.relatives'],
    level: 'B1',
    topics: ['university', 'opinions'],
  },
  {
    id: 's.b110',
    es: 'He echado el currículum en cuatro sitios y no me ha llamado nadie.',
    en: 'I’ve put my CV in at four places and nobody has called me.',
    concepts: ['p.echar-un-curriculum', 'g.present-perfect', 'g.negation'],
    level: 'B1',
    topics: ['work'],
  },
  {
    id: 's.b111',
    es: 'Llevo seis meses buscando trabajo y ya me da igual dónde sea.',
    en: 'I’ve been looking for work for six months and I no longer care where.',
    concepts: ['p.buscar-trabajo', 'p.da-igual', 'g.subjunctive-relative'],
    level: 'B1',
    topics: ['work', 'feelings'],
  },

  // --- Advising, agreeing, hedging an opinion ------------------------------
  {
    id: 's.b112',
    es: 'Deberías descansar un poco antes de tomar una decisión así.',
    en: 'You should rest a bit before making a decision like that.',
    concepts: ['p.deberias', 'p.tomar-una-decision', 'v.antes'],
    level: 'B1',
    topics: ['opinions', 'social'],
  },
  {
    id: 's.b113',
    es: '¿Por qué no le echas un vistazo y me dices qué te parece?',
    en: 'Why don’t you have a quick look and tell me what you think?',
    concepts: ['p.por-que-no', 'p.echar-un-vistazo', 'p.me-parece'],
    level: 'B1',
    topics: ['work', 'opinions'],
  },
  {
    id: 's.b114',
    es: 'Lo mejor es que se lo cuentes tú, y cuanto antes.',
    en: 'The best thing is for you to tell him yourself, and the sooner the better.',
    concepts: ['p.lo-mejor-es', 'g.subjunctive-intro', 'g.lo-nominal'],
    level: 'B1',
    topics: ['social', 'opinions'],
    note: 'cuanto antes — "as soon as possible" — is fixed and extremely common.',
  },
  {
    id: 's.b115',
    es: 'Estoy de acuerdo contigo, aunque no del todo.',
    en: 'I agree with you, though not entirely.',
    concepts: ['p.estoy-de-acuerdo', 'v.aunque'],
    level: 'B1',
    topics: ['opinions'],
  },
  {
    id: 's.b116',
    es: 'Me parece que no prestamos atención a lo importante.',
    en: 'It seems to me we’re not paying attention to what matters.',
    concepts: ['p.me-parece', 'p.prestar-atencion', 'g.lo-nominal'],
    level: 'B1',
    topics: ['opinions', 'work'],
  },
  {
    id: 's.b117',
    es: 'Aunque llueva, salimos igual; ya lo hemos decidido.',
    en: 'Even if it rains, we’re going anyway; we’ve already decided.',
    concepts: ['v.aunque', 'g.subjunctive-intro', 'v.llover'],
    level: 'B1',
    topics: ['plans', 'weather'],
    blanks: ['llueva'],
    note: 'aunque + subjunctive here because the rain is hypothetical. With aunque llueve it would already be raining.',
  },
  {
    id: 's.b118',
    es: 'Aunque es caro, sobre todo por la zona, merece la pena.',
    en: 'Although it’s expensive, mainly because of the area, it’s worth it.',
    concepts: ['v.aunque', 'v.sobre-todo', 'p.merece-la-pena'],
    level: 'B1',
    topics: ['home', 'opinions'],
    note: 'aunque + indicative: the price is an accepted fact, not a hypothesis.',
  },
  {
    id: 's.b119',
    es: 'Sobre todo, no te preocupes: no pasa nada.',
    en: 'Above all, don’t worry: it’s fine.',
    concepts: ['v.sobre-todo', 'p.no-pasa-nada', 'g.commands'],
    level: 'B1',
    topics: ['social', 'feelings'],
  },
  {
    id: 's.b120',
    es: 'Lo pasamos muy bien, aunque acabamos agotados.',
    en: 'We had a great time, though we ended up exhausted.',
    concepts: ['p.pasarlo-bien', 'v.aunque', 'g.preterite'],
    level: 'B1',
    topics: ['social', 'past'],
  },

  // --- Preterite across the persons, vosotros included ---------------------
  {
    id: 's.b121',
    es: '¿Vosotros fuisteis al concierto del sábado?',
    en: 'Did you lot go to Saturday’s concert?',
    concepts: ['g.preterite', 'v.ir', 'v.vosotros'],
    level: 'B1',
    topics: ['past', 'social'],
    note: 'fuisteis is both ir and ser in the preterite — context decides which.',
  },
  {
    id: 's.b122',
    es: 'Aquel verano fue el mejor de todos, y vosotros erais unos críos.',
    en: 'That summer was the best of all, and you were just kids.',
    concepts: ['g.preterite-imperfect', 'v.ser', 'v.vosotros'],
    level: 'B1',
    topics: ['past'],
  },
  {
    id: 's.b123',
    es: '¿Qué hicisteis al final el fin de semana?',
    en: 'What did you end up doing at the weekend?',
    concepts: ['g.preterite', 'v.hacer', 'v.vosotros'],
    level: 'B1',
    topics: ['past'],
  },
  {
    id: 's.b124',
    es: 'Tuvimos que esperar una hora y aun así no nos atendieron.',
    en: 'We had to wait an hour and still weren’t seen.',
    concepts: ['g.preterite', 'v.tener', 'p.tener-que'],
    level: 'B1',
    topics: ['past', 'health'],
  },
  {
    id: 's.b125',
    es: 'No pude avisarte porque no tenía cobertura.',
    en: 'I couldn’t let you know because I had no signal.',
    concepts: ['g.preterite-imperfect', 'v.poder', 'v.movil'],
    level: 'B1',
    topics: ['past', 'storytelling'],
  },
  {
    id: 's.b126',
    es: 'Quisimos entrar, pero ya habían cerrado la puerta.',
    en: 'We wanted to go in, but they’d already shut the door.',
    concepts: ['g.preterite', 'v.querer', 'g.pluperfect'],
    level: 'B1',
    topics: ['past', 'storytelling'],
  },
  {
    id: 's.b127',
    es: 'Le dije la verdad y no me creyó.',
    en: 'I told him the truth and he didn’t believe me.',
    concepts: ['g.preterite', 'v.decir', 'g.object-pronouns'],
    level: 'B1',
    topics: ['past', 'social'],
  },
  {
    id: 's.b128',
    es: 'Vi a tu hermana en el mercado y me dio un abrazo.',
    en: 'I saw your sister at the market and she gave me a hug.',
    concepts: ['g.preterite', 'v.ver', 'v.dar'],
    level: 'B1',
    topics: ['past', 'social'],
  },
  {
    id: 's.b129',
    es: 'Nunca supimos quién había pagado la cuenta.',
    en: 'We never found out who had paid the bill.',
    concepts: ['g.preterite', 'v.saber', 'g.pluperfect'],
    level: 'B1',
    topics: ['past', 'restaurant'],
    note: 'In the preterite saber means "found out", not "knew" — the tense changes the meaning.',
  },
  {
    id: 's.b130',
    es: 'Vinieron a las ocho y se fueron sin cenar.',
    en: 'They came at eight and left without having dinner.',
    concepts: ['g.preterite', 'v.venir', 'v.sin'],
    level: 'B1',
    topics: ['past', 'social'],
  },
  {
    id: 's.b131',
    es: 'Salimos tarde y por eso perdimos el último tren.',
    en: 'We left late and that’s why we missed the last train.',
    concepts: ['g.preterite', 'v.salir', 'v.por-eso'],
    level: 'B1',
    topics: ['past', 'transport'],
  },
  {
    id: 's.b132',
    es: '¿Dónde pusisteis las llaves? No las encuentro.',
    en: 'Where did you put the keys? I can’t find them.',
    concepts: ['g.preterite', 'v.poner', 'v.vosotros', 'v.llave'],
    level: 'B1',
    topics: ['home', 'past'],
  },
  {
    id: 's.b133',
    es: 'Estuvisteis muy amables con mis padres, gracias.',
    en: 'You were very kind to my parents, thank you.',
    concepts: ['g.preterite', 'v.estar', 'v.vosotros'],
    level: 'B1',
    topics: ['social', 'past'],
  },

  // --- Imperfect across the persons ----------------------------------------
  {
    id: 's.b134',
    es: 'Cuando erais pequeños, ¿veníais mucho por aquí?',
    en: 'When you were little, did you come here often?',
    concepts: ['g.imperfect', 'v.ser', 'v.venir', 'v.vosotros'],
    level: 'B1',
    topics: ['past', 'family'],
  },
  {
    id: 's.b135',
    es: 'Antes teníamos más tiempo y salíamos casi todas las noches.',
    en: 'We used to have more time and went out almost every night.',
    concepts: ['g.imperfect', 'v.tener', 'v.salir'],
    level: 'B1',
    topics: ['past', 'social'],
  },
  {
    id: 's.b136',
    es: 'Mis abuelos veían la tele con el volumen altísimo.',
    en: 'My grandparents used to watch TV at a deafening volume.',
    concepts: ['g.imperfect', 'v.ver', 'v.abuelo'],
    level: 'B1',
    topics: ['past', 'family'],
  },
  {
    id: 's.b137',
    es: 'No sabíamos que estabais aquí, nadie nos dijo nada.',
    en: 'We didn’t know you were here, nobody told us.',
    concepts: ['g.imperfect', 'v.saber', 'v.estar', 'v.vosotros'],
    level: 'B1',
    topics: ['past', 'social'],
  },
  {
    id: 's.b138',
    es: 'Siempre me daba consejos que yo no quería oír.',
    en: 'He was always giving me advice I didn’t want to hear.',
    concepts: ['g.imperfect', 'v.dar', 'v.querer'],
    level: 'B1',
    topics: ['past', 'family'],
  },
  {
    id: 's.b139',
    es: 'Decían que iban a arreglarlo, y ahí sigue.',
    en: 'They said they were going to fix it, and there it still is.',
    concepts: ['g.imperfect', 'v.decir', 'v.ir'],
    level: 'B1',
    topics: ['past', 'home'],
  },
  {
    id: 's.b140',
    es: 'De pequeña no podía dormir sin la luz encendida.',
    en: 'As a child I couldn’t sleep without the light on.',
    concepts: ['g.imperfect', 'v.poder', 'v.pequeno'],
    level: 'B1',
    topics: ['past'],
  },

  // --- Future across the persons -------------------------------------------
  {
    id: 's.b141',
    es: 'Mañana tendréis los resultados en el correo.',
    en: 'You’ll have the results in your inbox tomorrow.',
    concepts: ['g.future', 'v.tener', 'v.vosotros'],
    level: 'B1',
    topics: ['work', 'university'],
  },
  {
    id: 's.b142',
    es: 'Vendrán sobre las nueve, o eso han dicho.',
    en: 'They’ll come around nine, or so they’ve said.',
    concepts: ['g.future', 'v.venir', 'v.decir'],
    level: 'B1',
    topics: ['plans', 'social'],
  },
  {
    id: 's.b143',
    es: 'Saldremos temprano para evitar el tráfico.',
    en: 'We’ll leave early to avoid the traffic.',
    concepts: ['g.future', 'v.salir', 'g.por-para'],
    level: 'B1',
    topics: ['transport', 'plans'],
  },
  {
    id: 's.b144',
    es: '¿Podréis llegar a las siete o es muy justo?',
    en: 'Will you be able to get there by seven or is it too tight?',
    concepts: ['g.future', 'v.poder', 'v.vosotros'],
    level: 'B1',
    topics: ['plans'],
  },
  {
    id: 's.b145',
    es: 'Haré lo que pueda, pero no prometo nada.',
    en: 'I’ll do what I can, but I’m not promising anything.',
    concepts: ['g.future', 'v.hacer', 'g.subjunctive-relative'],
    level: 'B1',
    topics: ['work', 'social'],
  },

  // --- Past forms the corpus was missing entirely --------------------------
  {
    id: 's.b146',
    es: 'De pequeños hablábamos esloveno en casa y comíamos a las dos.',
    en: 'As children we spoke Slovenian at home and ate at two.',
    concepts: ['v.hablar', 'v.comer', 'g.imperfect'],
    level: 'B1',
    topics: ['past', 'family'],
    blanks: ['hablábamos', 'comíamos'],
  },
  {
    id: 's.b147',
    es: 'Ayer comimos en un sitio buenísimo, te lo recomiendo.',
    en: 'Yesterday we ate at a great place, I recommend it.',
    concepts: ['v.comer', 'g.preterite', 'p.te-recomiendo'],
    level: 'B1',
    topics: ['past', 'restaurant'],
  },
  {
    id: 's.b148',
    es: 'Trabajé cinco años en esa empresa antes de irme.',
    en: 'I worked five years at that company before leaving.',
    concepts: ['v.trabajar', 'g.preterite', 'v.empresa'],
    level: 'B1',
    topics: ['past', 'work'],
  },
  {
    id: 's.b149',
    es: '¿Dónde estudiaste la carrera, aquí o fuera?',
    en: 'Where did you do your degree, here or abroad?',
    concepts: ['v.estudiar', 'g.preterite', 'v.carrera'],
    level: 'B1',
    topics: ['past', 'university'],
  },
  {
    id: 's.b150',
    es: 'No bebimos nada, íbamos en coche.',
    en: 'We didn’t drink anything, we were driving.',
    concepts: ['v.beber', 'g.preterite', 'g.imperfect'],
    level: 'B1',
    topics: ['past', 'social'],
  },
  {
    id: 's.b151',
    es: 'Le escribí un correo larguísimo y no me contestó.',
    en: 'I wrote him a very long email and he didn’t reply.',
    concepts: ['v.escribir', 'g.preterite', 'g.object-pronouns'],
    level: 'B1',
    topics: ['past', 'work'],
  },
  {
    id: 's.b152',
    es: 'Leí el contrato entero antes de firmarlo, por si acaso.',
    en: 'I read the whole contract before signing it, just in case.',
    concepts: ['v.leer', 'g.preterite', 'v.antes'],
    level: 'B1',
    topics: ['past', 'work'],
  },
  {
    id: 's.b153',
    es: 'Cogimos el último metro por los pelos.',
    en: 'We caught the last metro by the skin of our teeth.',
    concepts: ['v.coger', 'g.preterite', 'v.metro'],
    level: 'B1',
    topics: ['past', 'transport'],
    note: 'por los pelos — "only just". Extremely common and completely fixed.',
  },
  {
    id: 's.b154',
    es: 'Condujo ella toda la vuelta porque yo estaba agotado.',
    en: 'She drove the whole way back because I was exhausted.',
    concepts: ['v.conducir', 'g.preterite', 'g.imperfect'],
    level: 'B1',
    topics: ['past', 'transport'],
    note: 'conduje, condujo — the -duc- verbs take a j in the preterite, with no accent.',
  },
  {
    id: 's.b155',
    es: 'Seguí sus indicaciones y acabé en el sitio equivocado.',
    en: 'I followed his directions and ended up in the wrong place.',
    concepts: ['v.seguir', 'g.preterite', 'v.girar'],
    level: 'B1',
    topics: ['past', 'directions'],
  },
  {
    id: 's.b156',
    es: 'Me levanté a las cinco y aun así llegué tarde.',
    en: 'I got up at five and still arrived late.',
    concepts: ['v.levantarse', 'g.preterite', 'v.tarde'],
    level: 'B1',
    topics: ['past', 'daily-routine'],
  },

  // --- The past, told to and about a group --------------------------------
  {
    id: 's.b157',
    es: '¿Qué comisteis en la boda? Nosotros comimos fatal.',
    en: 'What did you eat at the wedding? We ate terribly.',
    concepts: ['v.comer', 'g.preterite', 'v.vosotros'],
    level: 'B1',
    topics: ['past', 'food'],
  },
  {
    id: 's.b158',
    es: 'Vivimos allí tres años y luego nos mudamos al norte.',
    en: 'We lived there three years and then moved north.',
    concepts: ['v.vivir', 'g.preterite', 'v.nosotros'],
    level: 'B1',
    topics: ['past', 'home'],
  },
  {
    id: 's.b159',
    es: '¿Trabajasteis juntos en Madrid o os conocisteis después?',
    en: 'Did you work together in Madrid or did you meet later?',
    concepts: ['v.trabajar', 'v.conocer', 'g.preterite', 'v.vosotros'],
    level: 'B1',
    topics: ['past', 'work'],
  },
  {
    id: 's.b160',
    es: 'Estudiaron los dos la misma carrera y acabaron el mismo año.',
    en: 'They both did the same degree and finished the same year.',
    concepts: ['v.estudiar', 'g.preterite', 'v.carrera'],
    level: 'B1',
    topics: ['past', 'university'],
  },
  {
    id: 's.b161',
    es: 'Bebimos más de la cuenta y al día siguiente lo pagamos.',
    en: 'We drank more than we should have and paid for it the next day.',
    concepts: ['v.beber', 'v.pagar', 'g.preterite'],
    level: 'B1',
    topics: ['past', 'social'],
  },
  {
    id: 's.b162',
    es: '¿Viajasteis en agosto? Nosotros viajamos en julio y no había nadie.',
    en: 'Did you travel in August? We travelled in July and there was nobody around.',
    concepts: ['v.viajar', 'g.preterite', 'v.vosotros', 'v.julio'],
    level: 'B1',
    topics: ['past', 'travel'],
  },
  {
    id: 's.b163',
    es: '¿Cogisteis el AVE o fuisteis en coche?',
    en: 'Did you take the high-speed train or drive?',
    concepts: ['v.coger', 'g.preterite', 'v.vosotros'],
    level: 'B1',
    topics: ['past', 'transport'],
  },
  {
    id: 's.b164',
    es: '¿Comprasteis las entradas al final o se agotaron?',
    en: 'Did you get the tickets in the end or did they sell out?',
    concepts: ['v.comprar', 'g.preterite', 'v.entrada', 'v.vosotros'],
    level: 'B1',
    topics: ['past', 'shopping'],
  },
  {
    id: 's.b165',
    es: 'Escribieron una carta al director y no contestó nadie.',
    en: 'They wrote a letter to the editor and nobody replied.',
    concepts: ['v.escribir', 'g.preterite', 'g.negation'],
    level: 'B1',
    topics: ['past', 'opinions'],
  },
  {
    id: 's.b166',
    es: '¿Leísteis el correo que os mandé el jueves?',
    en: 'Did you read the email I sent you on Thursday?',
    concepts: ['v.leer', 'g.preterite', 'v.vosotros', 'v.jueves'],
    level: 'B1',
    topics: ['past', 'work'],
  },
  {
    id: 's.b167',
    es: 'Condujimos toda la noche y llegamos al amanecer.',
    en: 'We drove all night and arrived at dawn.',
    concepts: ['v.conducir', 'g.preterite', 'v.nosotros'],
    level: 'B1',
    topics: ['past', 'transport'],
  },
  {
    id: 's.b168',
    es: 'Seguimos las indicaciones y aun así nos perdimos dos veces.',
    en: 'We followed the directions and still got lost twice.',
    concepts: ['v.seguir', 'g.preterite', 'p.aun-asi'],
    level: 'B1',
    topics: ['past', 'directions'],
  },
  {
    id: 's.b169',
    es: '¿Os levantasteis muy temprano para coger el vuelo?',
    en: 'Did you get up very early to catch the flight?',
    concepts: ['v.levantarse', 'g.preterite', 'v.vosotros'],
    level: 'B1',
    topics: ['past', 'travel'],
  },
  {
    id: 's.b170',
    es: 'Pusieron la mesa entre todos y cenamos en el patio.',
    en: 'They laid the table between them and we ate in the courtyard.',
    concepts: ['v.poner', 'g.preterite', 'v.cena'],
    level: 'B1',
    topics: ['past', 'home'],
  },
  {
    id: 's.b171',
    es: '¿Qué trajisteis de comer? Nosotros trajimos vino.',
    en: 'What did you bring to eat? We brought wine.',
    concepts: ['v.traer', 'g.preterite', 'v.vosotros', 'v.vino'],
    level: 'B1',
    topics: ['past', 'social'],
  },
  {
    id: 's.b172',
    es: '¿Viste el partido? Yo lo vi entero y no me lo creo.',
    en: 'Did you see the match? I watched the whole thing and I still don’t believe it.',
    concepts: ['v.ver', 'g.preterite', 'v.tu'],
    level: 'B1',
    topics: ['past', 'hobbies'],
  },
  {
    id: 's.b173',
    es: 'Conocí a tu hermano el año pasado en una cena.',
    en: 'I met your brother last year at a dinner.',
    concepts: ['v.conocer', 'g.preterite', 'v.hermano'],
    level: 'B1',
    topics: ['past', 'social'],
  },

  // --- The imperfect, told about the group we used to be ------------------
  {
    id: 's.b174',
    es: 'Cuando vivíais en el pueblo, ¿comíais en casa de la abuela?',
    en: 'When you lived in the village, did you eat at your grandmother’s?',
    concepts: ['v.vivir', 'v.comer', 'g.imperfect', 'v.vosotros'],
    level: 'B1',
    topics: ['past', 'family'],
  },
  {
    id: 's.b175',
    es: 'Hablabas muy poco español entonces y ahora no paras.',
    en: 'You spoke very little Spanish back then and now you don’t stop.',
    concepts: ['v.hablar', 'g.imperfect', 'v.tu'],
    level: 'B1',
    topics: ['past', 'university'],
  },
  {
    id: 's.b176',
    es: 'Mis padres veían las noticias mientras cenaban, todos los días.',
    en: 'My parents watched the news while they had dinner, every day.',
    concepts: ['v.ver', 'g.imperfect', 'v.mientras'],
    level: 'B1',
    topics: ['past', 'family'],
  },
  {
    id: 's.b177',
    es: '¿Qué hacíais los domingos por la tarde cuando erais pequeños?',
    en: 'What did you use to do on Sunday afternoons when you were little?',
    concepts: ['v.hacer', 'g.imperfect', 'v.vosotros', 'v.domingo'],
    level: 'B1',
    topics: ['past', 'family'],
  },
  {
    id: 's.b178',
    es: 'Nos daban la paga los viernes y el lunes no quedaba nada.',
    en: 'They gave us pocket money on Fridays and by Monday there was nothing left.',
    concepts: ['v.dar', 'g.imperfect', 'v.viernes'],
    level: 'B1',
    topics: ['past', 'family'],
  },
  {
    id: 's.b179',
    es: 'De pequeña no comía nada verde, y mira ahora.',
    en: 'As a child I ate nothing green, and look at me now.',
    concepts: ['v.comer', 'g.imperfect', 'v.verde'],
    level: 'B1',
    topics: ['past', 'food'],
  },

  // --- The future and the conditional, both very thin --------------------
  {
    id: 's.b180',
    es: '¿Qué haréis en Navidad, os quedáis aquí?',
    en: 'What will you do at Christmas, are you staying here?',
    concepts: ['v.hacer', 'g.future', 'v.vosotros'],
    level: 'B1',
    topics: ['plans'],
  },
  {
    id: 's.b181',
    es: 'Harán lo que puedan, pero no te prometen nada.',
    en: 'They’ll do what they can, but they’re not promising anything.',
    concepts: ['v.hacer', 'g.future', 'g.subjunctive-relative'],
    level: 'B1',
    topics: ['work'],
  },
  {
    id: 's.b182',
    es: '¿Saldréis esta noche o lo dejamos para el sábado?',
    en: 'Are you going out tonight or shall we leave it for Saturday?',
    concepts: ['v.salir', 'g.future', 'v.vosotros'],
    level: 'B1',
    topics: ['plans', 'social'],
  },
  {
    id: 's.b183',
    es: 'Saldrán del aeropuerto sobre las diez, si no hay retraso.',
    en: 'They’ll leave the airport around ten, if there’s no delay.',
    concepts: ['v.salir', 'g.future', 'v.retraso'],
    level: 'B1',
    topics: ['travel'],
  },
  {
    id: 's.b184',
    es: 'Vosotros pondréis la música y nosotros nos encargamos del resto.',
    en: 'You’ll do the music and we’ll take care of the rest.',
    concepts: ['v.poner', 'g.future', 'v.vosotros'],
    level: 'B1',
    topics: ['social', 'plans'],
  },
  {
    id: 's.b185',
    es: 'Tendrás que decírselo tú, a mí no me va a escuchar.',
    en: 'You’ll have to tell him yourself, he won’t listen to me.',
    concepts: ['v.tener', 'g.future', 'v.tu', 'v.decir'],
    level: 'B1',
    topics: ['social'],
  },
  {
    id: 's.b186',
    es: 'Querríamos reservar para cuatro, si hay sitio.',
    en: 'We’d like to book for four, if there’s room.',
    concepts: ['v.querer', 'g.conditional', 'v.reservar'],
    level: 'B1',
    topics: ['restaurant'],
    register: 'formal',
  },
  {
    id: 's.b187',
    es: '¿Podríais echarme una mano un momento?',
    en: 'Could you give me a hand for a second?',
    concepts: ['v.poder', 'g.conditional', 'v.vosotros'],
    level: 'B1',
    topics: ['work', 'social'],
  },
  {
    id: 's.b188',
    es: 'Querrían quedarse más tiempo, pero tienen que volver el lunes.',
    en: 'They’d like to stay longer, but they have to go back on Monday.',
    concepts: ['v.querer', 'g.conditional', 'p.tener-que'],
    level: 'B1',
    topics: ['travel', 'social'],
  },
  {
    id: 's.b189',
    es: '¿Querrías venir con nosotros o prefieres quedarte?',
    en: 'Would you like to come with us or would you rather stay?',
    concepts: ['v.querer', 'g.conditional', 'v.tu', 'v.preferir'],
    level: 'B1',
    topics: ['plans', 'social'],
  },
  {
    id: 's.b190',
    es: 'Nosotros no podríamos vivir sin coche aquí.',
    en: 'We couldn’t live without a car here.',
    concepts: ['v.poder', 'g.conditional', 'v.coche'],
    level: 'B1',
    topics: ['transport', 'opinions'],
  },

  // --- Emotions with a cause, and emotions that change --------------------
  //
  // At A2 a feeling is a state: "estoy agobiado". At B1 it has a history and a
  // reason attached, and often it has moved since. That subordination is the
  // level, not the adjective.
  {
    id: 's.b191',
    es: 'Al principio estaba agobiada, pero desde que cambié de equipo se me ha pasado.',
    en: 'At first I was overwhelmed, but since I changed teams it’s worn off.',
    concepts: ['v.agobiado', 'g.preterite-imperfect', 'g.present-perfect'],
    level: 'B1',
    topics: ['feelings', 'work'],
    note: 'pasársele a uno algo — for a feeling to wear off. The se marks that it happened *to* you.',
  },
  {
    id: 's.b192',
    es: 'Estoy orgulloso de él, sobre todo porque nadie le ayudó.',
    en: 'I’m proud of him, above all because nobody helped him.',
    concepts: ['v.orgulloso', 'v.sobre-todo', 'v.porque'],
    level: 'B1',
    topics: ['feelings', 'family'],
  },
  {
    id: 's.b193',
    es: 'Me quedé decepcionada, no por el resultado sino por cómo lo contaron.',
    en: 'I was left disappointed, not by the result but by how they told it.',
    concepts: ['v.decepcionado', 'g.preterite'],
    level: 'B1',
    topics: ['feelings', 'opinions'],
    note: 'no por X sino por Y — corrects the assumed cause, which is a very B1 move.',
  },
  {
    id: 's.b194',
    es: 'Antes me daba miedo hablar en público; ahora me da pereza, que es distinto.',
    en: 'Public speaking used to scare me; now it just bores me, which is different.',
    concepts: ['p.me-da-miedo', 'g.imperfect', 'v.hablar'],
    level: 'B1',
    topics: ['feelings', 'work'],
  },
  {
    id: 's.b195',
    es: 'Me da pena que se vaya, aunque entiendo perfectamente por qué lo hace.',
    en: 'It saddens me that he’s leaving, though I completely understand why.',
    concepts: ['p.me-da-pena', 'v.aunque', 'g.subjunctive-intro'],
    level: 'B1',
    topics: ['feelings', 'social'],
  },
  {
    id: 's.b196',
    es: 'Lo que me da rabia no es el error, es que nadie avisara.',
    en: 'What makes me angry isn’t the mistake, it’s that nobody said anything.',
    concepts: ['p.me-da-rabia', 'g.relatives', 'g.subjunctive-intro'],
    level: 'B1',
    topics: ['feelings', 'work'],
  },
  {
    id: 's.b197',
    es: 'Estoy harta de discutir lo mismo cada semana, así que esta vez me callo.',
    en: 'I’m fed up arguing about the same thing every week, so this time I’m staying quiet.',
    concepts: ['v.harto', 'v.semana'],
    level: 'B1',
    topics: ['feelings', 'work'],
  },
  {
    id: 's.b198',
    es: 'Estoy hasta las narices del ruido, y eso que llevo diez años aquí.',
    en: 'I’ve had it up to here with the noise, and that’s after ten years here.',
    concepts: ['p.estoy-hasta', 'v.llevar'],
    level: 'B1',
    topics: ['feelings', 'home'],
    register: 'colloquial',
    note: 'y eso que — "and that’s despite". Concedes something that should have made it better.',
  },
  {
    id: 's.b199',
    es: 'Me preocupa que no diga nada, porque cuando calla es cuando está peor.',
    en: 'It worries me that he says nothing, because when he goes quiet is when he’s worst.',
    concepts: ['p.me-preocupa', 'g.subjunctive-intro', 'v.peor'],
    level: 'B1',
    topics: ['feelings', 'family'],
  },
  {
    id: 's.b200',
    es: 'Estaba preocupado por el examen, pero en cuanto empecé se me olvidó todo lo demás.',
    en: 'I was worried about the exam, but the moment I started I forgot everything else.',
    concepts: ['v.preocupado', 'p.se-me-ha-olvidado', 'g.preterite-imperfect'],
    level: 'B1',
    topics: ['feelings', 'university'],
  },
  {
    id: 's.b201',
    es: 'Echo de menos el pueblo, aunque cuando vivía allí me quejaba todo el día.',
    en: 'I miss the village, though when I lived there I complained all day.',
    concepts: ['p.echar-de-menos', 'v.quejarse', 'g.imperfect'],
    level: 'B1',
    topics: ['feelings', 'past'],
  },

  // --- Work and study: experience, cause, consequence ---------------------
  {
    id: 's.b202',
    es: 'Suspendí en febrero porque no presté atención en todo el cuatrimestre.',
    en: 'I failed in February because I paid no attention all term.',
    concepts: ['v.suspender', 'p.prestar-atencion', 'g.preterite'],
    level: 'B1',
    topics: ['university', 'past'],
  },
  {
    id: 's.b203',
    es: 'La asignatura no es difícil; lo difícil es aprobarla con este profesor.',
    en: 'The subject isn’t hard; what’s hard is passing it with this teacher.',
    concepts: ['v.asignatura', 'v.aprobar', 'g.lo-nominal'],
    level: 'B1',
    topics: ['university', 'opinions'],
  },
  {
    id: 's.b204',
    es: 'Llevo meses buscando trabajo y he echado el currículum hasta en sitios que no me gustan.',
    en: 'I’ve spent months job-hunting and I’ve put my CV in even at places I don’t like.',
    concepts: ['p.buscar-trabajo', 'p.echar-un-curriculum', 'v.llevar'],
    level: 'B1',
    topics: ['work'],
  },
  {
    id: 's.b205',
    es: 'La empresa paga bien, pero el sueldo no compensa el horario que tienen.',
    en: 'The company pays well, but the salary doesn’t make up for the hours they keep.',
    concepts: ['v.empresa', 'v.sueldo', 'v.horario'],
    level: 'B1',
    topics: ['work', 'opinions'],
  },
  {
    id: 's.b206',
    es: 'Cambié de empresa por el sueldo y me arrepentí a los tres meses.',
    en: 'I changed company for the money and regretted it three months later.',
    concepts: ['v.empresa', 'v.sueldo', 'g.preterite'],
    level: 'B1',
    topics: ['work', 'past'],
  },
  {
    id: 's.b207',
    es: 'Tomamos la decisión entre todos, así que ahora nadie puede quejarse.',
    en: 'We took the decision together, so now nobody can complain.',
    concepts: ['p.tomar-una-decision', 'v.quejarse'],
    level: 'B1',
    topics: ['work', 'opinions'],
  },
  {
    id: 's.b208',
    es: '¿Le has echado un vistazo al informe? Me parece que falta la mitad.',
    en: 'Have you had a look at the report? I think half of it is missing.',
    concepts: ['p.echar-un-vistazo', 'p.me-parece', 'g.present-perfect'],
    level: 'B1',
    topics: ['work'],
  },

  // --- Opinion, justified, and advice with a reason -----------------------
  {
    id: 's.b209',
    es: 'Estoy de acuerdo contigo en lo del horario, en lo demás no tanto.',
    en: 'I agree with you about the hours, about the rest not so much.',
    concepts: ['p.estoy-de-acuerdo', 'g.lo-nominal', 'v.horario'],
    level: 'B1',
    topics: ['opinions', 'work'],
  },
  {
    id: 's.b210',
    es: 'Me parece que se equivocan, aunque entiendo de dónde viene la idea.',
    en: 'I think they’re wrong, though I understand where the idea comes from.',
    concepts: ['p.me-parece', 'v.aunque', 'v.venir'],
    level: 'B1',
    topics: ['opinions'],
  },
  {
    id: 's.b211',
    es: 'Lo mejor es que lo hables con él antes de que se entere por otro lado.',
    en: 'The best thing is for you to talk to him before he hears it from someone else.',
    concepts: ['p.lo-mejor-es', 'g.subjunctive-intro', 'v.hablar'],
    level: 'B1',
    topics: ['opinions', 'social'],
  },
  {
    id: 's.b212',
    es: '¿Por qué no se lo dices tú? A ti te va a escuchar.',
    en: 'Why don’t you tell him yourself? He’ll listen to you.',
    concepts: ['p.por-que-no', 'g.object-pronouns', 'g.emphasis'],
    level: 'B1',
    topics: ['social', 'opinions'],
  },
  {
    id: 's.b213',
    es: 'Deberías descansar este fin de semana; llevas un mes sin parar.',
    en: 'You should rest this weekend; you’ve been going non-stop for a month.',
    concepts: ['p.deberias', 'v.llevar', 'v.fin-de-semana'],
    level: 'B1',
    topics: ['opinions', 'feelings'],
  },
  {
    id: 's.b214',
    es: 'A mí me da igual dónde cenemos, pero que sea cerca.',
    en: 'I don’t mind where we have dinner, as long as it’s nearby.',
    concepts: ['p.da-igual', 'g.subjunctive-relative', 'v.cerca'],
    level: 'B1',
    topics: ['plans', 'opinions'],
    note: 'que sea… on its own is an elliptical condition: "just as long as it is".',
  },
  {
    id: 's.b215',
    es: 'Por lo visto lo sabían todos menos nosotros, que es lo que más me molesta.',
    en: 'Apparently everyone knew except us, which is what annoys me most.',
    concepts: ['p.valer-la-pena', 'g.relatives', 'g.imperfect'],
    level: 'B1',
    topics: ['opinions', 'social'],
  },
  {
    id: 's.b216',
    es: 'Merece la pena ir en tren, sobre todo si vas con tiempo.',
    en: 'It’s worth going by train, especially if you’re not in a rush.',
    concepts: ['p.merece-la-pena', 'v.sobre-todo', 'v.tren'],
    level: 'B1',
    topics: ['travel', 'opinions'],
  },

  // --- Connectors doing real work across two clauses ----------------------
  {
    id: 's.b217',
    es: 'El piso está bien y además es barato; sin embargo, está lejísimos.',
    en: 'The flat is fine and what’s more it’s cheap; however, it’s miles away.',
    concepts: ['v.ademas', 'v.sin-embargo', 'v.piso'],
    level: 'B1',
    topics: ['home', 'opinions'],
    note: 'además adds on the same side; sin embargo turns the argument round.',
  },
  {
    id: 's.b218',
    es: 'Mi hermano estudió Derecho; yo, en cambio, no duré ni un año.',
    en: 'My brother studied law; I, on the other hand, didn’t last a year.',
    concepts: ['v.en-cambio', 'v.estudiar', 'g.preterite'],
    level: 'B1',
    topics: ['university', 'family'],
  },
  {
    id: 's.b219',
    es: 'No contestó al correo, o sea, que la respuesta ya la tienes.',
    en: 'He didn’t reply to the email — which means you already have your answer.',
    concepts: ['v.o-sea', 'g.object-pronouns'],
    level: 'B1',
    topics: ['work', 'social'],
    register: 'colloquial',
  },
  {
    id: 's.b220',
    es: 'Mientras vosotros preparabais la cena, nosotros recogíamos el salón.',
    en: 'While you were making dinner, we were tidying the living room.',
    concepts: ['v.mientras', 'g.imperfect', 'v.vosotros'],
    level: 'B1',
    topics: ['home', 'past'],
  },
  {
    id: 's.b221',
    es: 'Todo iba bien y de repente se cortó la luz en todo el barrio.',
    en: 'Everything was going fine and suddenly the power went out across the whole area.',
    concepts: ['v.de-repente', 'g.preterite-imperfect'],
    level: 'B1',
    topics: ['storytelling', 'home'],
  },

  // --- Complaints and problems, from report to resolution -----------------
  {
    id: 's.b222',
    es: 'Hay un problema con la caldera: no funciona desde el viernes y hace un frío horrible.',
    en: 'There’s a problem with the boiler: it hasn’t worked since Friday and it’s freezing.',
    concepts: ['p.hay-un-problema', 'p.no-funciona', 'v.viernes'],
    level: 'B1',
    topics: ['home'],
  },
  {
    id: 's.b223',
    es: 'El ascensor lleva averiado tres semanas y vivo en un séptimo.',
    en: 'The lift has been out of order for three weeks and I live on the seventh floor.',
    concepts: ['v.averiado', 'v.llevar', 'v.vivir'],
    level: 'B1',
    topics: ['home'],
  },
  {
    id: 's.b224',
    es: 'Me han cobrado de más otra vez, y ya van tres meses seguidos.',
    en: 'They’ve overcharged me again, and that’s three months running now.',
    concepts: ['p.me-han-cobrado', 'g.present-perfect'],
    level: 'B1',
    topics: ['shopping'],
  },
  {
    id: 's.b225',
    es: 'Querría devolver esto: lo compré el martes y ya se ha roto.',
    en: 'I’d like to return this: I bought it on Tuesday and it’s already broken.',
    concepts: ['p.querria-devolver', 'v.comprar', 'g.present-perfect'],
    level: 'B1',
    topics: ['shopping'],
    register: 'formal',
  },
  {
    id: 's.b226',
    es: 'Lo siento mucho, fue culpa mía y no volverá a pasar.',
    en: 'I’m really sorry, it was my fault and it won’t happen again.',
    concepts: ['p.lo-siento-mucho', 'g.future', 'g.preterite'],
    level: 'B1',
    topics: ['social', 'work'],
  },
  {
    id: 's.b227',
    es: '—Perdona el retraso. —No pasa nada, acabamos de empezar.',
    en: '“Sorry I’m late.” “No worries, we’ve only just started.”',
    concepts: ['p.no-pasa-nada', 'v.retraso'],
    level: 'B1',
    topics: ['social'],
    note: 'acabar de + infinitivo — "to have just done". Nothing to do with finishing.',
  },
  {
    id: 's.b228',
    es: 'Se me ha olvidado el cargador en casa, ¿me dejáis el vuestro un momento?',
    en: 'I’ve left my charger at home — can you lend me yours for a moment?',
    concepts: ['p.se-me-ha-olvidado', 'v.vosotros', 'v.vuestro'],
    level: 'B1',
    topics: ['daily-routine', 'social'],
  },

  // --- Hypothetical plans, in scenarios rather than as tense drill --------
  {
    id: 's.b229',
    es: 'Si me dieran el puesto, tendría que mudarme, y eso me da bastante pereza.',
    en: 'If they gave me the job, I’d have to move, and I really can’t face that.',
    concepts: ['g.si-hypothetical', 'g.conditional', 'v.tener'],
    level: 'B1',
    topics: ['work', 'feelings'],
  },
  {
    id: 's.b230',
    es: '¿Qué haríais vosotros en mi lugar? Porque yo ya no sé.',
    en: 'What would you do in my position? Because I’ve run out of ideas.',
    concepts: ['g.conditional', 'v.hacer', 'v.vosotros'],
    level: 'B1',
    topics: ['opinions', 'social'],
  },
  {
    id: 's.b231',
    es: 'Yo que tú no diría nada todavía; esperaría a ver qué pasa el lunes.',
    en: 'If I were you I wouldn’t say anything yet; I’d wait and see what happens on Monday.',
    concepts: ['p.yo-que-tu', 'g.conditional', 'v.decir'],
    level: 'B1',
    topics: ['opinions', 'work'],
  },
  {
    id: 's.b232',
    es: 'El año que viene viviremos más cerca del centro, o eso dice ella.',
    en: 'Next year we’ll live closer to the centre, or so she says.',
    concepts: ['g.future', 'v.vivir', 'v.decir'],
    level: 'B1',
    topics: ['plans', 'home'],
  },
  {
    id: 's.b233',
    es: 'Cuando terminéis el curso, ¿qué haréis, seguiréis estudiando?',
    en: 'When you finish the course, what will you do — will you carry on studying?',
    concepts: ['g.future', 'v.vosotros', 'v.seguir'],
    level: 'B1',
    topics: ['university', 'plans'],
    blanks: ['terminéis'],
    note: 'cuando about the future takes the subjunctive; the main clause keeps the future.',
  },
  {
    id: 's.b234',
    es: 'Tendremos que darnos prisa si queremos coger el de las ocho.',
    en: 'We’ll have to hurry if we want to catch the eight o’clock one.',
    concepts: ['g.future', 'p.darse-prisa', 'v.coger'],
    level: 'B1',
    topics: ['transport', 'plans'],
  },
  {
    id: 's.b235',
    es: 'Me gustaría cambiar de trabajo, pero con la hipoteca no me lo puedo permitir.',
    en: 'I’d like to change jobs, but with the mortgage I can’t afford to.',
    concepts: ['g.conditional', 'v.trabajo', 'v.poder'],
    level: 'B1',
    topics: ['work', 'opinions'],
  },
  {
    id: 's.b236',
    es: 'Podríamos quedar el jueves, aunque tendría que salir antes del trabajo.',
    en: 'We could meet on Thursday, though I’d have to leave work early.',
    concepts: ['g.conditional', 'v.quedar', 'v.aunque'],
    level: 'B1',
    topics: ['plans', 'work'],
  },

  // --- The colloquial register, in dialogue where it belongs --------------
  {
    id: 's.b237',
    es: '—¿Y ahora qué hacemos? —A ver, tranquilos, que algo se nos ocurrirá.',
    en: '“So what do we do now?” “Right, everyone calm down, we’ll think of something.”',
    concepts: ['p.a-ver', 'g.future'],
    level: 'B1',
    topics: ['social', 'slang'],
    register: 'colloquial',
  },
  {
    id: 's.b238',
    es: 'Me dijo en plan «ya hablamos» y llevo dos semanas esperando.',
    en: 'He was like “we’ll talk” and I’ve been waiting two weeks.',
    concepts: ['p.en-plan', 'v.llevar', 'g.reported-speech'],
    level: 'B1',
    topics: ['slang', 'social'],
    register: 'colloquial',
  },
  {
    id: 's.b239',
    es: '—¿Sabéis a qué hora empieza? —Ni idea, preguntad en la puerta.',
    en: '“Do you know what time it starts?” “No idea, ask at the door.”',
    concepts: ['p.ni-idea', 'v.vosotros', 'g.commands'],
    level: 'B1',
    topics: ['slang', 'social'],
    register: 'colloquial',
  },
  {
    id: 's.b240',
    es: '¡Qué fuerte lo que me acabas de contar! ¿Y él qué dijo?',
    en: 'That’s unbelievable, what you’ve just told me! And what did he say?',
    concepts: ['p.que-fuerte', 'v.decir', 'g.preterite'],
    level: 'B1',
    topics: ['slang', 'storytelling'],
    register: 'colloquial',
  },
  {
    id: 's.b241',
    es: 'Qué guay que os hayáis animado al final, lo vamos a pasar genial.',
    en: 'Great that you’ve decided to come after all, we’re going to have a brilliant time.',
    concepts: ['p.que-guay', 'p.pasarlo-bien', 'v.vosotros'],
    level: 'B1',
    topics: ['social', 'slang'],
    register: 'colloquial',
  },
  {
    id: 's.b242',
    es: 'Qué rollo tener que madrugar un sábado, con lo bien que se duerme.',
    en: 'What a drag having to get up early on a Saturday, when sleeping in is so good.',
    concepts: ['p.que-rollo', 'v.sabado', 'g.lo-nominal'],
    level: 'B1',
    topics: ['slang', 'daily-routine'],
    register: 'colloquial',
  },
  {
    id: 's.b243',
    es: 'A mi hermana le mola mucho ese grupo, a mí en cambio no me dice nada.',
    en: 'My sister really likes that band; it does nothing for me, though.',
    concepts: ['v.molar', 'v.en-cambio', 'v.hermano'],
    level: 'B1',
    topics: ['slang', 'hobbies'],
    register: 'colloquial',
  },
  {
    id: 's.b244',
    es: 'Tío, date prisa, que llevamos media hora esperándote.',
    en: 'Mate, hurry up, we’ve been waiting half an hour for you.',
    concepts: ['v.tio', 'p.darse-prisa', 'v.llevar'],
    level: 'B1',
    topics: ['slang', 'social'],
    register: 'colloquial',
  },
  {
    id: 's.b245',
    es: 'Hemos quedado a las nueve, pero conociéndolo llegará a las nueve y media.',
    en: 'We’ve arranged nine, but knowing him he’ll turn up at half past.',
    concepts: ['p.hemos-quedado', 'g.future', 'v.conocer'],
    level: 'B1',
    topics: ['plans', 'social'],
  },
  {
    id: 's.b246',
    es: 'Quedamos delante del cine y de ahí ya vemos qué hacemos.',
    en: 'Let’s meet in front of the cinema and take it from there.',
    concepts: ['p.quedamos-en', 'v.ver', 'v.hacer'],
    level: 'B1',
    topics: ['plans', 'social'],
  },
  {
    id: 's.b247',
    es: 'Tengo muchas ganas de que llegue el viernes, ha sido una semana durísima.',
    en: 'I’m really looking forward to Friday, it’s been a brutal week.',
    concepts: ['p.tener-ganas', 'g.subjunctive-intro', 'g.present-perfect'],
    level: 'B1',
    topics: ['feelings', 'work'],
  },

  // --- The future and the conditional, in the situations that produce them ---
  // In Spain the future tense is used to *guess about now* at least as often as
  // to talk about later, and the conditional does politeness, advice, regret and
  // reported speech. These are written as those four jobs, not as a paradigm.
  {
    id: 's.b248',
    es: '¿Qué hora es? — No sé, serán las diez y pico.',
    en: "What time is it? — I don't know, it must be gone ten.",
    concepts: ['v.ser', 'g.future', 'v.hora'],
    level: 'B1',
    topics: ['time', 'social'],
    blanks: ['serán'],
    note: 'The future guessing about the present. "Serán las diez" is a guess; "son las diez" is the time.',
  },
  {
    id: 's.b249',
    es: 'No contesta. Será que está reunido.',
    en: "He's not answering. He must be in a meeting.",
    concepts: ['v.ser', 'g.future', 'v.reunion'],
    level: 'B1',
    topics: ['work'],
    note: 'Será que… = it must be that… A whole guess in two words.',
  },
  {
    id: 's.b250',
    es: 'El año que viene seré yo quien organice la cena, ya me toca.',
    en: "Next year I'll be the one organising the dinner, it's my turn.",
    concepts: ['v.ser', 'g.future', 'v.ano-time', 'v.cena'],
    level: 'B1',
    topics: ['plans', 'social'],
  },
  {
    id: 's.b251',
    es: 'Con este tráfico seremos los últimos en llegar.',
    en: "With this traffic we'll be the last to arrive.",
    concepts: ['v.ser', 'g.future', 'v.coche'],
    level: 'B1',
    topics: ['transport', 'plans'],
  },
  {
    id: 's.b252',
    es: 'Vosotros seréis los primeros en probarlo, así que decid la verdad.',
    en: "You lot will be the first to try it, so tell me honestly.",
    concepts: ['v.ser', 'g.future', 'v.vosotros', 'v.primero'],
    level: 'B1',
    topics: ['social', 'opinions'],
  },
  {
    id: 's.b253',
    es: '¿Serás capaz de callarte por una vez?',
    en: 'Will you manage to keep quiet for once?',
    concepts: ['v.ser', 'g.future', 'v.tu'],
    level: 'B1',
    topics: ['social', 'slang'],
    register: 'colloquial',
  },
  {
    id: 's.b254',
    es: 'Esos serán los vecinos nuevos, los he visto bajando cajas.',
    en: "Those must be the new neighbours, I've seen them carrying boxes down.",
    concepts: ['v.ser', 'g.future', 'g.present-perfect', 'v.piso'],
    level: 'B1',
    topics: ['home', 'people'],
  },
  {
    id: 's.b255',
    es: 'Iré en tren, que en coche con obras es una tortura.',
    en: "I'll go by train — by car with the roadworks it's torture.",
    concepts: ['v.ir', 'g.future', 'v.tren', 'v.coche'],
    level: 'B1',
    topics: ['transport', 'plans'],
    blanks: ['Iré'],
  },
  {
    id: 's.b256',
    es: '¿Irás a la boda o te la vas a saltar?',
    en: 'Are you going to the wedding or are you skipping it?',
    concepts: ['v.ir', 'g.future', 'v.tu'],
    level: 'B1',
    topics: ['social', 'plans'],
  },
  {
    id: 's.b257',
    es: 'Iremos andando, que está aquí al lado.',
    en: "We'll walk, it's just here.",
    concepts: ['v.ir', 'g.future', 'v.andar', 'v.al-lado'],
    level: 'B1',
    topics: ['directions', 'plans'],
  },
  {
    id: 's.b258',
    es: '¿Iréis vosotros al concierto o os quedáis en casa?',
    en: 'Are you lot going to the concert or staying in?',
    concepts: ['v.ir', 'g.future', 'v.vosotros', 'v.casa'],
    level: 'B1',
    topics: ['plans', 'social'],
  },
  {
    id: 's.b259',
    es: 'Irán directos al hotel, llegan muy tarde.',
    en: "They'll go straight to the hotel, they arrive very late.",
    concepts: ['v.ir', 'g.future', 'v.hotel', 'v.tarde'],
    level: 'B1',
    topics: ['travel'],
  },
  {
    id: 's.b260',
    es: 'Ya lo sabrás cuando te llegue la carta.',
    en: "You'll find out when the letter arrives.",
    concepts: ['v.saber', 'g.future', 'v.ya', 'g.subjunctive-intro'],
    level: 'B1',
    topics: ['plans'],
    blanks: ['sabrás'],
  },
  {
    id: 's.b261',
    es: 'No sabré la nota hasta el viernes y estoy que no vivo.',
    en: "I won't know the mark until Friday and I'm on edge.",
    concepts: ['v.saber', 'g.future', 'v.viernes', 'v.estudiar'],
    level: 'B1',
    topics: ['university', 'feelings'],
  },
  {
    id: 's.b262',
    es: 'Pregunta en recepción, ellos sabrán si queda alguna habitación.',
    en: "Ask at reception, they'll know if there's a room left.",
    concepts: ['v.saber', 'g.future', 'v.quedar', 'v.hotel'],
    level: 'B1',
    topics: ['travel'],
  },
  {
    id: 's.b263',
    es: 'Nadie sabrá que has sido tú si no lo cuentas.',
    en: "Nobody will know it was you if you don't tell them.",
    concepts: ['v.saber', 'g.future', 'g.present-perfect', 'g.negation'],
    level: 'B1',
    topics: ['social'],
  },
  {
    id: 's.b264',
    es: 'Vosotros sabréis, pero yo no lo haría.',
    en: "You know best, but I wouldn't do it.",
    concepts: ['v.saber', 'g.future', 'v.vosotros', 'g.conditional'],
    level: 'B1',
    topics: ['opinions', 'social'],
    note: 'Tú sabrás / vosotros sabréis = "it’s your call" — polite disagreement, and pure future-as-speculation.',
  },
  {
    id: 's.b265',
    es: 'No querrá venir, siempre pone la misma excusa.',
    en: "He probably doesn't want to come, he always makes the same excuse.",
    concepts: ['v.querer', 'g.future', 'v.venir', 'v.poner'],
    level: 'B1',
    topics: ['social'],
    note: 'Another guess, not a plan: no querrá = "he mustn’t want to".',
  },
  {
    id: 's.b266',
    es: 'Cuando lo veas terminado, querrás uno igual.',
    en: "When you see it finished, you'll want one just like it.",
    concepts: ['v.querer', 'g.future', 'g.subjunctive-intro', 'v.ver'],
    level: 'B1',
    topics: ['opinions'],
  },
  {
    id: 's.b267',
    es: 'Querrán quedarse a cenar, así que compra algo de más.',
    en: "They'll want to stay for dinner, so buy a bit extra.",
    concepts: ['v.querer', 'g.future', 'v.cena', 'v.comprar'],
    level: 'B1',
    topics: ['food', 'social'],
  },
  {
    id: 's.b268',
    es: 'Podré llegar sobre las siete, pero no me esperéis para empezar.',
    en: "I'll be able to get there around seven, but don't wait for me to start.",
    concepts: ['v.poder', 'g.future', 'v.vosotros', 'v.siete'],
    level: 'B1',
    topics: ['plans', 'social'],
  },
  {
    id: 's.b269',
    es: 'Con este ruido no podrás concentrarte, vámonos a la biblioteca.',
    en: "You won't be able to concentrate with this noise, let's go to the library.",
    concepts: ['v.poder', 'g.future', 'v.tu', 'v.universidad'],
    level: 'B1',
    topics: ['university'],
  },
  {
    id: 's.b270',
    es: 'No sabría decirte, la verdad; pregúntale a ella.',
    en: "I honestly couldn't tell you; ask her.",
    concepts: ['v.saber', 'g.conditional', 'g.negation'],
    level: 'B1',
    topics: ['social', 'opinions'],
    blanks: ['sabría'],
    note: 'No sabría decirte is the standard polite way of saying "no idea" without sounding rude.',
  },
  {
    id: 's.b271',
    es: '¿Tú sabrías arreglar esto o llamamos a alguien?',
    en: 'Would you know how to fix this or shall we call someone?',
    concepts: ['v.saber', 'g.conditional', 'v.tu', 'v.casa'],
    level: 'B1',
    topics: ['home'],
  },
  {
    id: 's.b272',
    es: 'Nadie sabría explicarlo mejor que él.',
    en: 'Nobody could explain it better than him.',
    concepts: ['v.saber', 'g.conditional', 'v.mejor', 'g.comparisons'],
    level: 'B1',
    topics: ['opinions', 'people'],
  },
  {
    id: 's.b273',
    es: 'Estaría bien quedar antes y tomar algo tranquilamente.',
    en: 'It would be nice to meet up earlier and have a drink in peace.',
    concepts: ['v.estar', 'g.conditional', 'p.quedamos-en', 'v.tomar'],
    level: 'B1',
    topics: ['plans', 'social'],
    blanks: ['Estaría'],
  },
  {
    id: 's.b274',
    es: 'A esa hora ya estarían durmiendo, por eso no cogieron el teléfono.',
    en: "They'd have been asleep by then, that's why they didn't pick up.",
    concepts: ['v.estar', 'g.conditional', 'v.coger', 'v.movil'],
    level: 'B1',
    topics: ['past', 'social'],
    note: 'The conditional guessing about the *past*, exactly as the future guesses about the present.',
  },
  {
    id: 's.b275',
    es: 'Yo no estaría tan seguro, todavía falta la respuesta del banco.',
    en: "I wouldn't be so sure, the bank still hasn't replied.",
    concepts: ['v.estar', 'g.conditional', 'v.todavia'],
    level: 'B1',
    topics: ['work', 'opinions'],
  },
  {
    id: 's.b276',
    es: '¿Estaríais dispuestos a cambiar la fecha si hiciera falta?',
    en: 'Would you lot be willing to change the date if it were necessary?',
    concepts: ['v.estar', 'g.conditional', 'v.vosotros', 'v.sabado'],
    level: 'B1',
    topics: ['plans', 'work'],
  },
  {
    id: 's.b277',
    es: 'Saldría más barato en tren, pero tardaríamos el doble.',
    en: "It'd work out cheaper by train, but it'd take us twice as long.",
    concepts: ['v.salir', 'g.conditional', 'v.barato', 'v.tren'],
    level: 'B1',
    topics: ['travel', 'transport'],
    blanks: ['Saldría'],
    note: 'salir + adjective = to work out (cheap, expensive, well). Nothing to do with leaving.',
  },
  {
    id: 's.b278',
    es: 'Yo saldría ya, que a esta hora se pone imposible.',
    en: "I'd leave now, it gets impossible at this hour.",
    concepts: ['v.salir', 'g.conditional', 'v.ya', 'v.poner'],
    level: 'B1',
    topics: ['transport', 'plans'],
  },
  {
    id: 's.b279',
    es: 'Dijeron que saldrían del aeropuerto sobre las nueve.',
    en: "They said they'd leave the airport around nine.",
    concepts: ['v.salir', 'g.conditional', 'v.decir', 'v.nueve'],
    level: 'B1',
    topics: ['travel', 'past'],
    note: 'Reported speech pushes a future back into the conditional: saldrán → dijeron que saldrían.',
  },
  {
    id: 's.b280',
    es: 'Yo le pondría un poco más de sal, está bastante soso.',
    en: "I'd put a bit more salt in it, it's fairly bland.",
    concepts: ['v.poner', 'g.conditional', 'v.bastante'],
    level: 'B1',
    topics: ['food', 'opinions'],
    blanks: ['pondría'],
  },
  {
    id: 's.b281',
    es: '¿Dónde pondrías tú el sofá, contra la ventana o al fondo?',
    en: 'Where would you put the sofa, against the window or at the back?',
    concepts: ['v.poner', 'g.conditional', 'v.tu', 'v.casa'],
    level: 'B1',
    topics: ['home'],
  },
  {
    id: 's.b282',
    es: 'Nosotros pondríamos la reunión el martes, si a vosotros os viene bien.',
    en: "We'd put the meeting on Tuesday, if that works for you lot.",
    concepts: ['v.poner', 'g.conditional', 'v.reunion', 'v.martes'],
    level: 'B1',
    topics: ['work', 'plans'],
  },
  {
    id: 's.b283',
    es: 'Vendría encantada, pero ese fin de semana está fuera.',
    en: "She'd love to come, but she's away that weekend.",
    concepts: ['v.venir', 'g.conditional', 'v.fin-de-semana'],
    level: 'B1',
    topics: ['social', 'plans'],
  },
  {
    id: 's.b284',
    es: '¿Vendrías conmigo a mirar pisos el sábado por la mañana?',
    en: 'Would you come with me to look at flats on Saturday morning?',
    concepts: ['v.venir', 'g.conditional', 'v.piso', 'v.sabado'],
    level: 'B1',
    topics: ['home', 'plans'],
  },
  {
    id: 's.b285',
    es: 'Nos dijeron que vendrían a arreglarlo hoy y aquí no ha venido nadie.',
    en: "They told us they'd come and fix it today and nobody has turned up.",
    concepts: ['v.venir', 'g.conditional', 'g.present-perfect', 'v.hoy'],
    level: 'B1',
    topics: ['home', 'past'],
  },
  {
    id: 's.b286',
    es: 'Tendrías que habérmelo dicho antes, ahora ya es tarde.',
    en: "You should have told me earlier, it's too late now.",
    concepts: ['v.tener', 'g.conditional', 'p.deberias', 'v.ya'],
    level: 'B1',
    topics: ['social', 'past'],
  },
  {
    id: 's.b287',
    es: 'Tendríamos que llamarles antes de que cierren.',
    en: "We ought to call them before they close.",
    concepts: ['v.tener', 'g.conditional', 'g.subjunctive-intro'],
    level: 'B1',
    topics: ['plans', 'work'],
  },
  {
    id: 's.b288',
    es: '¿Qué haríais si os tocara la lotería, lo dejaríais todo?',
    en: 'What would you lot do if you won the lottery, would you pack it all in?',
    concepts: ['v.hacer', 'g.conditional', 'v.vosotros', 'v.dinero'],
    level: 'B1',
    topics: ['opinions', 'social'],
  },
  {
    id: 's.b289',
    es: 'Ellos harían lo mismo por nosotros, no le des más vueltas.',
    en: "They'd do the same for us, stop overthinking it.",
    concepts: ['v.hacer', 'g.conditional', 'v.dar'],
    level: 'B1',
    topics: ['social', 'feelings'],
  },
  {
    id: 's.b290',
    es: 'Sería una pena perderse el principio por diez minutos.',
    en: "It'd be a shame to miss the beginning over ten minutes.",
    concepts: ['v.ser', 'g.conditional', 'v.diez'],
    level: 'B1',
    topics: ['plans', 'social'],
  },
  {
    id: 's.b291',
    es: 'Serían las tres cuando por fin llegamos a casa.',
    en: 'It must have been three by the time we finally got home.',
    concepts: ['v.ser', 'g.conditional', 'g.preterite', 'v.casa'],
    level: 'B1',
    topics: ['past', 'storytelling'],
  },
  {
    id: 's.b292',
    es: 'Vosotros seríais los únicos que no os enterasteis de nada.',
    en: "You lot must have been the only ones who didn't find out.",
    concepts: ['v.ser', 'g.conditional', 'v.vosotros', 'g.preterite'],
    level: 'B1',
    topics: ['past', 'social'],
  },
  {
    id: 's.b293',
    es: 'Yo en tu lugar iría, aunque solo sea por no dar explicaciones luego.',
    en: "In your shoes I'd go, if only to avoid having to explain yourself later.",
    concepts: ['v.ir', 'g.conditional', 'v.aunque', 'v.luego'],
    level: 'B1',
    topics: ['opinions', 'social'],
    blanks: ['iría'],
  },
  {
    id: 's.b294',
    es: 'Iríamos más a menudo si no estuviera tan lejos.',
    en: "We'd go more often if it weren't so far.",
    concepts: ['v.ir', 'g.conditional', 'v.lejos'],
    level: 'B1',
    topics: ['plans', 'travel'],
  },
  {
    id: 's.b295',
    es: '¿Irías tú solo a un sitio así o prefieres que te acompañe?',
    en: "Would you go somewhere like that on your own or would you rather I came with you?",
    concepts: ['v.ir', 'g.conditional', 'v.tu', 'g.subjunctive-intro'],
    level: 'B1',
    topics: ['social', 'travel'],
  },

  // --- Preterite against imperfect, where the choice changes the meaning ------
  // The rule "finished vs ongoing" gets a learner about half way. What actually
  // separates B1 from A2 is the handful of verbs that mean something *different*
  // in each tense — conocí/conocía, supe/sabía, quise/quería, pude/podía — and
  // the habit of laying background under an event.
  {
    id: 's.b296',
    es: 'La conocí en una boda; ya la conocía de vista del barrio.',
    en: 'I met her at a wedding; I already knew her by sight from the neighbourhood.',
    concepts: ['g.preterite-imperfect', 'g.preterite', 'g.imperfect', 'g.object-pronouns'],
    level: 'B1',
    topics: ['past', 'people'],
    note: 'conocí = met, one moment. conocía = knew, an ongoing state. Same verb, different tense, different verb in English.',
  },
  {
    id: 's.b297',
    es: 'No sabía que estabas aquí; lo supe ayer por tu hermana.',
    en: 'I didn’t know you were here; I found out yesterday from your sister.',
    concepts: ['g.preterite-imperfect', 'v.saber', 'v.ayer'],
    level: 'B1',
    topics: ['past', 'social'],
    note: 'sabía = knew. supe = found out. The preterite turns a state into the moment it began.',
  },
  {
    id: 's.b298',
    es: 'Quería decírtelo antes, pero no quise estropearte la noche.',
    en: 'I wanted to tell you earlier, but I chose not to ruin your evening.',
    concepts: ['g.preterite-imperfect', 'v.querer', 'g.object-pronouns'],
    level: 'B1',
    topics: ['past', 'feelings'],
    note: 'no quise is a refusal, a decision taken. no quería is only a wish you had.',
  },
  {
    id: 's.b299',
    es: 'Podía haber ido, pero al final no pude por el trabajo.',
    en: 'I could have gone, but in the end I couldn’t because of work.',
    concepts: ['g.preterite-imperfect', 'v.poder', 'v.trabajo'],
    level: 'B1',
    topics: ['past', 'work'],
  },
  {
    id: 's.b300',
    es: 'Estaba lloviendo cuando salimos, así que volvimos a por el paraguas.',
    en: 'It was raining when we left, so we went back for the umbrella.',
    concepts: ['g.preterite-imperfect', 'g.imperfect', 'g.preterite'],
    level: 'B1',
    topics: ['past', 'weather'],
    note: 'The imperfect paints the scene; the preterite is what happened in it.',
  },
  {
    id: 's.b301',
    es: 'Todos los veranos íbamos al mismo pueblo, hasta que un año lo vendieron.',
    en: 'Every summer we went to the same village, until one year they sold it.',
    concepts: ['g.preterite-imperfect', 'g.imperfect', 'v.ano-time'],
    level: 'B1',
    topics: ['past', 'storytelling'],
    note: 'A repeated habit is imperfect; the single event that ends it is preterite.',
  },
  {
    id: 's.b302',
    es: 'Tenía que entregarlo el lunes y al final lo entregué el miércoles.',
    en: 'I was supposed to hand it in on Monday and in the end I handed it in on Wednesday.',
    concepts: ['g.preterite-imperfect', 'p.tener-que', 'g.object-pronouns'],
    level: 'B1',
    topics: ['past', 'university'],
    note: 'tenía que = was supposed to. tuve que = had to, and did.',
  },
  {
    id: 's.b303',
    es: 'Tuve que quedarme hasta las nueve porque nadie más sabía hacerlo.',
    en: 'I had to stay until nine because nobody else knew how to do it.',
    concepts: ['g.preterite-imperfect', 'p.tener-que', 'v.quedar'],
    level: 'B1',
    topics: ['past', 'work'],
  },
  {
    id: 's.b304',
    es: 'Mientras yo preparaba la cena, ella puso la mesa.',
    en: 'While I was making dinner, she laid the table.',
    concepts: ['g.preterite-imperfect', 'v.cena', 'v.poner'],
    level: 'B1',
    topics: ['past', 'home'],
  },
  {
    id: 's.b305',
    es: 'Fue un momento raro: todos hablaban a la vez y nadie escuchaba.',
    en: 'It was an odd moment: everyone was talking at once and nobody was listening.',
    concepts: ['g.preterite-imperfect', 'v.ser', 'g.imperfect'],
    level: 'B1',
    topics: ['past', 'storytelling'],
  },
  {
    id: 's.b306',
    es: 'De pequeña era muy tímida, pero un día se plantó y cambió todo.',
    en: 'As a girl she was very shy, but one day she stood her ground and everything changed.',
    concepts: ['g.preterite-imperfect', 'v.ser', 'v.pequeno'],
    level: 'B1',
    topics: ['past', 'people'],
  },
  {
    id: 's.b307',
    es: 'Cuando llegamos ya no había nadie: se habían ido todos.',
    en: 'When we arrived there was nobody left: they had all gone.',
    concepts: ['g.preterite-imperfect', 'v.ya', 'g.hay-estar'],
    level: 'B1',
    topics: ['past', 'storytelling'],
  },

  // --- Object pronouns, including the Spanish that Spain actually writes ------
  {
    id: 's.b308',
    es: '¿Le has dado las llaves a tu hermano? — Sí, se las di ayer.',
    en: 'Have you given your brother the keys? — Yes, I gave them to him yesterday.',
    concepts: ['g.object-pronouns', 'g.present-perfect', 'g.preterite'],
    level: 'B1',
    topics: ['home', 'family'],
    blanks: ['se'],
    note: 'le + las would be unpronounceable, so le becomes se: se las di. Not reflexive at all.',
  },
  {
    id: 's.b309',
    es: 'A mí me lo contó ella misma, no me lo he inventado.',
    en: 'She told me herself, I haven’t made it up.',
    concepts: ['g.object-pronouns', 'g.present-perfect', 'g.preterite'],
    level: 'B1',
    topics: ['social', 'past'],
    note: '"A mí me" doubles the pronoun on purpose — it is emphasis, not a mistake.',
  },
  {
    id: 's.b310',
    es: 'El informe lo mando yo, tú encárgate de las fotos.',
    en: 'I’ll send the report, you deal with the photos.',
    concepts: ['g.object-pronouns', 'v.trabajo', 'v.tu'],
    level: 'B1',
    topics: ['work'],
    note: 'Fronting the object needs a pronoun copy: "El informe lo mando yo". Dropping the lo is ungrammatical.',
  },
  {
    id: 's.b311',
    es: 'A Juan le vi ayer en el metro y no me saludó.',
    en: 'I saw Juan yesterday on the metro and he didn’t say hello.',
    concepts: ['g.object-pronouns', 'v.metro', 'g.preterite'],
    level: 'B1',
    topics: ['social', 'past'],
    note: 'le for a male person is standard in Spain — leísmo. In Latin America it would be lo vi.',
  },
  {
    id: 's.b312',
    es: 'Estoy buscándolo desde ayer y no aparece.',
    en: 'I’ve been looking for it since yesterday and it hasn’t turned up.',
    concepts: ['g.object-pronouns', 'v.ayer', 'g.negation'],
    level: 'B1',
    topics: ['home'],
    altEs: ['Lo estoy buscando desde ayer y no aparece.'],
    note: 'With a gerund the pronoun may attach or go in front — both are correct and both are used.',
  },
  {
    id: 's.b313',
    es: 'Voy a decírselo esta noche, no puedo esperar más.',
    en: 'I’m going to tell her tonight, I can’t wait any longer.',
    concepts: ['g.object-pronouns', 'g.ir-a-infinitive', 'v.decir'],
    level: 'B1',
    topics: ['social', 'feelings'],
    altEs: ['Se lo voy a decir esta noche, no puedo esperar más.'],
  },
  {
    id: 's.b314',
    es: 'No me lo digas, prefiero enterarme por mí misma.',
    en: 'Don’t tell me, I’d rather find out for myself.',
    concepts: ['g.object-pronouns', 'g.negation', 'v.decir'],
    level: 'B1',
    topics: ['social'],
    note: 'A negative command puts the pronouns in front; a positive one sticks them on: dímelo.',
  },
  {
    id: 's.b315',
    es: 'A nosotros nos parece bien, pero pregúntales a ellos.',
    en: 'It seems fine to us, but ask them.',
    concepts: ['g.object-pronouns', 'v.nosotros', 'v.bien'],
    level: 'B1',
    topics: ['opinions', 'social'],
  },
  {
    id: 's.b316',
    es: 'Las llaves las dejé encima de la mesa, te lo juro.',
    en: 'I left the keys on the table, I swear.',
    concepts: ['g.object-pronouns', 'g.preterite', 'v.mesa'],
    level: 'B1',
    topics: ['home', 'past'],
  },
  {
    id: 's.b317',
    es: '¿Os lo ha explicado ya o se lo explico yo?',
    en: 'Has she explained it to you lot yet, or shall I?',
    concepts: ['g.object-pronouns', 'v.vosotros', 'g.present-perfect', 'v.ya'],
    level: 'B1',
    topics: ['work', 'university'],
  },
];
