import type { Sentence } from '@/content/types';

/**
 * B1 sentences: speculation, hypotheticals, advice, complaints and the
 * connectors that hold a paragraph together.
 *
 * The shape is the point. A2 sentences carry a reason; B1 sentences carry a
 * relationship between two ideas — contrast, consequence, condition — which is
 * what the connectors and the new tenses exist to express.
 */
export const b1CoreSentences: Sentence[] = [
  // --- Future and speculation ----------------------------------------------
  {
    id: 's.b1',
    es: 'El año que viene viviré en Madrid.',
    en: "Next year I'll live in Madrid.",
    concepts: ['g.future', 'v.ano-time'],
    level: 'B1',
    topics: ['plans'],
    blanks: ['viviré'],
  },
  {
    id: 's.b2',
    es: '¿Dónde está Ana? — No sé, estará en el metro.',
    en: "Where's Ana? — I don't know, she's probably on the metro.",
    concepts: ['g.future', 'v.metro'],
    level: 'B1',
    topics: ['plans'],
    note: 'The future used as a guess about the present — extremely common in speech.',
  },
  {
    id: 's.b3',
    es: 'Mañana te lo diré, ahora no tengo tiempo.',
    en: "I'll tell you tomorrow, I haven't got time now.",
    concepts: ['g.future', 'v.tiempo', 'v.ahora'],
    level: 'B1',
    topics: ['plans'],
  },
  {
    id: 's.b4',
    es: 'Tendremos que salir antes si hay retraso.',
    en: "We'll have to leave earlier if there's a delay.",
    concepts: ['g.future', 'v.retraso', 'p.tener-que'],
    level: 'B1',
    topics: ['transport', 'plans'],
  },

  // --- Conditional: politeness, advice, hypotheticals ----------------------
  {
    id: 's.b5',
    es: '¿Podrías echarme una mano con esto?',
    en: 'Could you give me a hand with this?',
    concepts: ['g.conditional', 'v.poder'],
    level: 'B1',
    topics: ['social', 'work'],
    blanks: ['Podrías'],
  },
  {
    id: 's.b6',
    es: 'Yo que tú, hablaría con tu jefe.',
    en: "If I were you, I'd talk to your boss.",
    concepts: ['p.yo-que-tu', 'g.conditional', 'v.jefe'],
    level: 'B1',
    topics: ['work', 'opinions'],
  },
  {
    id: 's.b7',
    es: 'Deberías descansar más, estás agobiado.',
    en: 'You should rest more, you’re stressed out.',
    concepts: ['p.deberias', 'v.agobiado'],
    level: 'B1',
    topics: ['opinions', 'feelings'],
  },
  {
    id: 's.b8',
    es: 'Me gustaría cambiar de trabajo, pero no es fácil.',
    en: "I'd like to change jobs, but it isn't easy.",
    concepts: ['g.conditional', 'v.trabajo', 'v.facil'],
    level: 'B1',
    topics: ['work'],
  },
  {
    id: 's.b9',
    es: 'Te recomiendo que vayas en tren, merece la pena.',
    en: 'I recommend you go by train, it’s worth it.',
    concepts: ['p.te-recomiendo', 'p.merece-la-pena', 'v.tren'],
    level: 'B1',
    topics: ['travel', 'opinions'],
  },

  // --- Pluperfect and storytelling -----------------------------------------
  {
    id: 's.b10',
    es: 'Cuando llegué a la estación, el tren ya se había ido.',
    en: "When I got to the station, the train had already left.",
    concepts: ['g.pluperfect', 'v.estacion', 'v.tren'],
    level: 'B1',
    topics: ['past', 'transport'],
    blanks: ['se había ido'],
  },
  {
    id: 's.b11',
    es: 'No sabía que habías estudiado en Salamanca.',
    en: "I didn't know you'd studied in Salamanca.",
    concepts: ['g.pluperfect', 'v.estudiar'],
    level: 'B1',
    topics: ['past', 'university'],
  },
  {
    id: 's.b12',
    es: 'Estaba leyendo tranquilamente cuando de repente sonó el móvil.',
    en: 'I was reading quietly when suddenly the phone rang.',
    concepts: ['v.de-repente', 'g.preterite-imperfect', 'v.movil'],
    level: 'B1',
    topics: ['storytelling'],
    note: 'Imperfect for the background, preterite for the interruption — de repente marks the switch.',
  },
  {
    id: 's.b13',
    es: 'Al final no fuimos, porque había empezado a llover.',
    en: "In the end we didn't go, because it had started raining.",
    concepts: ['v.al-final', 'g.pluperfect', 'v.llover'],
    level: 'B1',
    topics: ['storytelling'],
  },
  {
    id: 's.b14',
    es: 'Mientras cenábamos, nos dimos cuenta de que faltaba alguien.',
    en: 'While we were having dinner, we realised someone was missing.',
    concepts: ['v.mientras', 'p.darse-cuenta', 'g.preterite-imperfect'],
    level: 'B1',
    topics: ['storytelling'],
  },

  // --- se and impersonal ---------------------------------------------------
  {
    id: 's.b15',
    es: 'En España se cena muy tarde.',
    en: 'In Spain people have dinner very late.',
    concepts: ['g.se-impersonal', 'v.cena', 'v.espana'],
    level: 'B1',
    topics: ['city'],
    blanks: ['se cena'],
  },
  {
    id: 's.b16',
    es: '¿Cómo se dice esto en español?',
    en: 'How do you say this in Spanish?',
    concepts: ['g.se-impersonal', 'v.espanol'],
    level: 'B1',
    topics: ['introductions'],
  },
  {
    id: 's.b17',
    es: 'Se me ha olvidado el móvil en casa.',
    en: "I've left my phone at home.",
    concepts: ['g.se-impersonal', 'p.se-me-ha-olvidado', 'v.movil'],
    level: 'B1',
    topics: ['daily-routine'],
    note: 'The accidental se — the thing forgot itself on you. Standard, not an excuse.',
  },
  {
    id: 's.b18',
    es: 'Aquí se come muy bien y no es caro.',
    en: 'The food here is great and it isn’t expensive.',
    concepts: ['g.se-impersonal', 'v.comer', 'v.caro'],
    level: 'B1',
    topics: ['restaurant', 'opinions'],
  },

  // --- Relative clauses ----------------------------------------------------
  {
    id: 's.b19',
    es: 'El piso que alquilamos está en Lavapiés.',
    en: 'The flat we rented is in Lavapiés.',
    concepts: ['g.relatives', 'v.piso'],
    level: 'B1',
    topics: ['home'],
    note: 'English can drop "that"; Spanish never drops que.',
  },
  {
    id: 's.b20',
    es: 'No entiendo lo que quieres decir.',
    en: "I don't understand what you mean.",
    concepts: ['g.relatives'],
    level: 'B1',
    topics: ['opinions'],
    blanks: ['lo que'],
  },
  {
    id: 's.b21',
    es: 'La chica con quien hablé trabaja en la misma empresa.',
    en: 'The girl I spoke to works at the same company.',
    concepts: ['g.relatives', 'v.empresa'],
    level: 'B1',
    topics: ['work'],
  },
  {
    id: 's.b22',
    es: 'Eso es lo que me da rabia.',
    en: "That's what makes me angry.",
    concepts: ['g.relatives', 'p.me-da-rabia'],
    level: 'B1',
    topics: ['feelings'],
  },

  // --- Feelings with range -------------------------------------------------
  {
    id: 's.b23',
    es: 'Estoy harto de las reuniones que no sirven para nada.',
    en: "I'm fed up with meetings that are pointless.",
    concepts: ['v.harto', 'v.reunion', 'g.relatives'],
    level: 'B1',
    topics: ['work', 'feelings'],
  },
  {
    id: 's.b24',
    es: 'Me preocupa que no haya contestado todavía.',
    en: "It worries me that he hasn't replied yet.",
    concepts: ['p.me-preocupa', 'g.subjunctive-intro'],
    level: 'B1',
    topics: ['feelings'],
    note: 'Emotion + que sends the next verb into the subjunctive.',
  },
  {
    id: 's.b25',
    es: 'Echo mucho de menos a mi familia.',
    en: 'I really miss my family.',
    concepts: ['p.echar-de-menos', 'v.familia'],
    level: 'B1',
    topics: ['feelings', 'family'],
  },
  {
    id: 's.b26',
    es: 'Tengo muchas ganas de que llegue el verano.',
    en: "I'm really looking forward to summer.",
    concepts: ['p.tener-ganas', 'g.subjunctive-intro'],
    level: 'B1',
    topics: ['feelings', 'plans'],
  },
  {
    id: 's.b27',
    es: 'Me llevo muy bien con mis compañeros de piso.',
    en: 'I get on really well with my flatmates.',
    concepts: ['p.llevarse-bien', 'v.companero'],
    level: 'B1',
    topics: ['social', 'home'],
  },

  // --- Complaining and sorting problems out --------------------------------
  {
    id: 's.b28',
    es: 'Perdone, hay un problema con la reserva.',
    en: "Excuse me, there's a problem with the booking.",
    concepts: ['p.hay-un-problema', 'v.reservar'],
    level: 'B1',
    topics: ['travel'],
    register: 'formal',
  },
  {
    id: 's.b29',
    es: 'El ascensor no funciona, está averiado desde el martes.',
    en: "The lift doesn't work, it's been out of order since Tuesday.",
    concepts: ['p.no-funciona', 'v.averiado', 'v.martes'],
    level: 'B1',
    topics: ['home'],
  },
  {
    id: 's.b30',
    es: 'Creo que me han cobrado de más.',
    en: 'I think I’ve been overcharged.',
    concepts: ['p.me-han-cobrado', 'v.creo-que', 'g.present-perfect'],
    level: 'B1',
    topics: ['shopping'],
  },
  {
    id: 's.b31',
    es: 'Querría devolver esto, no me queda bien.',
    en: "I'd like to return this, it doesn't fit me.",
    concepts: ['p.querria-devolver', 'p.me-queda-bien', 'g.conditional'],
    level: 'B1',
    topics: ['shopping'],
    register: 'formal',
  },
  {
    id: 's.b32',
    es: 'Lo siento mucho, no volverá a pasar.',
    en: "I'm really sorry, it won't happen again.",
    concepts: ['p.lo-siento-mucho', 'g.future'],
    level: 'B1',
    topics: ['social'],
  },
  {
    id: 's.b33',
    es: 'No pasa nada, de verdad.',
    en: "It's fine, honestly.",
    concepts: ['p.no-pasa-nada'],
    level: 'B1',
    topics: ['social'],
  },

  // --- Connectors doing real work ------------------------------------------
  {
    id: 's.b34',
    es: 'El sueldo no está mal; sin embargo, el horario es horrible.',
    en: "The salary isn't bad; however, the hours are terrible.",
    concepts: ['v.sin-embargo', 'v.sueldo', 'v.horario'],
    level: 'B1',
    topics: ['work', 'opinions'],
    blanks: ['sin embargo'],
  },
  {
    id: 's.b35',
    es: 'Es caro y además está lejos, por eso no voy nunca.',
    en: "It's expensive and it's far as well, that's why I never go.",
    concepts: ['v.ademas', 'v.por-eso', 'v.lejos', 'v.nunca'],
    level: 'B1',
    topics: ['opinions'],
  },
  {
    id: 's.b36',
    es: 'A mí me gusta el norte; en cambio, mi hermano prefiere la costa.',
    en: 'I like the north; my brother, on the other hand, prefers the coast.',
    concepts: ['v.en-cambio', 'v.preferir', 'p.me-gusta'],
    level: 'B1',
    topics: ['opinions', 'travel'],
  },
  {
    id: 's.b37',
    es: 'Por lo visto han cambiado el horario otra vez.',
    en: 'Apparently they’ve changed the timetable again.',
    concepts: ['p.valer-la-pena', 'v.horario', 'g.present-perfect'],
    level: 'B1',
    topics: ['transport'],
  },
  {
    id: 's.b38',
    es: 'Tienes razón, o sea, que al final no merece la pena.',
    en: "You're right, I mean, in the end it isn't worth it.",
    concepts: ['p.tener-razon', 'v.o-sea', 'p.merece-la-pena', 'v.al-final'],
    level: 'B1',
    topics: ['opinions', 'slang'],
  },
  {
    id: 's.b39',
    es: 'Tengo que darme prisa, la reunión empieza en diez minutos.',
    en: "I have to hurry, the meeting starts in ten minutes.",
    concepts: ['p.darse-prisa', 'v.reunion', 'v.diez'],
    level: 'B1',
    topics: ['work'],
  },
  {
    id: 's.b40',
    es: 'Aprobé todas las asignaturas menos una.',
    en: 'I passed every subject except one.',
    concepts: ['v.aprobar', 'v.asignatura', 'v.menos'],
    level: 'B1',
    topics: ['university', 'past'],
  },

  // --- Imperfect: the background of a story -------------------------------
  {
    id: 's.b41',
    es: 'Cuando era pequeña, pasábamos todos los veranos en el pueblo.',
    en: 'When I was little, we spent every summer in the village.',
    concepts: ['g.imperfect', 'v.familia'],
    level: 'B1',
    topics: ['past', 'family'],
    blanks: ['era', 'pasábamos'],
    note: 'Repeated past habit → imperfect. Todos los veranos is the giveaway.',
  },
  {
    id: 's.b42',
    es: 'Antes fumaba mucho, pero lo dejé hace tres años.',
    en: 'I used to smoke a lot, but I gave up three years ago.',
    concepts: ['g.preterite-imperfect', 'v.antes'],
    level: 'B1',
    topics: ['past', 'health'],
    note: 'The habit is imperfect; the single event that ended it is preterite.',
  },
  {
    id: 's.b43',
    es: 'Estaba a punto de salir cuando me llamó mi hermano.',
    en: 'I was about to leave when my brother called me.',
    concepts: ['g.preterite-imperfect', 'v.hermano'],
    level: 'B1',
    topics: ['storytelling'],
    note: 'estar a punto de + infinitivo sets the scene the interruption cuts into.',
  },
  {
    id: 's.b44',
    es: 'Mientras esperaba el autobús, empezó a llover a mares.',
    en: 'While I was waiting for the bus, it started pouring down.',
    concepts: ['g.preterite-imperfect', 'v.mientras', 'v.llover'],
    level: 'B1',
    topics: ['storytelling', 'weather'],
    blanks: ['esperaba', 'empezó'],
  },
  {
    id: 's.b45',
    es: 'De pequeño no me gustaba nada el pescado; ahora me encanta.',
    en: "As a child I hated fish; now I love it.",
    concepts: ['g.imperfect', 'v.pescado'],
    level: 'B1',
    topics: ['food', 'past'],
  },
  {
    id: 's.b46',
    es: 'Éramos cuatro en clase y nos conocíamos desde siempre.',
    en: 'There were four of us in the class and we’d known each other forever.',
    concepts: ['g.imperfect', 'v.conocer'],
    level: 'B1',
    topics: ['past', 'university'],
  },
  {
    id: 's.b47',
    es: 'De repente se apagó la luz y nos quedamos a oscuras.',
    en: 'Suddenly the light went out and we were left in the dark.',
    concepts: ['v.de-repente', 'g.preterite'],
    level: 'B1',
    topics: ['storytelling'],
  },

  // --- Object pronouns: the level where they stop being optional ----------
  {
    id: 's.b48',
    es: 'El libro se lo presté a Marta la semana pasada.',
    en: 'I lent the book to Marta last week.',
    concepts: ['g.object-pronouns', 'g.preterite'],
    level: 'B1',
    topics: ['past'],
    blanks: ['se'],
    note: 'le + lo becomes se lo — Spanish never allows two l-pronouns in a row.',
  },
  {
    id: 's.b49',
    es: '¿Las llaves? Las dejé encima de la mesa.',
    en: 'The keys? I left them on the table.',
    concepts: ['g.object-pronouns', 'v.llave', 'v.mesa'],
    level: 'B1',
    topics: ['home'],
  },
  {
    id: 's.b50',
    es: 'Te lo explico otra vez, que veo que no ha quedado claro.',
    en: "I'll explain it to you again, I can see it wasn't clear.",
    concepts: ['g.object-pronouns'],
    level: 'B1',
    topics: ['university', 'social'],
  },
  {
    id: 's.b51',
    es: 'No me lo dijo nadie, me enteré por casualidad.',
    en: 'Nobody told me, I found out by chance.',
    concepts: ['g.object-pronouns', 'g.negation'],
    level: 'B1',
    topics: ['social', 'storytelling'],
  },
  {
    id: 's.b52',
    es: 'Voy a devolvérselo mañana sin falta.',
    en: "I'm going to give it back to him tomorrow without fail.",
    concepts: ['g.object-pronouns', 'g.ir-a-infinitive'],
    level: 'B1',
    topics: ['social'],
    note: 'Pronouns attach to the infinitive and pull the accent with them: devolvérselo.',
  },

  // --- First subjunctive: wanting, advising, doubting ---------------------
  {
    id: 's.b53',
    es: 'Quiero que me digas la verdad, aunque no me guste.',
    en: "I want you to tell me the truth, even if I don't like it.",
    concepts: ['g.subjunctive-intro'],
    level: 'B1',
    topics: ['social', 'feelings'],
    blanks: ['digas'],
  },
  {
    id: 's.b54',
    es: 'Te recomiendo que reserves con antelación, se llena mucho.',
    en: 'I recommend booking in advance, it gets very full.',
    concepts: ['p.te-recomiendo', 'v.reservar', 'g.subjunctive-intro'],
    level: 'B1',
    topics: ['restaurant', 'travel'],
    blanks: ['reserves'],
  },
  {
    id: 's.b55',
    es: 'Me preocupa que se lo tome a mal.',
    en: "I'm worried he'll take it badly.",
    concepts: ['p.me-preocupa', 'g.subjunctive-intro'],
    level: 'B1',
    topics: ['feelings', 'social'],
    blanks: ['tome'],
    note: 'tomarse algo a mal / a bien — how a message lands, not how it was meant.',
  },
  {
    id: 's.b56',
    es: 'Espero que te mejores pronto.',
    en: 'I hope you get better soon.',
    concepts: ['g.subjunctive-intro', 'p.lo-siento-mucho'],
    level: 'B1',
    topics: ['health', 'social'],
    note: 'The standard get-well message in Spain, and pure subjunctive.',
  },
  {
    id: 's.b57',
    es: 'Es mejor que lo hablemos en persona.',
    en: "It's better if we talk about it in person.",
    concepts: ['g.subjunctive-intro'],
    level: 'B1',
    topics: ['work', 'social'],
  },
  {
    id: 's.b58',
    es: 'No creo que llegue a tiempo con este tráfico.',
    en: "I don't think he'll get there in time in this traffic.",
    concepts: ['g.subjunctive-intro', 'v.tarde'],
    level: 'B1',
    topics: ['transport'],
  },

  // --- Future and conditional ---------------------------------------------
  {
    id: 's.b59',
    es: 'Estará en el metro, por eso no coge el móvil.',
    en: "He must be on the metro, that's why he isn't picking up.",
    concepts: ['g.future', 'v.metro', 'v.movil', 'v.por-eso'],
    level: 'B1',
    topics: ['transport'],
    note: 'The future used for a present guess — one of the most Spanish things in the language.',
  },
  {
    id: 's.b60',
    es: 'El año que viene me mudaré a Valencia, si todo sale bien.',
    en: "Next year I'll move to Valencia, if all goes well.",
    concepts: ['g.future', 'v.ano-time'],
    level: 'B1',
    topics: ['plans', 'home'],
  },
  {
    id: 's.b61',
    es: '¿Podrías echarme una mano con esto un momento?',
    en: 'Could you give me a hand with this for a moment?',
    concepts: ['g.conditional', 'v.poder'],
    level: 'B1',
    topics: ['social', 'work'],
    note: 'The conditional is the politeness gear: podrías, not puedes.',
  },
  {
    id: 's.b62',
    es: 'Yo en tu lugar no diría nada todavía.',
    en: "In your place I wouldn't say anything yet.",
    concepts: ['g.conditional', 'p.yo-que-tu'],
    level: 'B1',
    topics: ['opinions', 'social'],
  },
  {
    id: 's.b63',
    es: 'Me dijeron que la reunión sería el jueves.',
    en: 'They told me the meeting would be on Thursday.',
    concepts: ['g.conditional', 'v.reunion'],
    level: 'B1',
    topics: ['work'],
  },

  // --- Pluperfect and se ---------------------------------------------------
  {
    id: 's.b64',
    es: 'Cuando llegué, ya se habían ido todos.',
    en: 'When I arrived, everyone had already left.',
    concepts: ['g.pluperfect'],
    level: 'B1',
    topics: ['storytelling'],
    blanks: ['habían'],
  },
  {
    id: 's.b65',
    es: 'No sabía que habías estado en Galicia.',
    en: "I didn't know you'd been to Galicia.",
    concepts: ['g.pluperfect', 'g.imperfect'],
    level: 'B1',
    topics: ['travel', 'past'],
  },
  {
    id: 's.b66',
    es: 'Aquí se cena tardísimo, sobre las diez.',
    en: 'People eat dinner really late here, around ten.',
    concepts: ['g.se-impersonal', 'v.cena', 'v.diez'],
    level: 'B1',
    topics: ['food', 'social'],
  },
  {
    id: 's.b67',
    es: 'Se me ha roto el móvil justo antes del examen.',
    en: 'My phone broke right before the exam.',
    concepts: ['g.se-impersonal', 'v.movil'],
    level: 'B1',
    topics: ['university'],
    note: 'The accidental se: nobody broke it, it broke on me. Spanish avoids blaming the speaker.',
  },
  {
    id: 's.b68',
    es: 'En esa oficina se trabaja mucho y se cobra poco.',
    en: 'In that office people work a lot and get paid little.',
    concepts: ['g.se-impersonal', 'v.trabajo'],
    level: 'B1',
    topics: ['work'],
  },
  {
    id: 's.b69',
    es: 'Ese es el compañero del que te hablé.',
    en: "That's the colleague I told you about.",
    concepts: ['g.relatives', 'v.companero'],
    level: 'B1',
    topics: ['work', 'social'],
    note: 'Spanish keeps the preposition attached to the relative: del que, con el que, en el que.',
  },

  // --- Feelings, work and complaints with real texture --------------------
  {
    id: 's.b70',
    es: 'Estoy agobiada con el trabajo, no doy abasto.',
    en: "I'm overwhelmed with work, I can't keep up.",
    concepts: ['v.agobiado', 'v.trabajo'],
    level: 'B1',
    topics: ['work', 'feelings'],
    register: 'colloquial',
    note: 'no dar abasto — to be unable to cope with the volume. Heard constantly in Spain.',
  },
  {
    id: 's.b71',
    es: 'Estoy harto de que cambien el horario cada semana.',
    en: "I'm fed up with them changing the schedule every week.",
    concepts: ['v.harto', 'v.horario', 'g.subjunctive-intro'],
    level: 'B1',
    topics: ['work', 'feelings'],
    blanks: ['cambien'],
  },
  {
    id: 's.b72',
    es: 'Me da rabia haber perdido tanto tiempo con eso.',
    en: 'It makes me angry to have wasted so much time on that.',
    concepts: ['p.me-da-rabia', 'v.tiempo'],
    level: 'B1',
    topics: ['feelings'],
    register: 'colloquial',
  },
  {
    id: 's.b73',
    es: 'Con mi jefe me llevo bien; con el resto del equipo, menos.',
    en: 'I get on well with my boss; with the rest of the team, less so.',
    concepts: ['p.llevarse-bien', 'v.jefe', 'v.menos'],
    level: 'B1',
    topics: ['work', 'social'],
  },
  {
    id: 's.b74',
    es: 'Al final me di cuenta de que no merecía la pena discutir.',
    en: 'In the end I realised it wasn’t worth arguing.',
    concepts: ['p.darse-cuenta', 'p.merece-la-pena', 'v.al-final'],
    level: 'B1',
    topics: ['opinions', 'storytelling'],
  },
  {
    id: 's.b75',
    es: 'Tengo muchas ganas de que lleguen las vacaciones.',
    en: "I'm really looking forward to the holidays.",
    concepts: ['p.tener-ganas', 'g.subjunctive-intro'],
    level: 'B1',
    topics: ['plans', 'feelings'],
    blanks: ['lleguen'],
  },
  {
    id: 's.b76',
    es: 'Echo mucho de menos la comida de mi madre.',
    en: "I really miss my mother's cooking.",
    concepts: ['p.echar-de-menos', 'v.comer'],
    level: 'B1',
    topics: ['food', 'feelings'],
  },
  {
    id: 's.b77',
    es: 'Hay un problema con la calefacción, lleva dos días sin funcionar.',
    en: "There's a problem with the heating, it hasn't worked for two days.",
    concepts: ['p.hay-un-problema', 'p.no-funciona'],
    level: 'B1',
    topics: ['home'],
  },
  {
    id: 's.b78',
    es: 'El ascensor está averiado otra vez, sin embargo nadie lo arregla.',
    en: 'The lift is out of order again; however, nobody fixes it.',
    concepts: ['v.averiado', 'v.sin-embargo'],
    level: 'B1',
    topics: ['home'],
  },
  {
    id: 's.b79',
    es: 'Querría devolver esto, además tengo el tique aquí.',
    en: "I'd like to return this, and I've got the receipt here.",
    concepts: ['p.querria-devolver', 'v.ademas'],
    level: 'B1',
    topics: ['shopping'],
    register: 'formal',
  },
  {
    id: 's.b80',
    es: 'Estoy buscando trabajo, he echado el currículum en varios sitios.',
    en: "I'm looking for work, I've put my CV in at several places.",
    concepts: ['p.buscar-trabajo', 'p.echar-un-curriculum', 'g.present-perfect'],
    level: 'B1',
    topics: ['work'],
  },
  {
    id: 's.b81',
    es: 'Suspendí el primer examen, pero aprobé en septiembre.',
    en: 'I failed the first exam, but I passed in September.',
    concepts: ['v.suspender', 'v.aprobar', 'g.preterite'],
    level: 'B1',
    topics: ['university', 'past'],
  },
  {
    id: 's.b82',
    es: 'Lo mejor es que se lo digas tú directamente.',
    en: "The best thing is for you to tell him yourself.",
    concepts: ['p.lo-mejor-es', 'g.object-pronouns', 'g.subjunctive-intro'],
    level: 'B1',
    topics: ['social', 'opinions'],
  },
  {
    id: 's.b83',
    es: 'Date prisa, que el tren sale en diez minutos.',
    en: "Hurry up, the train leaves in ten minutes.",
    concepts: ['p.darse-prisa', 'v.tren', 'g.commands'],
    level: 'B1',
    topics: ['transport'],
    register: 'colloquial',
  },
  {
    id: 's.b84',
    es: 'Lo pasamos genial en Granada, en cambio en Sevilla llovió todo el finde.',
    en: 'We had a great time in Granada; in Seville, on the other hand, it rained all weekend.',
    concepts: ['p.pasarlo-bien', 'v.en-cambio', 'v.llover'],
    level: 'B1',
    topics: ['travel', 'past'],
    register: 'colloquial',
  },
  {
    id: 's.b85',
    es: 'Por lo visto han cambiado de opinión otra vez.',
    en: 'Apparently they’ve changed their minds again.',
    concepts: ['p.valer-la-pena', 'g.present-perfect'],
    level: 'B1',
    topics: ['work', 'opinions'],
  },
// --- Filling the gaps the audit found at B1 ------------------------------
  {
    id: 's.b86',
    es: 'Estoy muy orgulloso de ti, de verdad.',
    en: 'I’m really proud of you, honestly.',
    concepts: ['v.orgulloso'],
    level: 'B1',
    topics: ['feelings', 'social'],
  },
  {
    id: 's.b87',
    es: 'Me quedé bastante decepcionado con el final de la serie.',
    en: 'I was pretty disappointed with the end of the series.',
    concepts: ['v.decepcionado', 'g.preterite'],
    level: 'B1',
    topics: ['feelings', 'hobbies'],
  },
  {
    id: 's.b88',
    es: 'Me da pena que se vaya, nos llevábamos muy bien.',
    en: 'It makes me sad that he’s leaving, we got on really well.',
    concepts: ['p.me-da-pena', 'p.llevarse-bien', 'g.subjunctive-intro'],
    level: 'B1',
    topics: ['feelings', 'social'],
    blanks: ['vaya'],
  },
  {
    id: 's.b89',
    es: 'Me da miedo conducir de noche con esta lluvia.',
    en: 'I’m scared of driving at night in this rain.',
    concepts: ['p.me-da-miedo', 'v.conducir'],
    level: 'B1',
    topics: ['feelings', 'transport'],
  },
  {
    id: 's.b90',
    es: 'Estoy hasta las narices de las obras del edificio.',
    en: "I've had it up to here with the building works.",
    concepts: ['p.estoy-hasta'],
    level: 'B1',
    topics: ['feelings', 'home'],
    register: 'colloquial',
  },
  {
    id: 's.b91',
    es: 'Terminé la carrera en junio, sobre todo gracias a mi familia.',
    en: 'I finished my degree in June, above all thanks to my family.',
    concepts: ['v.carrera', 'v.sobre-todo', 'g.preterite'],
    level: 'B1',
    topics: ['university', 'family'],
  },
  {
    id: 's.b92',
    es: '¿Por qué no le echas un vistazo antes de enviarlo?',
    en: 'Why don’t you have a quick look at it before sending it?',
    concepts: ['p.por-que-no', 'p.echar-un-vistazo'],
    level: 'B1',
    topics: ['work', 'social'],
  },
  {
    id: 's.b93',
    es: 'Me parece que no prestaste atención a lo que dije.',
    en: 'I get the feeling you weren’t paying attention to what I said.',
    concepts: ['p.me-parece', 'p.prestar-atencion', 'g.relatives'],
    level: 'B1',
    topics: ['social', 'opinions'],
  },

  // --- Spiral: earlier vocabulary re-met inside B1 grammar -----------------
  {
    id: 's.b94',
    es: 'Cuando era pequeño mi abuela hacía una comida increíble los domingos.',
    en: 'When I was small my grandmother made incredible food on Sundays.',
    concepts: ['g.imperfect', 'v.comida', 'v.domingo', 'v.abuelo'],
    level: 'B1',
    topics: ['past', 'family', 'food'],
  },
  {
    id: 's.b95',
    es: 'Me di cuenta de que no entendía nada y pedí que hablaran más despacio.',
    en: 'I realised I understood nothing and asked them to speak more slowly.',
    concepts: ['p.darse-cuenta', 'p.mas-despacio', 'g.subjunctive-intro'],
    level: 'B1',
    topics: ['storytelling', 'social'],
    note: 'A repair phrase learned at A1 comes back inside a reported request at B1.',
  },
  {
    id: 's.b96',
    es: 'Espero que haga sol el domingo, tengo muchas ganas de ir a la playa.',
    en: 'I hope it’s sunny on Sunday, I’m really looking forward to going to the beach.',
    concepts: ['g.subjunctive-intro', 'p.hace-sol', 'p.tener-ganas', 'v.domingo'],
    level: 'B1',
    topics: ['weather', 'plans'],
    blanks: ['haga'],
  },
  {
    id: 's.b97',
    es: 'Yo que tú compraría el verde, el rojo se ve en todas partes.',
    en: 'If I were you I’d buy the green one, you see the red one everywhere.',
    concepts: ['p.yo-que-tu', 'v.verde', 'v.rojo', 'g.conditional'],
    level: 'B1',
    topics: ['shopping', 'opinions'],
  },
  {
    id: 's.b98',
    es: 'Nos conocimos en una fiesta y desde entonces nos llevamos muy bien.',
    en: 'We met at a party and we’ve got on well ever since.',
    concepts: ['v.fiesta', 'p.llevarse-bien', 'g.preterite'],
    level: 'B1',
    topics: ['social', 'past'],
  },
  {
    id: 's.b99',
    es: 'Antes no me gustaba nada el pescado; ahora lo como casi todas las semanas.',
    en: 'I used to hate fish; now I eat it almost every week.',
    concepts: ['g.preterite-imperfect', 'v.gustar', 'v.semana', 'v.antes'],
    level: 'B1',
    topics: ['food', 'past'],
  },
  {
    id: 's.b100',
    es: 'Le dije que era simpático, pero no me hizo ni caso.',
    en: 'I told him he was nice, but he paid me no attention at all.',
    concepts: ['v.simpatico', 'g.reported-speech', 'g.object-pronouns'],
    level: 'B1',
    topics: ['social', 'storytelling'],
    note: 'no hacer ni caso — to ignore completely. The ni is what makes it emphatic.',
  },
  {
    id: 's.b101',
    es: 'Te recomiendo que vayas en septiembre: hace buen tiempo y hay menos gente.',
    en: 'I recommend going in September: the weather is good and there are fewer people.',
    concepts: ['p.te-recomiendo', 'v.septiembre', 'p.que-tiempo-hace', 'v.gente'],
    level: 'B1',
    topics: ['travel', 'opinions'],
  },

  // --- Feelings with a cause attached --------------------------------------
  {
    id: 's.b102',
    es: 'Están preocupados porque su hijo lleva dos meses sin encontrar nada.',
    en: 'They’re worried because their son has spent two months finding nothing.',
    concepts: ['v.preocupado', 'v.hijo', 'p.buscar-trabajo'],
    level: 'B1',
    topics: ['feelings', 'work'],
  },
  {
    id: 's.b103',
    es: 'Mis padres están muy orgullosos de que haya terminado la carrera.',
    en: 'My parents are very proud that I’ve finished my degree.',
    concepts: ['v.orgulloso', 'v.carrera', 'g.subjunctive-intro'],
    level: 'B1',
    topics: ['feelings', 'university'],
    blanks: ['haya'],
    note: 'Emotion + que sends the next verb into the subjunctive, even when the fact is certain.',
  },
  {
    id: 's.b104',
    es: 'Me quedé decepcionada, esperaba bastante más de ese curso.',
    en: 'I was left disappointed, I expected quite a bit more from that course.',
    concepts: ['v.decepcionado', 'g.preterite-imperfect', 'v.clase'],
    level: 'B1',
    topics: ['feelings', 'university'],
  },
  {
    id: 's.b105',
    es: 'Me da pena dejar el piso, he vivido cuatro años aquí.',
    en: 'It makes me sad to leave the flat, I’ve lived here four years.',
    concepts: ['p.me-da-pena', 'v.piso', 'g.present-perfect'],
    level: 'B1',
    topics: ['feelings', 'home'],
  },
  {
    id: 's.b106',
    es: 'Me da miedo que se entere antes de que se lo cuente yo.',
    en: 'I’m scared he’ll find out before I tell him myself.',
    concepts: ['p.me-da-miedo', 'g.subjunctive-intro'],
    level: 'B1',
    topics: ['feelings', 'social'],
    blanks: ['entere'],
    note: 'antes de que always takes the subjunctive — no exceptions.',
  },
  {
    id: 's.b107',
    es: 'Estoy hasta las narices de que cambien el horario cada dos por tres.',
    en: 'I’ve had it up to here with them changing the schedule constantly.',
    concepts: ['p.estoy-hasta', 'v.horario', 'g.subjunctive-intro'],
    level: 'B1',
    topics: ['feelings', 'work'],
    register: 'colloquial',
    note: 'cada dos por tres — "all the time". One of those fixed phrases with no logic to parse.',
  },

  // --- Studying and looking for work ---------------------------------------
  {
    id: 's.b108',
    es: 'Suspendí una asignatura en febrero y la aprobé en junio.',
    en: 'I failed one subject in February and passed it in June.',
    concepts: ['v.suspender', 'v.asignatura', 'v.aprobar'],
    level: 'B1',
    topics: ['university', 'past'],
  },
  {
    id: 's.b109',
    es: 'La carrera está bien, pero hay asignaturas que no sirven para nada.',
    en: 'The degree is fine, but there are subjects that are completely useless.',
    concepts: ['v.carrera', 'v.asignatura', 'g.relatives'],
    level: 'B1',
    topics: ['university', 'opinions'],
  },
  {
    id: 's.b110',
    es: 'He echado el currículum en cuatro sitios y no me ha llamado nadie.',
    en: 'I’ve put my CV in at four places and nobody has called me.',
    concepts: ['p.echar-un-curriculum', 'g.present-perfect', 'g.negation'],
    level: 'B1',
    topics: ['work'],
  },
  {
    id: 's.b111',
    es: 'Llevo seis meses buscando trabajo y ya me da igual dónde sea.',
    en: 'I’ve been looking for work for six months and I no longer care where.',
    concepts: ['p.buscar-trabajo', 'p.da-igual', 'g.subjunctive-relative'],
    level: 'B1',
    topics: ['work', 'feelings'],
  },

  // --- Advising, agreeing, hedging an opinion ------------------------------
  {
    id: 's.b112',
    es: 'Deberías descansar un poco antes de tomar una decisión así.',
    en: 'You should rest a bit before making a decision like that.',
    concepts: ['p.deberias', 'p.tomar-una-decision', 'v.antes'],
    level: 'B1',
    topics: ['opinions', 'social'],
  },
  {
    id: 's.b113',
    es: '¿Por qué no le echas un vistazo y me dices qué te parece?',
    en: 'Why don’t you have a quick look and tell me what you think?',
    concepts: ['p.por-que-no', 'p.echar-un-vistazo', 'p.me-parece'],
    level: 'B1',
    topics: ['work', 'opinions'],
  },
  {
    id: 's.b114',
    es: 'Lo mejor es que se lo cuentes tú, y cuanto antes.',
    en: 'The best thing is for you to tell him yourself, and the sooner the better.',
    concepts: ['p.lo-mejor-es', 'g.subjunctive-intro', 'g.lo-nominal'],
    level: 'B1',
    topics: ['social', 'opinions'],
    note: 'cuanto antes — "as soon as possible" — is fixed and extremely common.',
  },
  {
    id: 's.b115',
    es: 'Estoy de acuerdo contigo, aunque no del todo.',
    en: 'I agree with you, though not entirely.',
    concepts: ['p.estoy-de-acuerdo', 'v.aunque'],
    level: 'B1',
    topics: ['opinions'],
  },
  {
    id: 's.b116',
    es: 'Me parece que no prestamos atención a lo importante.',
    en: 'It seems to me we’re not paying attention to what matters.',
    concepts: ['p.me-parece', 'p.prestar-atencion', 'g.lo-nominal'],
    level: 'B1',
    topics: ['opinions', 'work'],
  },
  {
    id: 's.b117',
    es: 'Aunque llueva, salimos igual; ya lo hemos decidido.',
    en: 'Even if it rains, we’re going anyway; we’ve already decided.',
    concepts: ['v.aunque', 'g.subjunctive-intro', 'v.llover'],
    level: 'B1',
    topics: ['plans', 'weather'],
    blanks: ['llueva'],
    note: 'aunque + subjunctive here because the rain is hypothetical. With aunque llueve it would already be raining.',
  },
  {
    id: 's.b118',
    es: 'Aunque es caro, sobre todo por la zona, merece la pena.',
    en: 'Although it’s expensive, mainly because of the area, it’s worth it.',
    concepts: ['v.aunque', 'v.sobre-todo', 'p.merece-la-pena'],
    level: 'B1',
    topics: ['home', 'opinions'],
    note: 'aunque + indicative: the price is an accepted fact, not a hypothesis.',
  },
  {
    id: 's.b119',
    es: 'Sobre todo, no te preocupes: no pasa nada.',
    en: 'Above all, don’t worry: it’s fine.',
    concepts: ['v.sobre-todo', 'p.no-pasa-nada', 'g.commands'],
    level: 'B1',
    topics: ['social', 'feelings'],
  },
  {
    id: 's.b120',
    es: 'Lo pasamos muy bien, aunque acabamos agotados.',
    en: 'We had a great time, though we ended up exhausted.',
    concepts: ['p.pasarlo-bien', 'v.aunque', 'g.preterite'],
    level: 'B1',
    topics: ['social', 'past'],
  },
];
