import type { Sentence } from '@/content/types';

/**
 * B2 sentences: arguing, conceding, hypothesising and reporting.
 *
 * These are deliberately longer and subordinated. A B2 sentence usually holds
 * two clauses in tension — a concession before an objection, a condition before
 * a consequence — because that is the level's actual demand.
 */
export const b2CoreSentences: Sentence[] = [
  // --- Disagreeing with the subjunctive ------------------------------------
  {
    id: 's.c1',
    es: 'No creo que sea tan sencillo como parece.',
    en: "I don't think it's as simple as it looks.",
    concepts: ['g.subjunctive-opinion', 'g.comparisons'],
    level: 'B2',
    topics: ['opinions'],
    blanks: ['sea'],
  },
  {
    id: 's.c2',
    es: 'Puede ser, pero no estoy de acuerdo con esa medida.',
    en: "Maybe, but I don't agree with that measure.",
    concepts: ['p.puede-ser-pero', 'p.no-estoy-de-acuerdo', 'v.medida'],
    level: 'B2',
    topics: ['opinions'],
  },
  {
    id: 's.c3',
    es: 'No digo que esté mal, lo que pasa es que no es realista.',
    en: "I'm not saying it's wrong, the thing is it isn't realistic.",
    concepts: ['g.subjunctive-opinion', 'p.lo-que-pasa-es'],
    level: 'B2',
    topics: ['opinions'],
    note: 'Concede, then object — the standard shape of Spanish disagreement.',
  },
  {
    id: 's.c4',
    es: 'Me molesta que nadie tenga en cuenta a los inquilinos.',
    en: 'It annoys me that nobody takes tenants into account.',
    concepts: ['g.subjunctive-opinion', 'p.tener-en-cuenta'],
    level: 'B2',
    topics: ['opinions', 'home'],
  },
  {
    id: 's.c5',
    es: 'Yo no lo veo así; a fin de cuentas, el problema es el alquiler.',
    en: "I don't see it that way; at the end of the day, the problem is the rent.",
    concepts: ['p.no-lo-veo-asi', 'p.a-fin-de-cuentas', 'v.alquiler'],
    level: 'B2',
    topics: ['opinions', 'home'],
  },
  {
    id: 's.c6',
    es: 'Por mucho que insistas, no voy a cambiar de opinión.',
    en: "However much you insist, I'm not going to change my mind.",
    concepts: ['p.por-mucho-que', 'g.subjunctive-opinion'],
    level: 'B2',
    topics: ['opinions'],
  },

  // --- Hypothesising -------------------------------------------------------
  {
    id: 's.c7',
    es: 'Si tuviera más tiempo, me apuntaría a un curso de fotografía.',
    en: "If I had more time, I'd sign up for a photography course.",
    concepts: ['g.si-hypothetical', 'g.conditional'],
    level: 'B2',
    topics: ['plans', 'hobbies'],
    blanks: ['tuviera', 'apuntaría'],
  },
  {
    id: 's.c8',
    es: '¿Qué harías si te ofrecieran un trabajo en otro país?',
    en: 'What would you do if they offered you a job in another country?',
    concepts: ['g.si-hypothetical', 'v.trabajo', 'v.pais'],
    level: 'B2',
    topics: ['work', 'opinions'],
  },
  {
    id: 's.c9',
    es: 'Si fuera más barato, mucha gente lo usaría a diario.',
    en: 'If it were cheaper, a lot of people would use it daily.',
    concepts: ['g.si-hypothetical', 'v.barato', 'v.gente'],
    level: 'B2',
    topics: ['transport', 'opinions'],
  },
  {
    id: 's.c10',
    es: 'Si hubiera sabido que había huelga, no habría cogido el coche.',
    en: "If I'd known there was a strike, I wouldn't have taken the car.",
    concepts: ['g.si-hypothetical', 'g.pluperfect', 'v.coger'],
    level: 'B2',
    topics: ['transport'],
    note: 'The past hypothetical: si + pluperfect subjunctive → conditional perfect.',
  },
  {
    id: 's.c11',
    es: 'Puede que suban el precio otra vez, no me extrañaría.',
    en: "They may put the price up again, it wouldn't surprise me.",
    concepts: ['p.puede-que', 'p.no-me-extrana', 'v.aumentar'],
    level: 'B2',
    topics: ['opinions', 'shopping'],
  },
  {
    id: 's.c12',
    es: 'A lo mejor viene, pero yo no contaría con ello.',
    en: "Maybe he'll come, but I wouldn't count on it.",
    concepts: ['p.a-lo-mejor', 'g.conditional'],
    level: 'B2',
    topics: ['plans', 'slang'],
    note: 'a lo mejor is one of the few "maybe" expressions that keeps the indicative.',
  },

  // --- Reporting what was said ---------------------------------------------
  {
    id: 's.c13',
    es: 'Me dijo que estaba agobiado y que necesitaba unos días libres.',
    en: 'He told me he was overwhelmed and needed a few days off.',
    concepts: ['g.reported-speech', 'v.agobiado'],
    level: 'B2',
    topics: ['work', 'feelings'],
    blanks: ['estaba', 'necesitaba'],
  },
  {
    id: 's.c14',
    es: 'Preguntó si habíamos terminado el informe.',
    en: 'She asked whether we had finished the report.',
    concepts: ['g.reported-speech', 'g.pluperfect'],
    level: 'B2',
    topics: ['work'],
  },
  {
    id: 's.c15',
    es: 'Me comentó que vendría al día siguiente.',
    en: 'He mentioned he would come the next day.',
    concepts: ['p.me-comento-que', 'g.reported-speech', 'g.conditional'],
    level: 'B2',
    topics: ['work', 'social'],
    note: 'mañana becomes al día siguiente — the time reference shifts with the tense.',
  },
  {
    id: 's.c16',
    es: 'Según el periódico, al parecer van a reducir las plantillas.',
    en: 'According to the paper, apparently they’re going to cut staff.',
    concepts: ['p.segun', 'p.al-parecer', 'v.reducir'],
    level: 'B2',
    topics: ['work', 'opinions'],
  },
  {
    id: 's.c17',
    es: 'El jefe nos pidió que llegáramos antes.',
    en: 'The boss asked us to arrive earlier.',
    concepts: ['g.reported-speech', 'v.jefe'],
    level: 'B2',
    topics: ['work'],
    note: 'A reported imperative becomes the imperfect subjunctive.',
  },

  // --- Weighing both sides -------------------------------------------------
  {
    id: 's.c18',
    es: 'Por un lado es más cómodo; por otro, sale bastante más caro.',
    en: "On one hand it's more convenient; on the other, it works out a lot more expensive.",
    concepts: ['p.por-un-lado', 'g.comparisons', 'v.bastante'],
    level: 'B2',
    topics: ['opinions'],
  },
  {
    id: 's.c19',
    es: 'La ventaja es que ahorras tiempo; la desventaja, que pierdes flexibilidad.',
    en: 'The advantage is that you save time; the drawback, that you lose flexibility.',
    concepts: ['p.la-ventaja-es'],
    level: 'B2',
    topics: ['opinions', 'work'],
  },
  {
    id: 's.c20',
    es: 'Hay que tener en cuenta que no todo el mundo tiene coche.',
    en: 'You have to bear in mind that not everyone has a car.',
    concepts: ['p.hay-que-tener-en-cuenta', 'v.coche'],
    level: 'B2',
    topics: ['opinions', 'transport'],
  },
  {
    id: 's.c21',
    es: 'A pesar de que el paro ha bajado, los sueldos siguen igual.',
    en: 'Despite unemployment having fallen, wages are still the same.',
    concepts: ['p.a-pesar-de', 'v.paro', 'v.sueldo', 'g.present-perfect'],
    level: 'B2',
    topics: ['work', 'opinions'],
  },
  {
    id: 's.c22',
    es: 'Aun así, en mi opinión merece la pena intentarlo.',
    en: "Even so, in my opinion it's worth trying.",
    concepts: ['p.aun-asi', 'p.en-mi-opinion', 'p.merece-la-pena'],
    level: 'B2',
    topics: ['opinions'],
  },
  {
    id: 's.c23',
    es: 'En resumen, la vivienda se ha convertido en el problema principal.',
    en: 'In short, housing has become the main problem.',
    concepts: ['p.en-resumen', 'v.vivienda', 'g.present-perfect'],
    level: 'B2',
    topics: ['opinions', 'home'],
  },

  // --- Register and tone ---------------------------------------------------
  {
    id: 's.c24',
    es: 'Le agradecería que me confirmara la cita por correo.',
    en: "I'd be grateful if you could confirm the appointment by email.",
    concepts: ['g.register', 'g.si-hypothetical', 'v.cita'],
    level: 'B2',
    topics: ['work'],
    register: 'formal',
    blanks: ['confirmara'],
  },
  {
    id: 's.c25',
    es: 'Oye, ¿te importa si lo dejamos para mañana?',
    en: 'Hey, do you mind if we leave it until tomorrow?',
    concepts: ['g.register', 'v.manana'],
    level: 'B2',
    topics: ['social', 'work'],
    register: 'colloquial',
  },
  {
    id: 's.c26',
    es: '¡Venga ya! Eso no se lo cree nadie.',
    en: "Oh come on! Nobody believes that.",
    concepts: ['p.venga-ya', 'g.se-impersonal'],
    level: 'B2',
    topics: ['slang', 'opinions'],
    register: 'colloquial',
    note: 'Tone does the work — the same words could be encouragement with a different delivery.',
  },
  {
    id: 's.c27',
    es: 'La verdad es que, o sea, no me convence del todo.',
    en: "To be honest, I mean, it doesn't really convince me.",
    concepts: ['p.la-verdad-es-que', 'p.o-sea-que'],
    level: 'B2',
    topics: ['slang', 'opinions'],
    register: 'colloquial',
  },
  {
    id: 's.c28',
    es: 'Total, que al final no fuimos a ninguna parte.',
    en: "Anyway, so in the end we didn't go anywhere.",
    concepts: ['p.en-plan-b2', 'v.al-final'],
    level: 'B2',
    topics: ['storytelling', 'slang'],
    register: 'colloquial',
  },
  {
    id: 's.c29',
    es: 'Exigen que trabajemos los sábados y encima sin pagar.',
    en: 'They demand we work Saturdays, and on top of that unpaid.',
    concepts: ['v.exigir', 'g.subjunctive-opinion', 'v.sabado'],
    level: 'B2',
    topics: ['work', 'opinions'],
  },
  {
    id: 's.c30',
    es: 'Lograron llevar a cabo el proyecto a pesar de los recortes.',
    en: 'They managed to carry out the project despite the cuts.',
    concepts: ['v.lograr', 'p.llevar-a-cabo', 'p.a-pesar-de'],
    level: 'B2',
    topics: ['work'],
  },

  // --- Disagreeing: more ways to concede before you object -----------------
  {
    id: 's.c31',
    es: 'Estoy de acuerdo en parte, pero creo que te dejas algo importante.',
    en: "I partly agree, but I think you're leaving out something important.",
    altEs: ['Estoy de acuerdo en parte, aunque creo que te dejas algo importante.'],
    concepts: ['p.estoy-de-acuerdo-en-parte'],
    level: 'B2',
    topics: ['opinions'],
  },
  {
    id: 's.c32',
    es: 'Desde mi punto de vista, el problema no es el dinero sino la organización.',
    en: "From my point of view, the problem isn't the money but the organisation.",
    concepts: ['p.desde-mi-punto'],
    level: 'B2',
    topics: ['opinions', 'work'],
    note: 'no… sino… corrects the previous claim; no… pero… would merely add to it.',
  },
  {
    id: 's.c33',
    es: 'No creo que valga la pena discutirlo otra vez.',
    en: "I don't think it's worth arguing about again.",
    concepts: ['g.subjunctive-opinion', 'p.merece-la-pena'],
    level: 'B2',
    topics: ['opinions'],
    blanks: ['valga'],
  },
  {
    id: 's.c34',
    es: 'Puede ser, pero los datos dicen justo lo contrario.',
    en: 'Maybe, but the figures say exactly the opposite.',
    concepts: ['p.puede-ser-pero', 'v.dato'],
    level: 'B2',
    topics: ['opinions', 'work'],
  },
  {
    id: 's.c35',
    es: 'Yo no lo veo así: para mí, esa medida perjudica a los de siempre.',
    en: "I don't see it like that: for me, that policy hurts the same people as always.",
    concepts: ['p.no-lo-veo-asi', 'v.medida'],
    level: 'B2',
    topics: ['opinions'],
  },
  {
    id: 's.c36',
    es: 'No estoy de acuerdo con cómo se ha planteado el debate.',
    en: "I don't agree with the way the debate has been framed.",
    concepts: ['p.no-estoy-de-acuerdo', 'g.present-perfect'],
    level: 'B2',
    topics: ['opinions'],
  },
  {
    id: 's.c37',
    es: 'Por mucho que lo repitan en la tele, no se lo cree nadie.',
    en: 'However much they repeat it on TV, nobody believes it.',
    concepts: ['p.por-mucho-que', 'g.se-impersonal'],
    level: 'B2',
    topics: ['opinions'],
    blanks: ['repitan'],
  },
  {
    id: 's.c38',
    es: 'Lo que pasa es que nadie quiere asumir la responsabilidad.',
    en: 'The thing is nobody wants to take responsibility.',
    concepts: ['p.lo-que-pasa-es'],
    level: 'B2',
    topics: ['work', 'opinions'],
    register: 'colloquial',
  },
  {
    id: 's.c39',
    es: 'Me molesta que se hable tanto y se haga tan poco.',
    en: 'It annoys me that there’s so much talk and so little action.',
    concepts: ['g.subjunctive-opinion', 'g.se-impersonal'],
    level: 'B2',
    topics: ['opinions'],
    blanks: ['hable', 'haga'],
  },

  // --- Hypothesising: the whole conditional range -------------------------
  {
    id: 's.c40',
    es: 'Si viviera más cerca del trabajo, no perdería dos horas al día.',
    en: "If I lived closer to work, I wouldn't lose two hours a day.",
    altEs: ['Si viviese más cerca del trabajo, no perdería dos horas al día.'],
    concepts: ['g.si-hypothetical', 'g.conditional'],
    level: 'B2',
    topics: ['work', 'transport'],
    blanks: ['viviera'],
    note: '-ara and -ase endings are equally correct; Spain uses both, -ara more in speech.',
  },
  {
    id: 's.c41',
    es: 'Yo que tú, me lo pensaría dos veces antes de firmar.',
    en: "If I were you, I'd think twice before signing.",
    concepts: ['p.yo-que-tu', 'g.conditional'],
    level: 'B2',
    topics: ['work', 'opinions'],
    register: 'colloquial',
  },
  {
    id: 's.c42',
    es: 'De haberlo sabido antes, habría cambiado el billete.',
    en: "Had I known earlier, I'd have changed the ticket.",
    altEs: ['Si lo hubiera sabido antes, habría cambiado el billete.'],
    concepts: ['g.si-hypothetical', 'g.pluperfect'],
    level: 'B2',
    topics: ['travel'],
    note: 'de + infinitive compuesto is a compact written alternative to the si clause.',
  },
  {
    id: 's.c43',
    es: 'Igual llega tarde otra vez, ya sabes cómo es.',
    en: "He'll probably be late again, you know what he's like.",
    concepts: ['p.igual-viene'],
    level: 'B2',
    topics: ['social', 'slang'],
    register: 'colloquial',
    note: 'In Spain igual usually means "maybe", not "equally", and keeps the indicative.',
  },
  {
    id: 's.c44',
    es: 'Supongo que estará de camino, salió hace media hora.',
    en: "I suppose he's on his way, he left half an hour ago.",
    concepts: ['p.supongo-que', 'g.future'],
    level: 'B2',
    topics: ['social'],
    note: 'The future tense used for present guesswork — estará = "he must be".',
  },
  {
    id: 's.c45',
    es: 'Me imagino que habrán cancelado el vuelo por la huelga.',
    en: 'I imagine they must have cancelled the flight because of the strike.',
    concepts: ['p.me-imagino-que', 'g.future'],
    level: 'B2',
    topics: ['travel'],
  },
  {
    id: 's.c46',
    es: 'Puede que no le hayan avisado a tiempo.',
    en: 'They may not have told him in time.',
    concepts: ['p.puede-que', 'g.subjunctive-opinion'],
    level: 'B2',
    topics: ['work'],
    blanks: ['hayan'],
  },
  {
    id: 's.c47',
    es: '¿Qué harías si te tocara la lotería mañana?',
    en: 'What would you do if you won the lottery tomorrow?',
    concepts: ['g.si-hypothetical', 'g.conditional'],
    level: 'B2',
    topics: ['plans', 'opinions'],
  },
  {
    id: 's.c48',
    es: 'Si por mí fuera, lo dejaríamos para septiembre.',
    en: "If it were up to me, we'd leave it until September.",
    concepts: ['g.si-hypothetical', 'g.conditional'],
    level: 'B2',
    topics: ['work', 'plans'],
    note: 'si por mí fuera is a fixed chunk — learn it whole rather than parsing it.',
  },

  // --- Reporting: second-hand information and its hedges ------------------
  {
    id: 's.c49',
    es: 'Según los vecinos, llevan meses quejándose del ruido.',
    en: 'According to the neighbours, they’ve been complaining about the noise for months.',
    concepts: ['p.segun', 'v.quejarse'],
    level: 'B2',
    topics: ['home', 'opinions'],
    note: 'llevar + gerundio replaces "have been doing" — llevan meses quejándose.',
  },
  {
    id: 's.c50',
    es: 'Al parecer, la reunión se ha aplazado hasta el lunes.',
    en: 'Apparently the meeting has been postponed until Monday.',
    concepts: ['p.al-parecer', 'v.reunion', 'g.se-impersonal'],
    level: 'B2',
    topics: ['work'],
  },
  {
    id: 's.c51',
    es: 'Por lo que parece, no tenían ni idea de lo que estaba pasando.',
    en: 'From what it looks like, they had no idea what was going on.',
    concepts: ['p.por-lo-que-parece', 'g.imperfect'],
    level: 'B2',
    topics: ['work', 'opinions'],
  },
  {
    id: 's.c52',
    es: 'Me comentó que llevaba un año buscando piso sin suerte.',
    en: "He mentioned he'd spent a year looking for a flat with no luck.",
    concepts: ['p.me-comento-que', 'g.reported-speech', 'v.vivienda'],
    level: 'B2',
    topics: ['home', 'social'],
  },
  {
    id: 's.c53',
    es: 'Nos dijeron que el pedido llegaría esa misma semana.',
    en: 'They told us the order would arrive that same week.',
    concepts: ['g.reported-speech', 'g.conditional'],
    level: 'B2',
    topics: ['shopping', 'work'],
    note: 'esa misma semana, not esta — the deixis shifts with the reported tense.',
  },
  {
    id: 's.c54',
    es: 'Le pregunté si pensaba quedarse mucho tiempo en Madrid.',
    en: 'I asked him whether he was planning to stay in Madrid long.',
    concepts: ['g.reported-speech'],
    level: 'B2',
    topics: ['social', 'travel'],
  },
  {
    id: 's.c55',
    es: 'La noticia decía que iban a aumentar el precio del billete.',
    en: 'The news story said they were going to put the ticket price up.',
    concepts: ['v.noticia', 'v.aumentar', 'g.reported-speech'],
    level: 'B2',
    topics: ['transport', 'opinions'],
  },
  {
    id: 's.c56',
    es: 'Insistió en que no le habían informado de nada.',
    en: 'He insisted that nobody had informed him of anything.',
    concepts: ['g.reported-speech', 'g.pluperfect'],
    level: 'B2',
    topics: ['work'],
  },

  // --- Building a case: the topics an adult actually argues about ---------
  {
    id: 's.c57',
    es: 'Por un lado ahorras en alquiler; por otro, pierdes toda la mañana en el tren.',
    en: 'On one hand you save on rent; on the other, you lose your whole morning on the train.',
    concepts: ['p.por-un-lado', 'v.alquiler'],
    level: 'B2',
    topics: ['home', 'transport'],
  },
  {
    id: 's.c58',
    es: 'La ventaja es que hay más oferta; la desventaja, que los precios no bajan.',
    en: 'The advantage is there’s more supply; the drawback, that prices don’t come down.',
    concepts: ['p.la-ventaja-es', 'v.vivienda'],
    level: 'B2',
    topics: ['home', 'opinions'],
  },
  {
    id: 's.c59',
    es: 'De hecho, el paro juvenil sigue siendo el doble que la media europea.',
    en: 'In fact, youth unemployment is still double the European average.',
    concepts: ['p.de-hecho', 'v.paro', 'g.comparisons'],
    level: 'B2',
    topics: ['work', 'opinions'],
  },
  {
    id: 's.c60',
    es: 'En realidad, la desigualdad no se explica solo por los sueldos.',
    en: 'Actually, inequality isn’t explained by wages alone.',
    concepts: ['p.en-realidad', 'v.desigualdad', 'v.sueldo', 'g.se-impersonal'],
    level: 'B2',
    topics: ['work', 'opinions'],
  },
  {
    id: 's.c61',
    es: 'Es decir, que si no se construye nada, el alquiler seguirá subiendo.',
    en: 'That is to say, if nothing gets built, rent will keep going up.',
    concepts: ['p.es-decir', 'v.alquiler', 'g.future'],
    level: 'B2',
    topics: ['home', 'opinions'],
    note: 'seguir + gerundio — "to keep on doing", far more common than continuar.',
  },
  {
    id: 's.c62',
    es: 'Hay que tener en cuenta que no todo el mundo puede teletrabajar.',
    en: 'You have to bear in mind that not everyone can work from home.',
    concepts: ['p.hay-que-tener-en-cuenta'],
    level: 'B2',
    topics: ['work'],
  },
  {
    id: 's.c63',
    es: 'A pesar de la polémica, la medida salió adelante sin cambios.',
    en: 'Despite the controversy, the measure went through unchanged.',
    concepts: ['p.a-pesar-de', 'v.polemica', 'v.medida'],
    level: 'B2',
    topics: ['opinions'],
    note: 'a pesar de + noun; a pesar de que + clause. The de never disappears.',
  },
  {
    id: 's.c64',
    es: 'Aun así, reducir el tráfico del centro me parece razonable.',
    en: 'Even so, reducing traffic in the centre seems reasonable to me.',
    concepts: ['p.aun-asi', 'v.reducir'],
    level: 'B2',
    topics: ['city', 'opinions'],
  },
  {
    id: 's.c65',
    es: 'A fin de cuentas, el medio ambiente nos afecta a todos por igual.',
    en: 'At the end of the day, the environment affects all of us equally.',
    concepts: ['p.a-fin-de-cuentas', 'v.medioambiente'],
    level: 'B2',
    topics: ['opinions'],
  },
  {
    id: 's.c66',
    es: 'Las redes sociales han cambiado la manera de informarse.',
    en: 'Social media has changed the way people get their news.',
    concepts: ['v.red-social', 'g.present-perfect', 'g.reflexive'],
    level: 'B2',
    topics: ['opinions'],
  },
  {
    id: 's.c67',
    es: 'Resumiendo: ni es tan grave como dicen ni se arregla en un año.',
    en: 'To sum up: it’s neither as serious as they say nor fixable in a year.',
    concepts: ['p.resumiendo', 'g.comparisons'],
    level: 'B2',
    topics: ['opinions'],
    note: 'ni… ni… negates both halves and needs no separate no.',
  },
  {
    id: 's.c68',
    es: 'En resumen, hace falta menos discurso y más presupuesto.',
    en: 'In short, less rhetoric and more budget is what’s needed.',
    concepts: ['p.en-resumen'],
    level: 'B2',
    topics: ['opinions', 'work'],
  },
  {
    id: 's.c69',
    es: 'El dato más preocupante es que la situación no ha mejorado desde 2019.',
    en: 'The most worrying figure is that the situation hasn’t improved since 2019.',
    concepts: ['v.dato', 'v.preocupado', 'g.present-perfect'],
    level: 'B2',
    topics: ['opinions'],
  },
  {
    id: 's.c70',
    es: 'Exigen resultados inmediatos sin poner un euro encima de la mesa.',
    en: 'They demand immediate results without putting a single euro on the table.',
    concepts: ['v.exigir'],
    level: 'B2',
    topics: ['work', 'opinions'],
  },

  // --- Register: the same content, three different rooms ------------------
  {
    id: 's.c71',
    es: 'Por cierto, ¿al final os quedasteis hasta el final del concierto?',
    en: 'By the way, did you end up staying until the end of the concert?',
    concepts: ['p.por-cierto', 'g.preterite'],
    level: 'B2',
    topics: ['social'],
    register: 'colloquial',
    note: 'The vosotros preterite — quedasteis — is everyday Spain, not a textbook curiosity.',
  },
  {
    id: 's.c72',
    es: 'La verdad es que no me apetece nada discutirlo hoy.',
    en: "To be honest, I really don't feel like discussing it today.",
    concepts: ['p.la-verdad-es-que', 'p.me-apetece'],
    level: 'B2',
    topics: ['social', 'feelings'],
    register: 'colloquial',
  },
  {
    id: 's.c73',
    es: 'O sea, que al final vamos a tener que repetirlo todo.',
    en: 'So basically we’re going to have to redo the whole thing.',
    concepts: ['p.o-sea-que'],
    level: 'B2',
    topics: ['work', 'slang'],
    register: 'colloquial',
  },
  {
    id: 's.c74',
    es: '¿Trabajar gratis? Ni de broma.',
    en: 'Work for free? No chance.',
    concepts: ['p.ni-de-broma'],
    level: 'B2',
    topics: ['work', 'slang'],
    register: 'colloquial',
  },
  {
    id: 's.c75',
    es: 'Le escribo en relación con el pedido número 4021.',
    en: 'I am writing to you regarding order number 4021.',
    concepts: ['g.register'],
    level: 'B2',
    topics: ['work', 'shopping'],
    register: 'formal',
    note: 'The standard opening of a Spanish business email — en relación con, never sobre.',
  },
  {
    id: 's.c76',
    es: 'Quedo a la espera de su respuesta. Un cordial saludo.',
    en: 'I look forward to your reply. Kind regards.',
    concepts: ['g.register'],
    level: 'B2',
    topics: ['work'],
    register: 'formal',
    note: 'The fixed close. Un saludo alone is the everyday version between colleagues.',
  },
  {
    id: 's.c77',
    es: 'Oye, ¿tú crees que le habrá sentado mal lo que dije?',
    en: 'Hey, do you reckon he took what I said badly?',
    concepts: ['g.register', 'g.future'],
    level: 'B2',
    topics: ['social', 'feelings'],
    register: 'colloquial',
  },
  {
    id: 's.c78',
    es: 'Se ruega a los pasajeros que no dejen el equipaje sin vigilancia.',
    en: 'Passengers are kindly asked not to leave luggage unattended.',
    concepts: ['g.register', 'g.se-impersonal', 'g.subjunctive-opinion'],
    level: 'B2',
    topics: ['travel', 'transport'],
    register: 'formal',
    note: 'Public-announcement Spanish: se ruega + que + subjunctive. You will hear this in every Spanish station.',
  },
  {
    id: 's.c79',
    es: 'Lograron un acuerdo, aunque a nadie acabó de convencerle del todo.',
    en: 'They reached an agreement, though it didn’t entirely convince anyone.',
    concepts: ['v.lograr', 'p.no-termina-de'],
    level: 'B2',
    topics: ['work', 'opinions'],
  },
  {
    id: 's.c80',
    es: 'Llevaron a cabo la reforma en tiempo récord y encima costó menos.',
    en: 'They carried out the renovation in record time, and on top of that it cost less.',
    concepts: ['p.llevar-a-cabo', 'p.encima'],
    level: 'B2',
    topics: ['home', 'work'],
  },

  // --- Spiral: everyday vocabulary inside B2 argument ----------------------
  {
    id: 's.c81',
    es: 'Si el alquiler no subiera cada año, mucha gente joven no se iría del barrio.',
    en: 'If rent didn’t go up every year, a lot of young people wouldn’t leave the neighbourhood.',
    concepts: ['g.si-hypothetical', 'v.alquiler', 'v.joven', 'v.gente'],
    level: 'B2',
    topics: ['home', 'opinions'],
    blanks: ['subiera'],
  },
  {
    id: 's.c82',
    es: 'No creo que el color de la fachada sea el problema, la verdad.',
    en: 'I don’t think the colour of the façade is the problem, honestly.',
    concepts: ['g.subjunctive-opinion', 'v.color', 'p.la-verdad-es-que'],
    level: 'B2',
    topics: ['opinions', 'home'],
  },
  {
    id: 's.c83',
    es: 'Me comentó que en agosto no había nadie en la oficina, y no me extraña.',
    en: 'He mentioned there was nobody in the office in August, and it doesn’t surprise me.',
    concepts: ['p.me-comento-que', 'v.agosto', 'p.no-me-extrana', 'g.reported-speech'],
    level: 'B2',
    topics: ['work'],
  },
  {
    id: 's.c84',
    es: 'Por un lado el pan de aquí es mejor; por otro, cuesta el doble.',
    en: 'On one hand the bread here is better; on the other, it costs twice as much.',
    concepts: ['p.por-un-lado', 'v.pan', 'g.comparisons'],
    level: 'B2',
    topics: ['food', 'opinions'],
  },
  {
    id: 's.c85',
    es: 'A lo mejor está en casa, pero a estas horas yo no llamaría.',
    en: 'He might be at home, but I wouldn’t call at this hour.',
    concepts: ['p.a-lo-mejor', 'v.casa', 'g.conditional', 'v.hora'],
    level: 'B2',
    topics: ['social'],
  },
  {
    id: 's.c86',
    es: 'Aun así, no entiendo por qué nadie dijo nada en su momento.',
    en: 'Even so, I don’t understand why nobody said anything at the time.',
    concepts: ['p.aun-asi', 'p.no-entiendo', 'v.por-que', 'v.decir'],
    level: 'B2',
    topics: ['work', 'opinions'],
  },

  // --- Staking a position, and softening it --------------------------------
  {
    id: 's.c87',
    es: 'En mi opinión el problema no es el precio, es que no hay oferta.',
    en: 'In my opinion the problem isn’t the price, it’s that there’s no supply.',
    concepts: ['p.en-mi-opinion', 'v.vivienda'],
    level: 'B2',
    topics: ['opinions', 'home'],
  },
  {
    id: 's.c88',
    es: 'Desde mi punto de vista, eso se arregla con transporte, no con más coches.',
    en: 'From my point of view, that’s fixed with transport, not with more cars.',
    concepts: ['p.desde-mi-punto', 'v.coche', 'g.se-impersonal'],
    level: 'B2',
    topics: ['transport', 'opinions'],
  },
  {
    id: 's.c89',
    es: 'En realidad nunca lo dijo así; se lo han atribuido después.',
    en: 'Actually he never said it that way; it’s been attributed to him since.',
    concepts: ['p.en-realidad', 'g.present-perfect', 'g.object-pronouns'],
    level: 'B2',
    topics: ['opinions'],
  },
  {
    id: 's.c90',
    es: 'De hecho, las redes sociales fueron donde primero se supo.',
    en: 'In fact, social media was where it was first known.',
    concepts: ['p.de-hecho', 'v.red-social', 'g.se-impersonal'],
    level: 'B2',
    topics: ['opinions'],
  },
  {
    id: 's.c91',
    es: 'Estoy de acuerdo en parte: el diagnóstico sí, la solución no.',
    en: 'I partly agree: with the diagnosis yes, with the solution no.',
    concepts: ['p.estoy-de-acuerdo-en-parte'],
    level: 'B2',
    topics: ['opinions'],
  },
  {
    id: 's.c92',
    es: 'Supongo que tendrán sus motivos, aunque a mí no me convencen.',
    en: 'I suppose they must have their reasons, though they don’t convince me.',
    concepts: ['p.supongo-que', 'v.aunque', 'g.future'],
    level: 'B2',
    topics: ['opinions', 'work'],
  },
  {
    id: 's.c93',
    es: 'Igual me equivoco, pero yo diría que ya lo sabían.',
    en: 'I might be wrong, but I’d say they already knew.',
    concepts: ['p.igual-viene', 'g.conditional', 'g.imperfect'],
    level: 'B2',
    topics: ['opinions'],
    register: 'colloquial',
  },
  {
    id: 's.c94',
    es: 'Me imagino que a estas alturas ya se habrán enterado todos.',
    en: 'I imagine by this point everyone must have found out.',
    concepts: ['p.me-imagino-que', 'g.future'],
    level: 'B2',
    topics: ['social', 'work'],
  },
  {
    id: 's.c95',
    es: 'Por lo que parece, la noticia era falsa desde el principio.',
    en: 'From what it looks like, the story was false from the start.',
    concepts: ['p.por-lo-que-parece', 'v.noticia', 'g.imperfect'],
    level: 'B2',
    topics: ['opinions'],
  },
  {
    id: 's.c96',
    es: 'Es decir, que hay que tener en cuenta el medio ambiente, no solo el coste.',
    en: 'That is to say, the environment has to be taken into account, not just the cost.',
    concepts: ['p.es-decir', 'p.tener-en-cuenta', 'v.medioambiente'],
    level: 'B2',
    topics: ['opinions'],
  },
  {
    id: 's.c97',
    es: 'Habría que tener en cuenta que no todos tienen el mismo horario.',
    en: 'It would have to be borne in mind that not everyone has the same schedule.',
    concepts: ['p.tener-en-cuenta', 'v.horario', 'g.conditional'],
    level: 'B2',
    topics: ['work', 'opinions'],
  },
  {
    id: 's.c98',
    es: 'Total, que después de dos horas de reunión no decidimos nada.',
    en: 'Anyway, so after a two-hour meeting we decided nothing.',
    concepts: ['p.en-plan-b2', 'v.reunion', 'g.preterite'],
    level: 'B2',
    topics: ['work', 'storytelling'],
    register: 'colloquial',
  },
  {
    id: 's.c99',
    es: 'Por cierto, ¿al final qué pasó con lo del contrato?',
    en: 'By the way, what happened with the contract thing in the end?',
    concepts: ['p.por-cierto', 'g.lo-nominal', 'g.preterite'],
    level: 'B2',
    topics: ['work', 'social'],
    register: 'colloquial',
  },
  {
    id: 's.c100',
    es: '¡Venga ya! Eso no te lo crees ni tú.',
    en: 'Oh come on! Not even you believe that.',
    concepts: ['p.venga-ya', 'g.object-pronouns'],
    level: 'B2',
    topics: ['slang', 'opinions'],
    register: 'colloquial',
  },
  {
    id: 's.c101',
    es: '¿Volver a empezar de cero? Ni de broma.',
    en: 'Start again from scratch? Not a chance.',
    concepts: ['p.ni-de-broma', 'v.cero'],
    level: 'B2',
    topics: ['slang', 'work'],
    register: 'colloquial',
  },
  {
    id: 's.c102',
    es: 'Resumiendo: mucha noticia y muy pocos datos.',
    en: 'To sum up: plenty of headlines and very little data.',
    concepts: ['p.resumiendo', 'v.noticia', 'v.dato'],
    level: 'B2',
    topics: ['opinions'],
  },
  {
    id: 's.c103',
    es: 'El medio ambiente ya no es un tema secundario para casi nadie.',
    en: 'The environment is no longer a side issue for almost anyone.',
    concepts: ['v.medioambiente', 'g.negation'],
    level: 'B2',
    topics: ['opinions'],
  },
  {
    id: 's.c104',
    es: 'Las redes sociales amplifican la polémica y luego se olvida todo.',
    en: 'Social media amplifies the controversy and then it all gets forgotten.',
    concepts: ['v.red-social', 'v.polemica', 'g.se-impersonal'],
    level: 'B2',
    topics: ['opinions'],
  },
];
