import type { Sentence } from '@/content/types';

/**
 * C1 sentences. Many of these are pairs in disguise: the same content said two
 * ways, where the difference is register, hedging or implication rather than
 * meaning.
 *
 * Several are deliberately ironic. Their `note` explains the gap between what
 * the words say and what the speaker means — which is precisely the skill.
 */
export const c1CoreSentences: Sentence[] = [
  // --- Conceding vs dismissing ---------------------------------------------
  {
    id: 's.d1',
    es: 'Aunque tienes razón, no creo que sea el momento.',
    en: "Although you're right, I don't think this is the moment.",
    concepts: ['g.aunque-nuance', 'p.tener-razon', 'g.subjunctive-opinion'],
    level: 'C1',
    topics: ['opinions'],
    blanks: ['tienes'],
    note: 'Indicative: the rightness is granted before the objection lands.',
  },
  {
    id: 's.d2',
    es: 'Aunque tengas razón, vamos a hacerlo así.',
    en: "Even if you're right, we're doing it this way.",
    concepts: ['g.aunque-nuance'],
    level: 'C1',
    topics: ['opinions'],
    blanks: ['tengas'],
    note: 'Subjunctive: the rightness is waved aside as beside the point. Same words, colder.',
  },
  {
    id: 's.d3',
    es: 'Si bien la medida es necesaria, no termina de resolver el problema de fondo.',
    en: 'While the measure is necessary, it doesn’t quite address the underlying problem.',
    concepts: ['p.si-bien', 'p.no-termina-de', 'v.medida'],
    level: 'C1',
    topics: ['opinions'],
    register: 'formal',
  },
  {
    id: 's.d4',
    es: 'Por mucho que lo intente, no consigo verle la lógica.',
    en: 'However much I try, I can’t see the logic in it.',
    concepts: ['p.por-mucho-que', 'g.aunque-nuance'],
    level: 'C1',
    topics: ['opinions'],
  },

  // --- Lo, and naming abstractions -----------------------------------------
  {
    id: 's.d5',
    es: 'Lo difícil no es empezar, es mantenerlo.',
    en: 'The hard part isn’t starting, it’s keeping it up.',
    concepts: ['g.lo-nominal'],
    level: 'C1',
    topics: ['opinions'],
    blanks: ['Lo difícil'],
  },
  {
    id: 's.d6',
    es: 'No te imaginas lo mal que se portó.',
    en: 'You can’t imagine how badly he behaved.',
    concepts: ['g.lo-nominal'],
    level: 'C1',
    topics: ['storytelling'],
  },
  {
    id: 's.d7',
    es: 'Lo de la reunión lo dejamos para el lunes, ¿te parece?',
    en: 'We’ll leave the whole meeting thing until Monday, does that work?',
    concepts: ['g.lo-nominal', 'v.reunion'],
    level: 'C1',
    topics: ['work'],
    register: 'colloquial',
    note: 'lo de names a whole situation without describing it — near-untranslatable and everywhere.',
  },
  {
    id: 's.d8',
    es: 'Lo que más me sorprendió fue el tono, no el contenido.',
    en: 'What surprised me most was the tone, not the content.',
    concepts: ['g.lo-nominal', 'v.tono'],
    level: 'C1',
    topics: ['opinions'],
  },

  // --- Real or hypothetical antecedents ------------------------------------
  {
    id: 's.d9',
    es: 'Busco a alguien que sepa alemán y pueda empezar ya.',
    en: 'I’m looking for someone who knows German and can start straight away.',
    concepts: ['g.subjunctive-relative', 'v.aleman'],
    level: 'C1',
    topics: ['work'],
    blanks: ['sepa'],
    note: 'Subjunctive: no such person identified yet — anyone who fits will do.',
  },
  {
    id: 's.d10',
    es: 'Conozco a alguien que sabe alemán, te paso su contacto.',
    en: 'I know someone who knows German, I’ll pass you their details.',
    concepts: ['g.subjunctive-relative'],
    level: 'C1',
    topics: ['work'],
    note: 'Indicative: a specific, existing person. Same clause, opposite implication.',
  },
  {
    id: 's.d11',
    es: 'No hay nada que podamos hacer a estas alturas.',
    en: 'There’s nothing we can do at this stage.',
    concepts: ['g.subjunctive-relative'],
    level: 'C1',
    topics: ['opinions'],
  },
  {
    id: 's.d12',
    es: 'Pase lo que pase, avísame en cuanto sepas algo.',
    en: 'Whatever happens, let me know as soon as you hear anything.',
    concepts: ['g.subjunctive-relative'],
    level: 'C1',
    topics: ['social'],
    note: 'The doubled verb — pase lo que pase, digan lo que digan — means "no matter what".',
  },

  // --- Irony, where the words say the opposite -----------------------------
  {
    id: 's.d13',
    es: 'Pues sí que empezamos bien.',
    en: 'Well, this is a great start.',
    concepts: ['p.pues-si-que'],
    level: 'C1',
    topics: ['slang'],
    register: 'colloquial',
    note: 'Said when something has already gone wrong. Positive words, negative meaning.',
  },
  {
    id: 's.d14',
    es: 'Sí, hombre, sí. Y yo me lo creo.',
    en: 'Yeah, right. And I believe it.',
    concepts: ['p.si-hombre'],
    level: 'C1',
    topics: ['slang'],
    register: 'colloquial',
    note: 'Formally agreement, actually flat refusal. The intonation does everything.',
  },
  {
    id: 's.d15',
    es: 'Vaya tela con el horario nuevo.',
    en: 'Unbelievable, this new schedule.',
    concepts: ['p.vaya-tela', 'v.horario'],
    level: 'C1',
    topics: ['work', 'slang'],
    register: 'colloquial',
  },
  {
    id: 's.d16',
    es: 'Llegó tarde y encima se quejó de la comida.',
    en: 'He turned up late and on top of that complained about the food.',
    concepts: ['p.encima', 'v.quejarse'],
    level: 'C1',
    topics: ['storytelling'],
    note: 'encima is not neutral "also" — it carries the grievance.',
  },
  {
    id: 's.d17',
    es: 'Su explicación no tuvo desperdicio, todo hay que decirlo.',
    en: 'His explanation was really something, it has to be said.',
    concepts: ['p.merecer-la-pena-c1', 'p.todo-hay-que-decirlo'],
    level: 'C1',
    topics: ['opinions'],
    note: 'Praise on the surface; in this frame, almost certainly mockery.',
  },

  // --- Hedging and softening -----------------------------------------------
  {
    id: 's.d18',
    es: 'No es que no me guste, es que no me convence del todo.',
    en: "It's not that I don't like it, it's that it doesn't fully convince me.",
    concepts: ['p.no-es-que', 'g.reformulation'],
    level: 'C1',
    topics: ['opinions'],
    blanks: ['guste'],
    note: 'First clause subjunctive, second indicative — the standard hedge.',
  },
  {
    id: 's.d19',
    es: 'Hasta cierto punto estoy de acuerdo; dicho esto, hay matices.',
    en: 'Up to a point I agree; that said, there are nuances.',
    concepts: ['p.hasta-cierto-punto', 'p.dicho-esto', 'v.matiz'],
    level: 'C1',
    topics: ['opinions'],
  },
  {
    id: 's.d20',
    es: 'Más bien diría que es una cuestión de enfoque.',
    en: "I'd say it's rather a question of approach.",
    concepts: ['p.mas-bien', 'v.enfoque', 'g.conditional'],
    level: 'C1',
    topics: ['opinions'],
  },
  {
    id: 's.d21',
    es: 'Permítame que matice: no estoy en contra, soy reticente.',
    en: 'Allow me to qualify that: I’m not against it, I’m guarded.',
    concepts: ['v.matizar', 'v.reticente'],
    level: 'C1',
    topics: ['opinions'],
    register: 'formal',
  },

  // --- Reformulating the same content --------------------------------------
  {
    id: 's.d22',
    es: 'Se ha cometido un error en la facturación.',
    en: 'An error has been made in the billing.',
    concepts: ['g.reformulation', 'g.se-impersonal'],
    level: 'C1',
    topics: ['work'],
    register: 'formal',
    note: 'Compare: "os habéis equivocado". Same fact, no one blamed.',
  },
  {
    id: 's.d23',
    es: 'A raíz de la polémica, la empresa cambió de postura.',
    en: 'In the wake of the controversy, the company changed its stance.',
    concepts: ['p.a-raiz-de', 'v.polemica', 'v.postura', 'v.empresa'],
    level: 'C1',
    topics: ['work', 'opinions'],
    register: 'formal',
  },
  {
    id: 's.d24',
    es: 'Dicho de otro modo, el planteamiento era erróneo desde el principio.',
    en: 'To put it another way, the approach was wrong from the start.',
    concepts: ['p.dicho-de-otro-modo', 'v.planteamiento'],
    level: 'C1',
    topics: ['opinions'],
  },
  {
    id: 's.d25',
    es: 'De ahí que sea tan difícil encontrar piso en el centro.',
    en: 'Which is why it’s so hard to find a flat in the centre.',
    concepts: ['p.de-ahi-que', 'v.piso'],
    level: 'C1',
    topics: ['home', 'opinions'],
    note: 'de ahí que always takes the subjunctive.',
  },
  {
    id: 's.d26',
    es: 'Te lo presto siempre y cuando me lo devuelvas el viernes.',
    en: "I'll lend it to you provided you give it back on Friday.",
    concepts: ['p.siempre-y-cuando'],
    level: 'C1',
    topics: ['social'],
  },
  {
    id: 's.d27',
    es: 'Ahora bien, en la medida en que asumamos el coste, tiene sentido.',
    en: 'That said, insofar as we take on the cost, it makes sense.',
    concepts: ['p.ahora-bien', 'p.en-la-medida-en-que', 'v.asumir'],
    level: 'C1',
    topics: ['work', 'opinions'],
    register: 'formal',
  },

  // --- Idiom in ordinary use -----------------------------------------------
  {
    id: 's.d28',
    es: 'Como no se ponga las pilas, no aprueba.',
    en: 'If he doesn’t get his act together, he won’t pass.',
    concepts: ['p.ponerse-las-pilas', 'v.aprobar'],
    level: 'C1',
    topics: ['university', 'slang'],
    register: 'colloquial',
    note: 'como + subjunctive is a threat-flavoured conditional, very common in speech.',
  },
  {
    id: 's.d29',
    es: 'Se fue por las ramas y al final no contestó a la pregunta.',
    en: 'He went off on a tangent and in the end didn’t answer the question.',
    concepts: ['p.irse-por-las-ramas', 'v.al-final'],
    level: 'C1',
    topics: ['opinions'],
  },
  {
    id: 's.d30',
    es: 'Metí la pata, y por si fuera poco delante de su madre.',
    en: 'I put my foot in it, and as if that weren’t enough, in front of his mother.',
    concepts: ['p.meter-la-pata', 'p.por-si-fuera-poco'],
    level: 'C1',
    topics: ['social', 'storytelling'],
    register: 'colloquial',
  },
  {
    id: 's.d31',
    es: 'Aceptó a regañadientes, pero aceptó.',
    en: 'He agreed grudgingly, but he agreed.',
    concepts: ['p.a-regañadientes'],
    level: 'C1',
    topics: ['storytelling'],
  },
  {
    id: 's.d32',
    es: 'De buenas a primeras me dijo que se iba del país.',
    en: 'Out of nowhere he told me he was leaving the country.',
    concepts: ['p.de-buenas-a-primeras', 'g.reported-speech', 'v.pais'],
    level: 'C1',
    topics: ['storytelling'],
  },

  // --- Aunque: the same word, two different concessions -------------------
  {
    id: 's.d33',
    es: 'Aunque tienes razón, el planteamiento sigue sin convencerme.',
    en: "Although you're right, the approach still doesn't convince me.",
    concepts: ['g.aunque-nuance', 'v.planteamiento', 'p.tener-razon'],
    level: 'C1',
    topics: ['opinions'],
    note: 'Indicative: the speaker grants the point as an established fact.',
  },
  {
    id: 's.d34',
    es: 'Aunque tengas razón, eso no cambia lo que hay que hacer ahora.',
    en: "Even if you're right, that doesn't change what has to be done now.",
    concepts: ['g.aunque-nuance'],
    level: 'C1',
    topics: ['opinions'],
    blanks: ['tengas'],
    note: 'Subjunctive: the point is conceded only hypothetically, and then set aside.',
  },
  {
    id: 's.d35',
    es: 'Aunque cueste creerlo, la propuesta salió adelante por unanimidad.',
    en: 'Hard as it is to believe, the proposal went through unanimously.',
    concepts: ['g.aunque-nuance'],
    level: 'C1',
    topics: ['work', 'opinions'],
  },
  {
    id: 's.d36',
    es: 'Si bien el informe es riguroso, sus conclusiones resultan discutibles.',
    en: 'While the report is rigorous, its conclusions are debatable.',
    concepts: ['p.si-bien'],
    level: 'C1',
    topics: ['work', 'opinions'],
    register: 'formal',
    note: 'si bien belongs to written register — you will read it far more often than hear it.',
  },
  {
    id: 's.d37',
    es: 'Dicho esto, tampoco conviene exagerar el alcance del problema.',
    en: "That said, there's no point exaggerating the scale of the problem either.",
    concepts: ['p.dicho-esto'],
    level: 'C1',
    topics: ['opinions'],
  },
  {
    id: 's.d38',
    es: 'Ahora bien, habría que preguntarse a quién beneficia realmente.',
    en: 'That being said, one would have to ask who really benefits.',
    concepts: ['p.ahora-bien', 'g.conditional'],
    level: 'C1',
    topics: ['opinions'],
    register: 'formal',
  },

  // --- Lo: naming the abstract ---------------------------------------------
  {
    id: 's.d39',
    es: 'Lo curioso es que nadie se dio cuenta hasta el final.',
    en: 'The curious thing is that nobody noticed until the end.',
    concepts: ['g.lo-nominal', 'p.darse-cuenta'],
    level: 'C1',
    topics: ['storytelling'],
    blanks: ['Lo'],
  },
  {
    id: 's.d40',
    es: 'Lo de la reunión lo dejamos para la semana que viene.',
    en: "We'll leave the meeting thing until next week.",
    concepts: ['g.lo-nominal', 'v.reunion'],
    level: 'C1',
    topics: ['work'],
    note: 'lo de X = "that business with X" — vague on purpose, and extremely common.',
  },
  {
    id: 's.d41',
    es: 'No te imaginas lo bien que se come en ese pueblo.',
    en: "You can't imagine how well you eat in that village.",
    concepts: ['g.lo-nominal', 'g.se-impersonal'],
    level: 'C1',
    topics: ['food', 'travel'],
    note: 'lo + adverbio + que intensifies: lo bien que, lo rápido que, lo mal que.',
  },
  {
    id: 's.d42',
    es: 'Lo que más me sorprendió fue lo tranquilo que se lo tomó.',
    en: 'What surprised me most was how calmly he took it.',
    concepts: ['g.lo-nominal', 'g.emphasis'],
    level: 'C1',
    topics: ['storytelling', 'feelings'],
  },
  {
    id: 's.d43',
    es: 'Lo difícil no es aprobar, sino mantener el nivel después.',
    en: "The hard part isn't passing, it's keeping the level up afterwards.",
    concepts: ['g.lo-nominal', 'v.aprobar'],
    level: 'C1',
    topics: ['university'],
  },

  // --- Relative clauses: specific or not ----------------------------------
  {
    id: 's.d44',
    es: 'Necesitamos a alguien que sepa moverse en ese ámbito.',
    en: 'We need someone who knows how to operate in that field.',
    concepts: ['g.subjunctive-relative', 'v.ambito'],
    level: 'C1',
    topics: ['work'],
    blanks: ['sepa'],
    note: 'The person does not exist yet, so the relative clause takes the subjunctive.',
  },
  {
    id: 's.d45',
    es: 'Conozco a alguien que sabe moverse en ese ámbito.',
    en: 'I know someone who knows how to operate in that field.',
    concepts: ['g.subjunctive-relative', 'v.ambito'],
    level: 'C1',
    topics: ['work'],
    note: 'Same clause, indicative: this person is real and identified. Compare with the previous one.',
  },
  {
    id: 's.d46',
    es: 'No hay nada que me saque más de quicio que la impuntualidad.',
    en: 'There is nothing that drives me up the wall more than lateness.',
    concepts: ['g.subjunctive-relative', 'p.sacar-de-quicio'],
    level: 'C1',
    topics: ['feelings'],
    note: 'After a negated antecedent — no hay nada que — the subjunctive is obligatory.',
  },
  {
    id: 's.d47',
    es: 'Haz lo que te parezca, pero avísame antes.',
    en: 'Do whatever you think best, but let me know first.',
    concepts: ['g.subjunctive-relative', 'g.commands'],
    level: 'C1',
    topics: ['social'],
  },

  // --- Irony and implication -----------------------------------------------
  {
    id: 's.d48',
    es: 'Pues sí que hemos empezado con buen pie.',
    en: "Well, we've certainly got off to a great start.",
    concepts: ['p.pues-si-que'],
    level: 'C1',
    topics: ['slang'],
    register: 'colloquial',
    note: 'Positive on paper, sarcastic in practice. Delivery carries the whole meaning.',
  },
  {
    id: 's.d49',
    es: 'Vaya tela con el horario que nos han puesto este mes.',
    en: "Unbelievable, the schedule they've given us this month.",
    concepts: ['p.vaya-tela', 'v.horario'],
    level: 'C1',
    topics: ['work', 'slang'],
    register: 'colloquial',
  },
  {
    id: 's.d50',
    es: 'Y encima me lo cobraron dos veces, no te digo más.',
    en: 'And on top of that they charged me twice — need I say more.',
    concepts: ['p.encima', 'p.no-te-digo-mas', 'p.me-han-cobrado'],
    level: 'C1',
    topics: ['shopping', 'slang'],
    register: 'colloquial',
  },
  {
    id: 's.d51',
    es: 'Menos mal que lo comprobé antes de enviarlo.',
    en: 'Just as well I checked it before sending it.',
    concepts: ['p.menos-mal'],
    level: 'C1',
    topics: ['work'],
    register: 'colloquial',
  },
  {
    id: 's.d52',
    es: 'Sí, hombre, sí, y yo me lo creo.',
    en: 'Yeah, right, and I believe it.',
    concepts: ['p.si-hombre'],
    level: 'C1',
    topics: ['slang'],
    register: 'colloquial',
    note: 'Formally agreement, functionally flat refusal. Spain runs on this kind of inversion.',
  },
  {
    id: 's.d53',
    es: 'Por si fuera poco, encima llegó tarde a su propia presentación.',
    en: 'As if that weren’t enough, he then turned up late to his own presentation.',
    concepts: ['p.por-si-fuera-poco', 'p.encima'],
    level: 'C1',
    topics: ['work', 'storytelling'],
  },
  {
    id: 's.d54',
    es: 'Su respuesta no tuvo desperdicio, te la cuento luego.',
    en: 'His reply was priceless, I’ll tell you later.',
    concepts: ['p.merecer-la-pena-c1'],
    level: 'C1',
    topics: ['storytelling', 'slang'],
    register: 'colloquial',
  },

  // --- Hedging and softening ----------------------------------------------
  {
    id: 's.d55',
    es: 'No es que no me interese, es que no tengo tiempo material.',
    en: "It's not that I'm not interested, it's that I genuinely have no time.",
    concepts: ['p.no-es-que'],
    level: 'C1',
    topics: ['social', 'opinions'],
    blanks: ['interese'],
    note: 'First clause subjunctive, second indicative — the asymmetry is the rule.',
  },
  {
    id: 's.d56',
    es: 'Estoy de acuerdo hasta cierto punto, pero habría matices que añadir.',
    en: 'I agree up to a point, but there would be some nuances to add.',
    concepts: ['p.hasta-cierto-punto', 'v.matiz'],
    level: 'C1',
    topics: ['opinions'],
  },
  {
    id: 's.d57',
    es: 'En cierto modo tiene razón, aunque no lo diría tan alto.',
    en: "In a way he's right, though I wouldn't say it so loudly.",
    concepts: ['p.en-cierto-modo', 'g.conditional'],
    level: 'C1',
    topics: ['opinions'],
  },
  {
    id: 's.d58',
    es: 'El argumento no termina de sostenerse cuando miras los datos.',
    en: "The argument doesn't quite hold up when you look at the figures.",
    concepts: ['p.no-termina-de', 'v.dato'],
    level: 'C1',
    topics: ['opinions'],
  },
  {
    id: 's.d59',
    es: 'Por lo general funciona bien, todo hay que decirlo.',
    en: 'Generally speaking it works well, it has to be said.',
    concepts: ['p.por-lo-general', 'p.todo-hay-que-decirlo'],
    level: 'C1',
    topics: ['opinions'],
  },
  {
    id: 's.d60',
    es: 'Se mostró bastante reticente a comprometerse con una fecha.',
    en: 'He was fairly reluctant to commit to a date.',
    concepts: ['v.reticente'],
    level: 'C1',
    topics: ['work'],
  },
  {
    id: 's.d61',
    es: 'La respuesta fue un no rotundo, sin margen para negociar.',
    en: 'The answer was a flat no, with no room to negotiate.',
    concepts: ['v.rotundo'],
    level: 'C1',
    topics: ['work', 'opinions'],
  },

  // --- Reformulating and structuring an argument --------------------------
  {
    id: 's.d62',
    es: 'Dicho de otro modo: el problema no es técnico, es político.',
    en: 'To put it another way: the problem isn’t technical, it’s political.',
    concepts: ['p.dicho-de-otro-modo', 'g.reformulation'],
    level: 'C1',
    topics: ['opinions'],
  },
  {
    id: 's.d63',
    es: 'En otras palabras, nadie quiere asumir el coste.',
    en: 'In other words, nobody wants to take on the cost.',
    concepts: ['p.en-otras-palabras', 'v.asumir'],
    level: 'C1',
    topics: ['work', 'opinions'],
  },
  {
    id: 's.d64',
    es: 'Más bien diría que es una cuestión de prioridades.',
    en: "I'd say it's more a question of priorities.",
    concepts: ['p.mas-bien', 'g.conditional'],
    level: 'C1',
    topics: ['opinions'],
    note: 'más bien corrects a framing without contradicting the speaker outright.',
  },
  {
    id: 's.d65',
    es: 'Permítame que matice una cosa antes de seguir.',
    en: 'Allow me to qualify one thing before we go on.',
    concepts: ['v.matizar', 'g.register'],
    level: 'C1',
    topics: ['work', 'opinions'],
    register: 'formal',
    blanks: ['matice'],
  },
  {
    id: 's.d66',
    es: 'Conviene matizar que el estudio se hizo antes de la pandemia.',
    en: "It's worth qualifying that the study was done before the pandemic.",
    concepts: ['v.matizar', 'v.constatar'],
    level: 'C1',
    topics: ['opinions'],
    register: 'formal',
  },
  {
    id: 's.d67',
    es: 'Por lo tanto, cualquier comparación con el año pasado es engañosa.',
    en: 'Therefore any comparison with last year is misleading.',
    concepts: ['p.por-lo-tanto', 'g.comparisons'],
    level: 'C1',
    topics: ['opinions'],
    register: 'formal',
  },
  {
    id: 's.d68',
    es: 'Han subido los tipos de interés; de ahí que se hayan parado tantas obras.',
    en: 'Interest rates have gone up; hence so many building projects have stalled.',
    concepts: ['p.de-ahi-que', 'v.vivienda'],
    level: 'C1',
    topics: ['home'],
    blanks: ['hayan'],
    note: 'de ahí que always takes the subjunctive, however factual the consequence.',
  },
  {
    id: 's.d69',
    es: 'Te echo una mano siempre y cuando me avises con tiempo.',
    en: "I'll give you a hand provided you let me know in advance.",
    concepts: ['p.siempre-y-cuando', 'p.echar-una-mano'],
    level: 'C1',
    topics: ['social', 'work'],
    blanks: ['avises'],
  },
  {
    id: 's.d70',
    es: 'A raíz de la polémica, la empresa cambió por completo su postura.',
    en: 'In the wake of the controversy, the company completely changed its stance.',
    concepts: ['p.a-raiz-de', 'v.postura', 'v.polemica'],
    level: 'C1',
    topics: ['work', 'opinions'],
    register: 'formal',
  },
  {
    id: 's.d71',
    es: 'En la medida en que se cumplan los plazos, no habrá problema.',
    en: 'Insofar as the deadlines are met, there won’t be a problem.',
    concepts: ['p.en-la-medida-en-que'],
    level: 'C1',
    topics: ['work'],
    register: 'formal',
  },

  // --- Idiom in circulation ------------------------------------------------
  {
    id: 's.d72',
    es: 'Como no nos pongamos las pilas, no llegamos a la fecha.',
    en: "Unless we get our act together, we won't make the deadline.",
    concepts: ['p.ponerse-las-pilas'],
    level: 'C1',
    topics: ['work', 'slang'],
    register: 'colloquial',
    note: 'como + subjuntivo at the start of a sentence means "if/unless", with a warning tone.',
  },
  {
    id: 's.d73',
    es: 'Lleva toda la mañana dándome la lata con lo mismo.',
    en: "He's been going on at me about the same thing all morning.",
    concepts: ['p.dar-la-lata'],
    level: 'C1',
    topics: ['slang', 'work'],
    register: 'colloquial',
  },
  {
    id: 's.d74',
    es: 'Metí la pata al mencionarlo delante de todo el mundo.',
    en: 'I put my foot in it by mentioning it in front of everyone.',
    concepts: ['p.meter-la-pata'],
    level: 'C1',
    topics: ['social', 'storytelling'],
    register: 'colloquial',
  },
  {
    id: 's.d75',
    es: 'Estaba en las nubes y se le pasó la parada.',
    en: 'He had his head in the clouds and missed his stop.',
    concepts: ['p.estar-en-las-nubes'],
    level: 'C1',
    topics: ['transport', 'storytelling'],
    register: 'colloquial',
  },
  {
    id: 's.d76',
    es: 'No tengo ni pajolera idea de cómo funciona ese programa.',
    en: 'I haven’t the faintest idea how that programme works.',
    concepts: ['p.no-tener-ni-idea'],
    level: 'C1',
    topics: ['work', 'slang'],
    register: 'colloquial',
  },
  {
    id: 's.d77',
    es: 'Se fue por las ramas y no contestó a la pregunta.',
    en: 'He went off on a tangent and never answered the question.',
    concepts: ['p.irse-por-las-ramas'],
    level: 'C1',
    topics: ['opinions', 'work'],
  },
  {
    id: 's.d78',
    es: 'A duras penas conseguimos terminar antes de que cerraran.',
    en: 'We barely managed to finish before they closed.',
    concepts: ['p.a-duras-penas'],
    level: 'C1',
    topics: ['storytelling'],
    note: 'antes de que always takes the subjunctive: antes de que cerraran.',
  },
  {
    id: 's.d79',
    es: 'Ya te digo, con este calor no hay quien trabaje.',
    en: 'You can say that again — in this heat nobody can get any work done.',
    concepts: ['p.ya-te-digo', 'p.hace-calor'],
    level: 'C1',
    topics: ['weather', 'slang'],
    register: 'colloquial',
    note: 'no hay quien + subjuntivo — "there is nobody who can", a fixed complaint frame.',
  },
  {
    id: 's.d80',
    es: 'El tono del correo era escueto, casi seco.',
    en: 'The tone of the email was terse, almost curt.',
    concepts: ['v.tono', 'v.escueto'],
    level: 'C1',
    topics: ['work', 'social'],
  },
// --- Filling the gaps the audit found at C1 ------------------------------
  {
    id: 's.d81',
    es: 'Son problemas de otra índole, no conviene mezclarlos.',
    en: 'They are problems of a different nature; it’s unwise to mix them.',
    concepts: ['v.indole'],
    level: 'C1',
    topics: ['work', 'opinions'],
    register: 'formal',
  },
  {
    id: 's.d82',
    es: 'El estudio tiene un sesgo evidente: solo preguntaron a sus propios clientes.',
    en: 'The study has an obvious bias: they only asked their own customers.',
    concepts: ['v.sesgo', 'v.constatar'],
    level: 'C1',
    topics: ['opinions', 'work'],
  },

  // --- Idiom, met a second time in a different frame -----------------------
  {
    id: 's.d83',
    es: 'Deja de darme la lata con eso, ya te he dicho que no.',
    en: 'Stop going on at me about that, I’ve already told you no.',
    concepts: ['p.dar-la-lata', 'g.commands', 'g.present-perfect'],
    level: 'C1',
    topics: ['social', 'slang'],
    register: 'colloquial',
  },
  {
    id: 's.d84',
    es: 'Si me echas una mano con esto, terminamos en media hora.',
    en: 'If you give me a hand with this, we’ll finish in half an hour.',
    concepts: ['p.echar-una-mano', 'g.si-hypothetical'],
    level: 'C1',
    topics: ['work', 'social'],
  },
  {
    id: 's.d85',
    es: 'Perdona, estaba en las nubes. ¿Qué me decías?',
    en: 'Sorry, I was miles away. What were you saying?',
    concepts: ['p.estar-en-las-nubes', 'g.imperfect'],
    level: 'C1',
    topics: ['social', 'slang'],
    register: 'colloquial',
  },
  {
    id: 's.d86',
    es: 'De sistemas no tengo ni pajolera idea, que lo mire otro.',
    en: 'I haven’t the faintest idea about systems, let someone else look at it.',
    concepts: ['p.no-tener-ni-idea', 'g.subjunctive-intro'],
    level: 'C1',
    topics: ['work', 'slang'],
    register: 'colloquial',
  },
  {
    id: 's.d87',
    es: 'Firmó a regañadientes, y se le notaba en la cara.',
    en: 'He signed grudgingly, and you could see it on his face.',
    concepts: ['p.a-regañadientes', 'g.preterite'],
    level: 'C1',
    topics: ['work', 'storytelling'],
  },
  {
    id: 's.d88',
    es: 'De buenas a primeras cambiaron el plan sin avisar a nadie.',
    en: 'Out of nowhere they changed the plan without telling anyone.',
    concepts: ['p.de-buenas-a-primeras', 'g.preterite'],
    level: 'C1',
    topics: ['work', 'storytelling'],
  },
  {
    id: 's.d89',
    es: 'Llegamos a duras penas, y encima el sitio estaba cerrado.',
    en: 'We barely made it, and on top of that the place was shut.',
    concepts: ['p.a-duras-penas', 'p.encima'],
    level: 'C1',
    topics: ['travel', 'storytelling'],
  },
  {
    id: 's.d90',
    es: 'Menos mal que guardé una copia, si no lo habríamos perdido todo.',
    en: 'Just as well I kept a copy, otherwise we’d have lost everything.',
    concepts: ['p.menos-mal', 'g.si-hypothetical', 'g.pluperfect'],
    level: 'C1',
    topics: ['work'],
    register: 'colloquial',
  },
  {
    id: 's.d91',
    es: 'Llegó tarde, sin el informe y sin disculparse. No te digo más.',
    en: 'He arrived late, without the report and without apologising. Need I say more.',
    concepts: ['p.no-te-digo-mas', 'v.sin'],
    level: 'C1',
    topics: ['work', 'slang'],
    register: 'colloquial',
  },
  {
    id: 's.d92',
    es: '—Está imposible el centro en agosto. —Ya te digo.',
    en: '“The centre is impossible in August.” “You can say that again.”',
    concepts: ['p.ya-te-digo', 'v.agosto'],
    level: 'C1',
    topics: ['city', 'slang'],
    register: 'colloquial',
  },

  // --- Hedging and structuring, second pass --------------------------------
  {
    id: 's.d93',
    es: 'En cierto modo nos vino bien, aunque en su momento no lo pareciera.',
    en: 'In a way it worked out for us, though at the time it didn’t seem so.',
    concepts: ['p.en-cierto-modo', 'v.aunque', 'g.aunque-nuance'],
    level: 'C1',
    topics: ['opinions', 'past'],
  },
  {
    id: 's.d94',
    es: 'Por lo general no suelo opinar de estas cosas, pero esta vez sí.',
    en: 'Generally speaking I don’t tend to comment on these things, but this time I will.',
    concepts: ['p.por-lo-general', 'v.postura'],
    level: 'C1',
    topics: ['opinions'],
  },
  {
    id: 's.d95',
    es: 'En otras palabras: el enfoque era correcto y el momento pésimo.',
    en: 'In other words: the approach was right and the timing dreadful.',
    concepts: ['p.en-otras-palabras', 'v.enfoque'],
    level: 'C1',
    topics: ['work', 'opinions'],
  },
  {
    id: 's.d96',
    es: 'No se avisó a tiempo; por lo tanto, la queja está justificada.',
    en: 'Notice was not given in time; therefore the complaint is justified.',
    concepts: ['p.por-lo-tanto', 'g.se-impersonal', 'v.quejarse'],
    level: 'C1',
    topics: ['work', 'opinions'],
    register: 'formal',
  },
  {
    id: 's.d97',
    es: 'Son cuestiones de índole muy distinta, no conviene tratarlas juntas.',
    en: 'These are questions of a very different nature; they shouldn’t be dealt with together.',
    concepts: ['v.indole', 'v.matizar'],
    level: 'C1',
    topics: ['work', 'opinions'],
    register: 'formal',
  },
  {
    id: 's.d98',
    es: 'El enfoque cambia por completo si lo miras desde el otro lado.',
    en: 'The angle changes completely if you look at it from the other side.',
    concepts: ['v.enfoque', 'v.postura'],
    level: 'C1',
    topics: ['opinions'],
  },
  {
    id: 's.d99',
    es: 'Cualquier encuesta hecha así arrastra un sesgo evidente.',
    en: 'Any survey done that way carries an obvious bias.',
    concepts: ['v.sesgo', 'v.dato'],
    level: 'C1',
    topics: ['opinions', 'work'],
  },
  {
    id: 's.d100',
    es: 'Se negó en redondo: un no rotundo, sin explicaciones.',
    en: 'He flatly refused: a categorical no, with no explanation.',
    concepts: ['v.rotundo', 'g.preterite'],
    level: 'C1',
    topics: ['work', 'opinions'],
  },
  {
    id: 's.d101',
    es: 'Quiero plantear una cosa antes de que se cierre el punto.',
    en: 'I want to raise something before this point is closed.',
    concepts: ['v.plantear', 'g.subjunctive-intro'],
    level: 'C1',
    topics: ['work'],
    blanks: ['cierre'],
  },
  {
    id: 's.d102',
    es: 'Lo planteó como una duda, pero era una crítica en toda regla.',
    en: 'He framed it as a question, but it was a full-blown criticism.',
    concepts: ['v.plantear', 'v.planteamiento', 'g.imperfect'],
    level: 'C1',
    topics: ['work', 'opinions'],
  },

  // --- Reformulation as a move, not a phrase -------------------------------
  {
    id: 's.d103',
    es: 'Se ha producido un retraso. O mejor dicho: nadie lo pidió a tiempo.',
    en: 'A delay has occurred. Or rather: nobody ordered it in time.',
    concepts: ['g.reformulation', 'g.se-impersonal', 'v.retraso'],
    level: 'C1',
    topics: ['work'],
    note: 'The impersonal first version hides the agent; the reformulation puts it back. Both are true.',
  },
  {
    id: 's.d104',
    es: 'Es complicado. Bueno, complicado no: es que no quieren.',
    en: 'It’s complicated. Well, not complicated: they just don’t want to.',
    concepts: ['g.reformulation', 'p.no-es-que'],
    level: 'C1',
    topics: ['work', 'opinions'],
    register: 'colloquial',
    note: 'Spoken reformulation: state it, reject your own word, replace it. Very common in argument.',
  },
  {
    id: 's.d105',
    es: 'Digamos que no fue su mejor intervención, por decirlo suavemente.',
    en: 'Let’s say it wasn’t his finest contribution, to put it mildly.',
    concepts: ['g.reformulation', 'p.dicho-de-otro-modo'],
    level: 'C1',
    topics: ['opinions'],
  },
  {
    id: 's.d106',
    es: 'Lo que quería decir, y no me salió, es que el plazo era imposible.',
    en: 'What I meant, and failed to say, is that the deadline was impossible.',
    concepts: ['g.reformulation', 'g.lo-nominal'],
    level: 'C1',
    topics: ['work'],
  },

  // --- Aunque, third pass: the choice carries the attitude -----------------
  {
    id: 's.d107',
    es: 'Aunque me lo pidas de rodillas, no voy a firmar eso.',
    en: 'Even if you beg me, I’m not signing that.',
    concepts: ['g.aunque-nuance', 'v.aunque'],
    level: 'C1',
    topics: ['work', 'opinions'],
    blanks: ['pidas'],
    note: 'Subjunctive: the begging is hypothetical and pre-emptively dismissed.',
  },
  {
    id: 's.d108',
    es: 'Aunque me lo pediste dos veces, se me pasó, y lo siento.',
    en: 'Even though you asked me twice, it slipped my mind, and I’m sorry.',
    concepts: ['g.aunque-nuance', 'g.preterite'],
    level: 'C1',
    topics: ['social', 'work'],
    note: 'Indicative: the asking actually happened and is being conceded.',
  },
  {
    id: 's.d109',
    es: 'Aunque sea la norma, sigue pareciéndome injusto.',
    en: 'Even if it is the rule, it still strikes me as unfair.',
    concepts: ['g.aunque-nuance', 'v.medida'],
    level: 'C1',
    topics: ['opinions'],
  },

  // --- Subjunctive relatives, with the antecedent doing the work -----------
  {
    id: 's.d110',
    es: 'Quiero un piso que dé al patio, no uno que dé a la calle.',
    en: 'I want a flat that looks onto the courtyard, not one onto the street.',
    concepts: ['g.subjunctive-relative', 'v.piso', 'v.dar'],
    level: 'C1',
    topics: ['home'],
    blanks: ['dé'],
    note: 'dé with an accent is the subjunctive of dar; de without is the preposition.',
  },
  {
    id: 's.d111',
    es: 'El que llegue primero coge sitio para todos.',
    en: 'Whoever gets there first saves seats for everyone.',
    concepts: ['g.subjunctive-relative', 'v.coger'],
    level: 'C1',
    topics: ['social'],
    note: 'el que + subjunctive = "whoever", an unidentified person. With llega it would be a known one.',
  },

  // --- Deepening the thinnest C1 concepts ---------------------------------
  {
    id: 's.d112',
    es: 'Le dio la lata toda la tarde hasta que cedió.',
    en: 'She went on at him all afternoon until he gave in.',
    concepts: ['p.dar-la-lata', 'g.preterite'],
    level: 'C1',
    topics: ['social', 'slang'],
    register: 'colloquial',
  },
  {
    id: 's.d113',
    es: 'Como no os pongáis las pilas, esto no sale.',
    en: 'Unless you lot get your act together, this isn’t happening.',
    concepts: ['p.ponerse-las-pilas', 'v.vosotros'],
    level: 'C1',
    topics: ['work', 'slang'],
    register: 'colloquial',
  },
  {
    id: 's.d114',
    es: '¿Me echáis una mano con las sillas antes de que llegue la gente?',
    en: 'Can you give me a hand with the chairs before people arrive?',
    concepts: ['p.echar-una-mano', 'v.vosotros', 'g.subjunctive-intro'],
    level: 'C1',
    topics: ['social'],
  },
  {
    id: 's.d115',
    es: 'Estabais en las nubes los dos, no oísteis nada.',
    en: 'You were both miles away, you didn’t hear a thing.',
    concepts: ['p.estar-en-las-nubes', 'v.vosotros', 'g.imperfect'],
    level: 'C1',
    topics: ['social', 'slang'],
    register: 'colloquial',
  },
  {
    id: 's.d116',
    es: 'De esto no tenéis ni pajolera idea, y se nota.',
    en: 'You haven’t the faintest idea about this, and it shows.',
    concepts: ['p.no-tener-ni-idea', 'v.vosotros', 'g.se-impersonal'],
    level: 'C1',
    topics: ['slang', 'work'],
    register: 'colloquial',
  },
  {
    id: 's.d117',
    es: 'Aceptaron a regañadientes y a duras penas cumplieron.',
    en: 'They agreed grudgingly and barely delivered.',
    concepts: ['p.a-regañadientes', 'p.a-duras-penas', 'g.preterite'],
    level: 'C1',
    topics: ['work'],
  },
  {
    id: 's.d118',
    es: 'De buenas a primeras nos cambiaron el sitio, sin avisar.',
    en: 'Out of nowhere they moved us, without warning.',
    concepts: ['p.de-buenas-a-primeras', 'g.preterite'],
    level: 'C1',
    topics: ['work', 'storytelling'],
  },
  {
    id: 's.d119',
    es: 'Menos mal que lo dijisteis, si no habríamos firmado.',
    en: 'Just as well you said so, otherwise we’d have signed.',
    concepts: ['p.menos-mal', 'v.vosotros', 'g.pluperfect'],
    level: 'C1',
    topics: ['work'],
    register: 'colloquial',
  },
  {
    id: 's.d120',
    es: 'Ni contestaron ni pidieron perdón. No te digo más.',
    en: 'They neither replied nor apologised. Need I say more.',
    concepts: ['p.no-te-digo-mas', 'g.negation'],
    level: 'C1',
    topics: ['work', 'slang'],
    register: 'colloquial',
  },
  {
    id: 's.d121',
    es: '—Está imposible aparcar por aquí. —Ya te digo, y cada año peor.',
    en: '“Parking round here is impossible.” “You can say that again, and worse every year.”',
    concepts: ['p.ya-te-digo', 'v.peor'],
    level: 'C1',
    topics: ['city', 'slang'],
    register: 'colloquial',
  },
  {
    id: 's.d122',
    es: 'En cierto modo os entiendo, aunque no lo habría hecho así.',
    en: 'In a way I understand you, though I wouldn’t have done it that way.',
    concepts: ['p.en-cierto-modo', 'v.vosotros', 'g.conditional'],
    level: 'C1',
    topics: ['opinions'],
  },
  {
    id: 's.d123',
    es: 'Por lo general no me meto, pero esta vez sí que voy a decir algo.',
    en: 'Generally I don’t get involved, but this time I am going to say something.',
    concepts: ['p.por-lo-general', 'g.emphasis'],
    level: 'C1',
    topics: ['opinions'],
  },
  {
    id: 's.d124',
    es: 'En otras palabras: no dijeron que no, dijeron que no ahora.',
    en: 'In other words: they didn’t say no, they said not now.',
    concepts: ['p.en-otras-palabras', 'g.precision'],
    level: 'C1',
    topics: ['work', 'opinions'],
  },
  {
    id: 's.d125',
    es: 'No se avisó con tiempo; por lo tanto, la queja procede.',
    en: 'Notice was not given in time; therefore the complaint stands.',
    concepts: ['p.por-lo-tanto', 'g.se-impersonal'],
    level: 'C1',
    topics: ['work'],
    register: 'formal',
  },
];
