import type { Sentence } from '@/content/types';

/**
 * C2 sentences. Many come in near-identical pairs where a single word changes
 * the speaker's position rather than the facts — which is the whole point of
 * the level.
 *
 * `note` carries the weight here: it explains what the choice signals, because
 * at C2 the answer is rarely wrong, only worse.
 */
export const c2CoreSentences: Sentence[] = [
  // --- Precisión: la palabra exacta ----------------------------------------
  {
    id: 's.e1c',
    es: 'No lo niega: alega que nadie le avisó.',
    en: 'He doesn’t deny it: he claims nobody told him.',
    concepts: ['v.alegar', 'g.precision'],
    level: 'C2',
    topics: ['work', 'opinions'],
    blanks: ['alega'],
    note: 'alegar deja caer que el hablante no se lo cree del todo.',
  },
  {
    id: 's.e2c',
    es: 'Sostiene que él no estaba allí, pese a las pruebas.',
    en: 'He maintains he wasn’t there, despite the evidence.',
    concepts: ['v.sostener', 'g.precision'],
    level: 'C2',
    topics: ['opinions'],
    note: 'sostener implica resistencia frente a la duda ajena; afirmar no.',
  },
  {
    id: 's.e3c',
    es: 'Ha habido un pequeño contratiempo con la entrega.',
    en: 'There’s been a slight hitch with the delivery.',
    concepts: ['v.contratiempo', 'g.precision'],
    level: 'C2',
    topics: ['work'],
    note: 'Elegir contratiempo en vez de problema le dice al cliente cómo reaccionar.',
  },
  {
    id: 's.e4c',
    es: 'Más que enfadada, yo diría que estaba decepcionada.',
    en: 'More than angry, I’d say she was disappointed.',
    concepts: ['v.molesto', 'g.precision', 'g.conditional'],
    level: 'C2',
    topics: ['feelings'],
  },
  {
    id: 's.e5c',
    es: 'La reacción del ministerio fue más bien tibia.',
    en: 'The ministry’s reaction was decidedly lukewarm.',
    concepts: ['v.tibio', 'p.mas-bien'],
    level: 'C2',
    topics: ['opinions'],
    note: 'tibio aplicado a una reacción es crítica, no descripción.',
  },
  {
    id: 's.e6c',
    es: 'Reconoció el error, aunque puntualizó que no era el único responsable.',
    en: 'He admitted the mistake, though he clarified he wasn’t solely responsible.',
    concepts: ['v.reconocer', 'v.matizar-c2', 'g.aunque-nuance'],
    level: 'C2',
    topics: ['work'],
  },

  // --- Colocaciones --------------------------------------------------------
  {
    id: 's.e7c',
    es: 'Aceptarlo ahora sentaría un precedente peligroso.',
    en: 'Accepting it now would set a dangerous precedent.',
    concepts: ['p.sentar-precedente', 'g.conditional'],
    level: 'C2',
    topics: ['work', 'opinions'],
    blanks: ['sentaría'],
  },
  {
    id: 's.e8c',
    es: 'Nadie quiso asumir el riesgo, así que no se hizo nada.',
    en: 'Nobody was willing to take the risk, so nothing was done.',
    concepts: ['p.asumir-un-riesgo', 'g.se-impersonal'],
    level: 'C2',
    topics: ['work'],
    note: 'asumir un riesgo — tomar un riesgo es calco y se nota.',
  },
  {
    id: 's.e9c',
    es: 'El informe pone de manifiesto lo que todos sospechábamos.',
    en: 'The report highlights what we all suspected.',
    concepts: ['p.poner-de-manifiesto', 'g.lo-nominal'],
    level: 'C2',
    topics: ['work', 'opinions'],
    register: 'formal',
  },
  {
    id: 's.e10c',
    es: 'Su respuesta dio pie a un debate que duró horas.',
    en: 'His answer gave rise to a debate that lasted hours.',
    concepts: ['p.dar-pie-a', 'g.relatives'],
    level: 'C2',
    topics: ['opinions'],
  },
  {
    id: 's.e11c',
    es: 'Pasaron por alto el detalle más importante del contrato.',
    en: 'They overlooked the most important detail in the contract.',
    concepts: ['p.pasar-por-alto', 'g.comparisons'],
    level: 'C2',
    topics: ['work'],
  },
  {
    id: 's.e12c',
    es: 'Quiero dejar constancia de que me opuse desde el principio.',
    en: 'I want it placed on record that I objected from the start.',
    concepts: ['p.dejar-constancia'],
    level: 'C2',
    topics: ['work'],
    register: 'formal',
  },

  // --- Naturalidad: correcto pero raro -------------------------------------
  {
    id: 's.e13c',
    es: '¿Quién ha traído esto? — Lo ha traído Ana.',
    en: 'Who brought this? — Ana did.',
    concepts: ['g.naturalness', 'g.emphasis'],
    level: 'C2',
    topics: ['describing'],
    note: 'La información nueva va al final. «Ana lo ha traído» contestaría otra pregunta.',
  },
  {
    id: 's.e14c',
    es: 'Me he dejado el móvil en casa.',
    en: 'I’ve left my phone at home.',
    concepts: ['g.naturalness'],
    level: 'C2',
    topics: ['daily-routine'],
    note: 'Sin posesivo: «mi móvil» aquí suena traducido.',
  },
  {
    id: 's.e15c',
    es: 'Busco piso por la zona de Malasaña.',
    en: 'I’m looking for a flat around Malasaña.',
    concepts: ['g.naturalness', 'v.piso'],
    level: 'C2',
    topics: ['home'],
    note: 'buscar no lleva preposición, y sin artículo suena más natural.',
  },
  {
    id: 's.e16c',
    es: 'Esa película no la he visto, la verdad.',
    en: 'That film I haven’t seen, to be honest.',
    concepts: ['g.emphasis', 'p.la-verdad-es-que'],
    level: 'C2',
    topics: ['hobbies'],
    blanks: ['la'],
    note: 'Objeto adelantado y repetido con pronombre: sin «la» la frase cojea.',
  },

  // --- Énfasis y foco ------------------------------------------------------
  {
    id: 's.e17c',
    es: 'Lo que no soporto es que me den largas.',
    en: 'What I can’t stand is being fobbed off.',
    concepts: ['g.emphasis', 'g.lo-nominal', 'p.no-soporto'],
    level: 'C2',
    topics: ['feelings'],
  },
  {
    id: 's.e18c',
    es: 'Fue entonces cuando me di cuenta de que no iba en serio.',
    en: 'That was when I realised he wasn’t serious.',
    concepts: ['g.emphasis', 'p.darse-cuenta'],
    level: 'C2',
    topics: ['storytelling'],
  },
  {
    id: 's.e19c',
    es: 'Sí que me acuerdo, lo que pasa es que no dije nada.',
    en: 'I do remember, it’s just that I didn’t say anything.',
    concepts: ['g.emphasis', 'p.lo-que-pasa-es'],
    level: 'C2',
    topics: ['storytelling'],
    register: 'colloquial',
    note: '«Sí que» es el subrayado del español hablado.',
  },

  // --- Adaptar el mensaje al público ---------------------------------------
  {
    id: 's.e20c',
    es: 'Lamentamos comunicarles que la entrega sufrirá un retraso.',
    en: 'We regret to inform you that the delivery will be delayed.',
    concepts: ['g.audience', 'v.retraso'],
    level: 'C2',
    topics: ['work'],
    register: 'formal',
  },
  {
    id: 's.e21c',
    es: 'Nada, que se nos ha hecho tardísimo. Vamos para allá.',
    en: 'So basically we’re running really late. We’re on our way.',
    concepts: ['g.audience'],
    level: 'C2',
    topics: ['social'],
    register: 'colloquial',
    note: 'Misma información que la anterior, distancia opuesta.',
  },
  {
    id: 's.e22c',
    es: 'Le agradecería que me lo confirmara antes del viernes.',
    en: 'I’d be grateful if you could confirm it before Friday.',
    concepts: ['g.audience', 'g.si-hypothetical'],
    level: 'C2',
    topics: ['work'],
    register: 'formal',
  },

  // --- Reformular cuando no te entienden -----------------------------------
  {
    id: 's.e23c',
    es: 'Creo que no me he explicado bien: a lo que me refiero es a otra cosa.',
    en: 'I don’t think I explained myself well: what I mean is something else.',
    concepts: ['p.no-me-he-explicado', 'p.a-lo-que-me-refiero'],
    level: 'C2',
    topics: ['social', 'opinions'],
    note: 'Asumir la culpa del malentendido desactiva la tensión al instante.',
  },
  {
    id: 's.e24c',
    es: 'No es eso, ni mucho menos. Déjame que lo diga de otra manera.',
    en: 'That’s not it at all. Let me put it another way.',
    concepts: ['p.no-es-eso', 'p.dejame-que-lo-diga'],
    level: 'C2',
    topics: ['social'],
    register: 'colloquial',
  },
  {
    id: 's.e25c',
    es: 'No tanto un problema técnico como una cuestión de plazos.',
    en: 'Not so much a technical problem as a question of deadlines.',
    concepts: ['p.no-tanto-como', 'v.inconveniente'],
    level: 'C2',
    topics: ['work'],
    note: 'Corrige la caracterización ajena sin contradecirla de frente.',
  },

  // --- Sentido figurado e ironía -------------------------------------------
  {
    id: 's.e26c',
    es: 'Hizo oídos sordos a todas las advertencias.',
    en: 'He turned a deaf ear to every warning.',
    concepts: ['p.hacer-oidos-sordos'],
    level: 'C2',
    topics: ['storytelling'],
  },
  {
    id: 's.e27c',
    es: 'Vamos al grano: ¿lo hacemos o no?',
    en: 'Let’s get to the point: are we doing it or not?',
    concepts: ['p.ir-al-grano'],
    level: 'C2',
    topics: ['work'],
    register: 'colloquial',
  },
  {
    id: 's.e28c',
    es: 'Lleva media hora andándose con rodeos y aún no ha dicho nada.',
    en: 'He’s been beating about the bush for half an hour and still hasn’t said anything.',
    concepts: ['p.andarse-con-rodeos'],
    level: 'C2',
    topics: ['opinions'],
  },
  {
    id: 's.e29c',
    es: 'Es imposible discutir con él: no da el brazo a torcer.',
    en: 'It’s impossible to argue with him: he never backs down.',
    concepts: ['p.no-dar-el-brazo'],
    level: 'C2',
    topics: ['social'],
  },
  {
    id: 's.e30c',
    es: 'Tiene mucha mano izquierda con los clientes difíciles.',
    en: 'She’s very tactful with difficult clients.',
    concepts: ['p.tener-mano-izquierda'],
    level: 'C2',
    topics: ['work'],
  },

  // --- Argumento y síntesis ------------------------------------------------
  {
    id: 's.e31c',
    es: 'Cabe señalar que la medida, lejos de resolverlo, agravó el problema.',
    en: 'It is worth noting that the measure, far from solving it, made the problem worse.',
    concepts: ['p.cabe-senalar', 'p.lejos-de', 'v.medida'],
    level: 'C2',
    topics: ['opinions'],
    register: 'formal',
  },
  {
    id: 's.e32c',
    es: 'Estoy de acuerdo, con la salvedad de que los plazos son irreales.',
    en: 'I agree, with the caveat that the deadlines are unrealistic.',
    concepts: ['v.salvedad', 'p.estoy-de-acuerdo'],
    level: 'C2',
    topics: ['work', 'opinions'],
  },
  {
    id: 's.e33c',
    es: 'En última instancia, no se trata de dinero sino de confianza.',
    en: 'Ultimately, it isn’t about money but about trust.',
    concepts: ['p.en-ultima-instancia'],
    level: 'C2',
    topics: ['opinions'],
  },
  {
    id: 's.e34c',
    es: 'Damos por sentado que vendrá, pero nadie se lo ha preguntado.',
    en: 'We’re taking it for granted that he’ll come, but nobody has asked him.',
    concepts: ['p.dar-por-sentado'],
    level: 'C2',
    topics: ['social'],
  },

  // --- Decir con precisión: cuatro verbos, cuatro posiciones ---------------
  {
    id: 's.e35c',
    es: 'El portavoz afirmó que no había ninguna irregularidad.',
    en: 'The spokesperson stated that there was no irregularity.',
    concepts: ['v.afirmar', 'g.reported-speech'],
    level: 'C2',
    topics: ['opinions'],
    note: 'afirmar: se dice con seguridad y se asume la responsabilidad de lo dicho.',
  },
  {
    id: 's.e36c',
    es: 'Sigue sosteniendo que la culpa fue del proveedor.',
    en: 'He still maintains that it was the supplier’s fault.',
    concepts: ['v.sostener'],
    level: 'C2',
    topics: ['work', 'opinions'],
    note: 'sostener implica que otros lo discuten y aun así se mantiene.',
  },
  {
    id: 's.e37c',
    es: 'Alegó que nadie le había avisado, aunque el correo estaba enviado.',
    en: 'He claimed nobody had told him, although the email had been sent.',
    concepts: ['v.alegar', 'g.pluperfect'],
    level: 'C2',
    topics: ['work'],
    note: 'alegar casi siempre suena a excusa: el propio verbo pone en duda lo dicho.',
  },
  {
    id: 's.e38c',
    es: 'El informe señala que la tendencia se mantiene desde hace dos años.',
    en: 'The report points out that the trend has held for two years.',
    concepts: ['v.senalar'],
    level: 'C2',
    topics: ['work', 'opinions'],
    register: 'formal',
  },
  {
    id: 's.e39c',
    es: 'Reconoció que se había precipitado al tomar la decisión.',
    en: 'She admitted she had been hasty in taking the decision.',
    concepts: ['v.reconocer', 'p.tomar-una-decision'],
    level: 'C2',
    topics: ['work'],
    note: 'reconocer: admitir algo que no favorece a quien lo dice.',
  },
  {
    id: 's.e40c',
    es: 'Permíteme que puntualice un detalle: la fecha no es esa.',
    en: 'Let me clarify one detail: that isn’t the date.',
    concepts: ['v.matizar-c2'],
    level: 'C2',
    topics: ['work', 'opinions'],
    blanks: ['puntualice'],
    note: 'puntualizar corrige un detalle sin desmontar el conjunto del argumento.',
  },

  // --- Grados de problema --------------------------------------------------
  {
    id: 's.e41c',
    es: 'No hay ningún inconveniente en cambiar la fecha si avisas antes.',
    en: 'There’s no objection to changing the date if you give notice.',
    concepts: ['v.inconveniente'],
    level: 'C2',
    topics: ['work'],
    note: 'no hay inconveniente en… — la fórmula estándar para conceder algo sin entusiasmo.',
  },
  {
    id: 's.e42c',
    es: 'Tuvimos un contratiempo con el proveedor, pero está resuelto.',
    en: 'We had a hitch with the supplier, but it’s sorted.',
    concepts: ['v.contratiempo'],
    level: 'C2',
    topics: ['work'],
    note: 'contratiempo suaviza a propósito: pasajero y sin culpables señalados.',
  },
  {
    id: 's.e43c',
    es: 'Sufrieron un percance en la carretera, aunque nadie resultó herido.',
    en: 'They had a mishap on the road, though nobody was hurt.',
    concepts: ['v.percance'],
    level: 'C2',
    topics: ['travel', 'transport'],
  },
  {
    id: 's.e44c',
    es: 'Entre unas trabas y otras, el trámite duró casi un año.',
    en: 'Between one obstacle and another, the paperwork took nearly a year.',
    concepts: ['v.traba'],
    level: 'C2',
    topics: ['work'],
    note: 'trabas burocráticas: la queja española por excelencia.',
  },
  {
    id: 's.e45c',
    es: 'La reforma es una chapuza, se nota que fueron con prisa.',
    en: 'The renovation is a botched job, you can tell they rushed it.',
    concepts: ['v.chapuza', 'g.se-impersonal'],
    level: 'C2',
    topics: ['home', 'slang'],
    register: 'colloquial',
  },

  // --- Grados de reacción: del recelo a la indignación --------------------
  {
    id: 's.e46c',
    es: 'La propuesta se recibió con cierto recelo por parte del equipo.',
    en: 'The proposal was met with a degree of wariness from the team.',
    concepts: ['v.recelo', 'g.se-impersonal'],
    level: 'C2',
    topics: ['work', 'feelings'],
  },
  {
    id: 's.e47c',
    es: 'Está molesto, no indignado: la diferencia importa aquí.',
    en: 'He’s annoyed, not outraged — the difference matters here.',
    concepts: ['v.molesto', 'v.indignado'],
    level: 'C2',
    topics: ['feelings'],
    note: 'indignado lleva carga moral; molesto es simple irritación.',
  },
  {
    id: 's.e48c',
    es: 'Su escepticismo estaba más que justificado, visto lo visto.',
    en: 'His scepticism was more than justified, given how it turned out.',
    concepts: ['v.escepticismo'],
    level: 'C2',
    topics: ['opinions'],
    note: 'visto lo visto — "given what we’ve seen"; una coletilla muy usada al juzgar en retrospectiva.',
  },
  {
    id: 's.e49c',
    es: 'La respuesta fue tan tibia que casi ofendió más que un no.',
    en: 'The response was so lukewarm it almost offended more than a no.',
    concepts: ['v.tibio', 'v.contundente'],
    level: 'C2',
    topics: ['opinions'],
  },
  {
    id: 's.e50c',
    es: 'Es un diseño sobrio, y eso aquí es un elogio.',
    en: 'It’s an understated design, and here that’s a compliment.',
    concepts: ['v.sobrio'],
    level: 'C2',
    topics: ['describing'],
    note: 'sobrio aplicado al estilo es elogio, no descripción de la bebida.',
  },
  {
    id: 's.e51c',
    es: 'Prefiero un correo escueto a tres páginas que no dicen nada.',
    en: 'I’d rather have a terse email than three pages that say nothing.',
    concepts: ['v.escueto'],
    level: 'C2',
    topics: ['work'],
  },

  // --- Colocaciones: el verbo que pide cada sustantivo --------------------
  {
    id: 's.e52c',
    es: 'Aceptar eso ahora sentaría un precedente peligroso.',
    en: 'Accepting that now would set a dangerous precedent.',
    concepts: ['p.sentar-precedente', 'g.conditional'],
    level: 'C2',
    topics: ['work', 'opinions'],
  },
  {
    id: 's.e53c',
    es: 'Antes de firmar quisiera plantear una duda sobre el plazo.',
    en: 'Before signing I’d like to raise a doubt about the deadline.',
    concepts: ['p.plantear-una-duda', 'v.plantear'],
    level: 'C2',
    topics: ['work'],
    register: 'formal',
  },
  {
    id: 's.e54c',
    es: 'La reunión sirvió al menos para despejar dudas.',
    en: 'The meeting at least served to clear up doubts.',
    concepts: ['p.despejar-dudas', 'v.reunion'],
    level: 'C2',
    topics: ['work'],
  },
  {
    id: 's.e55c',
    es: 'Nadie quiso asumir el riesgo de adelantar la fecha.',
    en: 'Nobody was willing to take the risk of bringing the date forward.',
    concepts: ['p.asumir-un-riesgo', 'v.asumir'],
    level: 'C2',
    topics: ['work'],
  },
  {
    id: 's.e56c',
    es: 'Entablamos conversación en la cola y acabamos cenando juntos.',
    en: 'We struck up a conversation in the queue and ended up having dinner together.',
    concepts: ['p.entablar-conversacion'],
    level: 'C2',
    topics: ['social', 'storytelling'],
  },
  {
    id: 's.e57c',
    es: 'Aquel comentario dio pie a una discusión de dos horas.',
    en: 'That remark gave rise to a two-hour argument.',
    concepts: ['p.dar-pie-a'],
    level: 'C2',
    topics: ['social', 'opinions'],
    note: 'dar pie a, nunca dar pie para: la preposición no se negocia.',
  },
  {
    id: 's.e58c',
    es: 'El estudio pone de manifiesto una brecha que nadie esperaba.',
    en: 'The study reveals a gap nobody expected.',
    concepts: ['p.poner-de-manifiesto', 'v.desigualdad'],
    level: 'C2',
    topics: ['opinions'],
    register: 'formal',
  },
  {
    id: 's.e59c',
    es: 'No conviene pasar por alto lo que se dijo en la primera reunión.',
    en: "It's unwise to overlook what was said in the first meeting.",
    concepts: ['p.pasar-por-alto', 'g.lo-nominal', 'g.se-impersonal'],
    level: 'C2',
    topics: ['work'],
  },
  {
    id: 's.e60c',
    es: 'Quisiera dejar constancia de mi desacuerdo en el acta.',
    en: 'I’d like to place my disagreement on record in the minutes.',
    concepts: ['p.dejar-constancia', 'g.register'],
    level: 'C2',
    topics: ['work'],
    register: 'formal',
  },
  {
    id: 's.e61c',
    es: 'Se negó a tomar partido hasta conocer todos los detalles.',
    en: 'She refused to take sides until she knew all the details.',
    concepts: ['p.tomar-partido'],
    level: 'C2',
    topics: ['opinions'],
  },
  {
    id: 's.e62c',
    es: 'Esa idea ha ido ganando terreno en los últimos meses.',
    en: 'That idea has been gaining ground in recent months.',
    concepts: ['p.ganar-terreno', 'g.present-perfect'],
    level: 'C2',
    topics: ['opinions'],
    note: 'ir + gerundio marca un proceso gradual: ha ido ganando.',
  },

  // --- Sentido figurado y carácter ----------------------------------------
  {
    id: 's.e63c',
    es: 'Al final se salió con la suya, como siempre.',
    en: 'In the end he got his own way, as always.',
    concepts: ['p.salirse-con-la-suya'],
    level: 'C2',
    topics: ['social'],
    register: 'colloquial',
  },
  {
    id: 's.e64c',
    es: 'Hace falta mucha mano izquierda para llevar ese equipo.',
    en: 'It takes a lot of tact to manage that team.',
    concepts: ['p.tener-mano-izquierda'],
    level: 'C2',
    topics: ['work', 'social'],
  },
  {
    id: 's.e65c',
    es: 'Llevan años haciendo oídos sordos a las quejas de los vecinos.',
    en: 'They’ve spent years turning a deaf ear to the neighbours’ complaints.',
    concepts: ['p.hacer-oidos-sordos', 'v.quejarse'],
    level: 'C2',
    topics: ['home', 'opinions'],
  },
  {
    id: 's.e66c',
    es: 'Déjate de rodeos y ve al grano, que tenemos diez minutos.',
    en: 'Stop beating about the bush and get to the point, we’ve got ten minutes.',
    concepts: ['p.ir-al-grano', 'p.andarse-con-rodeos'],
    level: 'C2',
    topics: ['work'],
    register: 'colloquial',
  },
  {
    id: 's.e67c',
    es: 'Nadie pone en tela de juicio su competencia, solo el método.',
    en: 'Nobody is calling his competence into question, only the method.',
    concepts: ['p.poner-en-tela-de-juicio'],
    level: 'C2',
    topics: ['work', 'opinions'],
    register: 'formal',
  },
  {
    id: 's.e68c',
    es: 'No da el brazo a torcer ni cuando tiene todo en contra.',
    en: 'He won’t back down even when everything is against him.',
    concepts: ['p.no-dar-el-brazo'],
    level: 'C2',
    topics: ['opinions', 'describing'],
  },
  {
    id: 's.e69c',
    es: 'Me saca de quicio que cambien las reuniones a última hora.',
    en: 'It drives me up the wall when they move meetings at the last minute.',
    concepts: ['p.sacar-de-quicio', 'v.reunion'],
    level: 'C2',
    topics: ['work', 'feelings'],
    register: 'colloquial',
    blanks: ['cambien'],
  },

  // --- Reformular cuando el mensaje no ha llegado -------------------------
  {
    id: 's.e70c',
    es: 'Creo que no me he explicado bien; me explico: son dos cosas distintas.',
    en: 'I don’t think I explained myself well. Let me put it this way: they’re two different things.',
    concepts: ['p.no-me-he-explicado', 'p.me-explico'],
    level: 'C2',
    topics: ['social', 'opinions'],
    note: 'Asumir la culpa del malentendido reabre la conversación; insistir la cierra.',
  },
  {
    id: 's.e71c',
    es: 'A lo que me refiero es a que el plazo no depende de nosotros.',
    en: 'What I mean is that the deadline isn’t up to us.',
    concepts: ['p.a-lo-que-me-refiero'],
    level: 'C2',
    topics: ['work'],
    note: 'referirse pide a, y la preposición reaparece antes del que: es a que.',
  },
  {
    id: 's.e72c',
    es: 'Déjame que lo diga de otra manera, a ver si así queda claro.',
    en: 'Let me put it another way, and see if that makes it clear.',
    concepts: ['p.dejame-que-lo-diga', 'g.reformulation'],
    level: 'C2',
    topics: ['opinions'],
  },
  {
    id: 's.e73c',
    es: 'No es eso, ni mucho menos; lo que quiero decir es otra cosa.',
    en: 'That’s not it at all — the point I’m making is a different one.',
    concepts: ['p.no-es-eso', 'p.lo-que-quiero-decir'],
    level: 'C2',
    topics: ['social', 'opinions'],
    register: 'colloquial',
  },

  // --- Argumentar y sintetizar --------------------------------------------
  {
    id: 's.e74c',
    es: 'Cabe señalar que ninguna de las dos partes ha cedido todavía.',
    en: 'It is worth noting that neither side has given ground yet.',
    concepts: ['p.cabe-senalar', 'v.senalar'],
    level: 'C2',
    topics: ['opinions'],
    register: 'formal',
  },
  {
    id: 's.e75c',
    es: 'No cabe duda de que el planteamiento inicial era erróneo.',
    en: 'There is no doubt that the initial approach was wrong.',
    concepts: ['p.no-cabe-duda', 'v.planteamiento'],
    level: 'C2',
    topics: ['opinions'],
    note: 'no cabe duda de que — el de es obligatorio; quitarlo es queísmo.',
  },
  {
    id: 's.e76c',
    es: 'La medida es, a todas luces, insuficiente.',
    en: 'The measure is, by any measure, insufficient.',
    concepts: ['p.a-todas-luces', 'v.medida'],
    level: 'C2',
    topics: ['opinions'],
    register: 'formal',
  },
  {
    id: 's.e77c',
    es: 'No tanto una crisis como un cambio de modelo.',
    en: 'Not so much a crisis as a change of model.',
    concepts: ['p.no-tanto-como'],
    level: 'C2',
    topics: ['opinions'],
    note: 'El recurso más limpio para corregir una caracterización sin negarla del todo.',
  },
  {
    id: 's.e78c',
    es: 'Lejos de calmar los ánimos, el comunicado los encendió más.',
    en: 'Far from calming things down, the statement inflamed them further.',
    concepts: ['p.lejos-de'],
    level: 'C2',
    topics: ['opinions'],
  },
  {
    id: 's.e79c',
    es: 'Acepto la síntesis, con la salvedad del último punto.',
    en: 'I accept the summary, with the caveat of the last point.',
    concepts: ['v.sintesis', 'v.salvedad'],
    level: 'C2',
    topics: ['work', 'opinions'],
    register: 'formal',
  },
  {
    id: 's.e80c',
    es: 'En última instancia, lo que se juzga es el criterio, no el resultado.',
    en: 'Ultimately, what is being judged is the judgement, not the outcome.',
    concepts: ['p.en-ultima-instancia', 'g.se-impersonal', 'g.lo-nominal'],
    level: 'C2',
    topics: ['opinions'],
    register: 'formal',
  },

  // --- Precisión, segunda vuelta -------------------------------------------
  {
    id: 's.e81c',
    es: 'Nadie lo afirma abiertamente, pero todos lo dan por sentado.',
    en: 'Nobody states it openly, but everyone takes it for granted.',
    concepts: ['v.afirmar', 'p.dar-por-sentado'],
    level: 'C2',
    topics: ['opinions'],
  },
  {
    id: 's.e82c',
    es: 'Un percance sin importancia le costó el vuelo y dos días de trabajo.',
    en: 'A trivial mishap cost him the flight and two days’ work.',
    concepts: ['v.percance', 'v.contratiempo'],
    level: 'C2',
    topics: ['travel', 'work'],
  },
  {
    id: 's.e83c',
    es: 'Las trabas no son técnicas, son administrativas, que es peor.',
    en: 'The obstacles aren’t technical, they’re administrative, which is worse.',
    concepts: ['v.traba', 'v.peor'],
    level: 'C2',
    topics: ['work'],
  },
  {
    id: 's.e84c',
    es: 'Lo arreglaron en una tarde y se nota: es una chapuza.',
    en: 'They fixed it in an afternoon and it shows: it’s a botched job.',
    concepts: ['v.chapuza', 'g.se-impersonal'],
    level: 'C2',
    topics: ['home', 'slang'],
    register: 'colloquial',
  },
  {
    id: 's.e85c',
    es: 'Más que molesta, estaba indignada, y con razón.',
    en: 'More than annoyed, she was outraged, and rightly so.',
    concepts: ['v.indignado', 'v.molesto', 'p.tener-razon'],
    level: 'C2',
    topics: ['feelings'],
  },
  {
    id: 's.e86c',
    es: 'El escepticismo del público estaba justificado: ya habían prometido lo mismo antes.',
    en: 'The public’s scepticism was justified: they had promised the same thing before.',
    concepts: ['v.escepticismo', 'g.pluperfect'],
    level: 'C2',
    topics: ['opinions'],
  },
  {
    id: 's.e87c',
    es: 'Lo miraron con recelo hasta que explicó de dónde salían los datos.',
    en: 'They looked at it with suspicion until he explained where the figures came from.',
    concepts: ['v.recelo', 'v.dato', 'g.preterite'],
    level: 'C2',
    topics: ['work', 'feelings'],
  },
  {
    id: 's.e88c',
    es: 'Prefiero un estilo sobrio: nada de adornos ni de mayúsculas.',
    en: 'I prefer an understated style: no flourishes and no capitals.',
    concepts: ['v.sobrio', 'v.escueto'],
    level: 'C2',
    topics: ['describing', 'work'],
  },
  {
    id: 's.e89c',
    es: 'La respuesta fue contundente y zanjó el debate en dos frases.',
    en: 'The reply was emphatic and settled the debate in two sentences.',
    concepts: ['v.contundente', 'v.rotundo'],
    level: 'C2',
    topics: ['opinions'],
  },

  // --- Colocaciones, segunda vuelta ----------------------------------------
  {
    id: 's.e90c',
    es: 'Si me permite, quisiera plantear una duda sobre el punto tres.',
    en: 'If I may, I’d like to raise a doubt about point three.',
    concepts: ['p.plantear-una-duda', 'g.register'],
    level: 'C2',
    topics: ['work'],
    register: 'formal',
  },
  {
    id: 's.e91c',
    es: 'Entablar conversación con desconocidos se le da fatal.',
    en: 'He’s terrible at striking up conversation with strangers.',
    concepts: ['p.entablar-conversacion', 'g.se-impersonal'],
    level: 'C2',
    topics: ['social'],
    note: 'dársele bien / mal a alguien — how Spanish says someone is good or bad at something.',
  },
  {
    id: 's.e92c',
    es: 'Antes de firmar conviene despejar dudas, no después.',
    en: 'Doubts are best cleared up before signing, not after.',
    concepts: ['p.despejar-dudas', 'v.antes'],
    level: 'C2',
    topics: ['work'],
  },
  {
    id: 's.e93c',
    es: 'Prefirió no tomar partido, y eso ya fue tomar partido.',
    en: 'He chose not to take sides, and that in itself was taking sides.',
    concepts: ['p.tomar-partido', 'v.preferir'],
    level: 'C2',
    topics: ['opinions'],
  },
  {
    id: 's.e94c',
    es: 'La propuesta va ganando terreno entre los que al principio dudaban.',
    en: 'The proposal is gaining ground among those who doubted at first.',
    concepts: ['p.ganar-terreno', 'g.relatives'],
    level: 'C2',
    topics: ['opinions', 'work'],
  },
  {
    id: 's.e95c',
    es: 'Insistió hasta que se salió con la suya, como de costumbre.',
    en: 'He kept at it until he got his own way, as usual.',
    concepts: ['p.salirse-con-la-suya', 'g.preterite'],
    level: 'C2',
    topics: ['social', 'work'],
  },
  {
    id: 's.e96c',
    es: 'El informe pone en tela de juicio todo el procedimiento anterior.',
    en: 'The report calls the entire previous procedure into question.',
    concepts: ['p.poner-en-tela-de-juicio', 'p.poner-de-manifiesto'],
    level: 'C2',
    topics: ['work', 'opinions'],
    register: 'formal',
  },
  {
    id: 's.e97c',
    es: 'Damos por sentado que hay presupuesto y quizá no lo haya.',
    en: 'We’re taking it for granted that there’s a budget and there may not be.',
    concepts: ['p.dar-por-sentado', 'g.subjunctive-opinion'],
    level: 'C2',
    topics: ['work'],
  },

  // --- Reformular y cerrar un argumento ------------------------------------
  {
    id: 's.e98c',
    es: 'Me explico: no digo que esté mal hecho, digo que llega tarde.',
    en: 'Let me explain: I’m not saying it’s badly done, I’m saying it’s late.',
    concepts: ['p.me-explico', 'g.subjunctive-opinion'],
    level: 'C2',
    topics: ['work', 'opinions'],
  },
  {
    id: 's.e99c',
    es: 'Lo que quiero decir es que el problema estaba antes de que llegáramos.',
    en: 'The point I’m making is that the problem existed before we arrived.',
    concepts: ['p.lo-que-quiero-decir', 'g.subjunctive-intro'],
    level: 'C2',
    topics: ['work'],
    blanks: ['llegáramos'],
  },
  {
    id: 's.e100c',
    es: 'No cabe duda de que se podría haber hecho mejor.',
    en: 'There is no doubt it could have been done better.',
    concepts: ['p.no-cabe-duda', 'g.conditional', 'v.mejor'],
    level: 'C2',
    topics: ['work', 'opinions'],
  },
  {
    id: 's.e101c',
    es: 'El texto es, a todas luces, mejorable en su forma actual.',
    en: 'The text is, by any measure, capable of improvement as it stands.',
    concepts: ['p.a-todas-luces', 'v.escueto'],
    level: 'C2',
    topics: ['work'],
    register: 'formal',
  },
  {
    id: 's.e102c',
    es: 'Como síntesis vale, aunque deja fuera el punto más incómodo.',
    en: 'As a summary it works, though it leaves out the most awkward point.',
    concepts: ['v.sintesis', 'v.aunque', 'v.salvedad'],
    level: 'C2',
    topics: ['work', 'opinions'],
  },
];
