import type { Sentence } from '@/content/types';

/** Time, food, the café, family life. */
export const everydaySentences: Sentence[] = [
  {
    id: 's.e1',
    es: '¿Qué hora es?',
    en: 'What time is it?',
    concepts: ['p.que-hora-es', 'v.hora'],
    level: 'A1',
    topics: ['time'],
  },
  {
    id: 's.e2',
    es: 'Son las tres y media.',
    en: 'It’s half past three.',
    concepts: ['p.son-las', 'v.tres', 'v.media'],
    level: 'A1',
    topics: ['time'],
    blanks: ['Son'],
  },
  {
    id: 's.e3',
    es: 'Es la una menos cuarto.',
    en: 'It’s quarter to one.',
    concepts: ['p.son-las', 'v.cuarto', 'v.uno'],
    level: 'A2',
    topics: ['time'],
    note: 'One o’clock is the only singular hour: es la una.',
  },
  {
    id: 's.e4',
    es: 'Quedamos sobre las ocho, ¿vale?',
    en: 'Let’s meet around eight, okay?',
    concepts: ['v.quedar', 'p.sobre-las', 'v.ocho', 'v.vale'],
    level: 'A2',
    topics: ['plans', 'time'],
  },
  {
    id: 's.e5',
    es: 'Los viernes salgo con mis amigos.',
    en: 'On Fridays I go out with my friends.',
    concepts: ['v.viernes', 'v.salir', 'v.amigo'],
    level: 'A2',
    topics: ['social', 'time'],
    note: 'Los viernes = "on Fridays". No preposition needed.',
  },
  {
    id: 's.e6',
    es: 'Este fin de semana no hago nada.',
    en: 'I’m not doing anything this weekend.',
    concepts: ['v.fin-de-semana', 'v.hacer', 'g.negation'],
    level: 'A2',
    topics: ['plans'],
  },
  {
    id: 's.e7',
    es: 'Normalmente desayuno un café y una tostada.',
    en: 'I usually have a coffee and a piece of toast for breakfast.',
    concepts: ['v.desayuno', 'v.cafe'],
    level: 'A2',
    topics: ['food', 'daily-routine'],
  },
  {
    id: 's.e8',
    es: 'Comemos sobre las dos y media.',
    en: 'We have lunch around half past two.',
    concepts: ['v.comer', 'p.sobre-las', 'v.media'],
    level: 'A2',
    topics: ['food', 'time'],
    note: 'Lunch in Spain really is this late, and it is the main meal.',
  },
  {
    id: 's.e9',
    es: 'La cena es a las diez, es normal aquí.',
    en: 'Dinner is at ten, that’s normal here.',
    concepts: ['v.cena', 'v.ser', 'v.diez'],
    level: 'A2',
    topics: ['food', 'time'],
  },
  {
    id: 's.e10',
    es: 'Tengo hambre, ¿comemos algo?',
    en: 'I’m hungry, shall we eat something?',
    concepts: ['p.tengo-hambre', 'v.comer', 'g.tener-expressions'],
    level: 'A1',
    topics: ['food'],
    blanks: ['hambre'],
  },
  {
    id: 's.e11',
    es: 'Una caña y una tapa de tortilla, por favor.',
    en: 'A small beer and a portion of tortilla, please.',
    concepts: ['v.cana', 'v.tapa', 'v.tortilla', 'p.por-favor'],
    level: 'A2',
    topics: ['cafe', 'food'],
  },
  {
    id: 's.e12',
    es: '¿Me pones un zumo de naranja?',
    en: 'Can I get an orange juice?',
    concepts: ['p.me-pones', 'v.zumo'],
    level: 'A2',
    topics: ['cafe'],
    note: 'Zumo in Spain, jugo in Latin America.',
  },
  {
    id: 's.e13',
    es: 'La cuenta, por favor.',
    en: 'The bill, please.',
    concepts: ['v.cuenta', 'p.por-favor', 'p.la-cuenta-porfa'],
    level: 'A2',
    topics: ['restaurant'],
  },
  {
    id: 's.e14',
    es: '¿Nos trae la carta, por favor?',
    en: 'Could you bring us the menu, please?',
    concepts: ['v.carta', 'p.por-favor'],
    level: 'A2',
    topics: ['restaurant'],
  },
  {
    id: 's.e15',
    es: 'El agua está muy fría.',
    en: 'The water is very cold.',
    concepts: ['v.agua', 'v.estar', 'g.ser-estar'],
    level: 'A2',
    topics: ['food'],
    note: 'El agua, but fría — the noun is feminine despite the el.',
  },
  {
    id: 's.e16',
    es: 'Mi madre cocina muy bien.',
    en: 'My mother cooks really well.',
    concepts: ['v.madre', 'v.cocinar', 'v.muy'],
    level: 'A1',
    topics: ['family', 'food'],
  },
  {
    id: 's.e17',
    es: 'Mi abuela tiene ochenta y dos años.',
    en: 'My grandmother is eighty-two.',
    concepts: ['v.abuelo', 'v.tener', 'v.anos', 'g.tener-expressions'],
    level: 'A2',
    topics: ['family', 'numbers'],
  },
  {
    id: 's.e18',
    es: 'Somos cinco en casa.',
    en: 'There are five of us at home.',
    concepts: ['v.ser', 'v.cinco', 'v.casa'],
    level: 'A1',
    topics: ['family', 'home'],
    note: 'En casa — no article. Very fixed.',
  },
  {
    id: 's.e19',
    es: 'Mi hijo tiene siete años y va al colegio.',
    en: 'My son is seven and goes to school.',
    concepts: ['v.hijo', 'v.tener', 'v.siete', 'v.ir'],
    level: 'A2',
    topics: ['family'],
  },
  {
    id: 's.e20',
    es: 'Vivo con dos compañeros de piso.',
    en: 'I live with two flatmates.',
    concepts: ['v.vivir', 'v.companero', 'v.piso', 'v.dos'],
    level: 'A2',
    topics: ['home', 'university'],
  },
  {
    id: 's.e21',
    es: 'El piso está en la calle Goya.',
    en: 'The flat is on Goya street.',
    concepts: ['v.piso', 'v.estar', 'v.calle'],
    level: 'A2',
    topics: ['home', 'directions'],
  },
  {
    id: 's.e22',
    es: 'Hay una tienda muy barata cerca de aquí.',
    en: 'There’s a really cheap shop near here.',
    concepts: ['g.hay-estar', 'v.tienda', 'v.barato', 'v.cerca'],
    level: 'A2',
    topics: ['shopping'],
  },
  {
    id: 's.e23',
    es: 'Es demasiado caro para mí.',
    en: 'It’s too expensive for me.',
    concepts: ['v.ser', 'v.caro', 'g.por-para'],
    level: 'A2',
    topics: ['shopping'],
    blanks: ['para'],
  },
  {
    id: 's.e24',
    es: '¿Cuánto cuesta el billete de tren?',
    en: 'How much does the train ticket cost?',
    concepts: ['p.cuanto-cuesta', 'v.billete', 'v.tren'],
    level: 'A2',
    topics: ['transport', 'shopping'],
  },
  {
    id: 's.e25',
    es: 'Voy al supermercado, ¿necesitas algo?',
    en: 'I’m going to the supermarket, do you need anything?',
    concepts: ['v.ir', 'v.supermercado'],
    level: 'A2',
    topics: ['shopping'],
    note: 'a + el always contracts to al.',
  },
  {
    id: 's.e26',
    es: 'Mañana tengo clase a las nueve.',
    en: 'Tomorrow I have class at nine.',
    concepts: ['v.manana', 'v.tener', 'v.clase', 'v.nueve'],
    level: 'A1',
    topics: ['university', 'time'],
  },
  {
    id: 's.e27',
    es: 'Estudio en la universidad de Granada.',
    en: 'I study at the University of Granada.',
    concepts: ['v.estudiar', 'v.universidad'],
    level: 'A1',
    topics: ['university'],
  },
  {
    id: 's.e28',
    es: 'Trabajo por la mañana y estudio por la tarde.',
    en: 'I work in the morning and study in the afternoon.',
    concepts: ['v.trabajar', 'v.manana', 'v.estudiar', 'v.tarde', 'g.por-para'],
    level: 'A2',
    topics: ['work', 'university'],
    blanks: ['por'],
  },
  {
    id: 's.e29',
    es: 'A veces leo un libro antes de dormir.',
    en: 'Sometimes I read a book before sleeping.',
    concepts: ['v.a-veces', 'v.leer', 'v.libro', 'v.antes'],
    level: 'A2',
    topics: ['daily-routine', 'hobbies'],
  },
  {
    id: 's.e30',
    es: 'Nunca bebo café por la noche.',
    en: 'I never drink coffee at night.',
    concepts: ['v.nunca', 'v.beber', 'v.cafe', 'v.noche'],
    level: 'A2',
    topics: ['daily-routine', 'food'],
  },
  {
    id: 's.e31',
    es: 'Siempre escucho música cuando cocino.',
    en: 'I always listen to music when I cook.',
    concepts: ['v.siempre', 'v.escuchar', 'v.musica', 'v.cocinar'],
    level: 'A2',
    topics: ['hobbies', 'daily-routine'],
    note: 'Escuchar takes no preposition: escucho música.',
  },
  {
    id: 's.e32',
    es: 'Ahora no puedo, estoy en clase.',
    en: 'I can’t right now, I’m in class.',
    concepts: ['v.ahora', 'v.poder', 'v.estar', 'v.clase'],
    level: 'A2',
    topics: ['university', 'plans'],
  },
  {
    id: 's.e33',
    es: 'No tengo dinero hasta el viernes.',
    en: 'I don’t have any money until Friday.',
    concepts: ['v.tener', 'v.dinero', 'v.viernes', 'g.negation'],
    level: 'A2',
    topics: ['shopping'],
  },
  {
    id: 's.e34',
    es: 'El menú del día cuesta doce euros.',
    en: 'The set lunch menu costs twelve euros.',
    concepts: ['p.menu-del-dia'],
    level: 'A2',
    topics: ['restaurant'],
  },
  {
    id: 's.e35',
    es: 'De primero, ensalada; de segundo, pollo.',
    en: 'For the starter, salad; for the main, chicken.',
    concepts: ['v.primero'],
    level: 'A2',
    topics: ['restaurant'],
  },
  {
    id: 's.e36',
    es: '¿Para tomar aquí o para llevar?',
    en: 'To have here or takeaway?',
    concepts: ['p.para-tomar-aqui', 'g.por-para'],
    level: 'A2',
    topics: ['cafe'],
  },
  {
    id: 's.e37',
    es: '¿Con tarjeta o en efectivo?',
    en: 'By card or in cash?',
    concepts: ['p.con-tarjeta'],
    level: 'A2',
    topics: ['shopping'],
  },
  {
    id: 's.e38',
    es: 'Perdona, ¿cuánto es?',
    en: 'Excuse me, how much is it?',
    concepts: ['v.perdona', 'p.cuanto-es'],
    level: 'A1',
    topics: ['shopping', 'cafe'],
  },
  {
    id: 's.e39',
    es: 'Hoy he comido en casa de mis padres.',
    en: 'Today I ate at my parents’ house.',
    concepts: ['v.hoy', 'v.comer', 'v.casa', 'v.padre', 'g.present-perfect'],
    level: 'A2',
    topics: ['food', 'past'],
    note: 'Inside today, Spain reaches for the present perfect.',
  },
  {
    id: 's.e40',
    es: 'Esta mañana he ido al médico.',
    en: 'This morning I went to the doctor.',
    concepts: ['v.manana', 'v.ir', 'g.present-perfect'],
    level: 'A2',
    topics: ['health', 'past'],
    blanks: ['he'],
  },

  // --- At the bar: the register ladder from tú to usted -------------------
  {
    id: 's.e41',
    es: '¿Me puede poner un café con leche, por favor?',
    en: 'Could you get me a white coffee, please?',
    concepts: ['p.me-puede-poner', 'p.cafe-con-leche', 'v.poder'],
    level: 'A2',
    topics: ['cafe'],
    register: 'formal',
    note: 'The usted version of ¿me pones…? — same request, more distance.',
  },
  {
    id: 's.e42',
    es: '¿Me puede poner la cuenta cuando pueda?',
    en: 'Could you bring me the bill whenever you can?',
    concepts: ['p.me-puede-poner', 'v.cuenta'],
    level: 'A2',
    topics: ['cafe', 'restaurant'],
    register: 'formal',
  },
  {
    id: 's.e43',
    es: '¿Para tomar aquí o para llevar? — Para llevar, gracias.',
    en: 'To have here or takeaway? — Takeaway, thanks.',
    concepts: ['p.para-tomar-aqui', 'v.gracias'],
    level: 'A2',
    topics: ['cafe'],
    note: 'You will be asked this in every Spanish bar. Learn the answer, not just the question.',
  },
  {
    id: 's.e44',
    es: '¿Con tarjeta o en efectivo? — Con tarjeta, si puede ser.',
    en: 'By card or in cash? — By card, if that’s possible.',
    concepts: ['p.con-tarjeta', 'v.pagar'],
    level: 'A2',
    topics: ['shopping', 'cafe'],
    note: 'si puede ser — a very Spanish way of softening a preference into a request.',
  },
  {
    id: 's.e45',
    es: '¡Buenas! ¿Me pones una caña, por favor?',
    en: 'Hey there! Can I get a small beer, please?',
    concepts: ['p.buenas', 'p.me-pones', 'v.cana'],
    level: 'A2',
    topics: ['cafe', 'greetings'],
    register: 'colloquial',
    note: '¡Buenas! works at any hour — it is the clipped, friendly version of buenos días / buenas tardes.',
  },
  {
    id: 's.e46',
    es: 'Se me han olvidado las llaves y la maleta está dentro.',
    en: "I've forgotten the keys and the suitcase is inside.",
    concepts: ['v.llave', 'v.maleta', 'g.se-impersonal'],
    level: 'A2',
    topics: ['travel', 'home'],
  },
  {
    id: 's.e47',
    es: 'El viaje en tren fue largo, pero mereció la pena.',
    en: 'The train journey was long, but it was worth it.',
    concepts: ['v.viaje', 'v.tren', 'p.merece-la-pena'],
    level: 'A2',
    topics: ['travel', 'transport'],
  },
  {
    id: 's.e48',
    es: 'Antes de salir, siempre digo dónde dejo las llaves.',
    en: 'Before leaving, I always say where I’m leaving the keys.',
    concepts: ['v.antes', 'v.decir', 'v.llave'],
    level: 'A2',
    topics: ['daily-routine', 'home'],
  },
  {
    id: 's.e49',
    es: 'Estoy nervioso porque mañana tengo el examen.',
    en: "I'm nervous because I've got the exam tomorrow.",
    concepts: ['v.nervioso', 'g.ser-estar', 'v.manana'],
    level: 'A2',
    topics: ['feelings', 'university'],
  },
  {
    id: 's.e50',
    es: 'No está enfadada contigo, está cansada y ya está.',
    en: "She isn't angry with you, she's tired, that's all.",
    concepts: ['v.enfadado', 'v.cansado', 'g.ser-estar'],
    level: 'A2',
    topics: ['feelings'],
    note: 'y ya está — "and that’s that". Closes a sentence the way English uses "full stop".',
  },
// --- Filling the gaps the audit found at A2 ------------------------------
  {
    id: 's.e51',
    es: '¿Cómo está usted? — Muy bien, gracias, ¿y usted?',
    en: 'How are you? — Very well, thank you, and you?',
    concepts: ['v.usted', 'p.muy-bien'],
    level: 'A2',
    topics: ['greetings', 'social'],
    register: 'formal',
    note: 'In Spain usted is reserved for real distance — official business, much older strangers.',
  },
  {
    id: 's.e52',
    es: 'Me duele el estómago desde ayer y también la mano.',
    en: 'My stomach has hurt since yesterday, and my hand too.',
    concepts: ['v.estomago', 'v.mano', 'p.me-duele'],
    level: 'A2',
    topics: ['health'],
  },
  {
    id: 's.e53',
    es: 'Necesito ropa nueva: una camisa blanca y un vestido.',
    en: 'I need new clothes: a white shirt and a dress.',
    concepts: ['v.ropa', 'v.camisa', 'v.vestido'],
    level: 'A2',
    topics: ['shopping'],
  },
  {
    id: 's.e54',
    es: 'Mi novia trabaja en un hospital y sale muy tarde.',
    en: 'My girlfriend works in a hospital and finishes very late.',
    concepts: ['v.novio', 'v.trabajar', 'v.tarde'],
    level: 'A2',
    topics: ['people', 'work'],
  },

  // --- Spiral: A1 words re-met inside A2 structures ------------------------
  {
    id: 's.e55',
    es: 'Esta mañana he desayunado solo un café, sin pan ni fruta.',
    en: 'This morning I only had a coffee for breakfast, no bread or fruit.',
    concepts: ['g.present-perfect', 'v.pan', 'v.fruta', 'v.sin'],
    level: 'A2',
    topics: ['food', 'daily-routine'],
    note: 'ni replaces y after a negative: sin pan ni fruta.',
  },
  {
    id: 's.e56',
    es: 'El jamón de aquí es mejor que el de mi barrio, y más barato.',
    en: 'The ham here is better than the one in my neighbourhood, and cheaper.',
    concepts: ['g.comparisons', 'v.jamon', 'v.barato'],
    level: 'A2',
    topics: ['food', 'shopping'],
  },
  {
    id: 's.e57',
    es: 'Me levanto a las siete, pero los domingos me quedo en la cama.',
    en: 'I get up at seven, but on Sundays I stay in bed.',
    concepts: ['g.reflexive', 'v.domingo', 'v.levantarse'],
    level: 'A2',
    topics: ['daily-routine'],
  },
  {
    id: 's.e58',
    es: 'Tengo que comprar pollo, huevos y algo de verdura.',
    en: 'I have to buy chicken, eggs and some vegetables.',
    concepts: ['p.tener-que', 'v.comprar', 'v.pollo', 'v.huevo', 'v.verdura'],
    level: 'A2',
    topics: ['shopping', 'food'],
  },
  {
    id: 's.e59',
    es: 'Prefiero el vino tinto, pero hoy me apetece una cerveza.',
    en: 'I prefer red wine, but today I fancy a beer.',
    concepts: ['v.preferir', 'v.vino', 'v.cerveza', 'p.me-apetece'],
    level: 'A2',
    topics: ['cafe', 'opinions'],
  },
  {
    id: 's.e60',
    es: 'Mi hijo es más alto que yo y solo tiene quince años.',
    en: 'My son is taller than me and he’s only fifteen.',
    concepts: ['g.comparisons', 'v.hijo', 'v.alto', 'v.quince'],
    level: 'A2',
    topics: ['family', 'describing'],
  },
  {
    id: 's.e61',
    es: 'Hemos ido a Francia en coche, por la costa.',
    en: 'We went to France by car, along the coast.',
    concepts: ['g.present-perfect', 'v.francia', 'v.coche', 'g.por-para'],
    level: 'A2',
    topics: ['travel', 'transport'],
  },
  {
    id: 's.e62',
    es: 'Estoy contento porque por fin entiendo a los profesores.',
    en: 'I’m happy because I finally understand the teachers.',
    concepts: ['v.contento', 'p.no-entiendo', 'v.porque'],
    level: 'A2',
    topics: ['feelings', 'university'],
  },
  {
    id: 's.e63',
    es: 'No puedo escribir ahora, estoy escuchando una cosa.',
    en: 'I can’t write now, I’m listening to something.',
    concepts: ['v.escribir', 'v.escuchar', 'v.poder'],
    level: 'A2',
    topics: ['daily-routine'],
    note: 'estar + gerundio is for what is happening right this second, not for habits.',
  },
  {
    id: 's.e64',
    es: 'Hay que girar a la izquierda antes del semáforo, no después.',
    en: 'You have to turn left before the lights, not after.',
    concepts: ['v.izquierda', 'v.antes', 'p.hay-que-comer'],
    level: 'A2',
    topics: ['directions'],
  },
];
