import type { Sentence } from '@/content/types';

/**
 * Sentences someone would actually say. Each is tagged with the concepts it
 * exercises, so a single line can become a translation, a word bank, a gap
 * fill, a dictation and a listening item.
 */
export const foundationsSentences: Sentence[] = [
  {
    id: 's.f1',
    es: 'Hola, ¿qué tal?',
    en: 'Hi, how are you?',
    altEn: ['Hi, how’s it going?'],
    concepts: ['v.hola', 'p.que-tal'],
    level: 'A0',
    topics: ['greetings'],
  },
  {
    id: 's.f2',
    es: 'Muy bien, ¿y tú?',
    en: 'Very well, and you?',
    concepts: ['p.muy-bien', 'p.y-tu'],
    level: 'A0',
    topics: ['greetings'],
  },
  {
    id: 's.f3',
    es: 'Me llamo Matej.',
    en: 'My name is Matej.',
    altEs: ['Soy Matej.'],
    concepts: ['p.me-llamo', 'v.llamarse'],
    level: 'A0',
    topics: ['introductions'],
    blanks: ['llamo'],
  },
  {
    id: 's.f4',
    es: '¿Cómo te llamas?',
    en: 'What’s your name?',
    concepts: ['p.como-te-llamas', 'g.questions'],
    level: 'A0',
    topics: ['introductions'],
  },
  {
    id: 's.f5',
    es: 'Soy esloveno, de Liubliana.',
    en: 'I’m Slovenian, from Ljubljana.',
    concepts: ['v.ser', 'v.esloveno', 'p.soy-de'],
    level: 'A1',
    topics: ['introductions'],
    blanks: ['Soy'],
  },
  {
    id: 's.f6',
    es: '¿De dónde eres?',
    en: 'Where are you from?',
    concepts: ['p.de-donde-eres', 'v.ser', 'v.donde'],
    level: 'A0',
    topics: ['introductions'],
  },
  {
    id: 's.f7',
    es: 'Encantada, yo soy Marta.',
    en: 'Nice to meet you, I’m Marta.',
    concepts: ['p.encantado', 'v.ser'],
    level: 'A1',
    topics: ['introductions'],
    note: 'Marta says encantada because the adjective agrees with the speaker.',
  },
  {
    id: 's.f8',
    es: 'Vivo en Madrid desde hace dos años.',
    en: 'I’ve been living in Madrid for two years.',
    concepts: ['v.vivir', 'p.vivo-en', 'v.anos'],
    level: 'A2',
    topics: ['introductions', 'city'],
    note: 'Spanish uses the present with desde hace where English needs a perfect.',
  },
  {
    id: 's.f9',
    es: 'Tengo veintiún años.',
    en: 'I’m twenty-one.',
    concepts: ['v.tener', 'v.anos', 'g.tener-expressions'],
    level: 'A1',
    topics: ['introductions', 'numbers'],
    blanks: ['Tengo'],
    note: 'Age is something you *have* in Spanish.',
  },
  {
    id: 's.f10',
    es: '¿Cuántos años tienes?',
    en: 'How old are you?',
    concepts: ['p.cuantos-anos-tienes', 'v.tener'],
    level: 'A1',
    topics: ['introductions'],
  },
  {
    id: 's.f11',
    es: 'Hablo un poco de español.',
    en: 'I speak a bit of Spanish.',
    concepts: ['v.hablar', 'v.un-poco', 'g.present-regular'],
    level: 'A0',
    topics: ['introductions'],
    blanks: ['Hablo'],
  },
  {
    id: 's.f12',
    es: 'No hablo francés.',
    en: 'I don’t speak French.',
    concepts: ['v.no', 'v.hablar', 'g.negation'],
    level: 'A0',
    topics: ['introductions'],
    blanks: ['No'],
  },
  {
    id: 's.f13',
    es: '¿Vivís en Madrid o en Barcelona?',
    en: 'Do you (all) live in Madrid or Barcelona?',
    concepts: ['v.vivir', 'v.vosotros', 'g.present-regular'],
    level: 'A1',
    topics: ['introductions', 'city'],
    blanks: ['Vivís'],
    note: 'Vosotros form — you would use ustedes viven in Latin America.',
  },
  {
    id: 's.f14',
    es: 'Somos de Valencia.',
    en: 'We’re from Valencia.',
    concepts: ['v.ser', 'v.nosotros'],
    level: 'A1',
    topics: ['introductions'],
  },
  {
    id: 's.f15',
    es: 'Mi hermana es profesora.',
    en: 'My sister is a teacher.',
    concepts: ['v.hermano', 'v.ser', 'g.ser-estar'],
    level: 'A1',
    topics: ['family', 'work'],
    note: 'No article before a profession: es profesora, not es una profesora.',
  },
  {
    id: 's.f16',
    es: 'Estoy cansado hoy.',
    en: 'I’m tired today.',
    concepts: ['v.estar', 'v.cansado', 'g.ser-estar', 'v.hoy'],
    level: 'A1',
    topics: ['feelings'],
    blanks: ['Estoy'],
  },
  {
    id: 's.f17',
    es: 'Madrid está en el centro de España.',
    en: 'Madrid is in the centre of Spain.',
    concepts: ['v.estar', 'g.ser-estar'],
    level: 'A1',
    topics: ['city'],
    blanks: ['está'],
  },
  {
    id: 's.f18',
    es: 'Madrid es una ciudad muy grande.',
    en: 'Madrid is a very big city.',
    concepts: ['v.ser', 'v.ciudad', 'v.grande', 'v.muy', 'g.ser-estar'],
    level: 'A1',
    topics: ['city', 'describing'],
    blanks: ['es'],
  },
  {
    id: 's.f19',
    es: 'Mi piso es pequeño pero está muy bien.',
    en: 'My flat is small but it’s really nice.',
    concepts: ['v.piso', 'v.ser', 'v.estar', 'v.pequeno', 'v.pero', 'g.ser-estar'],
    level: 'A2',
    topics: ['home'],
    note: 'Ser for what it is, estar for how it feels to live in.',
  },
  {
    id: 's.f20',
    es: 'Tengo un perro que se llama Nube.',
    en: 'I have a dog called Nube.',
    concepts: ['v.tener', 'v.perro', 'v.llamarse'],
    level: 'A1',
    topics: ['family', 'home'],
    blanks: ['Tengo'],
  },
  {
    id: 's.f21',
    es: '¿Tienes hermanos?',
    en: 'Do you have any brothers or sisters?',
    concepts: ['v.tener', 'v.hermano', 'g.questions'],
    level: 'A1',
    topics: ['family'],
  },
  {
    id: 's.f22',
    es: 'Sí, tengo un hermano y dos hermanas.',
    en: 'Yes, I have one brother and two sisters.',
    concepts: ['v.si', 'v.tener', 'v.hermano', 'v.dos', 'v.y'],
    level: 'A1',
    topics: ['family', 'numbers'],
  },
  {
    id: 's.f23',
    es: 'Mis padres viven en un pueblo pequeño.',
    en: 'My parents live in a small village.',
    concepts: ['v.padre', 'v.vivir', 'v.pequeno'],
    level: 'A2',
    topics: ['family'],
    note: 'Los padres means "the parents", not "the fathers".',
  },
  {
    id: 's.f24',
    es: 'Vale, hasta luego.',
    en: 'Okay, see you later.',
    concepts: ['v.vale', 'p.hasta-luego'],
    level: 'A1',
    topics: ['greetings'],
  },
  {
    id: 's.f25',
    es: 'Perdona, ¿hablas inglés?',
    en: 'Excuse me, do you speak English?',
    concepts: ['v.perdona', 'v.hablar', 'g.questions'],
    level: 'A1',
    topics: ['greetings', 'city'],
  },
  {
    id: 's.f26',
    es: 'Muchas gracias, muy amable.',
    en: 'Thank you very much, that’s very kind.',
    concepts: ['v.gracias', 'v.muy'],
    level: 'A1',
    topics: ['greetings'],
  },
  {
    id: 's.f27',
    es: 'Buenos días, ¿me pones un café con leche?',
    en: 'Good morning, can I get a coffee with milk?',
    concepts: ['p.buenos-dias', 'p.me-pones', 'p.cafe-con-leche'],
    level: 'A2',
    topics: ['cafe'],
  },
  {
    id: 's.f28',
    es: 'Somos cuatro, ¿hay mesa?',
    en: 'There are four of us, is there a table?',
    concepts: ['v.ser', 'v.cuatro', 'g.hay-estar', 'v.mesa'],
    level: 'A2',
    topics: ['restaurant'],
  },
  {
    id: 's.f29',
    es: 'Hay un bar muy bueno en mi calle.',
    en: 'There’s a really good bar on my street.',
    concepts: ['g.hay-estar', 'v.calle', 'v.muy'],
    level: 'A1',
    topics: ['city'],
    blanks: ['Hay'],
  },
  {
    id: 's.f30',
    es: 'El bar está al lado del metro.',
    en: 'The bar is next to the metro.',
    concepts: ['v.estar', 'v.al-lado', 'v.metro', 'g.hay-estar'],
    level: 'A2',
    topics: ['directions'],
    blanks: ['está'],
  },
  {
    id: 's.f31',
    es: 'No tengo coche, voy en metro.',
    en: 'I don’t have a car, I take the metro.',
    concepts: ['v.no', 'v.tener', 'v.coche', 'v.ir', 'v.metro'],
    level: 'A2',
    topics: ['transport'],
  },
  {
    id: 's.f32',
    es: '¿Cómo estás? Te veo cansada.',
    en: 'How are you? You look tired.',
    concepts: ['p.como-estas', 'v.ver', 'v.cansado'],
    level: 'A2',
    topics: ['greetings', 'feelings'],
  },
  {
    id: 's.f33',
    es: 'Mi ordenador no funciona.',
    en: 'My computer isn’t working.',
    concepts: ['v.ordenador', 'v.no'],
    level: 'A1',
    topics: ['home', 'work'],
    note: 'In Spain it is ordenador; computadora would mark you as a Latin-American speaker.',
  },
  {
    id: 's.f34',
    es: '¿Me dejas tu móvil un momento?',
    en: 'Can you lend me your phone for a moment?',
    concepts: ['v.movil'],
    level: 'A2',
    topics: ['home', 'social'],
  },
  {
    id: 's.f35',
    es: 'Es un libro difícil, pero me gusta.',
    en: 'It’s a difficult book, but I like it.',
    concepts: ['v.ser', 'v.libro', 'v.dificil', 'v.pero', 'p.me-gusta'],
    level: 'A2',
    topics: ['hobbies'],
  },
  {
    id: 's.f36',
    es: 'Nosotras somos españolas.',
    en: 'We’re Spanish (women).',
    concepts: ['v.nosotros', 'v.ser', 'v.espanol', 'g.adjective-agreement'],
    level: 'A1',
    topics: ['introductions'],
    note: 'Nosotras and españolas — both feminine, because the group is.',
  },
  {
    id: 's.f37',
    es: '¿Sois de aquí?',
    en: 'Are you (all) from here?',
    concepts: ['v.ser', 'v.vosotros'],
    level: 'A1',
    topics: ['introductions'],
  },
  {
    id: 's.f38',
    es: 'La gente aquí es muy maja.',
    en: 'People here are really lovely.',
    concepts: ['v.gente', 'v.ser', 'v.majo'],
    level: 'A2',
    topics: ['describing', 'social'],
    note: 'La gente is singular in Spanish, so the verb is es.',
  },
  {
    id: 's.f39',
    es: 'Estamos en la plaza, ¿dónde estás tú?',
    en: 'We’re in the square, where are you?',
    concepts: ['v.estar', 'v.plaza', 'v.donde'],
    level: 'A2',
    topics: ['directions', 'plans'],
  },
  {
    id: 's.f40',
    es: 'Hoy no trabajo, tengo el día libre.',
    en: 'I’m not working today, I have the day off.',
    concepts: ['v.hoy', 'v.no', 'v.trabajar', 'v.tener', 'g.negation'],
    level: 'A2',
    topics: ['work'],
  },

  // --- The present tense, met across all three conjugations ----------------
  {
    id: 's.f41',
    es: 'Hablo español, mi hermana habla francés y mis padres no hablan idiomas.',
    en: 'I speak Spanish, my sister speaks French and my parents don’t speak languages.',
    concepts: ['g.present-regular', 'v.hablar', 'v.idioma'],
    level: 'A1',
    topics: ['introductions'],
    blanks: ['Hablo', 'habla', 'hablan'],
    note: 'One verb, three endings — the whole point of the -ar pattern in a single sentence.',
  },
  {
    id: 's.f42',
    es: 'Comemos a las dos y mis abuelos comen a la una.',
    en: 'We eat at two and my grandparents eat at one.',
    concepts: ['g.present-regular', 'v.comer', 'v.abuelo'],
    level: 'A1',
    topics: ['food', 'time'],
    blanks: ['Comemos', 'comen'],
  },
  {
    id: 's.f43',
    es: '¿Vives solo o vivís juntos?',
    en: 'Do you live alone or do you two live together?',
    concepts: ['g.present-regular', 'v.vivir', 'v.vosotros'],
    level: 'A1',
    topics: ['home'],
    note: 'vives / vivís — the tú and vosotros forms differ by one syllable and an accent.',
  },
  {
    id: 's.f44',
    es: 'Trabajo mucho, estudio poco y no leo nada.',
    en: 'I work a lot, study little and read nothing.',
    concepts: ['g.present-regular', 'v.trabajar', 'v.leer'],
    level: 'A1',
    topics: ['work', 'university'],
  },
  {
    id: 's.f45',
    es: 'Bebemos agua en la comida y no bebemos vino nunca.',
    en: 'We drink water with lunch and never drink wine.',
    concepts: ['g.present-regular', 'v.beber', 'v.agua'],
    level: 'A1',
    topics: ['food'],
  },

  // --- Gender, where getting it wrong actually shows ------------------------
  {
    id: 's.f46',
    es: 'El día está bueno, pero la mano me duele.',
    en: 'The weather is nice, but my hand hurts.',
    concepts: ['g.gender', 'v.dia', 'v.mano'],
    level: 'A1',
    topics: ['weather', 'health'],
    note: 'el día is masculine despite the -a; la mano feminine despite the -o. Both are common traps.',
  },
  {
    id: 's.f47',
    es: 'La foto del mapa está en el sofá.',
    en: 'The photo of the map is on the sofa.',
    concepts: ['g.gender', 'v.casa'],
    level: 'A1',
    topics: ['home'],
    note: 'foto is feminine (from fotografía); mapa and sofá are masculine. The ending decides less than you think.',
  },
  {
    id: 's.f48',
    es: 'Tengo un problema con la leche: no me gusta.',
    en: 'I have a problem with milk: I don’t like it.',
    concepts: ['g.gender', 'v.leche', 'g.gustar'],
    level: 'A1',
    topics: ['food'],
  },

  // --- Articles, plurals and agreement, together ---------------------------
  {
    id: 's.f49',
    es: 'Los coches rojos son más caros que las bicicletas azules.',
    en: 'Red cars are more expensive than blue bicycles.',
    concepts: ['g.plurals', 'g.adjective-agreement', 'v.rojo', 'v.azul'],
    level: 'A1',
    topics: ['transport', 'describing'],
    note: 'Article, noun and adjective all move to plural together — nothing is left behind.',
  },
  {
    id: 's.f50',
    es: 'Es una ciudad pequeña con unas calles muy estrechas.',
    en: 'It’s a small city with very narrow streets.',
    concepts: ['g.articles', 'g.adjective-agreement', 'v.calle'],
    level: 'A1',
    topics: ['city', 'describing'],
  },
  {
    id: 's.f51',
    es: 'Los lunes son largos y los viernes cortos.',
    en: 'Mondays are long and Fridays short.',
    concepts: ['g.plurals', 'g.adjective-agreement', 'v.lunes', 'v.viernes'],
    level: 'A1',
    topics: ['time'],
  },
  {
    id: 's.f52',
    es: 'Quiero el pan, no un pan cualquiera.',
    en: 'I want the bread, not just any bread.',
    concepts: ['g.articles', 'v.pan', 'p.quiero'],
    level: 'A1',
    topics: ['food', 'shopping'],
    note: 'el = the one we both know; un = any one. Spanish leans on this distinction more than English.',
  },

  // --- Questions, possessives, demonstratives, dates, numbers -------------
  {
    id: 's.f53',
    es: '¿Cuándo llegas y a qué hora te vas?',
    en: 'When do you arrive and what time are you leaving?',
    concepts: ['g.questions', 'v.cuando', 'v.hora'],
    level: 'A1',
    topics: ['time', 'travel'],
  },
  {
    id: 's.f54',
    es: '¿Cuál es tu apellido y cómo se escribe?',
    en: 'What’s your surname and how do you spell it?',
    concepts: ['g.questions', 'p.como-se-escribe'],
    level: 'A1',
    topics: ['introductions'],
    note: 'cuál asks you to pick from a set; qué asks for a definition. Spanish keeps them apart.',
  },
  {
    id: 's.f55',
    es: 'Nuestro piso es pequeño, pero vuestra casa es enorme.',
    en: 'Our flat is small, but your house is huge.',
    concepts: ['g.possessives', 'v.nuestro', 'v.vuestro'],
    level: 'A1',
    topics: ['home'],
  },
  {
    id: 's.f56',
    es: 'Su coche y sus bicicletas están en el garaje.',
    en: 'His car and his bicycles are in the garage.',
    concepts: ['g.possessives', 'v.su'],
    level: 'A1',
    topics: ['home', 'transport'],
    note: 'su agrees with the thing owned, not the owner — su coche, sus bicicletas.',
  },
  {
    id: 's.f57',
    es: 'Este café está frío, ese está mejor y aquel ya no lo quiere nadie.',
    en: 'This coffee is cold, that one is better and nobody wants that one over there any more.',
    concepts: ['g.demonstratives', 'v.ese', 'v.aquel'],
    level: 'A1',
    topics: ['cafe'],
    note: 'All three distances in one sentence: este, ese, aquel.',
  },
  {
    id: 's.f58',
    es: 'Esta semana no, esa tampoco; mejor la siguiente.',
    en: 'Not this week, not that one either; better the one after.',
    concepts: ['g.demonstratives', 'v.semana'],
    level: 'A1',
    topics: ['time', 'plans'],
  },
  {
    id: 's.f59',
    es: 'Nací el treinta y uno de diciembre de mil novecientos noventa y ocho.',
    en: 'I was born on the thirty-first of December, nineteen ninety-eight.',
    concepts: ['g.dates', 'g.numbers-system', 'v.diciembre'],
    level: 'A1',
    topics: ['time', 'numbers'],
    note: 'Spanish reads years as one whole number: mil novecientos noventa y ocho.',
  },
  {
    id: 's.f60',
    es: 'Del uno al quince de agosto está todo cerrado.',
    en: 'From the first to the fifteenth of August everything is closed.',
    concepts: ['g.dates', 'v.quince', 'v.agosto'],
    level: 'A1',
    topics: ['time'],
  },
  {
    id: 's.f61',
    es: 'Doscientos cincuenta más trescientos son quinientos cincuenta.',
    en: 'Two hundred and fifty plus three hundred is five hundred and fifty.',
    concepts: ['g.numbers-system', 'v.cincuenta'],
    level: 'A1',
    topics: ['numbers'],
    note: 'Spanish inserts no "and" between hundreds and tens: doscientos cincuenta, never doscientos y cincuenta.',
  },
  {
    id: 's.f62',
    es: 'Tengo sed y tengo prisa, así que voy a por agua ya.',
    en: 'I’m thirsty and in a hurry, so I’m going to get water now.',
    concepts: ['g.tener-expressions', 'p.tengo-prisa', 'g.ir-a-infinitive'],
    level: 'A1',
    topics: ['food', 'daily-routine'],
    note: 'ir a por algo — "to go and get something" — is Spain-specific; Latin America says ir por.',
  },
  {
    id: 's.f63',
    es: 'Tenemos frío porque la ventana está abierta.',
    en: 'We’re cold because the window is open.',
    concepts: ['g.tener-expressions', 'v.porque'],
    level: 'A1',
    topics: ['home', 'weather'],
    note: 'People tener frío; things and weather están or hace frío.',
  },
  {
    id: 's.f64',
    es: 'Voy a llamarte luego y vamos a hablar con calma.',
    en: 'I’ll call you later and we’re going to talk properly.',
    concepts: ['g.ir-a-infinitive', 'v.luego', 'v.hablar'],
    level: 'A1',
    topics: ['social', 'plans'],
  },
  {
    id: 's.f65',
    es: '¿Vais a quedaros o vais a volver esta noche?',
    en: 'Are you going to stay or are you going to come back tonight?',
    concepts: ['g.ir-a-infinitive', 'v.vosotros', 'v.noche'],
    level: 'A1',
    topics: ['plans', 'travel'],
  },
];
