import type { Sentence } from '@/content/types';

/**
 * Sentences someone would actually say. Each is tagged with the concepts it
 * exercises, so a single line can become a translation, a word bank, a gap
 * fill, a dictation and a listening item.
 */
export const foundationsSentences: Sentence[] = [
  {
    id: 's.f1',
    es: 'Hola, ¿qué tal?',
    en: 'Hi, how are you?',
    altEn: ['Hi, how’s it going?'],
    concepts: ['v.hola', 'p.que-tal'],
    level: 'A0',
    topics: ['greetings'],
  },
  {
    id: 's.f2',
    es: 'Muy bien, ¿y tú?',
    en: 'Very well, and you?',
    concepts: ['p.muy-bien', 'p.y-tu'],
    level: 'A0',
    topics: ['greetings'],
  },
  {
    id: 's.f3',
    es: 'Me llamo Matej.',
    en: 'My name is Matej.',
    altEs: ['Soy Matej.'],
    concepts: ['p.me-llamo', 'v.llamarse'],
    level: 'A0',
    topics: ['introductions'],
    blanks: ['llamo'],
  },
  {
    id: 's.f4',
    es: '¿Cómo te llamas?',
    en: 'What’s your name?',
    concepts: ['p.como-te-llamas', 'g.questions'],
    level: 'A0',
    topics: ['introductions'],
  },
  {
    id: 's.f5',
    es: 'Soy esloveno, de Liubliana.',
    en: 'I’m Slovenian, from Ljubljana.',
    concepts: ['v.ser', 'v.esloveno', 'p.soy-de'],
    level: 'A1',
    topics: ['introductions'],
    blanks: ['Soy'],
  },
  {
    id: 's.f6',
    es: '¿De dónde eres?',
    en: 'Where are you from?',
    concepts: ['p.de-donde-eres', 'v.ser', 'v.donde'],
    level: 'A0',
    topics: ['introductions'],
  },
  {
    id: 's.f7',
    es: 'Encantada, yo soy Marta.',
    en: 'Nice to meet you, I’m Marta.',
    concepts: ['p.encantado', 'v.ser'],
    level: 'A1',
    topics: ['introductions'],
    note: 'Marta says encantada because the adjective agrees with the speaker.',
  },
  {
    id: 's.f8',
    es: 'Vivo en Madrid desde hace dos años.',
    en: 'I’ve been living in Madrid for two years.',
    concepts: ['v.vivir', 'p.vivo-en', 'v.anos'],
    level: 'A2',
    topics: ['introductions', 'city'],
    note: 'Spanish uses the present with desde hace where English needs a perfect.',
  },
  {
    id: 's.f9',
    es: 'Tengo veintiún años.',
    en: 'I’m twenty-one.',
    concepts: ['v.tener', 'v.anos', 'g.tener-expressions'],
    level: 'A1',
    topics: ['introductions', 'numbers'],
    blanks: ['Tengo'],
    note: 'Age is something you *have* in Spanish.',
  },
  {
    id: 's.f10',
    es: '¿Cuántos años tienes?',
    en: 'How old are you?',
    concepts: ['p.cuantos-anos-tienes', 'v.tener'],
    level: 'A1',
    topics: ['introductions'],
  },
  {
    id: 's.f11',
    es: 'Hablo un poco de español.',
    en: 'I speak a bit of Spanish.',
    concepts: ['v.hablar', 'v.un-poco', 'g.present-regular'],
    level: 'A0',
    topics: ['introductions'],
    blanks: ['Hablo'],
  },
  {
    id: 's.f12',
    es: 'No hablo francés.',
    en: 'I don’t speak French.',
    concepts: ['v.no', 'v.hablar', 'g.negation'],
    level: 'A0',
    topics: ['introductions'],
    blanks: ['No'],
  },
  {
    id: 's.f13',
    es: '¿Vivís en Madrid o en Barcelona?',
    en: 'Do you (all) live in Madrid or Barcelona?',
    concepts: ['v.vivir', 'v.vosotros', 'g.present-regular'],
    level: 'A1',
    topics: ['introductions', 'city'],
    blanks: ['Vivís'],
    note: 'Vosotros form — you would use ustedes viven in Latin America.',
  },
  {
    id: 's.f14',
    es: 'Somos de Valencia.',
    en: 'We’re from Valencia.',
    concepts: ['v.ser', 'v.nosotros'],
    level: 'A1',
    topics: ['introductions'],
  },
  {
    id: 's.f15',
    es: 'Mi hermana es profesora.',
    en: 'My sister is a teacher.',
    concepts: ['v.hermano', 'v.ser', 'g.ser-estar'],
    level: 'A1',
    topics: ['family', 'work'],
    note: 'No article before a profession: es profesora, not es una profesora.',
  },
  {
    id: 's.f16',
    es: 'Estoy cansado hoy.',
    en: 'I’m tired today.',
    concepts: ['v.estar', 'v.cansado', 'g.ser-estar', 'v.hoy'],
    level: 'A1',
    topics: ['feelings'],
    blanks: ['Estoy'],
  },
  {
    id: 's.f17',
    es: 'Madrid está en el centro de España.',
    en: 'Madrid is in the centre of Spain.',
    concepts: ['v.estar', 'g.ser-estar'],
    level: 'A1',
    topics: ['city'],
    blanks: ['está'],
  },
  {
    id: 's.f18',
    es: 'Madrid es una ciudad muy grande.',
    en: 'Madrid is a very big city.',
    concepts: ['v.ser', 'v.ciudad', 'v.grande', 'v.muy', 'g.ser-estar'],
    level: 'A1',
    topics: ['city', 'describing'],
    blanks: ['es'],
  },
  {
    id: 's.f19',
    es: 'Mi piso es pequeño pero está muy bien.',
    en: 'My flat is small but it’s really nice.',
    concepts: ['v.piso', 'v.ser', 'v.estar', 'v.pequeno', 'v.pero', 'g.ser-estar'],
    level: 'A2',
    topics: ['home'],
    note: 'Ser for what it is, estar for how it feels to live in.',
  },
  {
    id: 's.f20',
    es: 'Tengo un perro que se llama Nube.',
    en: 'I have a dog called Nube.',
    concepts: ['v.tener', 'v.perro', 'v.llamarse'],
    level: 'A1',
    topics: ['family', 'home'],
    blanks: ['Tengo'],
  },
  {
    id: 's.f21',
    es: '¿Tienes hermanos?',
    en: 'Do you have any brothers or sisters?',
    concepts: ['v.tener', 'v.hermano', 'g.questions'],
    level: 'A1',
    topics: ['family'],
  },
  {
    id: 's.f22',
    es: 'Sí, tengo un hermano y dos hermanas.',
    en: 'Yes, I have one brother and two sisters.',
    concepts: ['v.si', 'v.tener', 'v.hermano', 'v.dos', 'v.y'],
    level: 'A1',
    topics: ['family', 'numbers'],
  },
  {
    id: 's.f23',
    es: 'Mis padres viven en un pueblo pequeño.',
    en: 'My parents live in a small village.',
    concepts: ['v.padre', 'v.vivir', 'v.pequeno'],
    level: 'A2',
    topics: ['family'],
    note: 'Los padres means "the parents", not "the fathers".',
  },
  {
    id: 's.f24',
    es: 'Vale, hasta luego.',
    en: 'Okay, see you later.',
    concepts: ['v.vale', 'p.hasta-luego'],
    level: 'A1',
    topics: ['greetings'],
  },
  {
    id: 's.f25',
    es: 'Perdona, ¿hablas inglés?',
    en: 'Excuse me, do you speak English?',
    concepts: ['v.perdona', 'v.hablar', 'g.questions'],
    level: 'A1',
    topics: ['greetings', 'city'],
  },
  {
    id: 's.f26',
    es: 'Muchas gracias, muy amable.',
    en: 'Thank you very much, that’s very kind.',
    concepts: ['v.gracias', 'v.muy'],
    level: 'A1',
    topics: ['greetings'],
  },
  {
    id: 's.f27',
    es: 'Buenos días, ¿me pones un café con leche?',
    en: 'Good morning, can I get a coffee with milk?',
    concepts: ['p.buenos-dias', 'p.me-pones', 'p.cafe-con-leche'],
    level: 'A2',
    topics: ['cafe'],
  },
  {
    id: 's.f28',
    es: 'Somos cuatro, ¿hay mesa?',
    en: 'There are four of us, is there a table?',
    concepts: ['v.ser', 'v.cuatro', 'g.hay-estar', 'v.mesa'],
    level: 'A2',
    topics: ['restaurant'],
  },
  {
    id: 's.f29',
    es: 'Hay un bar muy bueno en mi calle.',
    en: 'There’s a really good bar on my street.',
    concepts: ['g.hay-estar', 'v.calle', 'v.muy'],
    level: 'A1',
    topics: ['city'],
    blanks: ['Hay'],
  },
  {
    id: 's.f30',
    es: 'El bar está al lado del metro.',
    en: 'The bar is next to the metro.',
    concepts: ['v.estar', 'v.al-lado', 'v.metro', 'g.hay-estar'],
    level: 'A2',
    topics: ['directions'],
    blanks: ['está'],
  },
  {
    id: 's.f31',
    es: 'No tengo coche, voy en metro.',
    en: 'I don’t have a car, I take the metro.',
    concepts: ['v.no', 'v.tener', 'v.coche', 'v.ir', 'v.metro'],
    level: 'A2',
    topics: ['transport'],
  },
  {
    id: 's.f32',
    es: '¿Cómo estás? Te veo cansada.',
    en: 'How are you? You look tired.',
    concepts: ['p.como-estas', 'v.ver', 'v.cansado'],
    level: 'A2',
    topics: ['greetings', 'feelings'],
  },
  {
    id: 's.f33',
    es: 'Mi ordenador no funciona.',
    en: 'My computer isn’t working.',
    concepts: ['v.ordenador', 'v.no'],
    level: 'A1',
    topics: ['home', 'work'],
    note: 'In Spain it is ordenador; computadora would mark you as a Latin-American speaker.',
  },
  {
    id: 's.f34',
    es: '¿Me dejas tu móvil un momento?',
    en: 'Can you lend me your phone for a moment?',
    concepts: ['v.movil'],
    level: 'A2',
    topics: ['home', 'social'],
  },
  {
    id: 's.f35',
    es: 'Es un libro difícil, pero me gusta.',
    en: 'It’s a difficult book, but I like it.',
    concepts: ['v.ser', 'v.libro', 'v.dificil', 'v.pero', 'p.me-gusta'],
    level: 'A2',
    topics: ['hobbies'],
  },
  {
    id: 's.f36',
    es: 'Nosotras somos españolas.',
    en: 'We’re Spanish (women).',
    concepts: ['v.nosotros', 'v.ser', 'v.espanol', 'g.adjective-agreement'],
    level: 'A1',
    topics: ['introductions'],
    note: 'Nosotras and españolas — both feminine, because the group is.',
  },
  {
    id: 's.f37',
    es: '¿Sois de aquí?',
    en: 'Are you (all) from here?',
    concepts: ['v.ser', 'v.vosotros'],
    level: 'A1',
    topics: ['introductions'],
  },
  {
    id: 's.f38',
    es: 'La gente aquí es muy maja.',
    en: 'People here are really lovely.',
    concepts: ['v.gente', 'v.ser', 'v.majo'],
    level: 'A2',
    topics: ['describing', 'social'],
    note: 'La gente is singular in Spanish, so the verb is es.',
  },
  {
    id: 's.f39',
    es: 'Estamos en la plaza, ¿dónde estás tú?',
    en: 'We’re in the square, where are you?',
    concepts: ['v.estar', 'v.plaza', 'v.donde'],
    level: 'A2',
    topics: ['directions', 'plans'],
  },
  {
    id: 's.f40',
    es: 'Hoy no trabajo, tengo el día libre.',
    en: 'I’m not working today, I have the day off.',
    concepts: ['v.hoy', 'v.no', 'v.trabajar', 'v.tener', 'g.negation'],
    level: 'A2',
    topics: ['work'],
  },
];
