import type { Sentence } from '@/content/types';

/** Daily routine, reflexive verbs and the shape of an ordinary week. */
export const routineSentences: Sentence[] = [
  {
    id: 's.r1',
    es: 'Me levanto a las siete y media.',
    en: 'I get up at half past seven.',
    concepts: ['v.levantarse', 'g.reflexive', 'v.siete', 'v.media'],
    level: 'A2',
    topics: ['daily-routine'],
    blanks: ['Me'],
  },
  {
    id: 's.r2',
    es: 'Me ducho y desayuno rápido.',
    en: 'I have a shower and eat breakfast quickly.',
    concepts: ['v.ducharse', 'g.reflexive', 'v.desayuno'],
    level: 'A2',
    topics: ['daily-routine'],
  },
  {
    id: 's.r3',
    es: '¿A qué hora te levantas normalmente?',
    en: 'What time do you normally get up?',
    concepts: ['v.levantarse', 'g.reflexive', 'v.hora', 'g.questions'],
    level: 'A2',
    topics: ['daily-routine'],
  },
  {
    id: 's.r4',
    es: 'Los fines de semana me despierto tardísimo.',
    en: 'At weekends I wake up really late.',
    concepts: ['v.fin-de-semana', 'v.despertarse', 'g.reflexive'],
    level: 'A2',
    topics: ['daily-routine'],
    note: '-ísimo is the everyday way to say "really": tardísimo, buenísimo, cansadísimo.',
  },
  {
    id: 's.r5',
    es: 'Me acuesto sobre las doce.',
    en: 'I go to bed around twelve.',
    concepts: ['v.acostarse', 'g.reflexive', 'p.sobre-las'],
    level: 'A2',
    topics: ['daily-routine'],
  },
  {
    id: 's.r6',
    es: '¿A qué hora os acostáis vosotros?',
    en: 'What time do you (all) go to bed?',
    concepts: ['v.acostarse', 'g.reflexive', 'v.vosotros'],
    level: 'A2',
    topics: ['daily-routine'],
    blanks: ['os'],
    note: 'The os pronoun is the vosotros one — Spain only.',
  },
  {
    id: 's.r7',
    es: 'Voy al trabajo en metro todos los días.',
    en: 'I go to work by metro every day.',
    concepts: ['v.ir', 'v.trabajo', 'v.metro'],
    level: 'A2',
    topics: ['daily-routine', 'transport'],
  },
  {
    id: 's.r8',
    es: 'Cojo el autobús en la parada de la plaza.',
    en: 'I catch the bus at the stop in the square.',
    concepts: ['v.coger', 'v.autobus', 'v.parada', 'v.plaza'],
    level: 'A2',
    topics: ['transport'],
    note: 'Coger is completely ordinary in Spain — and best avoided in much of Latin America.',
  },
  {
    id: 's.r9',
    es: 'Tengo un coche, pero casi nunca conduzco.',
    en: 'I have a car, but I hardly ever drive.',
    concepts: ['v.tener', 'v.coche', 'v.nunca', 'v.conducir'],
    level: 'A2',
    topics: ['transport'],
  },
  {
    id: 's.r10',
    es: 'Tengo que estudiar esta tarde.',
    en: 'I have to study this afternoon.',
    concepts: ['p.tener-que', 'v.estudiar', 'v.tarde', 'g.tener-expressions'],
    level: 'A2',
    topics: ['university', 'daily-routine'],
    blanks: ['que'],
  },
  {
    id: 's.r11',
    es: 'No puedo salir, tengo mucho trabajo.',
    en: 'I can’t go out, I have a lot of work.',
    concepts: ['v.poder', 'v.salir', 'v.mucho', 'v.trabajo'],
    level: 'A2',
    topics: ['work', 'plans'],
  },
  {
    id: 's.r12',
    es: 'Hago deporte tres veces por semana.',
    en: 'I do sport three times a week.',
    concepts: ['v.hacer', 'v.deporte', 'v.tres', 'g.por-para'],
    level: 'A2',
    topics: ['hobbies', 'daily-routine'],
    blanks: ['por'],
  },
  {
    id: 's.r13',
    es: '¿Qué haces los sábados?',
    en: 'What do you do on Saturdays?',
    concepts: ['v.hacer', 'v.que', 'g.questions'],
    level: 'A1',
    topics: ['plans', 'daily-routine'],
  },
  {
    id: 's.r14',
    es: 'Después de comer, siempre tomo un café.',
    en: 'After lunch, I always have a coffee.',
    concepts: ['v.despues', 'v.comer', 'v.siempre', 'v.tomar', 'v.cafe'],
    level: 'A2',
    topics: ['daily-routine', 'food'],
  },
  {
    id: 's.r15',
    es: 'Estoy muy cansado, tengo sueño.',
    en: 'I’m really tired, I’m sleepy.',
    concepts: ['v.estar', 'v.cansado', 'p.tengo-sueno', 'g.ser-estar'],
    level: 'A2',
    topics: ['feelings'],
  },
  {
    id: 's.r16',
    es: 'Perdona, tengo prisa, ya hablamos.',
    en: 'Sorry, I’m in a hurry, we’ll talk later.',
    concepts: ['v.perdona', 'p.tengo-prisa', 'v.ya', 'v.hablar'],
    level: 'B1',
    topics: ['social', 'time'],
    note: 'Ya hablamos is a very Spanish way to close a conversation without committing to anything.',
  },
  {
    id: 's.r17',
    es: 'Hoy estoy contento porque no trabajo.',
    en: 'Today I’m happy because I’m not working.',
    concepts: ['v.estar', 'v.contento', 'v.porque', 'v.trabajar', 'g.ser-estar'],
    level: 'A2',
    topics: ['feelings', 'work'],
  },
  {
    id: 's.r18',
    es: 'Está un poco nerviosa por el examen.',
    en: 'She’s a bit nervous about the exam.',
    concepts: ['v.estar', 'v.nervioso', 'v.un-poco', 'g.adjective-agreement'],
    level: 'A2',
    topics: ['feelings', 'university'],
  },
  {
    id: 's.r19',
    es: 'Mi hermano está enfadado conmigo.',
    en: 'My brother is angry with me.',
    concepts: ['v.hermano', 'v.estar', 'v.enfadado'],
    level: 'A2',
    topics: ['feelings', 'family'],
    note: 'Enfadado in Spain, enojado in Latin America.',
  },
  {
    id: 's.r20',
    es: 'Escribo muchos correos en el trabajo.',
    en: 'I write a lot of emails at work.',
    concepts: ['v.escribir', 'v.mucho', 'v.trabajo'],
    level: 'A2',
    topics: ['work'],
  },
  {
    id: 's.r21',
    es: 'No sé dónde está mi móvil.',
    en: 'I don’t know where my phone is.',
    concepts: ['v.saber', 'v.donde', 'v.estar', 'v.movil'],
    level: 'A2',
    topics: ['home'],
    blanks: ['sé'],
    note: 'Saber for facts; if you knew the phone personally it would be conozco.',
  },
  {
    id: 's.r22',
    es: 'Conozco un sitio muy bueno para cenar.',
    en: 'I know a really good place for dinner.',
    concepts: ['v.conocer', 'v.cena', 'g.por-para'],
    level: 'A2',
    topics: ['restaurant', 'social'],
    note: 'Conocer for places and people; saber for facts.',
  },
  {
    id: 's.r23',
    es: '¿Sabes cocinar tortilla de patatas?',
    en: 'Do you know how to make Spanish omelette?',
    concepts: ['v.saber', 'v.cocinar', 'v.tortilla'],
    level: 'A2',
    topics: ['food'],
    note: 'Saber + infinitive means "to know how to".',
  },
  {
    id: 's.r24',
    es: 'Veo una serie española por la noche.',
    en: 'I watch a Spanish series at night.',
    concepts: ['v.ver', 'v.espanol', 'v.noche'],
    level: 'A2',
    topics: ['hobbies'],
  },
  {
    id: 's.r25',
    es: 'Mañana me levanto pronto porque tengo tren.',
    en: 'Tomorrow I’m getting up early because I have a train.',
    concepts: ['v.manana', 'v.levantarse', 'v.porque', 'v.tren'],
    level: 'A2',
    topics: ['daily-routine', 'travel'],
    note: 'Present tense doing future work — completely normal with a time marker.',
  },
  {
    id: 's.r26',
    es: 'Los lunes son horribles.',
    en: 'Mondays are horrible.',
    concepts: ['v.lunes', 'v.ser'],
    level: 'A1',
    topics: ['time', 'opinions'],
  },
  {
    id: 's.r27',
    es: 'Vivimos cerca de la universidad.',
    en: 'We live near the university.',
    concepts: ['v.vivir', 'v.cerca', 'v.universidad'],
    level: 'A1',
    topics: ['home', 'university'],
  },
  {
    id: 's.r28',
    es: 'Trabajáis mucho, ¿no?',
    en: 'You (all) work a lot, don’t you?',
    concepts: ['v.trabajar', 'v.vosotros', 'v.mucho'],
    level: 'A2',
    topics: ['work'],
    note: '¿no? tagged on the end is the everyday way to seek agreement.',
  },
  {
    id: 's.r29',
    es: 'Me lavo los dientes antes de salir.',
    en: 'I brush my teeth before going out.',
    concepts: ['g.reflexive', 'v.antes', 'v.salir'],
    level: 'A2',
    topics: ['daily-routine'],
    note: 'Spanish uses los dientes, not "my teeth" — the reflexive already says whose.',
  },
  {
    id: 's.r30',
    es: 'Me voy, que mañana madrugo.',
    en: 'I’m off, I’ve got an early start tomorrow.',
    concepts: ['g.reflexive', 'v.manana', 'v.ir'],
    level: 'B1',
    topics: ['social', 'daily-routine'],
    note: 'Irse = to leave. That que means "because" here — very colloquial and very common.',
  },

  // --- The morning, in more than one order ---------------------------------
  {
    id: 's.r31',
    es: 'Me despierto a las siete pero no me levanto hasta las siete y media.',
    en: 'I wake up at seven but I don’t get up until half past.',
    concepts: ['v.despertarse', 'v.levantarse', 'g.reflexive'],
    level: 'A2',
    topics: ['daily-routine'],
    note: 'despertarse and levantarse are two different moments, and Spanish keeps them apart.',
  },
  {
    id: 's.r32',
    es: 'Me ducho por la noche, así por la mañana tengo más tiempo.',
    en: 'I shower at night, that way I have more time in the morning.',
    concepts: ['v.ducharse', 'g.reflexive', 'v.noche'],
    level: 'A2',
    topics: ['daily-routine'],
  },
  {
    id: 's.r33',
    es: 'Tengo prisa, me ducho en cinco minutos y salgo.',
    en: 'I’m in a hurry, I’ll shower in five minutes and go.',
    concepts: ['p.tengo-prisa', 'v.ducharse', 'v.salir'],
    level: 'A2',
    topics: ['daily-routine'],
  },
  {
    id: 's.r34',
    es: 'Entonces te despiertas, desayunas y ya está, ¿no?',
    en: 'So you wake up, have breakfast and that’s it, right?',
    concepts: ['v.entonces', 'v.despertarse', 'v.desayuno'],
    level: 'A2',
    topics: ['daily-routine'],
    register: 'colloquial',
  },

  // --- dar, poner, llevar, traer: four verbs that carry a lot -------------
  {
    id: 's.r35',
    es: 'Llevo dos años estudiando español y todavía me cuesta.',
    en: 'I’ve been studying Spanish for two years and I still find it hard.',
    concepts: ['v.llevar', 'v.estudiar', 'v.espanol'],
    level: 'A2',
    topics: ['university', 'time'],
    blanks: ['Llevo'],
    note: 'llevar + tiempo + gerundio is how Spanish says "have been doing" — there is no present perfect here.',
  },
  {
    id: 's.r36',
    es: '¿Cuánto tiempo llevas esperando?',
    en: 'How long have you been waiting?',
    concepts: ['v.llevar', 'v.cuanto', 'v.tiempo'],
    level: 'A2',
    topics: ['social', 'time'],
  },
  {
    id: 's.r37',
    es: 'Hoy llevo el abrigo gris, hace frío.',
    en: 'I’m wearing the grey coat today, it’s cold.',
    concepts: ['v.llevar', 'v.gris', 'p.hace-frio'],
    level: 'A2',
    topics: ['shopping', 'weather'],
    note: 'The same verb does "wear" — llevar gafas, llevar barba, llevar abrigo.',
  },
  {
    id: 's.r38',
    es: 'Llevamos las bebidas nosotros, no compres nada.',
    en: 'We’ll bring the drinks, don’t buy anything.',
    concepts: ['v.llevar', 'v.comprar', 'g.commands'],
    level: 'A2',
    topics: ['social', 'food'],
    note: 'llevar is away from the speaker; traer is towards. English "bring" covers both, Spanish does not.',
  },
  {
    id: 's.r39',
    es: '¿Nos trae la carta y una jarra de agua, por favor?',
    en: 'Could you bring us the menu and a jug of water, please?',
    concepts: ['v.traer', 'v.carta', 'v.agua'],
    level: 'A2',
    topics: ['restaurant'],
  },
  {
    id: 's.r40',
    es: 'Traigo el postre yo, ya lo he comprado.',
    en: 'I’ll bring the dessert, I’ve already bought it.',
    concepts: ['v.traer', 'g.present-perfect', 'v.comprar'],
    level: 'A2',
    topics: ['food', 'social'],
    note: 'traigo, not trao — traer takes the -ig- yo form, like hacer takes hago.',
  },
  {
    id: 's.r41',
    es: '¿Me pones otro café y me traes la cuenta?',
    en: 'Could you get me another coffee and bring me the bill?',
    concepts: ['v.poner', 'v.traer', 'v.cuenta'],
    level: 'A2',
    topics: ['cafe'],
    note: 'poner for what the barman prepares, traer for what he carries over. Both in one breath.',
  },
  {
    id: 's.r42',
    es: 'Pon la mesa, que ya está la cena.',
    en: 'Lay the table, dinner’s ready.',
    concepts: ['v.poner', 'g.commands', 'v.cena'],
    level: 'A2',
    topics: ['home', 'food'],
  },
  {
    id: 's.r43',
    es: 'Dame un minuto y te doy una respuesta.',
    en: 'Give me a minute and I’ll give you an answer.',
    concepts: ['v.dar', 'g.commands'],
    level: 'A2',
    topics: ['work', 'social'],
  },
  {
    id: 's.r44',
    es: 'Mis padres me dieron el coche viejo cuando aprobé.',
    en: 'My parents gave me the old car when I passed.',
    concepts: ['v.dar', 'g.preterite', 'v.coche'],
    level: 'A2',
    topics: ['family', 'past'],
  },

  // --- Forms the corpus had nowhere, so conjugation could only be a table ---
  {
    id: 's.r45',
    es: 'Viajo bastante ahora, pero el año pasado viajé muchísimo más.',
    en: 'I travel quite a bit now, but last year I travelled far more.',
    concepts: ['v.viajar', 'g.present-regular', 'g.preterite'],
    level: 'A2',
    topics: ['travel', 'work'],
    note: 'Present and preterite of the same verb side by side — viajo, viajé.',
  },
  {
    id: 's.r46',
    es: 'Normalmente pago yo, pero ayer pagaste tú.',
    en: 'Normally I pay, but yesterday you paid.',
    concepts: ['v.pagar', 'g.present-regular', 'g.preterite'],
    level: 'A2',
    topics: ['shopping', 'social'],
  },
  {
    id: 's.r47',
    es: 'Compro el pan en la panadería de la esquina.',
    en: 'I buy bread at the bakery on the corner.',
    concepts: ['v.comprar', 'v.pan', 'g.present-regular'],
    level: 'A2',
    topics: ['shopping', 'food'],
  },
  {
    id: 's.r48',
    es: 'He llevado el coche al taller tres veces este mes.',
    en: 'I’ve taken the car to the garage three times this month.',
    concepts: ['v.llevar', 'g.present-perfect', 'v.coche'],
    level: 'A2',
    topics: ['transport'],
  },
  {
    id: 's.r49',
    es: 'He hablado con ella y ya está todo arreglado.',
    en: 'I’ve spoken to her and it’s all sorted now.',
    concepts: ['v.hablar', 'g.present-perfect'],
    level: 'A2',
    topics: ['social'],
  },
  {
    id: 's.r50',
    es: 'Hemos conocido a mucha gente en el curso.',
    en: 'We’ve met a lot of people on the course.',
    concepts: ['v.conocer', 'g.present-perfect', 'v.gente'],
    level: 'A2',
    topics: ['social', 'university'],
  },
  {
    id: 's.r51',
    es: 'He escrito tres correos y sigo sin respuesta.',
    en: 'I’ve written three emails and I still have no reply.',
    concepts: ['v.escribir', 'g.present-perfect', 'v.seguir'],
    level: 'A2',
    topics: ['work'],
    note: 'escrito, not escribido — one of the handful of irregular participles worth memorising.',
  },
  {
    id: 's.r52',
    es: 'Pondremos el aire acondicionado cuando llegue el verano.',
    en: 'We’ll put the air conditioning on when summer comes.',
    concepts: ['v.poner', 'g.future', 'g.subjunctive-intro'],
    level: 'B1',
    topics: ['home'],
    note: 'cuando about the future takes the subjunctive: cuando llegue, never cuando llegará.',
  },
];
