import type { Sentence } from '@/content/types';

/** Making plans, opinions, and the colloquial register people actually use. */
export const socialSentences: Sentence[] = [
  {
    id: 's.s1',
    es: '¿Quieres quedar mañana?',
    en: 'Do you want to meet up tomorrow?',
    concepts: ['v.querer', 'v.quedar', 'v.manana', 'p.quieres-quedar'],
    level: 'A2',
    topics: ['plans'],
    blanks: ['quedar'],
  },
  {
    id: 's.s2',
    es: 'Vale, ¿a qué hora quedamos?',
    en: 'Okay, what time shall we meet?',
    concepts: ['v.vale', 'v.quedar', 'v.hora'],
    level: 'A2',
    topics: ['plans'],
  },
  {
    id: 's.s3',
    es: 'Hemos quedado a las ocho delante del metro.',
    en: 'We’re meeting at eight in front of the metro.',
    concepts: ['v.quedar', 'g.present-perfect', 'v.ocho', 'v.delante', 'v.metro'],
    level: 'B1',
    topics: ['plans', 'directions'],
    note: 'Present perfect for a plan already agreed — extremely common in Spain.',
  },
  {
    id: 's.s4',
    es: '¿Qué haces mañana por la tarde?',
    en: 'What are you doing tomorrow afternoon?',
    concepts: ['v.hacer', 'v.manana', 'v.tarde', 'g.por-para'],
    level: 'A2',
    topics: ['plans'],
  },
  {
    id: 's.s5',
    es: 'Voy a estudiar por la mañana, pero podemos quedar por la tarde.',
    en: 'I’m going to study in the morning, but we can meet up in the afternoon.',
    concepts: ['g.ir-a-infinitive', 'v.estudiar', 'v.pero', 'v.poder', 'v.quedar'],
    level: 'A2',
    topics: ['plans'],
    blanks: ['Voy'],
  },
  {
    id: 's.s6',
    es: '¿Tomamos algo después de clase?',
    en: 'Shall we grab a drink after class?',
    concepts: ['v.tomar', 'p.tomar-algo', 'v.despues', 'v.clase'],
    level: 'A2',
    topics: ['plans', 'social'],
  },
  {
    id: 's.s7',
    es: 'Me apetece un café.',
    en: 'I fancy a coffee.',
    concepts: ['p.me-apetece', 'v.cafe'],
    level: 'A2',
    topics: ['plans', 'cafe'],
    blanks: ['apetece'],
  },
  {
    id: 's.s8',
    es: 'No me apetece salir hoy, estoy muerto.',
    en: 'I don’t feel like going out today, I’m shattered.',
    concepts: ['p.me-apetece', 'v.salir', 'v.estar'],
    level: 'B1',
    topics: ['plans', 'feelings'],
    note: 'Estoy muerto is everyday hyperbole for "I’m exhausted".',
  },
  {
    id: 's.s9',
    es: 'Vamos a cenar fuera el sábado.',
    en: 'We’re going out for dinner on Saturday.',
    concepts: ['g.ir-a-infinitive', 'v.cena'],
    level: 'A2',
    topics: ['plans', 'restaurant'],
  },
  {
    id: 's.s10',
    es: 'Me gusta mucho el cine español.',
    en: 'I really like Spanish cinema.',
    concepts: ['p.me-gusta', 'g.gustar', 'v.mucho', 'v.espanol'],
    level: 'A1',
    topics: ['hobbies', 'opinions'],
    blanks: ['gusta'],
  },
  {
    id: 's.s11',
    es: 'Me gustan las películas antiguas.',
    en: 'I like old films.',
    concepts: ['p.me-gustan', 'g.gustar', 'v.pelicula'],
    level: 'A2',
    topics: ['hobbies', 'opinions'],
    blanks: ['gustan'],
    note: 'Plural thing → gustan.',
  },
  {
    id: 's.s12',
    es: 'Me encanta viajar.',
    en: 'I love travelling.',
    concepts: ['p.me-encanta', 'g.gustar', 'v.viajar'],
    level: 'A2',
    topics: ['travel', 'opinions'],
    note: 'A verb after gustar-type verbs is always singular.',
  },
  {
    id: 's.s13',
    es: 'A mí no me gusta nada el fútbol.',
    en: 'I don’t like football at all.',
    concepts: ['p.no-me-gusta-nada', 'g.gustar', 'v.futbol', 'g.negation'],
    level: 'A2',
    topics: ['hobbies', 'opinions'],
    note: 'A mí adds emphasis — useful when you disagree with someone.',
  },
  {
    id: 's.s14',
    es: '¿Te gusta el fútbol? — Ni idea, no lo veo nunca.',
    en: 'Do you like football? — No idea, I never watch it.',
    concepts: ['g.gustar', 'v.futbol', 'p.ni-idea', 'v.nunca'],
    level: 'B1',
    topics: ['opinions', 'slang'],
  },
  {
    id: 's.s15',
    es: 'Creo que es buena idea.',
    en: 'I think it’s a good idea.',
    concepts: ['v.creo-que', 'v.ser'],
    level: 'A2',
    topics: ['opinions'],
  },
  {
    id: 's.s16',
    es: 'Pues no sé, a mí me da igual.',
    en: 'Well, I don’t know, I don’t mind either way.',
    concepts: ['v.pues', 'v.saber', 'p.da-igual'],
    level: 'B1',
    topics: ['opinions', 'slang'],
  },
  {
    id: 's.s17',
    es: 'Venga, nos vemos luego.',
    en: 'Alright, see you later.',
    concepts: ['v.venga', 'v.ver', 'v.luego'],
    level: 'A2',
    topics: ['social', 'slang'],
    note: 'Venga closes a conversation the way "right then" does in English.',
  },
  {
    id: 's.s18',
    es: 'Qué guay, ¿vienes tú también?',
    en: 'How cool, are you coming too?',
    concepts: ['p.que-guay', 'v.venir', 'v.tambien'],
    level: 'B1',
    topics: ['social', 'slang'],
  },
  {
    id: 's.s19',
    es: 'Tío, qué fuerte lo de ayer.',
    en: 'Mate, that thing yesterday was mad.',
    concepts: ['v.tio', 'p.que-fuerte', 'v.ayer'],
    level: 'B1',
    topics: ['slang', 'social'],
    note: 'Lo de + noun = "that business with…". Very common.',
  },
  {
    id: 's.s20',
    es: 'Estaba en plan cansado y me fui a casa.',
    en: 'I was kind of tired so I went home.',
    concepts: ['p.en-plan', 'v.cansado', 'g.imperfect', 'g.preterite'],
    level: 'B1',
    topics: ['slang', 'past'],
  },
  {
    id: 's.s21',
    es: 'Claro, hombre, sin problema.',
    en: 'Of course, no problem at all.',
    concepts: ['v.claro'],
    level: 'B1',
    topics: ['social', 'slang'],
    note: 'Hombre here is filler, not "man" — it is used to women too.',
  },
  {
    id: 's.s22',
    es: 'Esa canción mola mucho.',
    en: 'That song is really cool.',
    concepts: ['v.molar', 'v.mucho'],
    level: 'B1',
    topics: ['slang', 'hobbies'],
    note: 'Molar behaves like gustar: me mola, me molan.',
  },
  {
    id: 's.s23',
    es: 'Qué rollo, otra vez lloviendo.',
    en: 'What a drag, raining again.',
    concepts: ['p.que-rollo'],
    level: 'B1',
    topics: ['slang', 'weather'],
  },
  {
    id: 's.s24',
    es: 'A ver, déjame pensar un momento.',
    en: 'Let’s see, let me think for a second.',
    concepts: ['p.a-ver'],
    level: 'B1',
    topics: ['slang', 'social'],
  },
  {
    id: 's.s25',
    es: 'Salimos de fiesta y volvimos a las cinco.',
    en: 'We went out partying and got back at five.',
    concepts: ['p.salir-de-fiesta', 'g.preterite', 'v.cinco'],
    level: 'B1',
    topics: ['social', 'past'],
  },
  {
    id: 's.s26',
    es: 'Ayer fui al cine con Marta.',
    en: 'Yesterday I went to the cinema with Marta.',
    concepts: ['v.ayer', 'g.preterite', 'v.ir'],
    level: 'A2',
    topics: ['past', 'social'],
    blanks: ['fui'],
  },
  {
    id: 's.s27',
    es: '¿Qué hiciste el fin de semana?',
    en: 'What did you do at the weekend?',
    concepts: ['g.preterite', 'v.hacer', 'v.fin-de-semana'],
    level: 'A2',
    topics: ['past'],
    blanks: ['hiciste'],
  },
  {
    id: 's.s28',
    es: 'Estuve en Sevilla tres días.',
    en: 'I was in Seville for three days.',
    concepts: ['g.preterite', 'v.estar', 'v.tres'],
    level: 'A2',
    topics: ['past', 'travel'],
  },
  {
    id: 's.s29',
    es: 'De pequeño vivía en un pueblo.',
    en: 'As a child I lived in a village.',
    concepts: ['g.imperfect', 'v.vivir', 'v.pequeno'],
    level: 'B1',
    topics: ['past'],
    blanks: ['vivía'],
  },
  {
    id: 's.s30',
    es: 'Estaba en el bar cuando llegó Marta.',
    en: 'I was in the bar when Marta arrived.',
    concepts: ['g.preterite-imperfect', 'g.imperfect', 'g.preterite', 'v.estar'],
    level: 'B1',
    topics: ['past', 'storytelling'],
    note: 'Imperfect sets the scene, preterite is the event that cuts in.',
  },
  {
    id: 's.s31',
    es: 'Iba a llamarte, pero se me olvidó.',
    en: 'I was going to call you, but I forgot.',
    concepts: ['g.imperfect', 'p.se-me-ha-olvidado', 'v.pero'],
    level: 'B1',
    topics: ['past', 'social'],
  },
  {
    id: 's.s32',
    es: 'Aunque estaba cansado, salí igual.',
    en: 'Even though I was tired, I went out anyway.',
    concepts: ['v.aunque', 'g.imperfect', 'g.preterite', 'v.cansado'],
    level: 'B1',
    topics: ['past', 'storytelling'],
  },
  {
    id: 's.s33',
    es: 'Entonces llegó tarde y no pudimos entrar.',
    en: 'Then he arrived late and we couldn’t get in.',
    concepts: ['v.entonces', 'g.preterite', 'v.poder'],
    level: 'B1',
    topics: ['storytelling', 'past'],
  },
  {
    id: 's.s34',
    es: 'Quiero que vengas a la fiesta.',
    en: 'I want you to come to the party.',
    concepts: ['g.subjunctive-intro', 'v.querer', 'v.venir', 'v.fiesta'],
    level: 'B1',
    topics: ['plans', 'social'],
    blanks: ['vengas'],
  },
  {
    id: 's.s35',
    es: 'Espero que te guste.',
    en: 'I hope you like it.',
    concepts: ['g.subjunctive-intro', 'g.gustar'],
    level: 'B1',
    topics: ['social', 'opinions'],
  },
  {
    id: 's.s36',
    es: '¿Me lo puedes mandar por WhatsApp?',
    en: 'Can you send it to me on WhatsApp?',
    concepts: ['g.object-pronouns', 'v.poder', 'g.por-para'],
    level: 'B1',
    topics: ['social'],
  },
  {
    id: 's.s37',
    es: 'Le dije que no podía.',
    en: 'I told him I couldn’t.',
    concepts: ['g.object-pronouns', 'v.decir', 'g.preterite', 'g.imperfect'],
    level: 'B1',
    topics: ['past', 'social'],
  },
  {
    id: 's.s38',
    es: 'Gracias por venir, de verdad.',
    en: 'Thanks for coming, really.',
    concepts: ['v.gracias', 'g.por-para', 'v.venir'],
    level: 'A2',
    topics: ['social'],
    blanks: ['por'],
    note: 'Always gracias por, never gracias para.',
  },
  {
    id: 's.s39',
    es: 'Es un regalo para mi hermana.',
    en: 'It’s a present for my sister.',
    concepts: ['g.por-para', 'v.hermano'],
    level: 'A2',
    topics: ['shopping'],
    blanks: ['para'],
  },
  {
    id: 's.s40',
    es: 'Bueno, yo me voy yendo, que es tarde.',
    en: 'Right, I’m going to head off, it’s late.',
    concepts: ['v.bueno', 'g.reflexive', 'v.tarde'],
    level: 'B1',
    topics: ['social', 'slang'],
    note: 'Irse yendo — "to start leaving". Spaniards announce their departure long before actually going.',
  },

  // --- Fixing the plan: the exact wording Spaniards use -------------------
  {
    id: 's.s41',
    es: 'Hemos quedado a las ocho en la puerta del cine.',
    en: "We're meeting at eight at the cinema entrance.",
    concepts: ['p.hemos-quedado', 'v.quedar'],
    level: 'B1',
    topics: ['plans', 'social'],
    note: 'quedar is not reflexive here — hemos quedado, never nos hemos quedado, which would mean "we stayed".',
  },
  {
    id: 's.s42',
    es: 'Quedamos delante del metro y vamos andando.',
    en: "Let's meet in front of the metro and walk from there.",
    concepts: ['p.quedamos-en', 'v.quedar', 'v.metro'],
    level: 'B1',
    topics: ['plans', 'transport'],
    note: 'The present tense settles the plan — Spanish rarely uses a future here.',
  },
  {
    id: 's.s43',
    es: '¿A qué hora habéis quedado al final?',
    en: 'What time did you all end up arranging to meet?',
    concepts: ['p.hemos-quedado', 'v.vosotros', 'g.present-perfect'],
    level: 'B1',
    topics: ['plans', 'social'],
  },
  {
    id: 's.s44',
    es: 'Habíamos quedado en vernos el jueves, pero lo dejamos para el viernes.',
    en: "We'd agreed to meet on Thursday, but we moved it to Friday.",
    concepts: ['p.quedamos-en', 'g.pluperfect'],
    level: 'B1',
    topics: ['plans'],
    note: 'quedar en + infinitivo = to agree to do something, a step beyond arranging a time.',
  },
  {
    id: 's.s45',
    es: '¿Cómo eres? — Tranquilo, pero un poco cabezota.',
    en: "What are you like? — Easy-going, but a bit stubborn.",
    concepts: ['p.como-eres', 'g.ser-estar'],
    level: 'A2',
    topics: ['describing', 'people'],
    note: '¿Cómo eres? asks about character; ¿cómo estás? asks about right now.',
  },
  {
    id: 's.s46',
    es: 'Dime cómo eres y te digo con quién te llevarías bien.',
    en: "Tell me what you're like and I'll tell you who you'd get on with.",
    concepts: ['p.como-eres', 'p.llevarse-bien', 'g.conditional'],
    level: 'B1',
    topics: ['describing', 'people'],
  },

  // --- The small words that carry a Spanish conversation -------------------
  {
    id: 's.s47',
    es: '—¿Nos vamos? —Venga, vale, pero un momento.',
    en: '“Shall we go?” “Come on then, alright, but hang on a second.”',
    concepts: ['v.venga', 'v.vale'],
    level: 'A2',
    topics: ['social', 'slang'],
    register: 'colloquial',
    note: 'venga does encouragement, agreement and goodbye depending on tone alone.',
  },
  {
    id: 's.s48',
    es: '—¿Y tu hermano? —Pues no sé, no me ha dicho nada.',
    en: '“And your brother?” “Well, I don’t know, he hasn’t said anything to me.”',
    concepts: ['v.pues', 'g.present-perfect'],
    level: 'A2',
    topics: ['social', 'slang'],
    register: 'colloquial',
    note: 'pues buys you a second at the start of an answer. It means almost nothing and appears constantly.',
  },
  {
    id: 's.s49',
    es: 'Bueno, yo lo dejo aquí, que mañana madrugo.',
    en: 'Right, I’ll leave it there, I’ve got an early start tomorrow.',
    concepts: ['v.bueno', 'v.manana'],
    level: 'A2',
    topics: ['social', 'slang'],
    register: 'colloquial',
  },
  {
    id: 's.s50',
    es: '—¿Ya has comido? —Sí, ya, hace un rato.',
    en: '“Have you eaten yet?” “Yes, already, a while ago.”',
    concepts: ['v.ya', 'g.present-perfect'],
    level: 'A2',
    topics: ['food', 'social'],
    register: 'colloquial',
  },
  {
    id: 's.s51',
    es: 'Entonces quedamos a las ocho y luego ya vemos.',
    en: 'So we’ll meet at eight and then we’ll see.',
    concepts: ['v.entonces', 'v.luego', 'v.quedar'],
    level: 'A2',
    topics: ['plans', 'social'],
    register: 'colloquial',
    note: 'ya vemos — "we’ll see" — closes a plan without committing to the details.',
  },
  {
    id: 's.s52',
    es: '¿Quieres quedar mañana y tomamos algo por el centro?',
    en: 'Do you want to meet tomorrow and grab a drink in town?',
    concepts: ['p.quieres-quedar', 'p.tomar-algo'],
    level: 'A2',
    topics: ['plans', 'social'],
  },
  {
    id: 's.s53',
    es: 'El sábado salimos de fiesta, ¿te apuntas?',
    en: 'On Saturday we’re going out, are you in?',
    concepts: ['p.salir-de-fiesta', 'v.sabado'],
    level: 'A2',
    topics: ['social'],
    register: 'colloquial',
    note: '¿te apuntas? — "are you in?" — the standard invitation to join a plan.',
  },
  {
    id: 's.s54',
    es: 'Su novia es majísima, te va a caer muy bien.',
    en: 'His girlfriend is lovely, you’ll really like her.',
    concepts: ['v.novio', 'v.majo', 'v.su'],
    level: 'A2',
    topics: ['people', 'social'],
    register: 'colloquial',
    note: 'majo is one of the most Spanish compliments there is, and barely used elsewhere.',
  },
  {
    id: 's.s55',
    es: 'Perdona, ¿sabes dónde está la parada del veintiuno?',
    en: 'Excuse me, do you know where the number 21 stop is?',
    concepts: ['p.perdona-donde', 'v.parada', 'v.veintiuno'],
    level: 'A2',
    topics: ['directions', 'transport'],
  },

  // --- The colloquial register, heard rather than studied ------------------
  {
    id: 's.s56',
    es: 'O sea, que al final no viene nadie, ¿no?',
    en: 'So basically nobody’s coming in the end, right?',
    concepts: ['v.o-sea', 'v.al-final'],
    level: 'B1',
    topics: ['slang', 'social'],
    register: 'colloquial',
    note: 'o sea reformulates what was just said. In Spain it lands roughly once a sentence.',
  },
  {
    id: 's.s57',
    es: 'A ver, tampoco es para tanto, tío.',
    en: 'Come on, it’s not that big a deal, mate.',
    concepts: ['p.a-ver', 'v.tio'],
    level: 'B1',
    topics: ['slang', 'social'],
    register: 'colloquial',
    note: 'no es para tanto — "it’s not that bad" — the standard de-escalation.',
  },
  {
    id: 's.s58',
    es: '—¿Sabes algo de Marta? —Ni idea, tía, no me coge el teléfono.',
    en: '“Any news from Marta?” “No idea, she’s not picking up.”',
    concepts: ['p.ni-idea', 'v.tio', 'v.coger'],
    level: 'B1',
    topics: ['slang', 'social'],
    register: 'colloquial',
    note: 'tío / tía is address, not description — closer to "mate" than to "uncle".',
  },
  {
    id: 's.s59',
    es: '¡Qué fuerte! ¿Y ella qué dijo?',
    en: 'No way! And what did she say?',
    concepts: ['p.que-fuerte', 'g.preterite', 'v.decir'],
    level: 'B1',
    topics: ['slang', 'storytelling'],
    register: 'colloquial',
  },
  {
    id: 's.s60',
    es: 'Qué rollo tener que ir hasta allí un domingo.',
    en: 'What a drag having to go all the way there on a Sunday.',
    concepts: ['p.que-rollo', 'v.domingo', 'p.tener-que'],
    level: 'B1',
    topics: ['slang'],
    register: 'colloquial',
  },
  {
    id: 's.s61',
    es: 'Me dijo en plan «ya te llamo» y no llamó nunca.',
    en: 'He was like “I’ll call you” and never called.',
    concepts: ['p.en-plan', 'g.reported-speech', 'v.nunca'],
    level: 'B1',
    topics: ['slang', 'storytelling'],
    register: 'colloquial',
    note: 'en plan introduces a quotation or an approximation, exactly like English "like".',
  },
  {
    id: 's.s62',
    es: 'El sitio nuevo mola bastante, y encima está al lado.',
    en: 'The new place is pretty cool, and it’s right nearby too.',
    concepts: ['v.molar', 'v.cerca'],
    level: 'B1',
    topics: ['slang', 'opinions'],
    register: 'colloquial',
  },
  {
    id: 's.s63',
    es: '¡Qué guay que vengas! Se lo digo a los demás.',
    en: 'How great that you’re coming! I’ll tell the others.',
    concepts: ['p.que-guay', 'g.subjunctive-intro'],
    level: 'B1',
    topics: ['slang', 'social'],
    register: 'colloquial',
    blanks: ['vengas'],
  },
];
