import type { Sentence } from '@/content/types';

/**
 * Commands and the subjunctive — the two paradigms the conjugation system
 * declared and never carried.
 *
 * These sentences exist to make `f.<verb>.imperative` and
 * `f.<verb>.presentSubjunctive` *practisable*, not merely derivable. Paradigms
 * here are found by text-matching the conjugated form (see `verb-corpus.ts`),
 * so a paradigm with no sentence containing its forms is a conjugation table
 * and nothing else.
 *
 * Two authoring rules, both load-bearing:
 *
 * 1. **Every command opens with ¡ and puts the verb first.** That is how the
 *    corpus index tells "¡Habla más despacio!" from "Ella habla despacio" —
 *    the same six letters in the same corpus doing different jobs. A command
 *    written without its ¡ is invisible to the imperative and gets miscounted
 *    as present indicative.
 * 2. **No subjunctive sentence opens with ¡ followed by its own verb**, for the
 *    mirror reason: the first word of an exclamation is claimed by the
 *    imperative, so a subjunctive placed there would be credited to the wrong
 *    paradigm. Subordinate clauses are where the subjunctive lives anyway.
 */
export const subjunctiveImperativeSentences: Sentence[] = [
  // === Commands (tú) ========================================================
  {
    id: 's.j1',
    es: '¡Habla más despacio, por favor!',
    en: 'Speak more slowly, please!',
    concepts: ['g.commands'],
    level: 'A2',
    topics: ['social'],
    blanks: ['Habla'],
  },
  {
    id: 's.j2',
    es: '¡Come algo antes de salir!',
    en: 'Eat something before you go out!',
    concepts: ['g.commands'],
    level: 'A2',
    topics: ['food'],
    blanks: ['Come'],
  },
  {
    id: 's.j3',
    es: '¡Ven aquí un momento!',
    en: 'Come here a moment!',
    concepts: ['g.commands'],
    level: 'A2',
    topics: ['social'],
    blanks: ['Ven'],
    note: 'Ven is one of the eight irregular tú commands — not "viene".',
  },
  {
    id: 's.j4',
    es: '¡Ten cuidado con el escalón!',
    en: 'Be careful with the step!',
    concepts: ['g.commands'],
    level: 'A2',
    topics: ['city'],
    blanks: ['Ten'],
  },
  {
    id: 's.j5',
    es: '¡Haz la cama antes de irte!',
    en: 'Make the bed before you leave!',
    concepts: ['g.commands'],
    level: 'A2',
    topics: ['home'],
    blanks: ['Haz'],
  },
  {
    id: 's.j6',
    es: '¡Di la verdad de una vez!',
    en: 'Tell the truth once and for all!',
    concepts: ['g.commands'],
    level: 'A2',
    topics: ['social'],
    blanks: ['Di'],
  },
  {
    id: 's.j7',
    es: '¡Sal de ahí ahora mismo!',
    en: 'Get out of there right now!',
    concepts: ['g.commands'],
    level: 'A2',
    topics: ['home'],
    blanks: ['Sal'],
  },
  {
    id: 's.j8',
    es: '¡Pon el móvil en silencio!',
    en: 'Put your phone on silent!',
    concepts: ['g.commands'],
    level: 'A2',
    topics: ['social'],
    blanks: ['Pon'],
  },
  {
    id: 's.j9',
    es: '¡Sé puntual mañana!',
    en: 'Be on time tomorrow!',
    concepts: ['g.commands'],
    level: 'A2',
    topics: ['work'],
    blanks: ['Sé'],
  },
  {
    id: 's.j10',
    es: '¡Ve al médico si te duele tanto!',
    en: 'Go to the doctor if it hurts that much!',
    concepts: ['g.commands'],
    level: 'A2',
    topics: ['health'],
    blanks: ['Ve'],
  },
  {
    id: 's.j11',
    es: '¡Escucha esta canción, te va a encantar!',
    en: "Listen to this song, you're going to love it!",
    concepts: ['g.commands'],
    level: 'A2',
    topics: ['hobbies'],
    blanks: ['Escucha'],
  },
  {
    id: 's.j12',
    es: '¡Vive el momento y deja de preocuparte!',
    en: 'Live in the moment and stop worrying!',
    concepts: ['g.commands'],
    level: 'A2',
    topics: ['feelings'],
    blanks: ['Vive'],
  },

  // === Commands (usted) =====================================================
  {
    id: 's.j13',
    es: '¡Hable con el encargado, por favor!',
    en: 'Speak to the manager, please!',
    concepts: ['g.commands'],
    level: 'A2',
    topics: ['shopping'],
    register: 'formal',
    blanks: ['Hable'],
    note: 'The usted command borrows the subjunctive form.',
  },
  {
    id: 's.j14',
    es: '¡Coma despacio, que le sentará mejor!',
    en: "Eat slowly, it'll sit better with you!",
    concepts: ['g.commands'],
    level: 'A2',
    topics: ['health'],
    register: 'formal',
    blanks: ['Coma'],
  },
  {
    id: 's.j15',
    es: '¡Venga conmigo, le enseño la sala!',
    en: "Come with me, I'll show you the room!",
    // v.venir corroborates: "venga" is also a discourse marker ("venga, hasta
    // luego"), and the corpus index will not credit the paradigm without it.
    concepts: ['g.commands', 'v.venir'],
    level: 'A2',
    topics: ['work'],
    register: 'formal',
    blanks: ['Venga'],
  },
  {
    id: 's.j16',
    es: '¡Tenga paciencia, ya casi está!',
    en: "Be patient, it's nearly ready!",
    concepts: ['g.commands'],
    level: 'A2',
    topics: ['social'],
    register: 'formal',
    blanks: ['Tenga'],
  },
  {
    id: 's.j17',
    es: '¡Haga el favor de esperar fuera!',
    en: 'Kindly wait outside!',
    concepts: ['g.commands'],
    level: 'A2',
    topics: ['work'],
    register: 'formal',
    blanks: ['Haga'],
  },
  {
    id: 's.j18',
    es: '¡Diga lo que piensa sin miedo!',
    en: 'Say what you think without fear!',
    concepts: ['g.commands'],
    level: 'A2',
    topics: ['opinions'],
    register: 'formal',
    blanks: ['Diga'],
  },
  {
    id: 's.j19',
    es: '¡Salga por la puerta de atrás!',
    en: 'Leave through the back door!',
    concepts: ['g.commands'],
    level: 'A2',
    topics: ['directions'],
    register: 'formal',
    blanks: ['Salga'],
  },
  {
    id: 's.j20',
    es: '¡Ponga aquí su firma!',
    en: 'Put your signature here!',
    concepts: ['g.commands'],
    level: 'A2',
    topics: ['work'],
    register: 'formal',
    blanks: ['Ponga'],
  },
  {
    id: 's.j21',
    es: '¡Sea amable con el chaval!',
    en: 'Be kind to the lad!',
    concepts: ['g.commands'],
    level: 'A2',
    topics: ['people'],
    register: 'formal',
    blanks: ['Sea'],
  },
  {
    id: 's.j22',
    es: '¡Vaya al final del pasillo!',
    en: 'Go to the end of the corridor!',
    concepts: ['g.commands'],
    level: 'A2',
    topics: ['directions'],
    register: 'formal',
    blanks: ['Vaya'],
  },
  {
    id: 's.j23',
    es: '¡Escuche bien lo que le voy a decir!',
    en: "Listen carefully to what I'm going to tell you!",
    concepts: ['g.commands'],
    level: 'A2',
    topics: ['social'],
    register: 'formal',
    blanks: ['Escuche'],
  },
  {
    id: 's.j24',
    es: '¡Viva la vida como quiera!',
    en: 'Live life however you like!',
    concepts: ['g.commands'],
    level: 'A2',
    topics: ['feelings'],
    register: 'formal',
    blanks: ['Viva'],
  },

  // === Commands (vosotros) — the Peninsular one =============================
  {
    id: 's.j25',
    es: '¡Hablad más bajo, que hay gente durmiendo!',
    en: "Keep your voices down, there are people sleeping!",
    concepts: ['g.commands'],
    level: 'A2',
    topics: ['home'],
    blanks: ['Hablad'],
    note: 'Vosotros commands: drop the -r of the infinitive, add -d. No exceptions.',
  },
  {
    id: 's.j26',
    es: '¡Comed algo, que luego no hay nada!',
    en: "Eat something, there'll be nothing later!",
    concepts: ['g.commands'],
    level: 'A2',
    topics: ['food'],
    blanks: ['Comed'],
  },
  {
    id: 's.j27',
    es: '¡Venid pronto, que empezamos a las ocho!',
    en: "Come early, we're starting at eight!",
    concepts: ['g.commands'],
    level: 'A2',
    topics: ['plans'],
    blanks: ['Venid'],
  },
  {
    id: 's.j28',
    es: '¡Tened los billetes a mano!',
    en: 'Have your tickets ready!',
    concepts: ['g.commands'],
    level: 'A2',
    topics: ['transport'],
    blanks: ['Tened'],
  },
  {
    id: 's.j29',
    es: '¡Haced lo que os apetezca!',
    en: 'Do whatever you feel like!',
    concepts: ['g.commands'],
    level: 'A2',
    topics: ['social'],
    blanks: ['Haced'],
  },
  {
    id: 's.j30',
    es: '¡Decid la verdad, que os conozco!',
    en: 'Tell the truth, I know you!',
    concepts: ['g.commands'],
    level: 'A2',
    topics: ['social'],
    blanks: ['Decid'],
  },
  {
    id: 's.j31',
    es: '¡Salid ya o perderéis el tren!',
    en: "Leave now or you'll miss the train!",
    concepts: ['g.commands'],
    level: 'A2',
    topics: ['transport'],
    blanks: ['Salid'],
  },
  {
    id: 's.j32',
    es: '¡Poned la mesa mientras cocino!',
    en: 'Set the table while I cook!',
    concepts: ['g.commands'],
    level: 'A2',
    topics: ['home'],
    blanks: ['Poned'],
  },
  {
    id: 's.j33',
    es: '¡Sed buenos con vuestra abuela!',
    en: 'Be good to your grandmother!',
    concepts: ['g.commands'],
    level: 'A2',
    topics: ['family'],
    blanks: ['Sed'],
  },
  {
    id: 's.j34',
    es: '¡Id vosotros delante, que yo os alcanzo!',
    en: "You go ahead, I'll catch you up!",
    concepts: ['g.commands'],
    level: 'A2',
    topics: ['directions'],
    blanks: ['Id'],
  },
  {
    id: 's.j35',
    es: '¡Escuchad esto, que os va a hacer gracia!',
    en: "Listen to this, you're going to find it funny!",
    concepts: ['g.commands'],
    level: 'A2',
    topics: ['social'],
    blanks: ['Escuchad'],
  },
  {
    id: 's.j36',
    es: '¡Vivid un poco, que sois muy jóvenes!',
    en: "Live a little, you're very young!",
    concepts: ['g.commands'],
    level: 'A2',
    topics: ['feelings'],
    blanks: ['Vivid'],
  },

  // === Commands (nosotros and ustedes) ======================================
  {
    id: 's.j37',
    es: '¡Hablemos de esto mañana con calma!',
    en: "Let's talk about this tomorrow, calmly!",
    concepts: ['g.commands'],
    level: 'A2',
    topics: ['work'],
    blanks: ['Hablemos'],
    note: 'The nosotros command is the subjunctive: "let’s ...".',
  },
  {
    id: 's.j38',
    es: '¡Comamos fuera esta noche!',
    en: "Let's eat out tonight!",
    concepts: ['g.commands'],
    level: 'A2',
    topics: ['restaurant'],
    blanks: ['Comamos'],
  },
  {
    id: 's.j39',
    es: '¡Vamos a la playa el domingo!',
    en: "Let's go to the beach on Sunday!",
    concepts: ['g.commands'],
    level: 'A2',
    topics: ['plans'],
    blanks: ['Vamos'],
    note: 'Ir is the one verb whose nosotros command is not the subjunctive: vamos, not vayamos.',
  },
  {
    id: 's.j40',
    es: '¡Hagamos las maletas esta noche!',
    en: "Let's pack tonight!",
    concepts: ['g.commands'],
    level: 'A2',
    topics: ['travel'],
    blanks: ['Hagamos'],
  },
  {
    id: 's.j41',
    es: '¡Salgamos antes de que empiece a llover!',
    en: "Let's leave before it starts raining!",
    concepts: ['g.commands'],
    level: 'A2',
    topics: ['weather'],
    blanks: ['Salgamos'],
  },
  {
    id: 's.j42',
    es: '¡Vengamos temprano la próxima vez!',
    en: "Let's come early next time!",
    concepts: ['g.commands'],
    level: 'A2',
    topics: ['plans'],
    blanks: ['Vengamos'],
  },
  {
    id: 's.j43',
    es: '¡Pongamos la mesa entre todos!',
    en: "Let's all set the table together!",
    concepts: ['g.commands'],
    level: 'A2',
    topics: ['home'],
    blanks: ['Pongamos'],
  },
  {
    id: 's.j44',
    es: '¡Tengamos la fiesta en paz!',
    en: "Let's keep the peace!",
    concepts: ['g.commands'],
    level: 'A2',
    topics: ['slang'],
    blanks: ['Tengamos'],
  },
  {
    id: 's.j45',
    es: '¡Hablen con el director cuando quieran!',
    en: 'Speak to the director whenever you like!',
    concepts: ['g.commands'],
    level: 'A2',
    topics: ['work'],
    register: 'formal',
    blanks: ['Hablen'],
  },
  {
    id: 's.j46',
    es: '¡Vengan por aquí, señores!',
    en: 'Come this way, gentlemen!',
    concepts: ['g.commands'],
    level: 'A2',
    topics: ['restaurant'],
    register: 'formal',
    blanks: ['Vengan'],
  },
  {
    id: 's.j47',
    es: '¡Tengan lista la documentación!',
    en: 'Have your paperwork ready!',
    concepts: ['g.commands'],
    level: 'A2',
    topics: ['travel'],
    register: 'formal',
    blanks: ['Tengan'],
  },
  {
    id: 's.j48',
    es: '¡Digan lo que quieran, a mí me da igual!',
    en: "Let them say what they like, I don't care!",
    concepts: ['g.commands'],
    level: 'A2',
    topics: ['opinions'],
    blanks: ['Digan'],
  },
  {
    id: 's.j49',
    es: '¡Sean puntuales, que el tren no espera!',
    en: "Be punctual, the train doesn't wait!",
    concepts: ['g.commands'],
    level: 'A2',
    topics: ['transport'],
    register: 'formal',
    blanks: ['Sean'],
  },
  {
    id: 's.j50',
    es: '¡Vayan al andén tres, por favor!',
    en: 'Go to platform three, please!',
    concepts: ['g.commands'],
    level: 'A2',
    topics: ['transport'],
    register: 'formal',
    blanks: ['Vayan'],
  },
  {
    id: 's.j51',
    es: '¡Escuchen con atención, que solo lo digo una vez!',
    en: "Listen carefully, I'm only saying it once!",
    concepts: ['g.commands'],
    level: 'A2',
    topics: ['university'],
    register: 'formal',
    blanks: ['Escuchen'],
  },
  {
    id: 's.j52',
    es: '¡Coman lo que quieran, hay de sobra!',
    en: "Eat whatever you like, there's plenty!",
    concepts: ['g.commands'],
    level: 'A2',
    topics: ['food'],
    register: 'formal',
    blanks: ['Coman'],
  },
  {
    id: 's.j53',
    es: '¡Salgan por la izquierda al llegar!',
    en: 'Exit on the left when you arrive!',
    concepts: ['g.commands'],
    level: 'A2',
    topics: ['directions'],
    register: 'formal',
    blanks: ['Salgan'],
  },
  {
    id: 's.j54',
    es: '¡Pongan los móviles en silencio, por favor!',
    en: 'Put your phones on silent, please!',
    concepts: ['g.commands'],
    level: 'A2',
    topics: ['social'],
    register: 'formal',
    blanks: ['Pongan'],
  },
  {
    id: 's.j55',
    es: '¡Hagan cola aquí, por favor!',
    en: 'Queue here, please!',
    concepts: ['g.commands'],
    level: 'A2',
    topics: ['city'],
    register: 'formal',
    blanks: ['Hagan'],
  },
  {
    id: 's.j56',
    es: '¡Vivan como quieran, es su casa!',
    en: "Live however you like, it's your house!",
    concepts: ['g.commands'],
    level: 'A2',
    topics: ['home'],
    register: 'formal',
    blanks: ['Vivan'],
  },
  {
    id: 's.j57',
    es: '¡Vivamos aquí un año y luego decidimos!',
    en: "Let's live here for a year and then decide!",
    concepts: ['g.commands'],
    level: 'A2',
    topics: ['home'],
    blanks: ['Vivamos'],
  },
  {
    id: 's.j58',
    es: '¡Digamos la verdad y ya está!',
    en: "Let's just tell the truth and be done with it!",
    concepts: ['g.commands'],
    level: 'A2',
    topics: ['social'],
    blanks: ['Digamos'],
  },
  {
    id: 's.j59',
    es: '¡Escuchemos su versión antes de juzgar!',
    en: "Let's hear their side before we judge!",
    concepts: ['g.commands'],
    level: 'A2',
    topics: ['opinions'],
    blanks: ['Escuchemos'],
  },
  {
    id: 's.j60',
    es: '¡Seamos realistas con el presupuesto!',
    en: "Let's be realistic about the budget!",
    concepts: ['g.commands'],
    level: 'A2',
    topics: ['work'],
    blanks: ['Seamos'],
  },

  // === Subjunctive: wanting, hoping, asking (B1) ============================
  {
    id: 's.j61',
    es: 'Quiero que hables con ella antes del viernes.',
    en: 'I want you to speak to her before Friday.',
    concepts: ['g.subjunctive-intro'],
    level: 'B1',
    topics: ['work'],
    blanks: ['hables'],
  },
  {
    id: 's.j62',
    es: 'Espero que comas bien esta semana.',
    en: 'I hope you eat well this week.',
    concepts: ['g.subjunctive-intro'],
    level: 'B1',
    topics: ['health'],
    blanks: ['comas'],
  },
  {
    id: 's.j63',
    es: 'Me apetece que vengas conmigo al concierto.',
    en: 'I fancy you coming with me to the concert.',
    concepts: ['g.subjunctive-intro'],
    level: 'B1',
    topics: ['hobbies'],
    blanks: ['vengas'],
  },
  {
    id: 's.j64',
    es: 'Prefiero que tengas el móvil encendido.',
    en: 'I prefer you to keep your phone on.',
    concepts: ['g.subjunctive-intro'],
    level: 'B1',
    topics: ['social'],
    blanks: ['tengas'],
  },
  {
    id: 's.j65',
    es: 'Necesito que hagas la compra hoy.',
    en: 'I need you to do the shopping today.',
    concepts: ['g.subjunctive-intro'],
    level: 'B1',
    topics: ['shopping'],
    blanks: ['hagas'],
  },
  {
    id: 's.j66',
    es: 'Te pido que digas lo que piensas de verdad.',
    en: 'I am asking you to say what you really think.',
    concepts: ['g.subjunctive-intro'],
    level: 'B1',
    topics: ['opinions'],
    blanks: ['digas'],
  },
  {
    id: 's.j67',
    es: 'Quiero que salgas de casa más a menudo.',
    en: 'I want you to leave the house more often.',
    concepts: ['g.subjunctive-intro'],
    level: 'B1',
    topics: ['feelings'],
    blanks: ['salgas'],
  },
  {
    id: 's.j68',
    es: 'Espero que pongas la lavadora antes de irte.',
    en: 'I hope you put the washing on before you leave.',
    concepts: ['g.subjunctive-intro'],
    level: 'B1',
    topics: ['home'],
    blanks: ['pongas'],
  },
  {
    id: 's.j69',
    es: 'Ojalá seas feliz en Madrid.',
    en: 'I hope you are happy in Madrid.',
    concepts: ['g.subjunctive-intro'],
    level: 'B1',
    topics: ['feelings'],
    blanks: ['seas'],
  },
  {
    id: 's.j70',
    es: 'Quiero que estés tranquilo mañana.',
    en: 'I want you to be relaxed tomorrow.',
    concepts: ['g.subjunctive-intro'],
    level: 'B1',
    topics: ['feelings'],
    blanks: ['estés'],
  },
  {
    id: 's.j71',
    es: 'Espero que vayas al médico esta semana.',
    en: 'I hope you go to the doctor this week.',
    concepts: ['g.subjunctive-intro'],
    level: 'B1',
    topics: ['health'],
    blanks: ['vayas'],
  },
  {
    id: 's.j72',
    es: 'Necesito que sepas la verdad antes de decidir.',
    en: 'I need you to know the truth before you decide.',
    concepts: ['g.subjunctive-intro'],
    level: 'B1',
    topics: ['social'],
    blanks: ['sepas'],
  },
  {
    id: 's.j73',
    es: 'Quiero que puedas descansar el fin de semana.',
    en: 'I want you to be able to rest at the weekend.',
    concepts: ['g.subjunctive-intro'],
    level: 'B1',
    topics: ['feelings'],
    blanks: ['puedas'],
  },
  {
    id: 's.j74',
    es: 'Espero que quieras venir a la boda.',
    en: 'I hope you want to come to the wedding.',
    concepts: ['g.subjunctive-intro'],
    level: 'B1',
    topics: ['family'],
    blanks: ['quieras'],
  },
  {
    id: 's.j75',
    es: 'Te pido que me des una respuesta hoy.',
    en: 'I am asking you to give me an answer today.',
    concepts: ['g.subjunctive-intro'],
    level: 'B1',
    topics: ['work'],
    blanks: ['des'],
  },
  {
    id: 's.j76',
    es: 'Quiero que vivas donde te apetezca.',
    en: 'I want you to live wherever you like.',
    concepts: ['g.subjunctive-intro'],
    level: 'B1',
    topics: ['home'],
    blanks: ['vivas'],
  },

  // === Subjunctive: third person and plural ================================
  {
    id: 's.j77',
    es: 'No creo que sea buena idea discutirlo ahora.',
    en: "I don't think it's a good idea to discuss it now.",
    concepts: ['g.subjunctive-opinion'],
    level: 'B2',
    topics: ['opinions'],
    blanks: ['sea'],
  },
  {
    id: 's.j78',
    es: 'Dudo que esté en casa a estas horas.',
    en: "I doubt he's at home at this hour.",
    concepts: ['g.subjunctive-opinion'],
    level: 'B2',
    topics: ['people'],
    blanks: ['esté'],
  },
  {
    id: 's.j79',
    es: 'Me extraña que no tenga noticias suyas todavía.',
    en: "It surprises me that she hasn't heard from him yet.",
    concepts: ['g.subjunctive-opinion'],
    level: 'B2',
    topics: ['social'],
    blanks: ['tenga'],
  },
  {
    id: 's.j80',
    es: 'No me parece que vaya a llover esta tarde.',
    en: "I don't think it's going to rain this afternoon.",
    concepts: ['g.subjunctive-opinion'],
    level: 'B2',
    topics: ['weather'],
    blanks: ['vaya'],
  },
  {
    id: 's.j81',
    es: 'Es raro que haga tanto frío en mayo.',
    en: "It's odd that it's this cold in May.",
    concepts: ['g.subjunctive-opinion'],
    level: 'B2',
    topics: ['weather'],
    blanks: ['haga'],
  },
  {
    id: 's.j82',
    es: 'No creo que diga nada en la reunión.',
    en: "I don't think he'll say anything in the meeting.",
    concepts: ['g.subjunctive-opinion'],
    level: 'B2',
    topics: ['work'],
    blanks: ['diga'],
  },
  {
    id: 's.j83',
    es: 'Me molesta que hable así de sus compañeros.',
    en: 'It annoys me that he talks about his colleagues like that.',
    concepts: ['g.subjunctive-opinion'],
    level: 'B2',
    topics: ['work'],
    blanks: ['hable'],
  },
  {
    id: 's.j84',
    es: 'Es una pena que no venga con nosotros.',
    en: "It's a shame she isn't coming with us.",
    concepts: ['g.subjunctive-opinion'],
    level: 'B2',
    topics: ['social'],
    blanks: ['venga'],
  },
  {
    id: 's.j85',
    es: 'No creo que salga del hospital esta semana.',
    en: "I don't think he'll leave hospital this week.",
    concepts: ['g.subjunctive-opinion'],
    level: 'B2',
    topics: ['health'],
    blanks: ['salga'],
  },
  {
    id: 's.j86',
    es: 'Es importante que ponga todo por escrito.',
    en: "It's important that he puts everything in writing.",
    concepts: ['g.subjunctive-opinion'],
    level: 'B2',
    topics: ['work'],
    blanks: ['ponga'],
  },
  {
    id: 's.j87',
    es: 'Dudo que sepa lo que ha pasado.',
    en: "I doubt she knows what's happened.",
    concepts: ['g.subjunctive-opinion'],
    level: 'B2',
    topics: ['social'],
    blanks: ['sepa'],
  },
  {
    id: 's.j88',
    es: 'No creo que pueda ayudarnos con esto.',
    en: "I don't think he can help us with this.",
    concepts: ['g.subjunctive-opinion'],
    level: 'B2',
    topics: ['work'],
    blanks: ['pueda'],
  },
  {
    id: 's.j89',
    es: 'Me sorprende que quiera marcharse tan pronto.',
    en: 'It surprises me that she wants to leave so soon.',
    concepts: ['g.subjunctive-opinion'],
    level: 'B2',
    topics: ['feelings'],
    blanks: ['quiera'],
  },
  {
    id: 's.j90',
    es: 'Es lógico que coma menos cuando trabaja tanto.',
    en: "It's understandable that he eats less when he works this much.",
    concepts: ['g.subjunctive-opinion'],
    level: 'B2',
    topics: ['health'],
    blanks: ['coma'],
  },
  {
    id: 's.j91',
    es: 'No creo que viva en el centro todavía.',
    en: "I don't think she still lives in the centre.",
    concepts: ['g.subjunctive-opinion'],
    level: 'B2',
    topics: ['city'],
    blanks: ['viva'],
  },
  {
    id: 's.j92',
    es: 'Me alegra que dé el paso por fin.',
    en: "I'm glad he's finally taking the step.",
    concepts: ['g.subjunctive-opinion'],
    level: 'B2',
    topics: ['feelings'],
    blanks: ['dé'],
    note: 'Dé carries an accent to distinguish it from the preposition de.',
  },
  {
    id: 's.j93',
    es: 'No creo que sean tan caros como dicen.',
    en: "I don't think they're as expensive as people say.",
    concepts: ['g.subjunctive-opinion'],
    level: 'B2',
    topics: ['shopping'],
    blanks: ['sean'],
  },
  {
    id: 's.j94',
    es: 'Dudo que estén listos para el lunes.',
    en: "I doubt they'll be ready by Monday.",
    concepts: ['g.subjunctive-opinion'],
    level: 'B2',
    topics: ['work'],
    blanks: ['estén'],
  },
  {
    id: 's.j95',
    es: 'Es raro que tengan tantas quejas este mes.',
    en: "It's strange that they have so many complaints this month.",
    concepts: ['g.subjunctive-opinion'],
    level: 'B2',
    topics: ['work'],
    blanks: ['tengan'],
  },
  {
    id: 's.j96',
    es: 'No creo que vayan a cambiar de idea.',
    en: "I don't think they're going to change their minds.",
    concepts: ['g.subjunctive-opinion'],
    level: 'B2',
    topics: ['opinions'],
    blanks: ['vayan'],
  },
  {
    id: 's.j97',
    es: 'Me parece bien que hagan huelga si hace falta.',
    en: "I think it's fine for them to strike if necessary.",
    concepts: ['g.subjunctive-opinion'],
    level: 'B2',
    topics: ['work'],
    blanks: ['hagan'],
  },
  {
    id: 's.j98',
    es: 'Es probable que vengan en el tren de las siete.',
    en: "They'll probably come on the seven o'clock train.",
    concepts: ['g.subjunctive-opinion'],
    level: 'B2',
    topics: ['transport'],
    blanks: ['vengan'],
  },
  {
    id: 's.j99',
    es: 'No creo que digan nada a la prensa.',
    en: "I don't think they'll say anything to the press.",
    concepts: ['g.subjunctive-opinion'],
    level: 'B2',
    topics: ['work'],
    blanks: ['digan'],
  },
  {
    id: 's.j100',
    es: 'Dudo que salgan antes de las once.',
    en: "I doubt they'll leave before eleven.",
    concepts: ['g.subjunctive-opinion'],
    level: 'B2',
    topics: ['plans'],
    blanks: ['salgan'],
  },
  {
    id: 's.j101',
    es: 'Es mejor que pongan el aire acondicionado.',
    en: "It's better that they put the air conditioning on.",
    concepts: ['g.subjunctive-opinion'],
    level: 'B2',
    topics: ['weather'],
    blanks: ['pongan'],
  },
  {
    id: 's.j102',
    es: 'No creo que sepan lo difícil que ha sido.',
    en: "I don't think they know how hard it's been.",
    concepts: ['g.subjunctive-opinion'],
    level: 'B2',
    topics: ['feelings'],
    blanks: ['sepan'],
  },
  {
    id: 's.j103',
    es: 'Me extraña que puedan terminarlo hoy.',
    en: 'It surprises me that they can finish it today.',
    concepts: ['g.subjunctive-opinion'],
    level: 'B2',
    topics: ['work'],
    blanks: ['puedan'],
  },
  {
    id: 's.j104',
    es: 'No creo que quieran quedarse hasta el final.',
    en: "I don't think they want to stay until the end.",
    concepts: ['g.subjunctive-opinion'],
    level: 'B2',
    topics: ['social'],
    blanks: ['quieran'],
  },
  {
    id: 's.j105',
    es: 'Es una lástima que coman siempre lo mismo.',
    en: "It's a pity they always eat the same thing.",
    concepts: ['g.subjunctive-opinion'],
    level: 'B2',
    topics: ['food'],
    blanks: ['coman'],
  },
  {
    id: 's.j106',
    es: 'Dudo que vivan del alquiler solamente.',
    en: 'I doubt they live off the rent alone.',
    concepts: ['g.subjunctive-opinion'],
    level: 'B2',
    topics: ['home'],
    blanks: ['vivan'],
  },
  {
    id: 's.j107',
    es: 'Es raro que no den señales de vida.',
    en: "It's odd that they're not showing any sign of life.",
    concepts: ['g.subjunctive-opinion'],
    level: 'B2',
    topics: ['social'],
    blanks: ['den'],
  },

  // === Subjunctive: nosotros and vosotros ==================================
  {
    id: 's.j108',
    es: 'Quiere que hablemos con el casero mañana.',
    en: 'She wants us to speak to the landlord tomorrow.',
    concepts: ['g.subjunctive-intro'],
    level: 'B1',
    topics: ['home'],
    blanks: ['hablemos'],
  },
  {
    id: 's.j109',
    es: 'Nos piden que seamos discretos con el asunto.',
    en: 'They are asking us to be discreet about the matter.',
    concepts: ['g.subjunctive-intro'],
    level: 'B1',
    topics: ['work'],
    blanks: ['seamos'],
  },
  {
    id: 's.j110',
    es: 'Es mejor que vayamos en metro a esa hora.',
    en: "It's better for us to go by metro at that time.",
    concepts: ['g.subjunctive-intro'],
    level: 'B1',
    topics: ['transport'],
    blanks: ['vayamos'],
  },
  {
    id: 's.j111',
    es: 'Quiere que tengamos todo listo el jueves.',
    en: 'He wants us to have everything ready on Thursday.',
    concepts: ['g.subjunctive-intro'],
    level: 'B1',
    topics: ['work'],
    blanks: ['tengamos'],
  },
  {
    id: 's.j112',
    es: 'Nos pide que hagamos un esfuerzo más.',
    en: 'She is asking us to make one more effort.',
    concepts: ['g.subjunctive-intro'],
    level: 'B1',
    topics: ['work'],
    blanks: ['hagamos'],
  },
  {
    id: 's.j113',
    es: 'Prefiere que estemos allí antes de las nueve.',
    en: 'He prefers us to be there before nine.',
    concepts: ['g.subjunctive-intro'],
    level: 'B1',
    topics: ['plans'],
    blanks: ['estemos'],
  },
  {
    id: 's.j114',
    es: 'Espera que vengamos todos a la cena.',
    en: 'She hopes we all come to the dinner.',
    concepts: ['g.subjunctive-intro'],
    level: 'B1',
    topics: ['family'],
    blanks: ['vengamos'],
  },
  {
    id: 's.j115',
    es: 'Quiere que salgamos pronto para evitar el tráfico.',
    en: 'He wants us to leave early to avoid the traffic.',
    concepts: ['g.subjunctive-intro'],
    level: 'B1',
    topics: ['transport'],
    blanks: ['salgamos'],
  },
  {
    id: 's.j116',
    es: 'Es importante que sepamos qué esperan de nosotros.',
    en: "It's important that we know what they expect of us.",
    concepts: ['g.subjunctive-intro'],
    level: 'B1',
    topics: ['work'],
    blanks: ['sepamos'],
  },
  {
    id: 's.j117',
    es: 'Nos pide que le demos una oportunidad más.',
    en: 'He is asking us to give him one more chance.',
    concepts: ['g.subjunctive-intro'],
    level: 'B1',
    topics: ['social'],
    blanks: ['demos'],
  },
  {
    id: 's.j118',
    es: 'Quiere que podamos decidirlo entre todos.',
    en: 'She wants us to be able to decide it together.',
    concepts: ['g.subjunctive-intro'],
    level: 'B1',
    topics: ['opinions'],
    blanks: ['podamos'],
  },
  {
    id: 's.j119',
    es: 'Es raro que comamos tan tarde entre semana.',
    en: "It's unusual for us to eat this late on a weekday.",
    concepts: ['g.subjunctive-intro'],
    level: 'B1',
    topics: ['daily-routine'],
    blanks: ['comamos'],
  },
  {
    id: 's.j120',
    es: 'Prefiere que digamos la verdad desde el principio.',
    en: 'She prefers that we tell the truth from the start.',
    concepts: ['g.subjunctive-intro'],
    level: 'B1',
    topics: ['social'],
    blanks: ['digamos'],
  },
  {
    id: 's.j121',
    es: 'Quiere que pongamos la calefacción más baja.',
    en: 'He wants us to turn the heating down.',
    concepts: ['g.subjunctive-intro'],
    level: 'B1',
    topics: ['home'],
    blanks: ['pongamos'],
  },
  {
    id: 's.j122',
    es: 'Es mejor que vivamos cerca del trabajo.',
    en: "It's better for us to live near work.",
    concepts: ['g.subjunctive-intro'],
    level: 'B1',
    topics: ['home'],
    blanks: ['vivamos'],
  },
  {
    id: 's.j123',
    es: 'Espero que habléis con ellos esta semana.',
    en: 'I hope you talk to them this week.',
    concepts: ['g.subjunctive-intro'],
    level: 'B1',
    topics: ['social'],
    blanks: ['habléis'],
  },
  {
    id: 's.j124',
    es: 'Quiero que seáis sinceros conmigo.',
    en: 'I want you to be honest with me.',
    concepts: ['g.subjunctive-intro'],
    level: 'B1',
    topics: ['feelings'],
    blanks: ['seáis'],
  },
  {
    id: 's.j125',
    es: 'Es importante que tengáis el pasaporte a mano.',
    en: "It's important that you have your passports handy.",
    concepts: ['g.subjunctive-intro'],
    level: 'B1',
    topics: ['travel'],
    blanks: ['tengáis'],
  },
  {
    id: 's.j126',
    es: 'Prefiero que vayáis en taxi de noche.',
    en: 'I prefer you to go by taxi at night.',
    concepts: ['g.subjunctive-intro'],
    level: 'B1',
    topics: ['transport'],
    blanks: ['vayáis'],
  },
  {
    id: 's.j127',
    es: 'Espero que hagáis las paces pronto.',
    en: 'I hope you make up soon.',
    concepts: ['g.subjunctive-intro'],
    level: 'B1',
    topics: ['feelings'],
    blanks: ['hagáis'],
  },
  {
    id: 's.j128',
    es: 'Quiero que estéis a gusto en mi casa.',
    en: 'I want you to feel comfortable in my house.',
    concepts: ['g.subjunctive-intro'],
    level: 'B1',
    topics: ['home'],
    blanks: ['estéis'],
  },
  {
    id: 's.j129',
    es: 'Es mejor que vengáis antes de que cierre.',
    en: "It's better that you come before it closes.",
    concepts: ['g.subjunctive-intro'],
    level: 'B1',
    topics: ['plans'],
    blanks: ['vengáis'],
  },
  {
    id: 's.j130',
    es: 'Espero que sepáis lo mucho que os agradezco esto.',
    en: 'I hope you know how much I appreciate this.',
    concepts: ['g.subjunctive-intro'],
    level: 'B1',
    topics: ['feelings'],
    blanks: ['sepáis'],
  },
  {
    id: 's.j131',
    es: 'Quiero que digáis lo que pensáis de verdad.',
    en: 'I want you to say what you really think.',
    concepts: ['g.subjunctive-intro'],
    level: 'B1',
    topics: ['opinions'],
    blanks: ['digáis'],
  },
  {
    id: 's.j132',
    es: 'Prefiero que salgáis por la puerta principal.',
    en: 'I prefer you to leave by the main door.',
    concepts: ['g.subjunctive-intro'],
    level: 'B1',
    topics: ['directions'],
    blanks: ['salgáis'],
  },
  {
    id: 's.j133',
    es: 'Es importante que pongáis vuestro nombre en la lista.',
    en: "It's important that you put your name on the list.",
    concepts: ['g.subjunctive-intro'],
    level: 'B1',
    topics: ['university'],
    blanks: ['pongáis'],
  },
  {
    id: 's.j134',
    es: 'Espero que podáis quedaros hasta el domingo.',
    en: 'I hope you can stay until Sunday.',
    concepts: ['g.subjunctive-intro'],
    level: 'B1',
    topics: ['plans'],
    blanks: ['podáis'],
  },
  {
    id: 's.j135',
    es: 'Quiero que comáis algo antes de conducir.',
    en: 'I want you to eat something before driving.',
    concepts: ['g.subjunctive-intro'],
    level: 'B1',
    topics: ['food'],
    blanks: ['comáis'],
  },
  {
    id: 's.j136',
    es: 'Es raro que viváis tan lejos del centro.',
    en: "It's unusual that you live so far from the centre.",
    concepts: ['g.subjunctive-intro'],
    level: 'B1',
    topics: ['city'],
    blanks: ['viváis'],
  },
  {
    id: 's.j137',
    es: 'Espero que queráis repetir el año que viene.',
    en: 'I hope you want to do it again next year.',
    concepts: ['g.subjunctive-intro'],
    level: 'B1',
    topics: ['plans'],
    blanks: ['queráis'],
  },
  {
    id: 's.j138',
    es: 'Quiero que me deis vuestra opinión sincera.',
    en: 'I want you to give me your honest opinion.',
    concepts: ['g.subjunctive-intro'],
    level: 'B1',
    topics: ['opinions'],
    blanks: ['deis'],
  },
  {
    id: 's.j139',
    es: 'Busco a alguien que hable ruso y español.',
    en: 'I am looking for someone who speaks Russian and Spanish.',
    concepts: ['g.subjunctive-relative'],
    level: 'C1',
    topics: ['work'],
    blanks: ['hable'],
  },
  {
    id: 's.j140',
    es: 'No hay nadie aquí que sepa arreglarlo.',
    en: "There's nobody here who knows how to fix it.",
    concepts: ['g.subjunctive-relative'],
    level: 'C1',
    topics: ['work'],
    blanks: ['sepa'],
  },
  {
    id: 's.j141',
    es: 'Necesitamos un piso que tenga ascensor.',
    en: 'We need a flat that has a lift.',
    concepts: ['g.subjunctive-relative'],
    level: 'C1',
    topics: ['home'],
    blanks: ['tenga'],
  },
  {
    id: 's.j142',
    es: 'Quiero un trabajo que me permita viajar y que esté bien pagado.',
    en: 'I want a job that lets me travel and that is well paid.',
    concepts: ['g.subjunctive-relative'],
    level: 'C1',
    topics: ['work'],
    blanks: ['esté'],
  },
  {
    id: 's.j143',
    es: 'No creo que hablen inglés en esa oficina.',
    en: "I don't think they speak English in that office.",
    concepts: ['g.subjunctive-opinion'],
    level: 'B2',
    topics: ['work'],
    blanks: ['hablen'],
  },
  {
    id: 's.j144',
    es: 'Espero que venga pronto, que llevamos una hora esperando.',
    en: "I hope he comes soon, we've been waiting an hour.",
    // v.venir corroborates against the discourse marker "venga".
    concepts: ['g.subjunctive-intro', 'v.venir'],
    level: 'B1',
    topics: ['social'],
    blanks: ['venga'],
  },
  {
    id: 's.j145',
    es: 'Es normal que queramos un poco de tranquilidad.',
    en: "It's normal that we want a bit of peace and quiet.",
    concepts: ['g.subjunctive-intro'],
    level: 'B1',
    topics: ['feelings'],
    blanks: ['queramos'],
  },
];
