import type { ConversationScene } from '@/content/types';

/**
 * Scripted scenes. Each of your turns can be answered by picking a reply
 * (guided) or typing freely — the session decides which, based on how strong
 * the underlying concepts are. `options` always include at least one reply that
 * is grammatical but unnatural, because knowing the difference is the point.
 */
export const conversations: ConversationScene[] = [
  {
    id: 'conv.malentendido',
    title: 'No me he explicado bien',
    icon: 'chatbox-ellipses-outline',
    setting:
      'Reunión de equipo. Has propuesto algo, te han entendido justo al revés, y la conversación va camino de agriarse.',
    level: 'C2',
    topics: ['work', 'opinions'],
    partner: { name: 'Rocío' },
    turns: [
      {
        speaker: 'partner',
        es: 'O sea, que lo que propones es retrasarlo todo otro mes. Me parece un despropósito.',
        en: 'So what you’re proposing is delaying everything another month. That strikes me as absurd.',
      },
      {
        speaker: 'you',
        instruction: 'No la contradigas de frente: asume tú el malentendido y reformula.',
        accepted: [
          'creo que no me he explicado bien, no es eso lo que propongo',
          'no es eso, ni mucho menos, me explico',
          'creo que no me he explicado bien: a lo que me refiero es a otra cosa',
          'déjame que lo diga de otra manera, no hablo de retrasarlo todo',
        ],
        hints: ['creo que no me he explicado bien', 'a lo que me refiero es a…', 'no es eso, ni mucho menos'],
        concepts: ['p.no-me-he-explicado', 'p.a-lo-que-me-refiero', 'p.no-es-eso'],
      },
      {
        speaker: 'partner',
        es: 'Pues explícate, porque yo he entendido eso.',
        en: 'Go on then, because that’s what I understood.',
      },
      {
        speaker: 'you',
        instruction: 'Corrige la caracterización sin negarla del todo. Usa "no tanto… como…".',
        accepted: [
          'no tanto retrasarlo como reordenar las prioridades',
          'no es tanto un retraso como un cambio de orden',
          'no tanto un mes más como repartir el trabajo de otra forma',
          'más que retrasarlo, se trata de reordenarlo',
        ],
        hints: ['no tanto… como…', 'más que… se trata de…'],
        concepts: ['p.no-tanto-como', 'p.mas-bien'],
      },
      {
        speaker: 'partner',
        es: 'Ya, pero eso en la práctica es lo mismo. El cliente lo va a ver igual.',
        en: 'Right, but in practice that’s the same thing. The client will see it the same way.',
      },
      {
        speaker: 'you',
        instruction: 'Concede el punto y añade una salvedad que lo matice.',
        accepted: [
          'tienes razón, con la salvedad de que el cliente ya sabe que hay trabas',
          'estoy de acuerdo, con la salvedad de que los plazos nunca fueron realistas',
          'en eso llevas razón, ahora bien, el riesgo de no hacerlo es mayor',
          'cierto, aunque cabe señalar que asumiríamos menos riesgo',
        ],
        hints: ['con la salvedad de que…', 'ahora bien…', 'cabe señalar que…'],
        concepts: ['v.salvedad', 'p.ahora-bien', 'p.cabe-senalar', 'p.asumir-un-riesgo'],
      },
      {
        speaker: 'partner',
        es: 'Vale. Dicho así suena distinto. ¿Y cómo se lo contamos a ellos?',
        en: 'Fine. Put like that it sounds different. And how do we tell them?',
      },
      {
        speaker: 'you',
        instruction: 'Reformula el mismo mensaje en registro formal, como se lo dirías al cliente.',
        accepted: [
          'les escribimos diciendo que hemos reordenado el calendario para reducir riesgos',
          'lamentamos comunicarles que el calendario se ha reajustado',
          'les informamos de que se ha reajustado la planificación del proyecto',
          'se les comunica que hemos revisado los plazos de entrega',
        ],
        hints: ['les informamos de que…', 'se ha reajustado…', 'lamentamos comunicarles'],
        concepts: ['g.audience', 'g.reformulation', 'g.se-impersonal'],
      },
      {
        speaker: 'partner',
        es: 'Eso ya sí. Redáctalo tú, que tienes más mano izquierda que yo.',
        en: 'That works. You draft it — you’re more tactful than I am.',
      },
    ],
  },
  {
    id: 'conv.queja',
    title: 'Una queja formal',
    icon: 'briefcase-outline',
    setting:
      'Atención al cliente de una compañía de internet. Llevas tres semanas sin servicio y ya has llamado dos veces.',
    level: 'C1',
    topics: ['work', 'opinions'],
    partner: { name: 'Atención al cliente' },
    turns: [
      {
        speaker: 'partner',
        es: 'Buenos días, le atiende Marta. ¿En qué puedo ayudarle?',
        en: 'Good morning, Marta speaking. How can I help you?',
      },
      {
        speaker: 'you',
        instruction: 'Expón el problema en registro formal, sin acusar a nadie directamente.',
        accepted: [
          'buenos días, llevo tres semanas sin servicio y ya he llamado dos veces',
          'buenos días, se ha producido un problema con mi conexión desde hace tres semanas',
          'buenos días, querría reclamar: llevo tres semanas sin internet',
          'llevo tres semanas sin conexión y no se ha resuelto nada',
        ],
        hints: ['llevo tres semanas sin…', 'se ha producido…', 'querría reclamar'],
        concepts: ['g.reformulation', 'g.se-impersonal', 'g.register'],
      },
      {
        speaker: 'partner',
        es: 'Entiendo. Según nuestro sistema, la incidencia figura como resuelta.',
        en: 'I see. According to our system, the issue is logged as resolved.',
      },
      {
        speaker: 'you',
        instruction: 'Contradice el dato sin perder la cortesía. Atenúa con "no es que…" o "más bien".',
        accepted: [
          'no es que dude de su sistema, es que el servicio sigue sin funcionar',
          'más bien diría que el sistema no refleja la realidad',
          'no es que no le crea, pero sigo sin conexión',
          'permítame que matice: figurará como resuelta, pero no lo está',
        ],
        hints: ['no es que…, es que…', 'más bien', 'permítame que matice'],
        concepts: ['p.no-es-que', 'p.mas-bien', 'v.matizar', 'g.register'],
      },
      {
        speaker: 'partner',
        es: 'Puedo abrir una incidencia nueva, aunque el plazo sería de otras 48 horas.',
        en: 'I can open a new ticket, although the window would be another 48 hours.',
      },
      {
        speaker: 'you',
        instruction: 'Acepta a condición de algo. Usa "siempre y cuando".',
        accepted: [
          'de acuerdo, siempre y cuando esta vez se resuelva de verdad',
          'acepto siempre y cuando me confirmen por escrito',
          'vale, siempre y cuando no me cobren este mes',
          'de acuerdo, siempre y cuando me den un número de referencia',
        ],
        hints: ['siempre y cuando…', 'a condición de que…'],
        concepts: ['p.siempre-y-cuando', 'g.si-hypothetical'],
      },
      {
        speaker: 'partner',
        es: 'Por supuesto. Le envío la referencia por correo ahora mismo.',
        en: 'Of course. I’ll send you the reference by email right away.',
      },
      {
        speaker: 'you',
        instruction: 'Cierra la llamada dejando constancia de tu descontento, pero educadamente.',
        accepted: [
          'se lo agradezco, aunque espero que esta vez sea la última',
          'gracias, dicho esto, espero no tener que volver a llamar',
          'le agradezco la gestión, si bien la espera ha sido excesiva',
          'gracias, aunque tres semanas me parecen demasiadas',
        ],
        hints: ['dicho esto…', 'si bien…', 'aunque + subjuntivo'],
        concepts: ['p.dicho-esto', 'p.si-bien', 'g.aunque-nuance', 'g.register'],
      },
      {
        speaker: 'partner',
        es: 'Lo entiendo perfectamente. Disculpe las molestias.',
        en: 'I completely understand. Apologies for the inconvenience.',
      },
    ],
  },
  {
    id: 'conv.debate',
    title: '¿Pueblo o ciudad?',
    icon: 'chatbubbles-outline',
    setting:
      'Sobremesa en casa de unos amigos. Nadie se está enfadando, pero nadie va a ceder tampoco.',
    level: 'B2',
    topics: ['opinions', 'city'],
    partner: { name: 'Álvaro' },
    turns: [
      {
        speaker: 'partner',
        es: 'Yo lo tengo clarísimo: en cuanto pueda, me vuelvo al pueblo. La ciudad es insoportable.',
        en: "I'm absolutely clear about it: as soon as I can, I'm going back to the village. The city is unbearable.",
      },
      {
        speaker: 'you',
        instruction: 'Discrepa, pero concede algo primero. Usa "puede ser, pero…".',
        accepted: [
          'puede ser, pero en la ciudad hay más trabajo',
          'puede ser, pero yo no lo veo así',
          'estoy de acuerdo en parte, pero hay más oportunidades',
          'puede ser, pero no creo que sea tan fácil',
          'ya, pero en el pueblo no hay trabajo',
        ],
        hints: ['puede ser, pero…', 'no creo que…', 'estoy de acuerdo en parte'],
        concepts: ['p.puede-ser-pero', 'p.no-estoy-de-acuerdo', 'g.subjunctive-opinion'],
      },
      {
        speaker: 'partner',
        es: 'Ya, el trabajo. Pero ¿de qué te sirve el sueldo si se te va entero en el alquiler?',
        en: "Right, work. But what good is the salary if it all goes on rent?",
      },
      {
        speaker: 'you',
        instruction: 'Reconoce que tiene parte de razón y añade un matiz con "por un lado… por otro…".',
        accepted: [
          'tienes razón, por un lado el alquiler es carísimo, por otro hay más oportunidades',
          'por un lado sí, pero por otro lado en el pueblo tampoco es tan barato',
          'en eso tienes razón, pero hay que tener en cuenta el transporte',
          'por un lado es verdad, por otro no todo es el dinero',
        ],
        hints: ['por un lado… por otro…', 'hay que tener en cuenta que…', 'tienes razón'],
        concepts: ['p.por-un-lado', 'p.hay-que-tener-en-cuenta', 'p.tener-razon'],
      },
      {
        speaker: 'partner',
        es: 'Hombre, no me digas que prefieres pagar mil euros por cuarenta metros cuadrados.',
        en: "Come on, don't tell me you'd rather pay a thousand euros for forty square metres.",
      },
      {
        speaker: 'you',
        instruction: 'Especula sobre cómo sería tu vida en el pueblo. Usa "si + imperfecto de subjuntivo".',
        accepted: [
          'si viviera en el pueblo, me aburriría',
          'si me fuera al pueblo, no encontraría trabajo',
          'si tuviera que vivir allí, echaría de menos la ciudad',
          'si viviera en un pueblo, tendría que coger el coche para todo',
        ],
        hints: ['si viviera…', 'si tuviera…', 'me aburriría', 'echaría de menos'],
        concepts: ['g.si-hypothetical', 'g.conditional'],
      },
      {
        speaker: 'partner',
        es: 'Eso es un tópico. En mi pueblo hay más vida que en tu barrio, te lo digo yo.',
        en: "That's a cliché. There's more going on in my village than in your neighbourhood, I'm telling you.",
      },
      {
        speaker: 'you',
        instruction: 'Cierra el tema sin ceder del todo. Resume tu postura en una frase.',
        accepted: [
          'a fin de cuentas, cada uno con lo suyo',
          'en resumen, depende de lo que busques',
          'aun así, yo me quedo en la ciudad',
          'a fin de cuentas, no hay una respuesta única',
          'bueno, en resumen, no nos vamos a poner de acuerdo',
        ],
        hints: ['a fin de cuentas', 'en resumen', 'aun así', 'depende de'],
        concepts: ['p.a-fin-de-cuentas', 'p.en-resumen', 'p.aun-asi'],
      },
      {
        speaker: 'partner',
        es: 'En eso sí estamos de acuerdo. Anda, pásame el vino.',
        en: "On that we do agree. Go on, pass me the wine.",
      },
    ],
  },
  {
    id: 'conv.cafe-a1',
    title: 'Your first coffee',
    icon: 'cafe-outline',
    setting: 'A quiet neighbourhood bar, mid-morning. The barman is in no hurry.',
    level: 'A1',
    topics: ['cafe', 'greetings', 'numbers'],
    partner: { name: 'Camarero' },
    turns: [
      { speaker: 'partner', es: 'Buenos días. ¿Qué quiere?', en: 'Good morning. What would you like?' },
      {
        speaker: 'you',
        instruction: 'Greet him and ask for a coffee with milk.',
        accepted: [
          'buenos días, un café con leche, por favor',
          'buenos días, quiero un café con leche',
          'un café con leche, por favor',
          'hola, un café con leche por favor',
          'quiero un café con leche',
        ],
        hints: ['buenos días', 'un café con leche', 'por favor'],
        concepts: ['p.buenos-dias', 'p.cafe-con-leche', 'p.quiero', 'p.por-favor'],
        options: [
          {
            es: 'Buenos días. Un café con leche, por favor.',
            en: 'Good morning. A coffee with milk, please.',
            natural: true,
          },
          {
            es: 'Buenos días. Quiero un café con leche.',
            en: 'Good morning. I want a coffee with milk.',
            natural: true,
            note: 'Direct, but completely normal in a Spanish bar.',
          },
          {
            es: 'Buenos días. Yo tengo un café con leche.',
            en: 'Good morning. I have a coffee with milk.',
            natural: false,
            note: 'tener is for what you already own. To ask for something you need querer.',
          },
        ],
      },
      {
        speaker: 'partner',
        es: '¿Y algo de comer? Hay tortilla.',
        en: 'And something to eat? There’s tortilla.',
      },
      {
        speaker: 'you',
        instruction: 'Say no thank you — just the coffee.',
        accepted: [
          'no, gracias',
          'no, gracias, solo el café',
          'no gracias, solo un café',
          'no, solo el café, gracias',
        ],
        hints: ['no, gracias', 'solo'],
        concepts: ['v.no', 'v.gracias', 'v.cafe'],
        options: [
          { es: 'No, gracias. Solo el café.', en: 'No, thanks. Just the coffee.', natural: true },
          {
            es: 'No, gracias.',
            en: 'No, thank you.',
            natural: true,
          },
          {
            es: 'No me gusta la tortilla de nada.',
            en: 'I don’t like tortilla of nothing.',
            natural: false,
            note: 'de nada means "you’re welcome" — it cannot be tacked onto a sentence like this.',
          },
        ],
      },
      { speaker: 'partner', es: 'Muy bien. Son dos euros con veinte.', en: 'Right. That’s two euros twenty.' },
      {
        speaker: 'you',
        instruction: 'Ask whether you can pay by card.',
        accepted: [
          '¿puedo pagar con tarjeta?',
          'con tarjeta',
          '¿con tarjeta?',
          '¿puedo pagar con tarjeta, por favor?',
          '¿se puede pagar con tarjeta?',
        ],
        hints: ['pagar', 'con tarjeta'],
        concepts: ['v.pagar', 'v.con'],
        options: [
          { es: '¿Puedo pagar con tarjeta?', en: 'Can I pay by card?', natural: true },
          {
            es: '¿Con tarjeta?',
            en: 'By card?',
            natural: true,
            note: 'Two words is plenty — Spaniards shorten this constantly.',
          },
          {
            es: '¿Pago yo con la tarjeta de mí?',
            en: 'Do I pay with the card of me?',
            natural: false,
            note: 'de mí is not how possession works — it would be mi tarjeta.',
          },
        ],
      },
      {
        speaker: 'partner',
        es: 'Claro que sí. Aquí tienes. ¡Hasta luego!',
        en: 'Of course. Here you go. See you!',
      },
      {
        speaker: 'you',
        instruction: 'Say thank you and goodbye.',
        accepted: ['gracias, hasta luego', 'muchas gracias, hasta luego', 'gracias, adiós', 'hasta luego, gracias'],
        hints: ['gracias', 'hasta luego'],
        concepts: ['v.gracias', 'p.hasta-luego'],
        options: [
          { es: 'Gracias, hasta luego.', en: 'Thanks, see you later.', natural: true },
          {
            es: 'Muchas gracias, adiós.',
            en: 'Thank you very much, goodbye.',
            natural: true,
            note: 'adiós is fine, though hasta luego is what you will hear far more in Spain.',
          },
          {
            es: 'Gracias, buenas noches.',
            en: 'Thanks, good night.',
            natural: false,
            note: 'It is mid-morning — buenas noches is for after dark.',
          },
        ],
      },
    ],
  },
  {
    id: 'conv.cafe',
    title: 'Ordering in a Madrid café',
    icon: 'cafe-outline',
    setting: 'A busy neighbourhood bar at 9am. The barman is friendly and fast.',
    level: 'A2',
    topics: ['cafe', 'food'],
    partner: { name: 'Camarero' },
    turns: [
      { speaker: 'partner', es: '¡Buenas! Dime, ¿qué te pongo?', en: 'Morning! Go on, what can I get you?' },
      {
        speaker: 'you',
        instruction: 'Order a coffee with milk, politely.',
        accepted: [
          'un café con leche, por favor',
          'me pones un café con leche',
          '¿me pones un café con leche, por favor?',
          'quería un café con leche',
          'un café con leche',
        ],
        hints: ['un café con leche', 'por favor', 'me pones'],
        concepts: ['p.cafe-con-leche', 'p.me-pones', 'p.por-favor'],
        options: [
          { es: 'Un café con leche, por favor.', en: 'A coffee with milk, please.', natural: true },
          {
            es: '¿Me pones un café con leche?',
            en: 'Can I get a coffee with milk?',
            natural: true,
            note: 'The most natural bar order in Spain.',
          },
          {
            es: 'Yo deseo un café con leche.',
            en: 'I desire a coffee with milk.',
            natural: false,
            note: 'Grammatically fine, but desear sounds like a formal letter. Nobody orders like this.',
          },
        ],
      },
      { speaker: 'partner', es: '¿Y algo de comer? Tenemos tostadas.', en: 'And something to eat? We’ve got toast.' },
      {
        speaker: 'you',
        instruction: 'Say yes and ask for a tostada with tomato.',
        accepted: [
          'sí, una tostada con tomate',
          'sí, una tostada con tomate por favor',
          'vale, una tostada con tomate',
          'sí, con tomate',
        ],
        hints: ['sí', 'una tostada', 'con tomate'],
        concepts: ['v.si', 'v.pan'],
      },
      { speaker: 'partner', es: 'Marchando. ¿Para tomar aquí o para llevar?', en: 'Coming up. To have here or takeaway?' },
      {
        speaker: 'you',
        instruction: 'Say you’ll have it here.',
        accepted: ['aquí', 'para tomar aquí', 'aquí, gracias', 'para aquí'],
        hints: ['aquí'],
        concepts: ['p.para-tomar-aqui'],
        note: 'A bare "aquí" is completely normal — you do not need a full sentence.',
      },
      { speaker: 'partner', es: 'Son tres cuarenta.', en: 'That’s three forty.' },
      {
        speaker: 'you',
        instruction: 'Ask whether you can pay by card.',
        accepted: [
          '¿puedo pagar con tarjeta?',
          'puedo pagar con tarjeta',
          '¿con tarjeta?',
          '¿se puede pagar con tarjeta?',
        ],
        hints: ['puedo', 'pagar', 'con tarjeta'],
        concepts: ['v.poder', 'v.pagar', 'p.con-tarjeta'],
      },
      { speaker: 'partner', es: 'Claro, sin problema. ¡Que aproveche!', en: 'Of course, no problem. Enjoy!' },
    ],
  },

  {
    id: 'conv.directions',
    title: 'Asking for directions',
    icon: 'navigate-outline',
    setting: 'You are lost somewhere near Plaza Mayor and stop a passer-by.',
    level: 'A2',
    topics: ['directions', 'city'],
    partner: { name: 'Señora' },
    turns: [
      {
        speaker: 'you',
        instruction: 'Stop her politely and ask where the metro is.',
        accepted: [
          'perdona, ¿dónde está el metro?',
          'perdone, ¿dónde está el metro?',
          'perdona, ¿sabes dónde está el metro?',
          '¿dónde está el metro?',
          'perdone, ¿sabe dónde está el metro?',
        ],
        hints: ['perdona', 'dónde está', 'el metro'],
        concepts: ['v.perdona', 'p.donde-esta', 'v.metro'],
        options: [
          {
            es: 'Perdona, ¿sabes dónde está el metro?',
            en: 'Excuse me, do you know where the metro is?',
            natural: true,
            note: 'Softer than a bare question — this is what people actually say.',
          },
          { es: 'Perdona, ¿dónde está el metro?', en: 'Excuse me, where’s the metro?', natural: true },
          {
            es: '¿Dónde es el metro?',
            en: 'Where is the metro?',
            natural: false,
            note: 'Location always takes estar, never ser.',
          },
        ],
      },
      {
        speaker: 'partner',
        es: 'Sí, mira: sigue todo recto y gira a la derecha en la segunda calle.',
        en: 'Yes, look: carry straight on and turn right at the second street.',
      },
      {
        speaker: 'you',
        instruction: 'Check whether it’s far.',
        accepted: ['¿está lejos?', 'está lejos', '¿está muy lejos?', '¿queda lejos?'],
        hints: ['está', 'lejos'],
        concepts: ['v.lejos', 'v.estar'],
      },
      {
        speaker: 'partner',
        es: 'Qué va, cinco minutos andando. Está al lado de una farmacia.',
        en: 'Not at all, five minutes on foot. It’s next to a pharmacy.',
        note: '"Qué va" is an emphatic "not at all" — very Spanish.',
      },
      {
        speaker: 'you',
        instruction: 'Thank her warmly and say goodbye.',
        accepted: [
          'muchas gracias, hasta luego',
          'gracias, hasta luego',
          'muchas gracias, muy amable',
          'vale, muchas gracias',
          'gracias, adiós',
        ],
        hints: ['muchas gracias', 'hasta luego'],
        concepts: ['v.gracias', 'p.hasta-luego'],
      },
      { speaker: 'partner', es: 'De nada, ¡hasta luego!', en: 'You’re welcome, see you!' },
    ],
  },

  {
    id: 'conv.plans',
    title: 'Making plans with a friend',
    icon: 'chatbox-ellipses-outline',
    setting: 'A WhatsApp conversation with Marta on a Thursday evening.',
    level: 'B1',
    topics: ['plans', 'social'],
    partner: { name: 'Marta' },
    turns: [
      { speaker: 'partner', es: '¡Ey! ¿Qué haces mañana?', en: 'Hey! What are you doing tomorrow?' },
      {
        speaker: 'you',
        instruction: 'Say you’re studying in the morning but you’re free in the afternoon.',
        accepted: [
          'voy a estudiar por la mañana, pero por la tarde estoy libre',
          'por la mañana estudio, pero por la tarde estoy libre',
          'voy a estudiar por la mañana pero estoy libre por la tarde',
          'estudio por la mañana, pero la tarde la tengo libre',
        ],
        hints: ['voy a estudiar', 'por la mañana', 'pero', 'por la tarde', 'libre'],
        concepts: ['g.ir-a-infinitive', 'v.estudiar', 'v.manana', 'v.tarde', 'g.por-para'],
      },
      {
        speaker: 'partner',
        es: 'Vale, pues podemos quedar y tomar algo. ¿Te apetece?',
        en: 'Okay, we could meet up and grab a drink then. Do you fancy it?',
      },
      {
        speaker: 'you',
        instruction: 'Say yes, you fancy it, and ask what time.',
        accepted: [
          'sí, me apetece. ¿a qué hora quedamos?',
          'vale, me apetece. ¿a qué hora?',
          'sí, me apetece mucho. ¿a qué hora quedamos?',
          'claro, ¿a qué hora quedamos?',
        ],
        hints: ['me apetece', 'a qué hora', 'quedamos'],
        concepts: ['p.me-apetece', 'v.quedar', 'v.hora'],
        options: [
          {
            es: 'Sí, me apetece. ¿A qué hora quedamos?',
            en: 'Yes, I fancy it. What time shall we meet?',
            natural: true,
          },
          { es: 'Claro, ¿a qué hora quedamos?', en: 'Sure, what time shall we meet?', natural: true },
          {
            es: 'Sí, yo apetezco. ¿A qué hora?',
            en: 'Yes, I fancy. What time?',
            natural: false,
            note: 'Apetecer works like gustar — it has to be me apetece, not yo apetezco.',
          },
        ],
      },
      {
        speaker: 'partner',
        es: 'Sobre las ocho, ¿te va bien? Quedamos delante del metro.',
        en: 'Around eight, does that work? Let’s meet in front of the metro.',
      },
      {
        speaker: 'you',
        instruction: 'Agree, and say you might be five minutes late.',
        accepted: [
          'vale, pero igual llego cinco minutos tarde',
          'vale, quizá llegue cinco minutos tarde',
          'perfecto, aunque puede que llegue cinco minutos tarde',
          'vale, a lo mejor llego cinco minutos tarde',
        ],
        hints: ['vale', 'igual', 'llego', 'cinco minutos tarde'],
        concepts: ['v.vale', 'v.cinco'],
        note: 'Igual + present is a very Spanish way to say "maybe" — igual llego tarde.',
      },
      { speaker: 'partner', es: 'Tranqui, te espero. ¡Hasta mañana!', en: 'No worries, I’ll wait. See you tomorrow!' },
    ],
  },

  {
    id: 'conv.piso',
    title: 'Viewing a flat',
    icon: 'home-outline',
    setting: 'You are seeing a room in a shared flat in Lavapiés.',
    level: 'B1',
    topics: ['home', 'city'],
    partner: { name: 'Álvaro' },
    turns: [
      {
        speaker: 'partner',
        es: 'Hola, pasa. Esta es la habitación. ¿Qué te parece?',
        en: 'Hi, come in. This is the room. What do you think?',
      },
      {
        speaker: 'you',
        instruction: 'Say it’s small but you like it.',
        accepted: [
          'es pequeña, pero me gusta',
          'es pequeña pero me gusta mucho',
          'me gusta, aunque es pequeña',
          'es un poco pequeña, pero me gusta',
        ],
        hints: ['es pequeña', 'pero', 'me gusta'],
        concepts: ['v.pequeno', 'v.pero', 'p.me-gusta', 'g.adjective-agreement'],
        note: 'La habitación is feminine, so pequeña.',
      },
      {
        speaker: 'partner',
        es: 'Somos tres en el piso. ¿Trabajas o estudias?',
        en: 'There are three of us in the flat. Do you work or study?',
      },
      {
        speaker: 'you',
        instruction: 'Say you study at university and work in the afternoons.',
        accepted: [
          'estudio en la universidad y trabajo por las tardes',
          'estudio en la universidad y trabajo por la tarde',
          'estudio y trabajo por las tardes',
        ],
        hints: ['estudio', 'la universidad', 'trabajo', 'por las tardes'],
        concepts: ['v.estudiar', 'v.universidad', 'v.trabajar', 'g.por-para'],
      },
      { speaker: 'partner', es: '¿Y cuánto tiempo llevas en Madrid?', en: 'And how long have you been in Madrid?' },
      {
        speaker: 'you',
        instruction: 'Say you’ve been living here for two years.',
        accepted: [
          'llevo dos años aquí',
          'llevo dos años en madrid',
          'vivo aquí desde hace dos años',
          'llevo dos años viviendo aquí',
        ],
        hints: ['llevo', 'dos años', 'aquí'],
        concepts: ['v.anos', 'v.dos', 'v.vivir'],
        note: 'Llevar + time is the idiomatic way to express duration: llevo dos años aquí.',
      },
      {
        speaker: 'partner',
        es: 'Guay. Pues si te interesa, dímelo esta semana, ¿vale?',
        en: 'Cool. Well if you’re interested, let me know this week, okay?',
      },
    ],
  },

  // --- A1: the first exchanges that actually happen ------------------------
  {
    id: 'conv.presentarse',
    title: 'Meeting someone at a language exchange',
    icon: 'person-outline',
    setting: 'A busy bar hosting an intercambio. Someone sits down next to you.',
    level: 'A1',
    topics: ['introductions', 'greetings', 'people'],
    partner: { name: 'Lucía' },
    turns: [
      { speaker: 'partner', es: '¡Hola! ¿Qué tal? Yo soy Lucía.', en: 'Hi! How are you? I’m Lucía.' },
      {
        speaker: 'you',
        instruction: 'Say hello, say your name, and say you are pleased to meet her.',
        accepted: [
          'hola, me llamo mate, encantado',
          'hola, soy mate, encantado',
          'hola, me llamo mate. encantado',
          'hola, encantado, me llamo mate',
          'me llamo mate, encantado',
        ],
        hints: ['hola', 'me llamo', 'encantado'],
        concepts: ['p.me-llamo', 'p.encantado', 'v.hola'],
        options: [
          { es: 'Hola, me llamo Mate. Encantado.', en: 'Hi, my name is Mate. Nice to meet you.', natural: true },
          {
            es: 'Hola, soy Mate. Encantado.',
            en: 'Hi, I’m Mate. Nice to meet you.',
            natural: true,
            note: 'soy + name is just as normal as me llamo, and slightly quicker.',
          },
          {
            es: 'Hola, mi nombre está Mate.',
            en: 'Hi, my name is (located) Mate.',
            natural: false,
            note: 'estar is for states and places. Identity takes ser — or simply me llamo.',
          },
        ],
      },
      { speaker: 'partner', es: '¿Y de dónde eres? No eres de aquí, ¿no?', en: 'And where are you from? You’re not from here, are you?' },
      {
        speaker: 'you',
        instruction: 'Say you are Slovenian, and that you live in Madrid now.',
        accepted: [
          'soy esloveno, pero vivo en madrid',
          'soy esloveno y vivo en madrid',
          'soy esloveno, ahora vivo en madrid',
          'soy de eslovenia, pero vivo en madrid',
          'soy esloveno pero ahora vivo en madrid',
        ],
        hints: ['soy esloveno', 'vivo en Madrid'],
        concepts: ['v.esloveno', 'p.soy-de', 'v.vivir'],
        options: [
          { es: 'Soy esloveno, pero vivo en Madrid.', en: 'I’m Slovenian, but I live in Madrid.', natural: true },
          {
            es: 'Soy de Eslovenia y ahora vivo aquí.',
            en: 'I’m from Slovenia and now I live here.',
            natural: true,
            note: 'ser de + country works exactly as well as the adjective.',
          },
          {
            es: 'Estoy esloveno y vivo en Madrid.',
            en: 'I am (temporarily) Slovenian and live in Madrid.',
            natural: false,
            note: 'Nationality is not a passing state — it always takes ser.',
          },
        ],
      },
      { speaker: 'partner', es: '¡Qué bien! ¿Y cuántos años llevas aquí?', en: 'Great! And how long have you been here?' },
      {
        speaker: 'you',
        instruction: 'Say two years, and ask her the same question back.',
        accepted: [
          'dos años, ¿y tú?',
          'dos años. ¿y tú?',
          'llevo dos años, ¿y tú?',
          'dos años, ¿tú?',
          'hace dos años, ¿y tú?',
        ],
        hints: ['dos años', '¿y tú?'],
        concepts: ['v.anos', 'p.y-tu', 'v.dos'],
        options: [
          { es: 'Dos años. ¿Y tú?', en: 'Two years. And you?', natural: true },
          {
            es: 'Llevo dos años aquí. ¿Y tú?',
            en: 'I’ve been here two years. And you?',
            natural: true,
            note: 'llevar + time is the standard way to say how long you have been somewhere.',
          },
          {
            es: 'Tengo dos años aquí. ¿Y tú?',
            en: 'I am two years old here. And you?',
            natural: false,
            note: 'tener + años is your age. For duration Spanish uses llevar or hace.',
          },
        ],
      },
      { speaker: 'partner', es: 'Yo soy de Sevilla, pero llevo diez años en Madrid. ¡Bienvenido!', en: 'I’m from Seville, but I’ve been in Madrid ten years. Welcome!' },
    ],
  },
  {
    id: 'conv.hora',
    title: 'What time does it open?',
    icon: 'time-outline',
    setting: 'You stop someone outside a museum that looks shut.',
    level: 'A1',
    topics: ['time', 'numbers', 'city'],
    partner: { name: 'Señora' },
    turns: [
      { speaker: 'partner', es: 'Dime, ¿te ayudo en algo?', en: 'Tell me, can I help you with something?' },
      {
        speaker: 'you',
        instruction: 'Ask politely what time the museum opens.',
        accepted: [
          'perdona, ¿a qué hora abre el museo?',
          '¿a qué hora abre el museo?',
          'perdone, ¿a qué hora abre el museo?',
          'por favor, ¿a qué hora abre el museo?',
          '¿a qué hora abre?',
        ],
        hints: ['perdona', '¿a qué hora', 'abre'],
        concepts: ['v.hora', 'v.perdona', 'p.perdona-donde'],
        options: [
          { es: 'Perdona, ¿a qué hora abre el museo?', en: 'Excuse me, what time does the museum open?', natural: true },
          {
            es: '¿A qué hora abre el museo, por favor?',
            en: 'What time does the museum open, please?',
            natural: true,
          },
          {
            es: '¿Qué hora abre el museo?',
            en: 'What hour opens the museum?',
            natural: false,
            note: '¿Qué hora es? asks the time now. For a scheduled time you need a qué hora.',
          },
        ],
      },
      { speaker: 'partner', es: 'A las diez y media. Ahora son las diez menos cuarto.', en: 'At half past ten. It’s quarter to ten now.' },
      {
        speaker: 'you',
        instruction: 'Say thank you and that you will wait, then ask if there is a café nearby.',
        accepted: [
          'gracias, espero. ¿hay un café cerca?',
          'gracias. ¿hay una cafetería cerca?',
          'muchas gracias. ¿hay un café por aquí cerca?',
          'gracias, espero aquí. ¿hay un café cerca?',
          '¿hay un café cerca? gracias',
        ],
        hints: ['gracias', '¿hay', 'cerca'],
        concepts: ['v.gracias', 'g.hay-estar', 'v.cerca'],
        options: [
          { es: 'Gracias. ¿Hay un café cerca?', en: 'Thanks. Is there a café nearby?', natural: true },
          {
            es: 'Muchas gracias. ¿Hay una cafetería por aquí?',
            en: 'Thank you very much. Is there a café around here?',
            natural: true,
            note: 'por aquí — "around here" — is softer than cerca and very common.',
          },
          {
            es: 'Gracias. ¿Está un café cerca?',
            en: 'Thanks. Is a café nearby?',
            natural: false,
            note: 'Introducing something new needs hay. está is for a specific café you both know.',
          },
        ],
      },
      { speaker: 'partner', es: 'Sí, hay uno en la esquina. Muy bueno, además.', en: 'Yes, there’s one on the corner. A good one, too.' },
      {
        speaker: 'you',
        instruction: 'Thank her and say goodbye.',
        accepted: ['muchas gracias, hasta luego', 'gracias, hasta luego', 'muchas gracias, adiós', 'gracias, adiós'],
        hints: ['muchas gracias', 'hasta luego'],
        concepts: ['v.gracias', 'p.hasta-luego'],
        options: [
          { es: 'Muchas gracias, hasta luego.', en: 'Thank you very much, see you later.', natural: true },
          { es: 'Gracias, adiós.', en: 'Thanks, goodbye.', natural: true },
          {
            es: 'Gracias, buenas noches.',
            en: 'Thanks, good night.',
            natural: false,
            note: 'It is not yet ten in the morning — buenas noches is for after dark.',
          },
        ],
      },
    ],
  },
  {
    id: 'conv.familia',
    title: 'Talking about family',
    icon: 'people-outline',
    setting: 'A colleague is showing you photos on her phone at lunch.',
    level: 'A1',
    topics: ['family', 'people', 'describing'],
    partner: { name: 'Rocío' },
    turns: [
      { speaker: 'partner', es: 'Mira, estos son mis hermanos. ¿Tú tienes hermanos?', en: 'Look, these are my brothers and sisters. Do you have any siblings?' },
      {
        speaker: 'you',
        instruction: 'Say you have one brother and one sister.',
        accepted: [
          'sí, tengo un hermano y una hermana',
          'tengo un hermano y una hermana',
          'sí, un hermano y una hermana',
          'sí, tengo dos: un hermano y una hermana',
        ],
        hints: ['tengo', 'un hermano', 'una hermana'],
        concepts: ['v.tener', 'v.hermano', 'v.familia'],
        options: [
          { es: 'Sí, tengo un hermano y una hermana.', en: 'Yes, I have a brother and a sister.', natural: true },
          { es: 'Tengo un hermano y una hermana.', en: 'I have a brother and a sister.', natural: true },
          {
            es: 'Sí, soy un hermano y una hermana.',
            en: 'Yes, I am a brother and a sister.',
            natural: false,
            note: 'Family is something you have: tengo, not soy.',
          },
        ],
      },
      { speaker: 'partner', es: '¿Y cómo es tu hermana? ¿Se parece a ti?', en: 'And what’s your sister like? Does she look like you?' },
      {
        speaker: 'you',
        instruction: 'Say she is tall, dark-haired, and very nice.',
        accepted: [
          'es alta, morena y muy simpática',
          'ella es alta, morena y muy simpática',
          'es alta y morena, y muy simpática',
          'es alta, morena y simpática',
        ],
        hints: ['es alta', 'morena', 'muy simpática'],
        concepts: ['v.alto', 'v.moreno', 'v.simpatico'],
        options: [
          { es: 'Es alta, morena y muy simpática.', en: 'She’s tall, dark-haired and very nice.', natural: true },
          {
            es: 'Es una chica alta y morena, muy simpática.',
            en: 'She’s a tall, dark-haired girl, very nice.',
            natural: true,
          },
          {
            es: 'Es alto, moreno y muy simpático.',
            en: 'He’s tall, dark and very nice.',
            natural: false,
            note: 'Adjectives agree with the person described — your sister needs the -a endings.',
          },
        ],
      },
      { speaker: 'partner', es: '¡Como la mía! ¿Y viven en Eslovenia todavía?', en: 'Like mine! And do they still live in Slovenia?' },
      {
        speaker: 'you',
        instruction: 'Say yes, your parents and your sister live there, but your brother lives in Madrid.',
        accepted: [
          'sí, mis padres y mi hermana viven allí, pero mi hermano vive en madrid',
          'sí, mis padres y mi hermana sí, pero mi hermano vive en madrid',
          'mis padres y mi hermana viven allí, pero mi hermano vive en madrid',
          'sí, pero mi hermano vive en madrid',
        ],
        hints: ['mis padres', 'viven', 'pero mi hermano'],
        concepts: ['g.possessives', 'v.vivir', 'v.padre'],
        options: [
          {
            es: 'Sí, mis padres y mi hermana viven allí, pero mi hermano vive en Madrid.',
            en: 'Yes, my parents and my sister live there, but my brother lives in Madrid.',
            natural: true,
          },
          {
            es: 'Sí, pero mi hermano vive aquí, en Madrid.',
            en: 'Yes, but my brother lives here, in Madrid.',
            natural: true,
          },
          {
            es: 'Sí, mis padres y mi hermana vive allí.',
            en: 'Yes, my parents and my sister lives there.',
            natural: false,
            note: 'Two people are the subject, so the verb has to be plural: viven.',
          },
        ],
      },
      { speaker: 'partner', es: 'Pues nada, un día nos los presentas. ¡Venga, a comer!', en: 'Well then, one day you’ll introduce us. Come on, let’s eat!' },
    ],
  },
// --- A2: transactions that go slightly wrong -----------------------------
  {
    id: 'conv.ropa',
    title: 'Buying a jacket that nearly fits',
    icon: 'bag-handle-outline',
    setting: 'A clothes shop on a Saturday. The assistant is friendly but busy.',
    level: 'A2',
    topics: ['shopping'],
    partner: { name: 'Dependienta' },
    turns: [
      { speaker: 'partner', es: '¡Hola! ¿Te ayudo o estás mirando?', en: 'Hi! Can I help or are you just looking?' },
      {
        speaker: 'you',
        instruction: 'Say you are looking for a black jacket in size 40.',
        accepted: [
          'busco una chaqueta negra de la talla cuarenta',
          'estoy buscando una chaqueta negra de la talla cuarenta',
          'busco una chaqueta negra, talla cuarenta',
          'quería una chaqueta negra de la talla cuarenta',
        ],
        hints: ['busco', 'una chaqueta negra', 'la talla cuarenta'],
        concepts: ['v.chaqueta', 'v.talla', 'v.negro'],
        options: [
          { es: 'Busco una chaqueta negra de la talla cuarenta.', en: 'I’m looking for a black jacket in size 40.', natural: true },
          {
            es: 'Quería una chaqueta negra, talla cuarenta.',
            en: 'I’d like a black jacket, size 40.',
            natural: true,
            note: 'The imperfect quería is the standard politeness softener in a shop.',
          },
          {
            es: 'Busco para una chaqueta negra de la talla cuarenta.',
            en: 'I look for a black jacket in size 40.',
            natural: false,
            note: 'buscar takes no preposition — busco algo, never busco para algo.',
          },
        ],
      },
      { speaker: 'partner', es: 'Mira, esta es la última que queda. ¿Quieres probártela?', en: 'Look, this is the last one left. Do you want to try it on?' },
      {
        speaker: 'you',
        instruction: 'Say yes and ask where the fitting room is.',
        accepted: [
          'sí, ¿dónde está el probador?',
          'sí, por favor. ¿dónde está el probador?',
          'vale, ¿dónde está el probador?',
          'sí, ¿puedo probármela? ¿dónde está el probador?',
        ],
        hints: ['sí', '¿dónde está', 'el probador'],
        concepts: ['p.puedo-probarme', 'p.donde-esta', 'v.probar'],
        options: [
          { es: 'Sí, ¿dónde está el probador?', en: 'Yes, where’s the fitting room?', natural: true },
          { es: 'Vale, ¿dónde está el probador?', en: 'Okay, where’s the fitting room?', natural: true },
          {
            es: 'Sí, ¿dónde es el probador?',
            en: 'Yes, where is the fitting room?',
            natural: false,
            note: 'Location always takes estar, even for something fixed like a fitting room.',
          },
        ],
      },
      { speaker: 'partner', es: '¿Qué tal te queda?', en: 'How does it fit?' },
      {
        speaker: 'you',
        instruction: 'Say it fits well but it is too expensive for you.',
        accepted: [
          'me queda bien, pero es demasiado cara',
          'me queda muy bien, pero es demasiado cara para mí',
          'me queda bien, pero es muy cara',
          'bien, pero es demasiado cara',
        ],
        hints: ['me queda bien', 'pero', 'demasiado cara'],
        concepts: ['p.me-queda-bien', 'v.caro', 'v.demasiado'],
        options: [
          { es: 'Me queda bien, pero es demasiado cara.', en: 'It fits me well, but it’s too expensive.', natural: true },
          { es: 'Me queda muy bien, pero es demasiado cara para mí.', en: 'It fits really well, but it’s too expensive for me.', natural: true },
          {
            es: 'Me queda bien, pero es muy demasiado cara.',
            en: 'It fits well, but it’s very too expensive.',
            natural: false,
            note: 'demasiado already means "too much". muy demasiado stacks two intensifiers.',
          },
        ],
      },
      { speaker: 'partner', es: 'Te entiendo. La semana que viene hay rebajas, por si acaso.', en: 'I get it. There’s a sale next week, just in case.' },
    ],
  },
  {
    id: 'conv.farmacia',
    title: 'At the pharmacy',
    icon: 'heart-outline',
    setting: 'A neighbourhood pharmacy. You have had a sore throat for three days.',
    level: 'A2',
    topics: ['health'],
    partner: { name: 'Farmacéutico' },
    turns: [
      { speaker: 'partner', es: 'Buenas. Dígame, ¿qué le pasa?', en: 'Hello. Tell me, what’s wrong?' },
      {
        speaker: 'you',
        instruction: 'Say your throat hurts and you think you have a cold.',
        accepted: [
          'me duele la garganta y creo que tengo un resfriado',
          'me duele la garganta, creo que tengo un resfriado',
          'tengo dolor de garganta y creo que estoy resfriado',
          'me duele la garganta y creo que estoy resfriado',
        ],
        hints: ['me duele la garganta', 'creo que', 'un resfriado'],
        concepts: ['p.me-duele', 'v.garganta', 'v.creo-que'],
        options: [
          { es: 'Me duele la garganta y creo que tengo un resfriado.', en: 'My throat hurts and I think I have a cold.', natural: true },
          {
            es: 'Tengo dolor de garganta, creo que estoy resfriado.',
            en: 'I have a sore throat, I think I have a cold.',
            natural: true,
            note: 'tener dolor de… is slightly more clinical than me duele — both are normal here.',
          },
          {
            es: 'Mi garganta duele y tengo un frío.',
            en: 'My throat hurts and I have a cold (temperature).',
            natural: false,
            note: 'Spanish uses the article, not the possessive, for your own body — and un frío is the weather, not an illness.',
          },
        ],
      },
      { speaker: 'partner', es: '¿Tiene fiebre? ¿Ha dormido bien?', en: 'Do you have a temperature? Have you been sleeping well?' },
      {
        speaker: 'you',
        instruction: 'Say no fever, but you have not slept well and your back hurts.',
        accepted: [
          'fiebre no, pero no he dormido bien y me duele la espalda',
          'no tengo fiebre, pero no he dormido bien y me duele la espalda',
          'no, pero no he dormido bien y me duele la espalda',
          'fiebre no, pero me duele la espalda y no he dormido bien',
        ],
        hints: ['fiebre no', 'no he dormido bien', 'me duele la espalda'],
        concepts: ['v.fiebre', 'v.espalda', 'g.present-perfect'],
        options: [
          { es: 'Fiebre no, pero no he dormido bien y me duele la espalda.', en: 'No fever, but I haven’t slept well and my back hurts.', natural: true },
          { es: 'No tengo fiebre, pero no he dormido bien.', en: 'I don’t have a fever, but I haven’t slept well.', natural: true },
          {
            es: 'No soy fiebre, pero no he dormido bien.',
            en: 'I am not fever, but I haven’t slept well.',
            natural: false,
            note: 'Fever is something you have: tener fiebre, never ser or estar.',
          },
        ],
      },
      { speaker: 'partner', es: 'Le doy algo para la garganta. Si en tres días sigue igual, vaya al médico.', en: 'I’ll give you something for your throat. If it’s the same in three days, see a doctor.' },
      {
        speaker: 'you',
        instruction: 'Thank him and ask how much it costs.',
        accepted: [
          'gracias, ¿cuánto cuesta?',
          'muchas gracias. ¿cuánto es?',
          'vale, gracias. ¿cuánto cuesta?',
          'gracias. ¿cuánto le debo?',
        ],
        hints: ['gracias', '¿cuánto cuesta?'],
        concepts: ['p.cuanto-cuesta', 'v.gracias', 'p.cuanto-es'],
        options: [
          { es: 'Gracias. ¿Cuánto cuesta?', en: 'Thanks. How much is it?', natural: true },
          { es: 'Muchas gracias. ¿Cuánto es?', en: 'Thank you. How much is that?', natural: true },
          {
            es: 'Gracias. ¿Cuánto es el precio de esto?',
            en: 'Thanks. What is the price of this?',
            natural: false,
            note: 'Correct but stilted — nobody asks for el precio de esto over a counter.',
          },
        ],
      },
      { speaker: 'partner', es: 'Seis con cuarenta. Que se mejore.', en: 'Six forty. Get well soon.' },
    ],
  },
  {
    id: 'conv.tren',
    title: 'Buying a train ticket',
    icon: 'subway-outline',
    setting: 'A ticket window at Atocha. There is a queue behind you.',
    level: 'A2',
    topics: ['transport', 'travel'],
    partner: { name: 'Taquillero' },
    turns: [
      { speaker: 'partner', es: 'Siguiente, por favor. Dígame.', en: 'Next, please. Go ahead.' },
      {
        speaker: 'you',
        instruction: 'Ask for a return ticket to Valencia for tomorrow morning.',
        accepted: [
          'quería un billete de ida y vuelta a valencia para mañana por la mañana',
          'un billete de ida y vuelta a valencia para mañana por la mañana, por favor',
          'quería un billete a valencia para mañana por la mañana, ida y vuelta',
          'un ida y vuelta a valencia para mañana por la mañana',
        ],
        hints: ['quería un billete', 'ida y vuelta', 'mañana por la mañana'],
        concepts: ['v.billete', 'v.manana', 'v.tren'],
        options: [
          { es: 'Quería un billete de ida y vuelta a Valencia para mañana por la mañana.', en: 'I’d like a return ticket to Valencia for tomorrow morning.', natural: true },
          { es: 'Un ida y vuelta a Valencia para mañana por la mañana, por favor.', en: 'A return to Valencia for tomorrow morning, please.', natural: true },
          {
            es: 'Quería una entrada de ida y vuelta a Valencia.',
            en: 'I’d like an admission ticket, return, to Valencia.',
            natural: false,
            note: 'entrada gets you into a cinema or a museum. Travel takes billete.',
          },
        ],
      },
      { speaker: 'partner', es: 'Hay uno a las siete y otro a las nueve y media. ¿Cuál prefiere?', en: 'There’s one at seven and another at half past nine. Which do you prefer?' },
      {
        speaker: 'you',
        instruction: 'Say you prefer the half nine one because it is too early at seven.',
        accepted: [
          'prefiero el de las nueve y media porque las siete es muy temprano',
          'el de las nueve y media, las siete es demasiado temprano',
          'prefiero el de las nueve y media, a las siete es muy pronto',
          'el de las nueve y media, por favor, las siete es muy temprano',
        ],
        hints: ['prefiero el de…', 'porque', 'muy temprano'],
        concepts: ['v.preferir', 'v.porque', 'v.tarde'],
        options: [
          { es: 'Prefiero el de las nueve y media, porque las siete es muy temprano.', en: 'I prefer the half nine one, because seven is very early.', natural: true },
          { es: 'El de las nueve y media, que a las siete es muy pronto.', en: 'The half nine one — seven’s too early.', natural: true, note: 'That colloquial que introduces the reason without porque.' },
          {
            es: 'Prefiero el nueve y media porque el siete es muy temprano.',
            en: 'I prefer the nine thirty because the seven is very early.',
            natural: false,
            note: 'Referring back to a train needs el de + time — el de las nueve y media.',
          },
        ],
      },
      { speaker: 'partner', es: 'Muy bien. Son cuarenta y dos euros. ¿Con tarjeta o en efectivo?', en: 'Right. That’s forty-two euros. By card or cash?' },
      {
        speaker: 'you',
        instruction: 'Say by card, and ask which platform it leaves from.',
        accepted: [
          'con tarjeta. ¿de qué andén sale?',
          'con tarjeta, gracias. ¿de qué andén sale?',
          'con tarjeta. ¿desde qué andén sale?',
          'tarjeta. ¿de qué andén sale el tren?',
        ],
        hints: ['con tarjeta', '¿de qué andén sale?'],
        concepts: ['p.con-tarjeta', 'v.estacion', 'v.tren'],
        options: [
          { es: 'Con tarjeta. ¿De qué andén sale?', en: 'By card. Which platform does it leave from?', natural: true },
          { es: 'Con tarjeta, gracias. ¿Desde qué andén sale?', en: 'By card, thanks. Which platform does it depart from?', natural: true },
          {
            es: 'Con tarjeta. ¿Qué andén el tren sale?',
            en: 'By card. What platform the train leaves?',
            natural: false,
            note: 'The preposition cannot be dropped: de qué andén, and the verb follows the question word.',
          },
        ],
      },
      { speaker: 'partner', es: 'Eso lo ponen en el panel una hora antes. Buen viaje.', en: 'They put that on the board an hour before. Have a good trip.' },
    ],
  },

  // --- B1: conversations with a position to defend -------------------------
  {
    id: 'conv.trabajo',
    title: 'Explaining why you want to change jobs',
    icon: 'briefcase-outline',
    setting: 'A friend of a friend works where you have applied. You are having a coffee.',
    level: 'B1',
    topics: ['work', 'opinions'],
    partner: { name: 'Álvaro' },
    turns: [
      { speaker: 'partner', es: 'Así que quieres cambiar de trabajo. ¿Y eso? ¿No estabas a gusto?', en: 'So you want to change jobs. How come? Weren’t you happy?' },
      {
        speaker: 'you',
        instruction: 'Say the job is fine but you are fed up with the hours, and give a reason.',
        accepted: [
          'el trabajo está bien, pero estoy harto del horario, nunca sé cuándo salgo',
          'está bien, pero estoy harto del horario porque cambia cada semana',
          'el trabajo me gusta, pero estoy harto del horario',
          'no está mal, pero estoy harto del horario y quiero algo más estable',
        ],
        hints: ['está bien, pero…', 'estoy harto del horario', 'porque…'],
        concepts: ['v.harto', 'v.horario', 'v.trabajo'],
      },
      { speaker: 'partner', es: 'Ya. ¿Y has hablado con tu jefe? A lo mejor lo pueden cambiar.', en: 'Right. And have you talked to your boss? Maybe they can change it.' },
      {
        speaker: 'you',
        instruction: 'Say you already tried, and report what your boss told you.',
        accepted: [
          'ya lo intenté, me dijo que no se podía cambiar',
          'sí, ya hablé con él, me dijo que era imposible',
          'lo intenté, pero me dijo que no dependía de él',
          'sí, me dijo que lo miraría, pero no ha hecho nada',
        ],
        hints: ['ya lo intenté', 'me dijo que…'],
        concepts: ['g.reported-speech', 'v.jefe', 'g.preterite'],
      },
      { speaker: 'partner', es: 'Vaya. Pues aquí el ambiente es bueno, pero se trabaja mucho, te aviso.', en: 'Blimey. Well, the atmosphere here is good, but people work a lot, I’m warning you.' },
      {
        speaker: 'you',
        instruction: 'Say that does not worry you, and ask him for advice about the interview.',
        accepted: [
          'eso no me preocupa. ¿qué me recomiendas para la entrevista?',
          'no me importa trabajar. ¿algún consejo para la entrevista?',
          'eso no me preocupa, ¿tú qué harías en la entrevista?',
          'no pasa nada por eso. ¿qué me recomiendas para la entrevista?',
        ],
        hints: ['eso no me preocupa', '¿qué me recomiendas…?', 'yo que tú…'],
        concepts: ['p.me-preocupa', 'p.te-recomiendo', 'v.reunion'],
      },
      { speaker: 'partner', es: 'Yo que tú, sería sincero con lo del horario. Aquí lo valoran.', en: 'If I were you, I’d be honest about the hours thing. They value that here.' },
    ],
  },
  {
    id: 'conv.reclamacion',
    title: 'Something arrived broken',
    icon: 'chatbubbles-outline',
    setting: 'A shop counter. The lamp you ordered arrived with a cracked base.',
    level: 'B1',
    topics: ['shopping', 'opinions'],
    partner: { name: 'Encargado' },
    turns: [
      { speaker: 'partner', es: 'Buenas tardes. ¿Qué necesita?', en: 'Good afternoon. What do you need?' },
      {
        speaker: 'you',
        instruction: 'Explain there is a problem with your order and that it arrived broken.',
        accepted: [
          'hay un problema con mi pedido, ha llegado roto',
          'buenas tardes, hay un problema: el pedido llegó roto',
          'tengo un problema con el pedido, llegó roto',
          'hay un problema con mi pedido, la lámpara está rota',
        ],
        hints: ['hay un problema con…', 'ha llegado roto'],
        concepts: ['p.hay-un-problema', 'g.present-perfect', 'v.averiado'],
      },
      { speaker: 'partner', es: 'Vaya, lo siento. ¿Tiene el tique? Sin tique no puedo hacer nada.', en: 'Oh, I’m sorry. Do you have the receipt? Without it I can’t do anything.' },
      {
        speaker: 'you',
        instruction: 'Say you have it here, and that you would like to return it.',
        accepted: [
          'sí, lo tengo aquí. querría devolverlo',
          'sí, aquí está. querría devolverlo',
          'lo tengo aquí, querría devolverlo, por favor',
          'sí, aquí lo tiene. me gustaría devolverlo',
        ],
        hints: ['lo tengo aquí', 'querría devolver…'],
        concepts: ['p.querria-devolver', 'g.object-pronouns'],
      },
      { speaker: 'partner', es: 'Puedo cambiárselo por otro, pero el reembolso tarda dos semanas.', en: 'I can swap it for another, but a refund takes two weeks.' },
      {
        speaker: 'you',
        instruction: 'Say that is fine, you prefer the exchange, and ask when it would arrive.',
        accepted: [
          'no pasa nada, prefiero el cambio. ¿cuándo llegaría?',
          'vale, prefiero cambiarlo. ¿cuándo llegaría el nuevo?',
          'está bien, prefiero el cambio. ¿cuándo me llegaría?',
          'prefiero cambiarlo, ¿cuándo llegaría?',
        ],
        hints: ['no pasa nada', 'prefiero…', '¿cuándo llegaría?'],
        concepts: ['p.no-pasa-nada', 'v.preferir', 'g.conditional'],
      },
      { speaker: 'partner', es: 'En tres o cuatro días. Le aviso yo mismo cuando esté aquí.', en: 'In three or four days. I’ll let you know myself when it’s here.' },
    ],
  },

  // --- B2 and above: positions, not transactions ---------------------------
  {
    id: 'conv.negociar',
    title: 'Negotiating a deadline',
    icon: 'swap-horizontal-outline',
    setting: 'Your manager wants the report on Friday. It is Wednesday and it is not close.',
    level: 'B2',
    topics: ['work', 'opinions'],
    partner: { name: 'Nuria' },
    turns: [
      { speaker: 'partner', es: 'Necesito el informe el viernes. Ya lo hablamos la semana pasada.', en: 'I need the report on Friday. We already discussed it last week.' },
      {
        speaker: 'you',
        instruction: 'Concede the point first, then object. Do not simply refuse.',
        accepted: [
          'puede ser, pero lo que pasa es que faltan los datos de ventas',
          'tienes razón, lo que pasa es que todavía no tengo los datos',
          'estoy de acuerdo en parte, pero no han llegado los datos',
          'puede ser, pero hay que tener en cuenta que faltan los datos',
        ],
        hints: ['puede ser, pero…', 'lo que pasa es que…', 'hay que tener en cuenta que…'],
        concepts: ['p.puede-ser-pero', 'p.lo-que-pasa-es', 'p.hay-que-tener-en-cuenta'],
      },
      { speaker: 'partner', es: 'Los datos los tienes desde el lunes. Me consta.', en: 'You’ve had the data since Monday. I know that for a fact.' },
      {
        speaker: 'you',
        instruction: 'Report what someone else told you, shifting the tense correctly.',
        accepted: [
          'marta me comentó que los enviaría el jueves, no el lunes',
          'me dijeron que llegarían esta semana, todavía no están',
          'marta me dijo que los mandaría al día siguiente y aún no han llegado',
          'me comentó que estarían el jueves, no antes',
        ],
        hints: ['me comentó que…', 'me dijeron que… llegarían'],
        concepts: ['p.me-comento-que', 'g.reported-speech', 'g.conditional'],
      },
      { speaker: 'partner', es: 'Vale. ¿Y qué propones? Porque el cliente lo espera el viernes.', en: 'Fine. So what do you propose? Because the client expects it Friday.' },
      {
        speaker: 'you',
        instruction: 'Offer a hypothetical compromise using si + imperfect subjunctive.',
        accepted: [
          'si me dieras hasta el lunes, lo tendrías completo',
          'si pudiéramos mandarlo el lunes, iría con todos los datos',
          'si nos diera dos días más, el informe estaría entero',
          'si lo retrasáramos al lunes, no faltaría nada',
        ],
        hints: ['si me dieras…', 'si pudiéramos…', '…lo tendrías'],
        concepts: ['g.si-hypothetical', 'g.conditional'],
      },
      { speaker: 'partner', es: 'El lunes a primera hora, entonces. Y avísame si vuelve a pasar.', en: 'Monday first thing, then. And tell me if it happens again.' },
    ],
  },
  {
    id: 'conv.matiz',
    title: 'Conceder sin ceder',
    icon: 'git-branch-outline',
    setting: 'Un compañero da por cerrado un asunto que tú no ves cerrado. Estáis a solas.',
    level: 'C1',
    topics: ['work', 'opinions'],
    partner: { name: 'Javier' },
    turns: [
      { speaker: 'partner', es: 'Está claro que la culpa fue del proveedor. No hay más que hablar.', en: 'It’s obvious it was the supplier’s fault. There’s nothing more to discuss.' },
      {
        speaker: 'you',
        instruction: 'Concede el hecho como cierto (indicativo) y objeta a continuación.',
        accepted: [
          'aunque tienes razón, eso no explica los dos meses de retraso',
          'aunque llevas razón, el problema no empezó ahí',
          'aunque tienes razón, hay matices que conviene señalar',
          'si bien tienes razón, no es toda la historia',
        ],
        hints: ['aunque tienes razón…', 'si bien…', 'hay matices'],
        concepts: ['g.aunque-nuance', 'p.tener-razon', 'v.matiz'],
      },
      { speaker: 'partner', es: '¿Qué matices? Nos entregaron tarde, punto.', en: 'What nuances? They delivered late, full stop.' },
      {
        speaker: 'you',
        instruction: 'Atenúa la crítica: no niegues, pero señala que algo no acaba de encajar.',
        accepted: [
          'no es que no sea verdad, es que no termina de explicarlo todo',
          'hasta cierto punto sí, pero no termina de encajar',
          'no es que te quite la razón, es que falta una parte',
          'en cierto modo sí, ahora bien, no lo explica del todo',
        ],
        hints: ['no es que…, es que…', 'no termina de…', 'hasta cierto punto'],
        concepts: ['p.no-es-que', 'p.no-termina-de', 'p.hasta-cierto-punto'],
      },
      { speaker: 'partner', es: 'A ver, dilo claro. ¿Estás diciendo que nos equivocamos nosotros?', en: 'Go on, say it plainly. Are you saying we got it wrong?' },
      {
        speaker: 'you',
        instruction: 'Reformula para corregir la caracterización sin acusar a nadie.',
        accepted: [
          'más bien diría que el pedido se cursó tarde por nuestra parte',
          'dicho de otro modo: el error se produjo antes de llegar a ellos',
          'no tanto que nos equivocáramos como que lo pedimos tarde',
          'en otras palabras, se pidió tarde y eso lo arrastra todo',
        ],
        hints: ['más bien diría que…', 'dicho de otro modo…', 'se + verbo'],
        concepts: ['p.mas-bien', 'p.dicho-de-otro-modo', 'g.se-impersonal', 'g.reformulation'],
      },
      { speaker: 'partner', es: 'Pues eso habrá que decirlo en la reunión. Y no va a gustar.', en: 'Well, that’ll have to be said in the meeting. And it won’t go down well.' },
    ],
  },
  {
    id: 'conv.persuadir',
    title: 'El mismo argumento, otro público',
    icon: 'people-outline',
    setting: 'Has convencido al equipo. Ahora hay que convencer al comité, que no te conoce.',
    level: 'C2',
    topics: ['work', 'opinions'],
    partner: { name: 'Presidenta del comité' },
    turns: [
      { speaker: 'partner', es: 'Tiene cinco minutos. Le escuchamos.', en: 'You have five minutes. We’re listening.' },
      {
        speaker: 'you',
        instruction: 'Abre en registro formal, sin rodeos y sin sonar agresivo.',
        accepted: [
          'seré breve: cabe señalar que el modelo actual ya no se sostiene',
          'iré al grano: no cabe duda de que el sistema actual está agotado',
          'seré escueto. el planteamiento actual ha dejado de funcionar',
          'cabe señalar que, a todas luces, el modelo actual es insostenible',
        ],
        hints: ['cabe señalar que…', 'no cabe duda de que…', 'iré al grano'],
        concepts: ['p.cabe-senalar', 'p.no-cabe-duda', 'p.ir-al-grano', 'g.audience'],
      },
      { speaker: 'partner', es: 'Eso ya lo hemos oído otras veces. ¿Qué lo hace distinto ahora?', en: 'We’ve heard that before. What makes it different now?' },
      {
        speaker: 'you',
        instruction: 'Corrige la comparación: no es más de lo mismo, es otra cosa.',
        accepted: [
          'no tanto una propuesta nueva como una corrección de la anterior',
          'lejos de repetir lo de siempre, esto parte de los datos de este año',
          'no es tanto una idea nueva como una lectura distinta de los mismos datos',
          'lejos de ser más de lo mismo, invierte el planteamiento',
        ],
        hints: ['no tanto… como…', 'lejos de…'],
        concepts: ['p.no-tanto-como', 'p.lejos-de', 'v.planteamiento'],
      },
      { speaker: 'partner', es: 'Hay quien dirá que asumimos demasiado riesgo con esto.', en: 'Some will say we’re taking on too much risk with this.' },
      {
        speaker: 'you',
        instruction: 'Reconoce el riesgo y devuélvelo: no actuar también lo tiene.',
        accepted: [
          'lo reconozco, pero no hacer nada también sienta un precedente',
          'es cierto, ahora bien, no asumir ningún riesgo es asumir el mayor',
          'lo admito, aunque cabe señalar que la inacción tiene su propio coste',
          'sí, con la salvedad de que no decidir ya es una decisión',
        ],
        hints: ['lo reconozco, pero…', 'ahora bien…', 'con la salvedad de que…'],
        concepts: ['v.reconocer', 'p.sentar-precedente', 'p.ahora-bien', 'v.salvedad'],
      },
      { speaker: 'partner', es: 'Déjenos deliberar. Le diremos algo esta tarde.', en: 'Let us deliberate. We’ll get back to you this afternoon.' },
    ],
  },
];
