import type { CefrLevel } from '@/content/types';

/**
 * Placement question bank.
 *
 * Deliberately short and wide rather than deep: the goal is to find the right
 * starting point and spot two or three weak areas, not to grade an exam. Every
 * question is tagged with an `area` so the result can say something specific
 * ("ser vs estar needs work") instead of just naming a level.
 */

export type PlacementArea =
  | 'vocabulary'
  | 'present'
  | 'serEstar'
  | 'gustar'
  | 'past'
  | 'listening'
  | 'pronouns'
  | 'porPara'
  | 'subjunctive'
  | 'colloquial';

export const AREA_LABELS: Record<PlacementArea, string> = {
  vocabulary: 'vocabulary',
  present: 'the present tense',
  serEstar: 'ser vs estar',
  gustar: 'gustar-type verbs',
  past: 'past tenses',
  listening: 'listening',
  pronouns: 'object pronouns',
  porPara: 'por vs para',
  subjunctive: 'the subjunctive',
  colloquial: 'everyday spoken Spanish',
};

export interface PlacementQuestion {
  id: string;
  level: CefrLevel;
  area: PlacementArea;
  form: 'choice' | 'typed' | 'listen';
  prompt: string;
  promptSub?: string;
  /** Spanish spoken aloud for `listen` questions. */
  audio?: string;
  options?: string[];
  answer?: number;
  accepted?: string[];
  /** Concepts this question evidences, used to seed the learner model. */
  concepts: string[];
}

export const placementQuestions: PlacementQuestion[] = [
  // --- A0 ------------------------------------------------------------------
  {
    id: 'q.a0.1',
    level: 'A0',
    area: 'vocabulary',
    form: 'choice',
    prompt: 'gracias',
    options: ['thank you', 'please', 'sorry', 'goodbye'],
    answer: 0,
    concepts: ['v.gracias'],
  },
  {
    id: 'q.a0.2',
    level: 'A0',
    area: 'vocabulary',
    form: 'choice',
    prompt: '¿Cómo te llamas?',
    options: ['What’s your name?', 'How are you?', 'Where are you from?', 'How old are you?'],
    answer: 0,
    concepts: ['p.como-te-llamas'],
  },
  {
    id: 'q.a0.3',
    level: 'A0',
    area: 'present',
    form: 'choice',
    prompt: 'Yo ___ español.',
    promptSub: 'I speak Spanish.',
    options: ['hablo', 'hablas', 'habla', 'hablamos'],
    answer: 0,
    concepts: ['v.hablar', 'g.present-regular'],
  },
  {
    id: 'q.a0.4',
    level: 'A0',
    area: 'vocabulary',
    form: 'choice',
    prompt: 'How do you say "the house"?',
    options: ['la casa', 'el casa', 'la caso', 'el caso'],
    answer: 0,
    concepts: ['v.casa', 'g.gender'],
  },

  // --- A1 ------------------------------------------------------------------
  {
    id: 'q.a1.1',
    level: 'A1',
    area: 'serEstar',
    form: 'choice',
    prompt: 'Madrid ___ en España.',
    promptSub: 'Madrid is in Spain.',
    options: ['está', 'es', 'hay', 'tiene'],
    answer: 0,
    concepts: ['g.ser-estar', 'v.estar'],
  },
  {
    id: 'q.a1.2',
    level: 'A1',
    area: 'serEstar',
    form: 'choice',
    prompt: 'Hoy ___ muy cansado.',
    promptSub: 'Today I’m very tired.',
    options: ['estoy', 'soy', 'tengo', 'hay'],
    answer: 0,
    concepts: ['g.ser-estar', 'v.cansado'],
  },
  {
    id: 'q.a1.3',
    level: 'A1',
    area: 'vocabulary',
    form: 'choice',
    prompt: 'Tengo veintiún ___.',
    promptSub: 'I’m twenty-one.',
    options: ['años', 'anos', 'tiempo', 'edades'],
    answer: 0,
    concepts: ['g.tener-expressions', 'v.anos'],
  },
  {
    id: 'q.a1.4',
    level: 'A1',
    area: 'present',
    form: 'choice',
    prompt: '¿Vosotros ___ en Madrid?',
    promptSub: 'Do you (all) live in Madrid?',
    options: ['vivís', 'viven', 'vivimos', 'vives'],
    answer: 0,
    concepts: ['v.vosotros', 'v.vivir', 'g.present-regular'],
  },
  {
    id: 'q.a1.5',
    level: 'A1',
    area: 'gustar',
    form: 'choice',
    prompt: '___ los perros.',
    promptSub: 'I like dogs.',
    options: ['Me gustan', 'Me gusta', 'Yo gusto', 'Gusto'],
    answer: 0,
    concepts: ['g.gustar', 'p.me-gustan'],
  },
  {
    id: 'q.a1.6',
    level: 'A1',
    area: 'listening',
    form: 'listen',
    prompt: 'What did you hear?',
    audio: 'Tengo un perro pequeño.',
    options: ['I have a small dog.', 'I have a small cat.', 'I want a small dog.', 'He has a small dog.'],
    answer: 0,
    concepts: ['v.tener', 'v.perro', 'v.pequeno'],
  },

  // --- A2 ------------------------------------------------------------------
  {
    id: 'q.a2.1',
    level: 'A2',
    area: 'present',
    form: 'typed',
    prompt: 'I get up at seven.',
    accepted: ['Me levanto a las siete.', 'Yo me levanto a las siete.'],
    concepts: ['g.reflexive', 'v.levantarse'],
  },
  {
    id: 'q.a2.2',
    level: 'A2',
    area: 'porPara',
    form: 'choice',
    prompt: 'Gracias ___ todo.',
    promptSub: 'Thanks for everything.',
    options: ['por', 'para', 'de', 'a'],
    answer: 0,
    concepts: ['g.por-para'],
  },
  {
    id: 'q.a2.3',
    level: 'A2',
    area: 'vocabulary',
    form: 'choice',
    prompt: 'Which word is used in Spain for "computer"?',
    options: ['ordenador', 'computadora', 'calculadora', 'computador'],
    answer: 0,
    concepts: ['v.ordenador'],
  },
  {
    id: 'q.a2.4',
    level: 'A2',
    area: 'present',
    form: 'choice',
    prompt: 'Mañana ___ a estudiar.',
    promptSub: 'Tomorrow I’m going to study.',
    options: ['voy', 'iré', 'fui', 'iba'],
    answer: 0,
    concepts: ['g.ir-a-infinitive', 'v.ir'],
  },
  {
    id: 'q.a2.5',
    level: 'A2',
    area: 'listening',
    form: 'listen',
    prompt: 'What is being asked?',
    audio: '¿Me pones una caña, por favor?',
    options: [
      'Can I have a small beer, please?',
      'Can I have the bill, please?',
      'Do you have a table, please?',
      'Where is the bar, please?',
    ],
    answer: 0,
    concepts: ['p.me-pones', 'v.cana'],
  },
  {
    id: 'q.a2.6',
    level: 'A2',
    area: 'colloquial',
    form: 'choice',
    prompt: 'A Spanish friend says "vale". What do they mean?',
    options: ['okay', 'it’s worth it', 'wait', 'goodbye'],
    answer: 0,
    concepts: ['v.vale'],
  },
  {
    id: 'q.a2.7',
    level: 'A2',
    area: 'past',
    form: 'choice',
    prompt: 'Hoy ___ al médico.',
    promptSub: 'Today I went to the doctor.',
    options: ['he ido', 'fui', 'iba', 'voy'],
    answer: 0,
    concepts: ['g.present-perfect'],
  },

  // --- B1 ------------------------------------------------------------------
  {
    id: 'q.b1.1',
    level: 'B1',
    area: 'past',
    form: 'choice',
    prompt: 'Ayer ___ al cine con Marta.',
    promptSub: 'Yesterday I went to the cinema with Marta.',
    options: ['fui', 'he ido', 'iba', 'voy'],
    answer: 0,
    concepts: ['g.preterite'],
  },
  {
    id: 'q.b1.2',
    level: 'B1',
    area: 'past',
    form: 'choice',
    prompt: '___ en el bar cuando ___ Marta.',
    promptSub: 'I was in the bar when Marta arrived.',
    options: ['Estaba / llegó', 'Estuve / llegaba', 'Estaba / llegaba', 'Estuve / llegó'],
    answer: 0,
    concepts: ['g.preterite-imperfect'],
  },
  {
    id: 'q.b1.3',
    level: 'B1',
    area: 'pronouns',
    form: 'choice',
    prompt: '¿El libro? ___ tengo yo.',
    promptSub: 'The book? I’ve got it.',
    options: ['Lo', 'Le', 'La', 'Los'],
    answer: 0,
    concepts: ['g.object-pronouns'],
  },
  {
    id: 'q.b1.4',
    level: 'B1',
    area: 'past',
    form: 'typed',
    prompt: 'What did you do at the weekend?',
    accepted: ['¿Qué hiciste el fin de semana?', 'Qué hiciste el fin de semana'],
    concepts: ['g.preterite', 'v.hacer', 'v.fin-de-semana'],
  },
  {
    id: 'q.b1.5',
    level: 'B1',
    area: 'colloquial',
    form: 'choice',
    prompt: 'Someone says "hemos quedado a las ocho". What does it mean?',
    options: [
      'We’re meeting at eight',
      'We stayed until eight',
      'We finished at eight',
      'We waited until eight',
    ],
    answer: 0,
    concepts: ['v.quedar', 'g.present-perfect'],
  },
  {
    id: 'q.b1.6',
    level: 'B1',
    area: 'listening',
    form: 'listen',
    prompt: 'What does the speaker mean?',
    audio: 'No me apetece salir, estoy muerto.',
    options: [
      'They don’t feel like going out because they’re exhausted',
      'They’re going out even though they’re tired',
      'They want to go out but can’t',
      'They’re unwell and staying in bed',
    ],
    answer: 0,
    concepts: ['p.me-apetece', 'v.salir'],
  },
  {
    id: 'q.b1.7',
    level: 'B1',
    area: 'subjunctive',
    form: 'choice',
    prompt: 'Quiero que ___ a la fiesta.',
    promptSub: 'I want you to come to the party.',
    options: ['vengas', 'vienes', 'venir', 'vendrás'],
    answer: 0,
    concepts: ['g.subjunctive-intro'],
  },

  // --- B2 ------------------------------------------------------------------
  {
    id: 'q.b2.1',
    level: 'B2',
    area: 'subjunctive',
    form: 'choice',
    prompt: 'No creo que ___ buena idea.',
    promptSub: 'I don’t think it’s a good idea.',
    options: ['sea', 'es', 'está', 'esté'],
    answer: 0,
    concepts: ['g.subjunctive-intro'],
  },
  {
    id: 'q.b2.2',
    level: 'B2',
    area: 'pronouns',
    form: 'typed',
    prompt: 'Can you send it to me?',
    accepted: ['¿Me lo puedes mandar?', '¿Puedes mandármelo?', 'Me lo puedes mandar'],
    concepts: ['g.object-pronouns'],
  },
  {
    id: 'q.b2.3',
    level: 'B2',
    area: 'colloquial',
    form: 'choice',
    prompt: 'What does "en plan" mean in casual Spanish from Spain?',
    options: ['like… / sort of', 'on purpose', 'as planned', 'in short'],
    answer: 0,
    concepts: ['p.en-plan'],
  },
  {
    id: 'q.b2.4',
    level: 'B2',
    area: 'past',
    form: 'choice',
    prompt: '___ a llamarte, pero se me olvidó.',
    promptSub: 'I was going to call you, but I forgot.',
    options: ['Iba', 'Fui', 'Voy', 'Iré'],
    answer: 0,
    concepts: ['g.imperfect', 'p.se-me-ha-olvidado'],
  },

  // --- A0, extended --------------------------------------------------------
  {
    id: 'q.a0.5',
    level: 'A0',
    area: 'vocabulary',
    form: 'choice',
    prompt: 'por favor',
    options: ['please', 'thank you', 'excuse me', 'goodbye'],
    answer: 0,
    concepts: ['p.por-favor'],
  },
  {
    id: 'q.a0.6',
    level: 'A0',
    area: 'vocabulary',
    form: 'choice',
    prompt: 'Which one means "seven"?',
    options: ['siete', 'seis', 'nueve', 'cien'],
    answer: 0,
    concepts: ['v.siete'],
  },
  {
    id: 'q.a0.7',
    level: 'A0',
    area: 'present',
    form: 'choice',
    prompt: '¿Dónde ___ tú?',
    promptSub: 'Where do you live?',
    options: ['vives', 'vivo', 'vive', 'vivimos'],
    answer: 0,
    concepts: ['v.vivir', 'g.present-regular'],
  },
  {
    id: 'q.a0.8',
    level: 'A0',
    area: 'vocabulary',
    form: 'choice',
    prompt: 'hasta luego',
    options: ['see you later', 'good morning', 'how are you?', 'nice to meet you'],
    answer: 0,
    concepts: ['p.hasta-luego'],
  },
  {
    id: 'q.a0.9',
    level: 'A0',
    area: 'listening',
    form: 'listen',
    prompt: 'What did you hear?',
    audio: 'Buenos días.',
    options: ['Good morning.', 'Good night.', 'See you later.', 'Thank you very much.'],
    answer: 0,
    concepts: ['p.buenos-dias'],
  },

  // --- A1, extended --------------------------------------------------------
  {
    id: 'q.a1.7',
    level: 'A1',
    area: 'serEstar',
    form: 'choice',
    prompt: 'Mi hermana ___ profesora.',
    promptSub: 'My sister is a teacher.',
    options: ['es', 'está', 'tiene', 'hay'],
    answer: 0,
    concepts: ['g.ser-estar', 'v.ser'],
  },
  {
    id: 'q.a1.8',
    level: 'A1',
    area: 'vocabulary',
    form: 'choice',
    prompt: '¿Qué hora es? — Son las tres y ___.',
    promptSub: 'It’s half past three.',
    options: ['media', 'medio', 'mitad', 'cuarto'],
    answer: 0,
    concepts: ['v.media', 'p.son-las'],
  },
  {
    id: 'q.a1.9',
    level: 'A1',
    area: 'present',
    form: 'choice',
    prompt: 'Nosotros ___ a las dos.',
    promptSub: 'We have lunch at two.',
    options: ['comemos', 'coméis', 'comen', 'como'],
    answer: 0,
    concepts: ['v.comer', 'g.present-regular'],
  },
  {
    id: 'q.a1.10',
    level: 'A1',
    area: 'vocabulary',
    form: 'choice',
    prompt: 'Hay una farmacia ___ del metro.',
    promptSub: 'There’s a pharmacy next to the metro.',
    options: ['al lado', 'a lado', 'el lado', 'de lado'],
    answer: 0,
    concepts: ['v.al-lado'],
  },
  {
    id: 'q.a1.11',
    level: 'A1',
    area: 'gustar',
    form: 'choice',
    prompt: '___ mucho el cine español.',
    promptSub: 'I really like Spanish cinema.',
    options: ['Me gusta', 'Me gustan', 'Yo gusto', 'A mí gusta'],
    answer: 0,
    concepts: ['g.gustar', 'p.me-gusta'],
  },
  {
    id: 'q.a1.12',
    level: 'A1',
    area: 'vocabulary',
    form: 'typed',
    prompt: 'I have a dog.',
    accepted: ['Tengo un perro.', 'Yo tengo un perro.'],
    concepts: ['v.tener', 'v.perro'],
  },
  {
    id: 'q.a1.13',
    level: 'A1',
    area: 'listening',
    form: 'listen',
    prompt: 'What is being said?',
    audio: 'Estoy muy cansado hoy.',
    options: ['I’m very tired today.', 'I’m very happy today.', 'I’m working today.', 'I’m late today.'],
    answer: 0,
    concepts: ['v.estar', 'v.cansado'],
  },
  {
    id: 'q.a1.14',
    level: 'A1',
    area: 'vocabulary',
    form: 'choice',
    prompt: 'Which is the Spain word for "flat / apartment"?',
    options: ['el piso', 'el departamento', 'el apartamento', 'la planta'],
    answer: 0,
    concepts: ['v.piso'],
  },

  // --- A2, extended --------------------------------------------------------
  {
    id: 'q.a2.8',
    level: 'A2',
    area: 'present',
    form: 'choice',
    prompt: '¿A qué hora ___ vosotros?',
    promptSub: 'What time do you (all) go to bed?',
    options: ['os acostáis', 'te acuestas', 'se acuestan', 'nos acostamos'],
    answer: 0,
    concepts: ['g.reflexive', 'v.acostarse', 'v.vosotros'],
  },
  {
    id: 'q.a2.9',
    level: 'A2',
    area: 'vocabulary',
    form: 'choice',
    prompt: 'You need a ticket for the train. You ask for…',
    options: ['un billete', 'una entrada', 'un boleto', 'una tarjeta'],
    answer: 0,
    concepts: ['v.billete', 'v.entrada'],
  },
  {
    id: 'q.a2.10',
    level: 'A2',
    area: 'porPara',
    form: 'choice',
    prompt: 'Este regalo es ___ mi madre.',
    promptSub: 'This present is for my mother.',
    options: ['para', 'por', 'a', 'de'],
    answer: 0,
    concepts: ['g.por-para'],
  },
  {
    id: 'q.a2.11',
    level: 'A2',
    area: 'vocabulary',
    form: 'typed',
    prompt: 'I have to study this afternoon.',
    accepted: [
      'Tengo que estudiar esta tarde.',
      'Yo tengo que estudiar esta tarde.',
      'Tengo que estudiar por la tarde.',
    ],
    concepts: ['p.tener-que', 'v.estudiar'],
  },
  {
    id: 'q.a2.12',
    level: 'A2',
    area: 'colloquial',
    form: 'choice',
    prompt: 'In a Spanish bar, the most natural way to order is…',
    options: [
      '¿Me pones una caña?',
      'Yo deseo una cerveza pequeña.',
      'Quiero que me des una cerveza.',
      'Necesito una caña ahora.',
    ],
    answer: 0,
    concepts: ['p.me-pones', 'v.cana'],
  },
  {
    id: 'q.a2.13',
    level: 'A2',
    area: 'listening',
    form: 'listen',
    prompt: 'What is the speaker doing?',
    audio: 'Perdona, ¿sabes dónde está la estación?',
    options: [
      'Asking for directions',
      'Buying a ticket',
      'Booking a table',
      'Asking for the time',
    ],
    answer: 0,
    concepts: ['p.perdona-donde', 'v.estacion'],
  },
  {
    id: 'q.a2.14',
    level: 'A2',
    area: 'gustar',
    form: 'choice',
    prompt: 'No ___ nada el fútbol.',
    promptSub: 'I don’t like football at all.',
    options: ['me gusta', 'me gustan', 'gusto', 'me gustaría'],
    answer: 0,
    concepts: ['g.gustar', 'p.no-me-gusta-nada'],
  },
  {
    id: 'q.a2.15',
    level: 'A2',
    area: 'vocabulary',
    form: 'choice',
    prompt: 'Which verb do Spaniards use for taking the metro?',
    options: ['coger', 'tomar', 'agarrar', 'llevar'],
    answer: 0,
    concepts: ['v.coger'],
  },
  {
    id: 'q.a2.16',
    level: 'A2',
    area: 'present',
    form: 'choice',
    prompt: 'Yo no ___ dónde está.',
    promptSub: 'I don’t know where it is.',
    options: ['sé', 'conozco', 'sabo', 'sepo'],
    answer: 0,
    concepts: ['v.saber', 'v.conocer'],
  },

  // --- B1, extended --------------------------------------------------------
  {
    id: 'q.b1.8',
    level: 'B1',
    area: 'past',
    form: 'choice',
    prompt: 'Cuando era pequeño, ___ todos los veranos a la playa.',
    promptSub: 'When I was little, we went to the beach every summer.',
    options: ['íbamos', 'fuimos', 'vamos', 'habíamos ido'],
    answer: 0,
    concepts: ['g.imperfect', 'g.preterite-imperfect'],
  },
  {
    id: 'q.b1.9',
    level: 'B1',
    area: 'pronouns',
    form: 'choice',
    prompt: '¿El informe? Ya ___ he mandado a Marta.',
    promptSub: 'The report? I’ve already sent it to her.',
    options: ['se lo', 'le lo', 'lo le', 'se le'],
    answer: 0,
    concepts: ['g.object-pronouns'],
  },
  {
    id: 'q.b1.10',
    level: 'B1',
    area: 'colloquial',
    form: 'choice',
    prompt: 'A friend says "me da igual". They mean…',
    options: [
      'they don’t mind either way',
      'they strongly disagree',
      'they are annoyed',
      'they agree completely',
    ],
    answer: 0,
    concepts: ['p.da-igual'],
  },
  {
    id: 'q.b1.11',
    level: 'B1',
    area: 'subjunctive',
    form: 'choice',
    prompt: 'Espero que ___ bien el examen.',
    promptSub: 'I hope it goes well in the exam.',
    options: ['te salga', 'te sale', 'te salió', 'te saldrá'],
    answer: 0,
    concepts: ['g.subjunctive-intro'],
  },
  {
    id: 'q.b1.12',
    level: 'B1',
    area: 'past',
    form: 'typed',
    prompt: 'Yesterday I went to the cinema with Marta.',
    accepted: ['Ayer fui al cine con Marta.', 'Ayer fui al cine con Marta'],
    concepts: ['g.preterite', 'v.ayer'],
  },
  {
    id: 'q.b1.13',
    level: 'B1',
    area: 'listening',
    form: 'listen',
    prompt: 'What happened?',
    audio: 'Estaba en el bar cuando llegó Marta.',
    options: [
      'He was in the bar when Marta arrived',
      'He arrived at the bar with Marta',
      'He left the bar before Marta',
      'Marta was waiting in the bar',
    ],
    answer: 0,
    concepts: ['g.preterite-imperfect'],
  },
  {
    id: 'q.b1.14',
    level: 'B1',
    area: 'porPara',
    form: 'choice',
    prompt: 'Te llamo ___ teléfono ___ confirmar la hora.',
    promptSub: 'I’ll call you by phone to confirm the time.',
    options: ['por / para', 'para / por', 'por / por', 'para / para'],
    answer: 0,
    concepts: ['g.por-para'],
  },
  {
    id: 'q.b1.15',
    level: 'B1',
    area: 'colloquial',
    form: 'choice',
    prompt: '"Se me ha olvidado la maleta" literally frames the speaker as…',
    options: [
      'someone the forgetting happened to',
      'the one to blame',
      'the owner of the suitcase',
      'someone in a hurry',
    ],
    answer: 0,
    concepts: ['p.se-me-ha-olvidado'],
  },

  // --- B2, extended --------------------------------------------------------
  {
    id: 'q.b2.5',
    level: 'B2',
    area: 'subjunctive',
    form: 'choice',
    prompt: 'Si ___ más tiempo, viajaría más.',
    promptSub: 'If I had more time, I’d travel more.',
    options: ['tuviera', 'tengo', 'tendría', 'tuve'],
    answer: 0,
    concepts: [],
  },
  {
    id: 'q.b2.6',
    level: 'B2',
    area: 'subjunctive',
    form: 'choice',
    prompt: 'Cuando ___ a Madrid, te aviso.',
    promptSub: 'When I get to Madrid, I’ll let you know.',
    options: ['llegue', 'llego', 'llegaré', 'llegaba'],
    answer: 0,
    concepts: [],
  },
  {
    id: 'q.b2.7',
    level: 'B2',
    area: 'colloquial',
    form: 'choice',
    prompt: '"Ni que fuera millonario" expresses…',
    options: [
      'sarcasm about someone acting rich',
      'a wish to become rich',
      'admiration for a rich person',
      'a plan to earn money',
    ],
    answer: 0,
    concepts: [],
  },
  {
    id: 'q.b2.8',
    level: 'B2',
    area: 'past',
    form: 'choice',
    prompt: 'Me dijo que ya ___ el trabajo.',
    promptSub: 'He told me he had already finished the work.',
    options: ['había terminado', 'ha terminado', 'terminó', 'terminaba'],
    answer: 0,
    concepts: [],
  },
  {
    id: 'q.b2.9',
    level: 'B2',
    area: 'listening',
    form: 'listen',
    prompt: 'What is the speaker expressing?',
    audio: 'Aunque estaba cansado, salí igual.',
    options: [
      'He went out despite being tired',
      'He stayed in because he was tired',
      'He was tired after going out',
      'He got tired while out',
    ],
    answer: 0,
    concepts: ['v.aunque'],
  },

  // --- C1 ------------------------------------------------------------------
  {
    id: 'q.c1.1',
    level: 'C1',
    area: 'subjunctive',
    form: 'choice',
    prompt: 'De haberlo sabido, no ___ nada.',
    promptSub: 'Had I known, I wouldn’t have said anything.',
    options: ['habría dicho', 'diría', 'dije', 'haya dicho'],
    answer: 0,
    concepts: [],
  },
  {
    id: 'q.c1.2',
    level: 'C1',
    area: 'colloquial',
    form: 'choice',
    prompt: '"Está en las nubes" means someone is…',
    options: ['daydreaming', 'very happy', 'travelling', 'confused by the weather'],
    answer: 0,
    concepts: [],
  },
  {
    id: 'q.c1.3',
    level: 'C1',
    area: 'vocabulary',
    form: 'choice',
    prompt: '"Se rumorea que dimitirá" uses which construction?',
    options: [
      'impersonal se',
      'reflexive se',
      'passive with ser',
      'reciprocal se',
    ],
    answer: 0,
    concepts: [],
  },
  {
    id: 'q.c1.4',
    level: 'C1',
    area: 'colloquial',
    form: 'choice',
    prompt: 'Which is the most formal way to make a request?',
    options: [
      '¿Sería tan amable de enviármelo?',
      '¿Me lo mandas?',
      'Mándamelo, porfa.',
      '¿Me lo puedes mandar?',
    ],
    answer: 0,
    concepts: [],
  },
];
