import type { VerbSeed } from '@/content/verb-utils';

/**
 * The high-frequency verbs the course was missing.
 *
 * Written against the coverage audit, which reported the course conjugating 2
 * of 20 core B1 verbs and 0 of 12 core B2 verbs. A learner cannot narrate,
 * explain or argue without *creer*, *dejar*, *parecer*, *conseguir* or
 * *resultar*, and none of them existed — so the conjugation system was in place
 * and the verbs it needed to run on were not.
 *
 * Only deviations are written out; everything regular is generated by
 * `buildVerb`. Three rules worth restating because breaking them is silent:
 *
 *   1. **A stem change is per person, not per tense.** e→ie and o→ue hit
 *      yo/tú/él/ellos and leave nosotros and vosotros alone, so they go in
 *      `overrides`, never in `stems`. Using `stems` would produce *piensamos*.
 *   2. **Future and conditional share a stem**, so a verb declaring one
 *      declares both. Listing only the future is how a learner who met
 *      *tendré* could never reach *tendría*.
 *   3. **The subjunctive is derived from the present yo form minus its -o**, so
 *      overriding the present yo is usually all a subjunctive needs —
 *      parezco → parezca, consigo → consiga. Where the yo form is regular but
 *      the spelling has to shift (busqué, llegué), only the preterite yo needs
 *      saying; `respell` handles the subjunctive.
 */
export const coreVerbSeeds: VerbSeed[] = [
  // --- A1: the rest of the essentials --------------------------------------
  {
    id: 'haber',
    infinitive: 'haber',
    en: 'to have (auxiliary), there to be',
    level: 'A1',
    irregular: true,
    irregularityNote: 'Almost never used alone — it carries the perfect tenses, and its third person is "hay".',
    participle: 'habido',
    tenses: ['present', 'preterite', 'imperfect', 'future', 'conditional', 'presentSubjunctive'],
    overrides: {
      present: { yo: 'he', tu: 'has', el: 'ha', nosotros: 'hemos', vosotros: 'habéis', ellos: 'han' },
      preterite: { yo: 'hube', tu: 'hubiste', el: 'hubo', nosotros: 'hubimos', vosotros: 'hubisteis', ellos: 'hubieron' },
      presentSubjunctive: { yo: 'haya', tu: 'hayas', el: 'haya', nosotros: 'hayamos', vosotros: 'hayáis', ellos: 'hayan' },
    },
    stems: { future: 'habr', conditional: 'habr' },
    patterns: [
      { pattern: 'hay', en: 'there is / there are', example: { es: 'Hay una farmacia en la esquina.', en: "There's a chemist on the corner." } },
      { pattern: 'haber + participio', en: 'the perfect tenses', example: { es: 'He comido demasiado.', en: "I've eaten too much." } },
    ],
  },
  {
    id: 'llegar',
    infinitive: 'llegar',
    en: 'to arrive',
    level: 'A1',
    tenses: ['present', 'preterite', 'imperfect', 'presentPerfect', 'future', 'conditional', 'presentSubjunctive', 'imperative'],
    // g → gu before -é keeps the hard sound. The subjunctive gets it from `respell`.
    overrides: { preterite: { yo: 'llegué' } },
    patterns: [
      { pattern: 'llegar tarde', en: 'to be late', example: { es: 'Siempre llego tarde a clase.', en: "I'm always late to class." } },
    ],
  },
  { id: 'pasar', infinitive: 'pasar', en: 'to happen, to spend (time), to pass', level: 'A1', tenses: ['present', 'preterite', 'imperfect', 'presentPerfect', 'future', 'conditional', 'presentSubjunctive', 'imperative'], patterns: [{ pattern: '¿qué pasa?', en: "what's going on?", example: { es: '¿Qué te pasa?', en: "What's wrong with you?" } }] },
  { id: 'necesitar', infinitive: 'necesitar', en: 'to need', level: 'A1', tenses: ['present', 'preterite', 'imperfect', 'presentPerfect', 'future', 'conditional', 'presentSubjunctive'] },
  { id: 'esperar', infinitive: 'esperar', en: 'to wait, to hope', level: 'A1', tenses: ['present', 'preterite', 'imperfect', 'presentPerfect', 'future', 'conditional', 'presentSubjunctive', 'imperative'], patterns: [{ pattern: 'espero que + subjuntivo', en: 'I hope that…', example: { es: 'Espero que te mejores.', en: 'I hope you get better.' } }] },
  { id: 'ayudar', infinitive: 'ayudar', en: 'to help', level: 'A1', tenses: ['present', 'preterite', 'imperfect', 'presentPerfect', 'future', 'conditional', 'presentSubjunctive', 'imperative'], patterns: [{ pattern: 'ayudar a + infinitivo', en: 'to help do something', example: { es: '¿Me ayudas a llevar esto?', en: 'Can you help me carry this?' } }] },
  {
    id: 'buscar',
    infinitive: 'buscar',
    en: 'to look for',
    level: 'A1',
    tenses: ['present', 'preterite', 'imperfect', 'presentPerfect', 'future', 'conditional', 'presentSubjunctive', 'imperative'],
    // c → qu before -é. No preposition: buscar already contains the "for".
    overrides: { preterite: { yo: 'busqué' } },
  },
  {
    id: 'abrir',
    infinitive: 'abrir',
    en: 'to open',
    level: 'A1',
    irregular: true,
    irregularityNote: 'Regular except for the participle: abierto, not abrido.',
    participle: 'abierto',
    tenses: ['present', 'preterite', 'imperfect', 'presentPerfect', 'future', 'conditional', 'presentSubjunctive', 'imperative'],
  },
  {
    id: 'cerrar',
    infinitive: 'cerrar',
    en: 'to close',
    level: 'A1',
    irregular: true,
    irregularityNote: 'e → ie in the stressed forms; nosotros and vosotros keep the plain stem.',
    tenses: ['present', 'preterite', 'imperfect', 'presentPerfect', 'future', 'conditional', 'presentSubjunctive', 'imperative'],
    overrides: {
      presentSubjunctive: { nosotros: 'cerremos', vosotros: 'cerréis' }, present: { yo: 'cierro', tu: 'cierras', el: 'cierra', ellos: 'cierran' } },
  },
  {
    id: 'empezar',
    infinitive: 'empezar',
    en: 'to start',
    level: 'A1',
    irregular: true,
    irregularityNote: 'e → ie in the stem, and z → c before -é.',
    tenses: ['present', 'preterite', 'imperfect', 'presentPerfect', 'future', 'conditional', 'presentSubjunctive', 'imperative'],
    overrides: {
      presentSubjunctive: { nosotros: 'empecemos', vosotros: 'empecéis' },
      present: { yo: 'empiezo', tu: 'empiezas', el: 'empieza', ellos: 'empiezan' },
      preterite: { yo: 'empecé' },
    },
    patterns: [{ pattern: 'empezar a + infinitivo', en: 'to start doing something', example: { es: 'Empiezo a trabajar a las nueve.', en: 'I start work at nine.' } }],
  },
  { id: 'terminar', infinitive: 'terminar', en: 'to finish', level: 'A1', tenses: ['present', 'preterite', 'imperfect', 'presentPerfect', 'future', 'conditional', 'presentSubjunctive', 'imperative'] },
  {
    id: 'encontrar',
    infinitive: 'encontrar',
    en: 'to find',
    level: 'A1',
    irregular: true,
    irregularityNote: 'o → ue in the stressed forms.',
    tenses: ['present', 'preterite', 'imperfect', 'presentPerfect', 'future', 'conditional', 'presentSubjunctive', 'imperative'],
    overrides: {
      presentSubjunctive: { nosotros: 'encontremos', vosotros: 'encontréis' }, present: { yo: 'encuentro', tu: 'encuentras', el: 'encuentra', ellos: 'encuentran' } },
    patterns: [{ pattern: 'encontrarse mal', en: 'to feel unwell', example: { es: 'Me encuentro mal desde ayer.', en: "I've felt unwell since yesterday." } }],
  },
  {
    id: 'dormir',
    infinitive: 'dormir',
    en: 'to sleep',
    level: 'A1',
    irregular: true,
    irregularityNote: 'o → ue in the present, and o → u in the third-person preterite and the gerund.',
    gerund: 'durmiendo',
    tenses: ['present', 'preterite', 'imperfect', 'presentPerfect', 'future', 'conditional', 'presentSubjunctive', 'imperative'],
    overrides: {
      present: { yo: 'duermo', tu: 'duermes', el: 'duerme', ellos: 'duermen' },
      preterite: { el: 'durmió', ellos: 'durmieron' },
      presentSubjunctive: { nosotros: 'durmamos', vosotros: 'durmáis' },
    },
  },
  {
    id: 'doler',
    infinitive: 'doler',
    en: 'to hurt',
    level: 'A1',
    irregular: true,
    irregularityNote: 'o → ue, and it behaves like gustar — the body part is the subject.',
    tenses: ['present', 'preterite', 'imperfect', 'presentPerfect', 'future', 'conditional', 'presentSubjunctive'],
    overrides: {
      presentSubjunctive: { nosotros: 'dolamos', vosotros: 'doláis' }, present: { yo: 'duelo', tu: 'dueles', el: 'duele', ellos: 'duelen' } },
    patterns: [{ pattern: 'me duele + parte del cuerpo', en: 'my … hurts', example: { es: 'Me duelen las piernas.', en: 'My legs hurt.' } }],
  },

  // --- A2: the next layer --------------------------------------------------
  {
    id: 'volver',
    infinitive: 'volver',
    en: 'to return, to go back',
    level: 'A2',
    irregular: true,
    irregularityNote: 'o → ue, and the participle is vuelto.',
    participle: 'vuelto',
    tenses: ['present', 'preterite', 'imperfect', 'presentPerfect', 'future', 'conditional', 'presentSubjunctive', 'imperative'],
    overrides: {
      presentSubjunctive: { nosotros: 'volvamos', vosotros: 'volváis' }, present: { yo: 'vuelvo', tu: 'vuelves', el: 'vuelve', ellos: 'vuelven' } },
    patterns: [{ pattern: 'volver a + infinitivo', en: 'to do something again', example: { es: 'He vuelto a llamarle.', en: "I've called him again." } }],
  },
  {
    id: 'pensar',
    infinitive: 'pensar',
    en: 'to think',
    level: 'A2',
    irregular: true,
    irregularityNote: 'e → ie in the stressed forms.',
    tenses: ['present', 'preterite', 'imperfect', 'presentPerfect', 'future', 'conditional', 'presentSubjunctive', 'imperative'],
    overrides: {
      presentSubjunctive: { nosotros: 'pensemos', vosotros: 'penséis' }, present: { yo: 'pienso', tu: 'piensas', el: 'piensa', ellos: 'piensan' } },
    patterns: [{ pattern: 'pensar en', en: 'to think about', example: { es: 'Estoy pensando en el viaje.', en: "I'm thinking about the trip." } }],
  },
  {
    id: 'entender',
    infinitive: 'entender',
    en: 'to understand',
    level: 'A2',
    irregular: true,
    irregularityNote: 'e → ie in the stressed forms.',
    tenses: ['present', 'preterite', 'imperfect', 'presentPerfect', 'future', 'conditional', 'presentSubjunctive'],
    overrides: {
      presentSubjunctive: { nosotros: 'entendamos', vosotros: 'entendáis' }, present: { yo: 'entiendo', tu: 'entiendes', el: 'entiende', ellos: 'entienden' } },
  },
  {
    id: 'perder',
    infinitive: 'perder',
    en: 'to lose, to miss (a train)',
    level: 'A2',
    irregular: true,
    irregularityNote: 'e → ie in the stressed forms.',
    tenses: ['present', 'preterite', 'imperfect', 'presentPerfect', 'future', 'conditional', 'presentSubjunctive'],
    overrides: {
      presentSubjunctive: { nosotros: 'perdamos', vosotros: 'perdáis' }, present: { yo: 'pierdo', tu: 'pierdes', el: 'pierde', ellos: 'pierden' } },
    patterns: [{ pattern: 'perder el tren', en: 'to miss the train', example: { es: 'He perdido el último tren.', en: "I've missed the last train." } }],
  },
  {
    id: 'jugar',
    infinitive: 'jugar',
    en: 'to play',
    level: 'A2',
    irregular: true,
    irregularityNote: 'The only u → ue verb in Spanish, plus g → gu before -é.',
    tenses: ['present', 'preterite', 'imperfect', 'presentPerfect', 'future', 'conditional', 'presentSubjunctive', 'imperative'],
    overrides: {
      presentSubjunctive: { nosotros: 'juguemos', vosotros: 'juguéis' },
      present: { yo: 'juego', tu: 'juegas', el: 'juega', ellos: 'juegan' },
      preterite: { yo: 'jugué' },
    },
    patterns: [{ pattern: 'jugar a + deporte', en: 'to play a sport', example: { es: 'Jugamos al fútbol los jueves.', en: 'We play football on Thursdays.' } }],
  },
  {
    id: 'sentir',
    infinitive: 'sentir',
    en: 'to feel, to be sorry',
    level: 'A2',
    irregular: true,
    irregularityNote: 'e → ie in the present, e → i in the third-person preterite and the gerund.',
    gerund: 'sintiendo',
    tenses: ['present', 'preterite', 'imperfect', 'presentPerfect', 'future', 'conditional', 'presentSubjunctive'],
    overrides: {
      present: { yo: 'siento', tu: 'sientes', el: 'siente', ellos: 'sienten' },
      preterite: { el: 'sintió', ellos: 'sintieron' },
      presentSubjunctive: { nosotros: 'sintamos', vosotros: 'sintáis' },
    },
    patterns: [{ pattern: 'lo siento', en: "I'm sorry", example: { es: 'Lo siento mucho.', en: "I'm really sorry." } }],
  },
  {
    id: 'contar',
    infinitive: 'contar',
    en: 'to tell, to count',
    level: 'A2',
    irregular: true,
    irregularityNote: 'o → ue in the stressed forms.',
    tenses: ['present', 'preterite', 'imperfect', 'presentPerfect', 'future', 'conditional', 'presentSubjunctive', 'imperative'],
    overrides: {
      presentSubjunctive: { nosotros: 'contemos', vosotros: 'contéis' }, present: { yo: 'cuento', tu: 'cuentas', el: 'cuenta', ellos: 'cuentan' } },
    patterns: [{ pattern: 'contar con', en: 'to count on', example: { es: 'Cuenta conmigo.', en: 'Count on me.' } }],
  },
  {
    id: 'recordar',
    infinitive: 'recordar',
    en: 'to remember',
    level: 'A2',
    irregular: true,
    irregularityNote: 'o → ue in the stressed forms.',
    tenses: ['present', 'preterite', 'imperfect', 'presentPerfect', 'future', 'conditional', 'presentSubjunctive'],
    overrides: {
      presentSubjunctive: { nosotros: 'recordemos', vosotros: 'recordéis' }, present: { yo: 'recuerdo', tu: 'recuerdas', el: 'recuerda', ellos: 'recuerdan' } },
  },
  { id: 'olvidar', infinitive: 'olvidar', en: 'to forget', level: 'A2', tenses: ['present', 'preterite', 'imperfect', 'presentPerfect', 'future', 'conditional', 'presentSubjunctive'], patterns: [{ pattern: 'se me ha olvidado', en: 'I forgot (it slipped my mind)', example: { es: 'Se me ha olvidado el móvil.', en: "I've forgotten my phone." } }] },
  { id: 'dejar', infinitive: 'dejar', en: 'to leave, to let', level: 'A2', tenses: ['present', 'preterite', 'imperfect', 'presentPerfect', 'future', 'conditional', 'presentSubjunctive', 'imperative'], patterns: [{ pattern: 'dejar de + infinitivo', en: 'to stop doing something', example: { es: 'He dejado de fumar.', en: "I've stopped smoking." } }] },
  { id: 'cambiar', infinitive: 'cambiar', en: 'to change', level: 'A2', tenses: ['present', 'preterite', 'imperfect', 'presentPerfect', 'future', 'conditional', 'presentSubjunctive'] },
  { id: 'ganar', infinitive: 'ganar', en: 'to win, to earn', level: 'A2', tenses: ['present', 'preterite', 'imperfect', 'presentPerfect', 'future', 'conditional', 'presentSubjunctive'] },
  { id: 'intentar', infinitive: 'intentar', en: 'to try', level: 'A2', tenses: ['present', 'preterite', 'imperfect', 'presentPerfect', 'future', 'conditional', 'presentSubjunctive'], patterns: [{ pattern: 'intentar + infinitivo', en: 'to try to do something', example: { es: 'Voy a intentar llegar a tiempo.', en: "I'll try to get there on time." } }] },

  // --- B1: narrating and explaining ---------------------------------------
  {
    id: 'parecer',
    infinitive: 'parecer',
    en: 'to seem, to look like',
    level: 'B1',
    irregular: true,
    irregularityNote: 'c → zc in the yo form, which the subjunctive inherits: parezco → parezca.',
    tenses: ['present', 'preterite', 'imperfect', 'presentPerfect', 'future', 'conditional', 'presentSubjunctive'],
    overrides: { present: { yo: 'parezco' } },
    patterns: [{ pattern: 'me parece que…', en: 'I think that…', example: { es: 'Me parece que tienes razón.', en: 'I think you are right.' } }],
  },
  {
    id: 'creer',
    infinitive: 'creer',
    en: 'to believe, to think',
    level: 'B1',
    irregular: true,
    irregularityNote: 'The i of the ending becomes y between vowels: creyó, creyeron, creyendo.',
    gerund: 'creyendo',
    participle: 'creído',
    tenses: ['present', 'preterite', 'imperfect', 'presentPerfect', 'future', 'conditional', 'presentSubjunctive'],
    overrides: { preterite: { el: 'creyó', ellos: 'creyeron' } },
    patterns: [{ pattern: 'no creo que + subjuntivo', en: "I don't think that…", example: { es: 'No creo que sea buena idea.', en: "I don't think it's a good idea." } }],
  },
  {
    id: 'conseguir',
    infinitive: 'conseguir',
    en: 'to get, to manage to',
    level: 'B1',
    irregular: true,
    irregularityNote: 'e → i throughout, and the u of -gu- is dropped before a or o: consigo.',
    gerund: 'consiguiendo',
    tenses: ['present', 'preterite', 'imperfect', 'presentPerfect', 'future', 'conditional', 'presentSubjunctive'],
    overrides: {
      present: { yo: 'consigo', tu: 'consigues', el: 'consigue', ellos: 'consiguen' },
      preterite: { el: 'consiguió', ellos: 'consiguieron' },
    },
    patterns: [{ pattern: 'conseguir + infinitivo', en: 'to manage to do something', example: { es: 'Al final conseguí entrar.', en: 'In the end I managed to get in.' } }],
  },
  {
    id: 'servir',
    infinitive: 'servir',
    en: 'to serve, to be useful',
    level: 'B1',
    irregular: true,
    irregularityNote: 'e → i throughout the present and in the third-person preterite.',
    gerund: 'sirviendo',
    tenses: ['present', 'preterite', 'imperfect', 'presentPerfect', 'future', 'conditional', 'presentSubjunctive'],
    overrides: {
      present: { yo: 'sirvo', tu: 'sirves', el: 'sirve', ellos: 'sirven' },
      preterite: { el: 'sirvió', ellos: 'sirvieron' },
    },
    patterns: [{ pattern: 'no sirve para nada', en: "it's useless", example: { es: 'Este mando no sirve para nada.', en: 'This remote is completely useless.' } }],
  },
  {
    id: 'mover',
    infinitive: 'mover',
    en: 'to move',
    level: 'B1',
    irregular: true,
    irregularityNote: 'o → ue in the stressed forms.',
    tenses: ['present', 'preterite', 'imperfect', 'presentPerfect', 'future', 'conditional', 'presentSubjunctive'],
    overrides: {
      presentSubjunctive: { nosotros: 'movamos', vosotros: 'mováis' }, present: { yo: 'muevo', tu: 'mueves', el: 'mueve', ellos: 'mueven' } },
  },
  {
    id: 'crecer',
    infinitive: 'crecer',
    en: 'to grow',
    level: 'B1',
    irregular: true,
    irregularityNote: 'c → zc in the yo form.',
    tenses: ['present', 'preterite', 'imperfect', 'presentPerfect', 'future', 'conditional', 'presentSubjunctive'],
    overrides: { present: { yo: 'crezco' } },
  },
  {
    id: 'nacer',
    infinitive: 'nacer',
    en: 'to be born',
    level: 'B1',
    irregular: true,
    irregularityNote: 'c → zc in the yo form.',
    tenses: ['present', 'preterite', 'imperfect', 'presentPerfect', 'future', 'conditional', 'presentSubjunctive'],
    overrides: { present: { yo: 'nazco' } },
    patterns: [{ pattern: 'nací en…', en: 'I was born in…', example: { es: 'Nací en Liubliana en mil novecientos noventa.', en: 'I was born in Ljubljana in 1990.' } }],
  },
  {
    id: 'morir',
    infinitive: 'morir',
    en: 'to die',
    level: 'B1',
    irregular: true,
    irregularityNote: 'o → ue in the present, o → u in the third-person preterite, and the participle is muerto.',
    gerund: 'muriendo',
    participle: 'muerto',
    tenses: ['present', 'preterite', 'imperfect', 'presentPerfect', 'future', 'conditional', 'presentSubjunctive'],
    overrides: {
      present: { yo: 'muero', tu: 'mueres', el: 'muere', ellos: 'mueren' },
      preterite: { el: 'murió', ellos: 'murieron' },
      presentSubjunctive: { nosotros: 'muramos', vosotros: 'muráis' },
    },
  },
  {
    id: 'caer',
    infinitive: 'caer',
    en: 'to fall',
    level: 'B1',
    irregular: true,
    irregularityNote: 'Irregular yo form, and i → y between vowels: cayó, cayendo.',
    gerund: 'cayendo',
    participle: 'caído',
    tenses: ['present', 'preterite', 'imperfect', 'presentPerfect', 'future', 'conditional', 'presentSubjunctive'],
    overrides: {
      present: { yo: 'caigo' },
      preterite: { el: 'cayó', ellos: 'cayeron' },
    },
    patterns: [{ pattern: 'caer bien / mal', en: 'to like / dislike someone', example: { es: 'Tu hermano me cae muy bien.', en: 'I really like your brother.' } }],
  },
  { id: 'ocurrir', infinitive: 'ocurrir', en: 'to happen, to occur', level: 'B1', tenses: ['present', 'preterite', 'imperfect', 'presentPerfect', 'future', 'conditional', 'presentSubjunctive'], patterns: [{ pattern: 'se me ocurre', en: 'it occurs to me', example: { es: 'Se me ocurre una idea mejor.', en: 'I have a better idea.' } }] },

  // --- B2: argument and abstraction ---------------------------------------
  {
    id: 'suponer',
    infinitive: 'suponer',
    en: 'to suppose, to involve',
    level: 'B2',
    irregular: true,
    irregularityNote: 'Follows poner throughout: supongo, supuse, supondré, supuesto.',
    participle: 'supuesto',
    tenses: ['present', 'preterite', 'imperfect', 'presentPerfect', 'future', 'conditional', 'presentSubjunctive'],
    overrides: {
      present: { yo: 'supongo' },
      preterite: { yo: 'supuse', tu: 'supusiste', el: 'supuso', nosotros: 'supusimos', vosotros: 'supusisteis', ellos: 'supusieron' },
    },
    stems: { future: 'supondr', conditional: 'supondr' },
  },
  {
    id: 'mantener',
    infinitive: 'mantener',
    en: 'to maintain, to keep',
    level: 'B2',
    irregular: true,
    irregularityNote: 'Follows tener throughout: mantengo, mantuve, mantendré.',
    tenses: ['present', 'preterite', 'imperfect', 'presentPerfect', 'future', 'conditional', 'presentSubjunctive'],
    overrides: {
      present: { yo: 'mantengo', tu: 'mantienes', el: 'mantiene', ellos: 'mantienen' },
      preterite: { yo: 'mantuve', tu: 'mantuviste', el: 'mantuvo', nosotros: 'mantuvimos', vosotros: 'mantuvisteis', ellos: 'mantuvieron' },
    },
    stems: { future: 'mantendr', conditional: 'mantendr' },
  },
  {
    id: 'establecer',
    infinitive: 'establecer',
    en: 'to establish',
    level: 'B2',
    irregular: true,
    irregularityNote: 'c → zc in the yo form.',
    tenses: ['present', 'preterite', 'imperfect', 'presentPerfect', 'future', 'conditional', 'presentSubjunctive'],
    overrides: { present: { yo: 'establezco' } },
  },
  { id: 'permitir', infinitive: 'permitir', en: 'to allow', level: 'B2', tenses: ['present', 'preterite', 'imperfect', 'presentPerfect', 'future', 'conditional', 'presentSubjunctive'] },
  {
    id: 'impedir',
    infinitive: 'impedir',
    en: 'to prevent',
    level: 'B2',
    irregular: true,
    irregularityNote: 'e → i throughout the present and in the third-person preterite.',
    gerund: 'impidiendo',
    tenses: ['present', 'preterite', 'imperfect', 'presentPerfect', 'future', 'conditional', 'presentSubjunctive'],
    overrides: {
      present: { yo: 'impido', tu: 'impides', el: 'impide', ellos: 'impiden' },
      preterite: { el: 'impidió', ellos: 'impidieron' },
    },
  },
  { id: 'suceder', infinitive: 'suceder', en: 'to happen', level: 'B2', tenses: ['present', 'preterite', 'imperfect', 'presentPerfect', 'future', 'conditional', 'presentSubjunctive'] },
  { id: 'resultar', infinitive: 'resultar', en: 'to turn out, to prove', level: 'B2', tenses: ['present', 'preterite', 'imperfect', 'presentPerfect', 'future', 'conditional', 'presentSubjunctive'], patterns: [{ pattern: 'resulta que…', en: 'it turns out that…', example: { es: 'Resulta que ya lo sabían.', en: 'It turns out they already knew.' } }] },
];
