import { buildVerb, type VerbSeed } from '@/content/verb-utils';
import type { Verb } from '@/content/types';

/**
 * Verb paradigms. Only irregular forms are written out — everything else is
 * generated. Each verb × tense listed here automatically becomes a trackable
 * concept (`f.<verb>.<tense>`) that the learner model can schedule.
 */
const SEEDS: VerbSeed[] = [
  {
    id: 'ser',
    infinitive: 'ser',
    en: 'to be (identity)',
    level: 'A0',
    irregular: true,
    irregularityNote: 'Completely irregular — one of the two "to be" verbs.',
    participle: 'sido',
    gerund: 'siendo',
    tenses: ['present', 'preterite', 'imperfect', 'presentPerfect', 'future', 'conditional'],
    overrides: {
      present: { yo: 'soy', tu: 'eres', el: 'es', nosotros: 'somos', vosotros: 'sois', ellos: 'son' },
      preterite: {
        yo: 'fui',
        tu: 'fuiste',
        el: 'fue',
        nosotros: 'fuimos',
        vosotros: 'fuisteis',
        ellos: 'fueron',
      },
      imperfect: {
        yo: 'era',
        tu: 'eras',
        el: 'era',
        nosotros: 'éramos',
        vosotros: 'erais',
        ellos: 'eran',
      },
    },
    patterns: [
      {
        pattern: 'ser de + lugar',
        en: 'to be from somewhere',
        example: { es: 'Soy de Liubliana.', en: 'I’m from Ljubljana.' },
      },
    ],
  },
  {
    id: 'estar',
    infinitive: 'estar',
    en: 'to be (state, location)',
    level: 'A0',
    irregular: true,
    irregularityNote: 'Irregular yo form and accents throughout the present.',
    tenses: ['present', 'preterite', 'imperfect', 'presentPerfect', 'future', 'conditional'],
    overrides: {
      present: { yo: 'estoy', tu: 'estás', el: 'está', ellos: 'están' },
      preterite: {
        yo: 'estuve',
        tu: 'estuviste',
        el: 'estuvo',
        nosotros: 'estuvimos',
        vosotros: 'estuvisteis',
        ellos: 'estuvieron',
      },
    },
    patterns: [
      {
        pattern: 'estar + gerundio',
        en: 'to be doing something right now',
        example: { es: 'Estoy estudiando.', en: 'I’m studying.' },
      },
    ],
  },
  {
    id: 'tener',
    infinitive: 'tener',
    en: 'to have',
    level: 'A0',
    irregular: true,
    irregularityNote: 'e → ie stem change, plus an irregular yo form (tengo).',
    tenses: ['present', 'preterite', 'imperfect', 'presentPerfect', 'future', 'conditional'],
    stems: { future: 'tendr', conditional: 'tendr' },
    overrides: {
      present: { yo: 'tengo', tu: 'tienes', el: 'tiene', ellos: 'tienen' },
      preterite: {
        yo: 'tuve',
        tu: 'tuviste',
        el: 'tuvo',
        nosotros: 'tuvimos',
        vosotros: 'tuvisteis',
        ellos: 'tuvieron',
      },
    },
    patterns: [
      {
        pattern: 'tener que + infinitivo',
        en: 'to have to do something',
        example: { es: 'Tengo que irme ya.', en: 'I have to go now.' },
      },
      {
        pattern: 'tener + años / hambre / frío',
        en: 'states English expresses with "to be"',
        example: { es: 'Tengo mucha hambre.', en: 'I’m really hungry.' },
      },
    ],
  },
  {
    id: 'ir',
    infinitive: 'ir',
    en: 'to go',
    level: 'A1',
    irregular: true,
    irregularityNote: 'Wildly irregular; shares its preterite with ser.',
    participle: 'ido',
    gerund: 'yendo',
    tenses: ['present', 'preterite', 'imperfect', 'presentPerfect', 'future', 'conditional'],
    overrides: {
      present: { yo: 'voy', tu: 'vas', el: 'va', nosotros: 'vamos', vosotros: 'vais', ellos: 'van' },
      preterite: {
        yo: 'fui',
        tu: 'fuiste',
        el: 'fue',
        nosotros: 'fuimos',
        vosotros: 'fuisteis',
        ellos: 'fueron',
      },
      imperfect: {
        yo: 'iba',
        tu: 'ibas',
        el: 'iba',
        nosotros: 'íbamos',
        vosotros: 'ibais',
        ellos: 'iban',
      },
    },
    patterns: [
      {
        pattern: 'ir a + infinitivo',
        en: 'to be going to do something',
        example: { es: 'Vamos a quedar el sábado.', en: 'We’re going to meet up on Saturday.' },
      },
    ],
  },
  {
    id: 'hacer',
    infinitive: 'hacer',
    en: 'to do / to make',
    level: 'A1',
    irregular: true,
    irregularityNote: 'Irregular yo form, irregular preterite stem, participle hecho.',
    participle: 'hecho',
    tenses: ['present', 'preterite', 'imperfect', 'presentPerfect', 'future', 'conditional'],
    stems: { future: 'har', conditional: 'har' },
    overrides: {
      present: { yo: 'hago' },
      preterite: {
        yo: 'hice',
        tu: 'hiciste',
        el: 'hizo',
        nosotros: 'hicimos',
        vosotros: 'hicisteis',
        ellos: 'hicieron',
      },
    },
    patterns: [
      {
        pattern: 'hacer deporte / la compra',
        en: 'to do sport / to do the shopping',
        example: { es: 'Hago deporte tres veces por semana.', en: 'I exercise three times a week.' },
      },
    ],
  },
  {
    id: 'querer',
    infinitive: 'querer',
    en: 'to want / to love',
    level: 'A1',
    irregular: true,
    irregularityNote: 'e → ie in the present; irregular preterite stem quis-.',
    tenses: ['present', 'preterite', 'imperfect', 'future', 'conditional'],
    stems: { future: 'querr', conditional: 'querr' },
    overrides: {
      present: { yo: 'quiero', tu: 'quieres', el: 'quiere', ellos: 'quieren' },
      preterite: {
        yo: 'quise',
        tu: 'quisiste',
        el: 'quiso',
        nosotros: 'quisimos',
        vosotros: 'quisisteis',
        ellos: 'quisieron',
      },
    },
    patterns: [
      {
        pattern: 'querría / quería…',
        en: 'a softer "I’d like"',
        example: { es: 'Quería una mesa para dos.', en: 'I’d like a table for two.' },
      },
    ],
  },
  {
    id: 'poder',
    infinitive: 'poder',
    en: 'can / to be able to',
    level: 'A1',
    irregular: true,
    irregularityNote: 'o → ue in the present; preterite stem pud-.',
    gerund: 'pudiendo',
    tenses: ['present', 'preterite', 'imperfect', 'future', 'conditional'],
    stems: { future: 'podr', conditional: 'podr' },
    overrides: {
      present: { yo: 'puedo', tu: 'puedes', el: 'puede', ellos: 'pueden' },
      preterite: {
        yo: 'pude',
        tu: 'pudiste',
        el: 'pudo',
        nosotros: 'pudimos',
        vosotros: 'pudisteis',
        ellos: 'pudieron',
      },
    },
  },
  {
    id: 'saber',
    infinitive: 'saber',
    en: 'to know (facts)',
    level: 'A2',
    irregular: true,
    irregularityNote: 'Irregular yo (sé) and preterite stem sup-.',
    tenses: ['present', 'preterite', 'imperfect', 'future', 'conditional'],
    stems: { future: 'sabr', conditional: 'sabr' },
    overrides: {
      present: { yo: 'sé' },
      preterite: {
        yo: 'supe',
        tu: 'supiste',
        el: 'supo',
        nosotros: 'supimos',
        vosotros: 'supisteis',
        ellos: 'supieron',
      },
    },
  },
  {
    id: 'conocer',
    infinitive: 'conocer',
    en: 'to know (people, places)',
    level: 'A2',
    irregular: true,
    irregularityNote: 'Irregular yo form: conozco.',
    tenses: ['present', 'preterite', 'presentPerfect'],
    overrides: { present: { yo: 'conozco' } },
  },
  {
    id: 'ver',
    infinitive: 'ver',
    en: 'to see / to watch',
    level: 'A1',
    irregular: true,
    irregularityNote: 'Keeps the e of the stem in several forms; participle visto.',
    participle: 'visto',
    tenses: ['present', 'preterite', 'imperfect', 'presentPerfect'],
    overrides: {
      present: { yo: 'veo', vosotros: 'veis' },
      preterite: { yo: 'vi', el: 'vio' },
      imperfect: {
        yo: 'veía',
        tu: 'veías',
        el: 'veía',
        nosotros: 'veíamos',
        vosotros: 'veíais',
        ellos: 'veían',
      },
    },
  },
  {
    id: 'salir',
    infinitive: 'salir',
    en: 'to go out / to leave',
    level: 'A2',
    irregular: true,
    irregularityNote: 'Irregular yo (salgo) and future stem saldr-.',
    tenses: ['present', 'preterite', 'presentPerfect', 'future', 'conditional'],
    stems: { future: 'saldr', conditional: 'saldr' },
    overrides: { present: { yo: 'salgo' } },
    patterns: [
      {
        pattern: 'salir de fiesta / a cenar',
        en: 'to go out partying / for dinner',
        example: { es: 'Salimos a cenar el viernes.', en: 'We’re going out for dinner on Friday.' },
      },
    ],
  },
  {
    id: 'venir',
    infinitive: 'venir',
    en: 'to come',
    level: 'A2',
    irregular: true,
    irregularityNote: 'e → ie present, preterite stem vin-, future stem vendr-.',
    gerund: 'viniendo',
    tenses: ['present', 'preterite', 'presentPerfect', 'future', 'conditional'],
    stems: { future: 'vendr', conditional: 'vendr' },
    overrides: {
      present: { yo: 'vengo', tu: 'vienes', el: 'viene', ellos: 'vienen' },
      preterite: {
        yo: 'vine',
        tu: 'viniste',
        el: 'vino',
        nosotros: 'vinimos',
        vosotros: 'vinisteis',
        ellos: 'vinieron',
      },
    },
  },
  {
    id: 'decir',
    infinitive: 'decir',
    en: 'to say / to tell',
    level: 'A2',
    irregular: true,
    irregularityNote: 'e → i present, preterite stem dij-, participle dicho.',
    participle: 'dicho',
    gerund: 'diciendo',
    tenses: ['present', 'preterite', 'presentPerfect', 'future', 'conditional'],
    stems: { future: 'dir', conditional: 'dir' },
    overrides: {
      present: { yo: 'digo', tu: 'dices', el: 'dice', ellos: 'dicen' },
      preterite: {
        yo: 'dije',
        tu: 'dijiste',
        el: 'dijo',
        nosotros: 'dijimos',
        vosotros: 'dijisteis',
        ellos: 'dijeron',
      },
    },
  },

  // --- Regular workhorses ---------------------------------------------------
  {
    id: 'hablar',
    infinitive: 'hablar',
    en: 'to speak',
    level: 'A0',
    tenses: ['present', 'preterite', 'imperfect', 'presentPerfect'],
  },
  {
    id: 'comer',
    infinitive: 'comer',
    en: 'to eat / to have lunch',
    level: 'A0',
    tenses: ['present', 'preterite', 'imperfect', 'presentPerfect'],
  },
  {
    id: 'vivir',
    infinitive: 'vivir',
    en: 'to live',
    level: 'A0',
    tenses: ['present', 'preterite', 'imperfect', 'presentPerfect'],
  },
  { id: 'trabajar', infinitive: 'trabajar', en: 'to work', level: 'A1', tenses: ['present', 'preterite'] },
  { id: 'estudiar', infinitive: 'estudiar', en: 'to study', level: 'A1', tenses: ['present', 'preterite'] },
  { id: 'beber', infinitive: 'beber', en: 'to drink', level: 'A1', tenses: ['present', 'preterite'] },
  {
    id: 'tomar',
    infinitive: 'tomar',
    en: 'to take / to have (a drink)',
    level: 'A1',
    tenses: ['present', 'preterite'],
    patterns: [
      {
        pattern: 'tomar algo',
        en: 'to grab a drink',
        example: { es: '¿Tomamos algo después?', en: 'Shall we grab a drink afterwards?' },
      },
    ],
  },
  { id: 'escuchar', infinitive: 'escuchar', en: 'to listen to', level: 'A1', tenses: ['present'] },
  { id: 'viajar', infinitive: 'viajar', en: 'to travel', level: 'A1', tenses: ['present', 'preterite'] },
  { id: 'cocinar', infinitive: 'cocinar', en: 'to cook', level: 'A1', tenses: ['present'] },
  { id: 'comprar', infinitive: 'comprar', en: 'to buy', level: 'A1', tenses: ['present', 'preterite'] },
  { id: 'reservar', infinitive: 'reservar', en: 'to book', level: 'A2', tenses: ['present'] },
  { id: 'girar', infinitive: 'girar', en: 'to turn', level: 'A2', tenses: ['present'] },
  {
    id: 'quedar',
    infinitive: 'quedar',
    en: 'to meet up / to arrange to meet',
    level: 'A2',
    tenses: ['present', 'preterite', 'presentPerfect'],
    patterns: [
      {
        pattern: 'quedar con alguien',
        en: 'to meet up with someone',
        example: { es: 'He quedado con Marta a las ocho.', en: 'I’m meeting Marta at eight.' },
      },
      {
        pattern: 'quedar en + lugar',
        en: 'to agree to meet somewhere',
        example: { es: 'Quedamos en la plaza.', en: 'Let’s meet in the square.' },
      },
    ],
  },
  {
    id: 'escribir',
    infinitive: 'escribir',
    en: 'to write',
    level: 'A1',
    irregular: true,
    irregularityNote: 'Regular except for the participle: escrito.',
    participle: 'escrito',
    tenses: ['present', 'preterite', 'presentPerfect'],
  },
  {
    id: 'leer',
    infinitive: 'leer',
    en: 'to read',
    level: 'A1',
    irregular: true,
    irregularityNote: 'Spelling change in the preterite: leyó, leyeron.',
    gerund: 'leyendo',
    participle: 'leído',
    tenses: ['present', 'preterite'],
    overrides: {
      preterite: {
        tu: 'leíste',
        el: 'leyó',
        nosotros: 'leímos',
        vosotros: 'leísteis',
        ellos: 'leyeron',
      },
    },
  },
  {
    id: 'coger',
    infinitive: 'coger',
    en: 'to take / to catch',
    level: 'A2',
    irregular: true,
    irregularityNote: 'Spelling only: g → j before o, so yo cojo.',
    tenses: ['present', 'preterite'],
    overrides: { present: { yo: 'cojo' } },
    patterns: [
      {
        pattern: 'coger el metro / un taxi',
        en: 'to take the metro / a taxi',
        example: { es: 'Cojo el metro todos los días.', en: 'I take the metro every day.' },
      },
    ],
  },
  {
    id: 'conducir',
    infinitive: 'conducir',
    en: 'to drive',
    level: 'A2',
    irregular: true,
    irregularityNote: 'Irregular yo (conduzco) and preterite stem conduj-.',
    tenses: ['present', 'preterite'],
    overrides: {
      present: { yo: 'conduzco' },
      preterite: {
        yo: 'conduje',
        tu: 'condujiste',
        el: 'condujo',
        nosotros: 'condujimos',
        vosotros: 'condujisteis',
        ellos: 'condujeron',
      },
    },
  },
  {
    id: 'seguir',
    infinitive: 'seguir',
    en: 'to continue / to follow',
    level: 'A2',
    irregular: true,
    irregularityNote: 'e → i stem change.',
    gerund: 'siguiendo',
    tenses: ['present', 'preterite'],
    overrides: {
      present: { yo: 'sigo', tu: 'sigues', el: 'sigue', ellos: 'siguen' },
      preterite: { el: 'siguió', ellos: 'siguieron' },
    },
  },
  {
    id: 'probar',
    infinitive: 'probar',
    en: 'to try / to taste',
    level: 'A2',
    irregular: true,
    irregularityNote: 'o → ue stem change.',
    tenses: ['present'],
    overrides: { present: { yo: 'pruebo', tu: 'pruebas', el: 'prueba', ellos: 'prueban' } },
  },
  {
    id: 'pagar',
    infinitive: 'pagar',
    en: 'to pay',
    level: 'A1',
    irregular: true,
    irregularityNote: 'Spelling only: g → gu before e, so yo pagué.',
    tenses: ['present', 'preterite'],
    overrides: { preterite: { yo: 'pagué' } },
  },

  // --- Reflexives -----------------------------------------------------------
  {
    id: 'llamarse',
    infinitive: 'llamarse',
    en: 'to be called',
    level: 'A0',
    reflexive: true,
    tenses: ['present'],
  },
  {
    id: 'levantarse',
    infinitive: 'levantarse',
    en: 'to get up',
    level: 'A2',
    reflexive: true,
    tenses: ['present', 'preterite'],
  },
  {
    id: 'ducharse',
    infinitive: 'ducharse',
    en: 'to have a shower',
    level: 'A2',
    reflexive: true,
    tenses: ['present'],
  },
  {
    id: 'despertarse',
    infinitive: 'despertarse',
    en: 'to wake up',
    level: 'A2',
    reflexive: true,
    irregular: true,
    irregularityNote: 'e → ie stem change.',
    tenses: ['present'],
    overrides: {
      present: { yo: 'despierto', tu: 'despiertas', el: 'despierta', ellos: 'despiertan' },
    },
  },
  {
    id: 'acostarse',
    infinitive: 'acostarse',
    en: 'to go to bed',
    level: 'A2',
    reflexive: true,
    irregular: true,
    irregularityNote: 'o → ue stem change.',
    tenses: ['present'],
    overrides: { present: { yo: 'acuesto', tu: 'acuestas', el: 'acuesta', ellos: 'acuestan' } },
  },
  {
    id: 'dar',
    infinitive: 'dar',
    en: 'to give',
    level: 'A2',
    irregular: true,
    irregularityNote: 'Irregular yo form (doy) and an -er/-ir style preterite with no accents.',
    tenses: ['present', 'preterite', 'imperfect', 'presentPerfect'],
    overrides: {
      present: { yo: 'doy', vosotros: 'dais' },
      preterite: {
        yo: 'di',
        tu: 'diste',
        el: 'dio',
        nosotros: 'dimos',
        vosotros: 'disteis',
        ellos: 'dieron',
      },
    },
    patterns: [
      {
        pattern: 'dar + sensación',
        en: 'to make someone feel something',
        example: { es: 'Me da pena que se vaya.', en: 'It makes me sad that he’s leaving.' },
      },
      {
        pattern: 'dar igual',
        en: 'not to matter',
        example: { es: 'Me da igual, decide tú.', en: 'I don’t mind, you decide.' },
      },
    ],
  },
  {
    id: 'poner',
    infinitive: 'poner',
    en: 'to put',
    level: 'A2',
    irregular: true,
    irregularityNote: 'Irregular yo form (pongo), pus- preterite stem, participle puesto.',
    participle: 'puesto',
    tenses: ['present', 'preterite', 'presentPerfect', 'future', 'conditional'],
    stems: { future: 'pondr', conditional: 'pondr' },
    overrides: {
      present: { yo: 'pongo' },
      preterite: {
        yo: 'puse',
        tu: 'pusiste',
        el: 'puso',
        nosotros: 'pusimos',
        vosotros: 'pusisteis',
        ellos: 'pusieron',
      },
    },
    patterns: [
      {
        pattern: '¿me pones…?',
        en: 'can I get…? (ordering)',
        example: { es: '¿Me pones una caña?', en: 'Can I get a small beer?' },
      },
      {
        pattern: 'ponerse + adjetivo',
        en: 'to become / to get (a state)',
        example: { es: 'Se puso muy nervioso.', en: 'He got very nervous.' },
      },
    ],
  },
  {
    id: 'llevar',
    infinitive: 'llevar',
    en: 'to carry / to wear / to have been',
    level: 'A2',
    irregular: false,
    tenses: ['present', 'preterite', 'imperfect', 'presentPerfect'],
    patterns: [
      {
        pattern: 'llevar + tiempo + gerundio',
        en: 'to have been doing something for a while',
        example: {
          es: 'Llevo dos años estudiando español.',
          en: 'I’ve been studying Spanish for two years.',
        },
      },
      {
        pattern: 'llevarse bien / mal con',
        en: 'to get on well / badly with',
        example: { es: 'Me llevo muy bien con mi jefa.', en: 'I get on really well with my boss.' },
      },
    ],
  },
  {
    id: 'traer',
    infinitive: 'traer',
    en: 'to bring',
    level: 'A2',
    irregular: true,
    irregularityNote: 'Irregular yo form (traigo), traj- preterite stem, participle traído.',
    participle: 'traído',
    gerund: 'trayendo',
    tenses: ['present', 'preterite', 'presentPerfect'],
    overrides: {
      present: { yo: 'traigo' },
      preterite: {
        yo: 'traje',
        tu: 'trajiste',
        el: 'trajo',
        nosotros: 'trajimos',
        vosotros: 'trajisteis',
        ellos: 'trajeron',
      },
    },
    patterns: [
      {
        pattern: '¿nos trae…?',
        en: 'could you bring us…? (in a restaurant)',
        example: { es: '¿Nos trae la carta, por favor?', en: 'Could you bring us the menu, please?' },
      },
    ],
  },
];

export const verbs: Verb[] = SEEDS.map(buildVerb);
