import { readdirSync, readFileSync, statSync } from 'fs';
import { join } from 'path';

/**
 * The web deploy's one hardcoded list, and the guard that keeps it honest.
 *
 * Expo's static export writes a dynamic route to disk as the literal filename
 * `word/[id].html`. Nothing serves that at `/word/v.casa`, so each one needs a
 * rewrite — and the list has to live in a committed `vercel.json`, because
 * Vercel reads that file *before* the build and it therefore cannot be
 * generated by one.
 *
 * A hardcoded list of routes is exactly the kind of thing that rots, and this
 * one rots without a symptom: adding a route leaves the app working in the
 * browser, because client-side navigation never asks the server. Only a
 * refresh or a shared link breaks, which is precisely what a public demo is
 * for. So the list is asserted against the router directory rather than
 * trusted.
 */

const APP_DIR = join(__dirname, '..');
const vercel = JSON.parse(readFileSync(join(__dirname, '../../../vercel.json'), 'utf8')) as {
  cleanUrls: boolean;
  outputDirectory: string;
  rewrites: { source: string; destination: string }[];
};

/** Every `[param].tsx` under src/app, as the URL prefix that reaches it. */
function dynamicRoutes(dir: string, prefix = ''): { prefix: string; param: string }[] {
  const found: { prefix: string; param: string }[] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      if (entry === '__tests__') continue;
      // Route groups like (tabs) contribute no URL segment.
      const segment = entry.startsWith('(') && entry.endsWith(')') ? prefix : `${prefix}/${entry}`;
      found.push(...dynamicRoutes(full, segment));
      continue;
    }
    const match = /^\[([^\]]+)\]\.tsx$/.exec(entry);
    if (match) found.push({ prefix, param: match[1] });
  }
  return found;
}

describe('the deployed web build can serve every route', () => {
  const routes = dynamicRoutes(APP_DIR);

  it('finds the dynamic routes it is meant to be guarding', () => {
    // If this drops to zero the rest of the suite passes vacuously, which
    // would make the guard worse than no guard at all.
    expect(routes.length).toBeGreaterThan(0);
    expect(routes.map((route) => route.prefix).sort()).toEqual(
      ['/grammar', '/unit', '/verb', '/word'],
    );
  });

  it('has a rewrite for every dynamic route', () => {
    for (const { prefix, param } of routes) {
      const rewrite = vercel.rewrites.find((entry) => entry.source === `${prefix}/:${param}`);
      expect(rewrite).toBeDefined();
      // The destination is the percent-encoded *clean* path. Pointing it at
      // `[id].html` instead lands on cleanUrls' own 308 and never resolves —
      // which is how this was first got wrong.
      expect(rewrite!.destination).toBe(`${prefix}/%5B${param}%5D`);
      expect(rewrite!.destination).not.toContain('.html');
    }
  });

  it('keeps the icon-font rewrite, which Vercel makes necessary', () => {
    // Expo emits the vector-icon fonts under assets/node_modules/…, and Vercel
    // will not serve a path containing that segment, so every icon renders
    // blank without this. scripts/prepare-web-deploy.mjs does the rename.
    const font = vercel.rewrites.find((entry) => entry.source.startsWith('/assets/node_modules'));
    expect(font).toBeDefined();
    expect(font!.destination).toBe('/assets/nm/:path*');
  });

  it('builds into the directory it publishes', () => {
    expect(vercel.outputDirectory).toBe('dist');
    expect(vercel.cleanUrls).toBe(true);
  });
});
